### PR TITLE
[fix]: correct Job completions assignment across clusters

### LINKED ISSUE #7382: [bug]: Job completions assigned to wrong clusters - index mismatch in ensureWork
**What happened**:

I found a bug where Job `.spec.completions` get assigned to the wrong clusters when using divided replica scheduling.

In `pkg/controllers/binding/common.go`, the `ensureWork` function iterates over two slices using the same index:
- `targetClusters` (scheduler order)
- `jobCompletions` (alphabetically sorted by `AllocateWebsterSeats`)

Line 102 does `jobCompletions[i].Replicas` assuming index `i` matches between both slices, but they're in different orders. This assigns the wrong completions value to each cluster.

---

**What you expected to happen**:

Each cluster should get the correct completions value the scheduler calculated for it, regardless of alphabetical order.

---

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two clusters: `west` and `east` (alphabetical order differs from this order)
2. Create a Job with `completions: 10` and a PropagationPolicy:
```yaml
   replicaSchedulingType: Divided
   weightPreference:
     staticWeightList:
       - targetCluster: {clusterNames: [west]}
         weight: 6
       - targetCluster: {clusterNames: [east]}
         weight: 4
```
3. Check Job completions in each cluster:
```bash
   kubectl --context west get job -o jsonpath='{.spec.completions}'
   # Expected: 6, Actual: 4 (swapped!)
   
   kubectl --context east get job -o jsonpath='{.spec.completions}'
   # Expected: 4, Actual: 6 (swapped!)
```

---

**Impact:**
- Wrong number of Job completions per cluster
- Silent data corruption (no errors logged)
- Affects any cluster names not alphabetically ordered

**Fix:** Use map-based lookup by cluster name instead of index:
```go
jobCompletionsMap := make(map[string]int32)
for _, jc := range jobCompletions {
    jobCompletionsMap[jc.Name] = jc.Replicas
}
// Then: completions := jobCompletionsMap[targetCluster.Name]
```

---

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version: N/A
- Others: Affects all versions with Job divided scheduling

### PR DESCRIPTION
**Pull request by Ady0333**
**What type of PR is this?**

/kind bug

---

**What this PR does / why we need it**:

This PR fixes a critical bug where Kubernetes Job `.spec.completions` values are assigned to the wrong clusters when using divided replica scheduling.

---

**The Problem:**

In `ensureWork` (pkg/controllers/binding/common.go), two parallel slices are iterated with the same index `i`:

```go
// Line 69-109
for i := range targetClusters {
    targetCluster := targetClusters[i]
    ...
    if len(jobCompletions) > 0 {
        if err = helper.ApplyReplica(clonedWorkload, int64(jobCompletions[i].Replicas), 
            util.CompletionsField); err != nil {
            ...
        }
    }
}
```

However, these slices are in **different orders**:
- `targetClusters` preserves the scheduler's order from `ResourceBinding.Spec.Clusters`
- `jobCompletions` is alphabetically sorted by `AllocateWebsterSeats` (webstermethod.go:156-158)

This causes `jobCompletions[i]` to contain the completions value for a **different cluster** than `targetClusters[i]`.

---

**Impact:**

- **Silent data corruption**: Jobs receive wrong completions values with no error logs
- **Workload loss**: Clusters with too-few completions finish early, leaving work incomplete
- **Resource waste**: Clusters with too-many completions run duplicate work
- **Common scenario**: Any cluster names not alphabetically ordered (west/east, prod-us/prod-eu, cluster-b/cluster-a)

---

**Which issue(s) this PR fixes**:

Fixes #7382 

---

**Special notes for your reviewer**:

- Single file changed: `pkg/controllers/binding/common.go`
- The existing `Test_divideReplicasByJobCompletions` masks this bug because it uses equal weights (5/5) and sorts both slices before comparison
- Added regression test that verifies correct completions assignment with non-alphabetical cluster order
- No impact on non-Job workloads or Duplicated scheduling—only affects the Job completions branch

---
**Does this introduce a user-facing change?:**
```release-note
`karmada-controller-manager`: Fixed the issue that Job completions were assigned to the wrong replicas for each cluster.
```

### CODE REVIEW

**Comment by Ady0333** [comment]
Hello @XiShanYongYe-Chang!! Please review this pr and let me know if any changes are required.

**Comment by XiShanYongYe-Chang** [comment]
Thanks
Let me take a look.
The CI lint is failed, can you help fix it?

**Comment by Ady0333** [comment]
@XiShanYongYe-Chang , i have fixed the lint error. Please check it once...

**Comment by XiShanYongYe-Chang** [comment]
Hi @Ady0333, can you help update the release note, You can add the corresponding component name at the beginning according to the recommended writing method provided in the reminder. For example:

```
`karmada-controller-manager`: Fixed the issue that Job completions were assigned to the wrong replicas for each cluster.
```

**Comment by XiShanYongYe-Chang** [comment]
Thanks a lot @Ady0333 
/gemini review

**Comment by XiShanYongYe-Chang** [comment]
By the way, can you help squash the commits into one?

File: pkg/controllers/binding/common.go [hunk 1]
```diff
@@ -90,22 +98,9 @@ func ensureWork(
...
-			// setting this field as well.
-			// Refer to: https://kubernetes.io/docs/concepts/workloads/controllers/job/#parallel-jobs.
-			if err = helper.ApplyReplica(clonedWorkload, int64(jobCompletions[i].Replicas), util.CompletionsField); err != nil {
-				klog.ErrorS(err, "Failed to apply Completions for workload in cluster.",
-					"workloadKind", clonedWorkload.GetKind(), "workloadNamespace", clonedWorkload.GetNamespace(),
-					"workloadName", clonedWorkload.GetName(), "cluster", targetCluster.Name)
-				errs = append(errs, err)
-				continue
-			}
+		if err = applyJobCompletions(clonedWorkload, targetCluster.Name, jobCompletionsMap); err != nil {
```
Comment (zhzhuang-zju) [inline pkg/controllers/binding/common.go]:
```suggestion
		// jobSpec.Completions specifies the desired number of successfully finished pods the job should be run with.
		// When the replica scheduling policy is set to "divided", jobSpec.Completions should also be divided accordingly.
		// The weight assigned to each cluster roughly equals that cluster's jobSpec.Parallelism value. This approach helps
		// balance the execution time of the job across member clusters.
		if err = applyJobCompletions(clonedWorkload, targetCluster.Name, jobCompletionsMap); err != nil {
```

File: pkg/controllers/binding/job_completions_bug_test.go [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+
+import (
+	"testing"
+
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
+
+	workv1alpha2 "github.com/karmada-io/karmada/pkg/apis/work/v1alpha2"
+)
+
+// TestJobCompletionsCorrectAssignment verifies correct completions assignment
```
Comment (zhzhuang-zju) [inline pkg/controllers/binding/job_completions_bug_test.go]: We already have a `common_test.go`, so this unit test can be moved into it. Generally, we do not create a separate unit test file just for a single bugfix.

In addition, please refer to the format of other unit tests in `common_test.go`, which features higher information density and better scalability.

File: pkg/controllers/binding/common.go [hunk 3]
```diff
@@ -158,6 +153,33 @@ func ensureWork(
 	return errors.NewAggregate(errs)
 }
 
+// applyJobCompletions applies the divided completions value to a Job workload for a specific cluster.
+func applyJobCompletions(
+	workload *unstructured.Unstructured, clusterName string, completionsMap map[string]int32,
+) error {
```
[the remark this answers is not in the document]
Comment (zhzhuang-zju) [reply pkg/controllers/binding/common.go]: > Additionally, the function signature should preferably be written on a single line.

+1

File: pkg/controllers/binding/common.go [hunk 4]
```diff
@@ -90,22 +98,9 @@ func ensureWork(
...
-				klog.ErrorS(err, "Failed to apply Completions for workload in cluster.",
-					"workloadKind", clonedWorkload.GetKind(), "workloadNamespace", clonedWorkload.GetNamespace(),
-					"workloadName", clonedWorkload.GetName(), "cluster", targetCluster.Name)
-				errs = append(errs, err)
-				continue
-			}
+		if err = applyJobCompletions(clonedWorkload, targetCluster.Name, jobCompletionsMap); err != nil {
+			errs = append(errs, err)
+			continue
 		}
```
[the remark this answers is not in the document]
Comment (zhzhuang-zju) [reply pkg/controllers/binding/common.go]: Make sense to me, please check this @Ady0333

**Comment by zhzhuang-zju** [comment]
> Hi @Ady0333, can you help update the release note, You can add the corresponding component name at the beginning according to the recommended writing method provided in the reminder. For example:
> 
> ```
> `karmada-controller-manager`: Fixed the issue that Job completions were assigned to the wrong replicas for each cluster.
> ```

image

@Ady0333, also please make sure the release note is wrapped as shown above, this will help the release team to collect the release notes, thanks :)

**Comment by Ady0333** [comment]
@zhzhuang-zju Thanks for the review, I will make all the suggested changes.

**Comment by Ady0333** [comment]
@zhzhuang-zju I have made all the suggested changes. Please go through them once and ket me know if anything needs to be changed.

**Comment by XiShanYongYe-Chang** [comment]
@Ady0333  can you help squash the commits into one?

**Comment by Ady0333** [comment]
> @Ady0333 can you help squash the commits into one?

@XiShanYongYe-Chang I have squashed the commits as requested.

File: pkg/controllers/binding/common_test.go [hunk 5]
```diff
@@ -499,3 +499,76 @@ func Test_divideReplicasByJobCompletions(t *testing.T) {
...
+			}
+
+			got := make(map[string]int32, len(tt.targetClusters))
+			for _, targetCluster := range tt.targetClusters {
+				completions, ok := jobCompletionsMap[targetCluster.Name]
+				if !ok {
+					t.Fatalf("no completions found for cluster %s", targetCluster.Name)
+				}
+				got[targetCluster.Name] = completions
+			}
```
Comment (XiShanYongYe-Chang) [inline pkg/controllers/binding/common_test.go]: This test looks a little weird, not a test for a function, which leads to a lot of extra processing. I recommend testing the two new functions directly.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Other parts lgtm

File: pkg/controllers/binding/common.go [hunk 6]
```diff
@@ -158,6 +145,51 @@ func ensureWork(
...
+	if !ok {
+		return fmt.Errorf("no completions found for cluster %s", clusterName)
+	}
+
+	// Set allocated completions for Job only when the '.spec.completions' field not omitted from resource template.
+	// For jobs running with a 'work queue' usually leaves '.spec.completions' unset, in that case we skip
+	// setting this field as well.
+	// Refer to: https://kubernetes.io/docs/concepts/workloads/controllers/job/#parallel-jobs.
+	if err := helper.ApplyReplica(workload, int64(completions), util.CompletionsField); err != nil {
+		klog.ErrorS(err, "Failed to apply Completions for workload in cluster.",
```
Comment (zhzhuang-zju) [inline pkg/controllers/binding/common.go]:
```suggestion
```
Just a nit: move this log to the caller `ensureWork`.

Generally, low-level functions should avoid printing logs; it's up to the caller to decide whether logging is needed.

File: pkg/controllers/binding/common_test.go [hunk 7]
```diff
@@ -499,3 +499,76 @@ func Test_divideReplicasByJobCompletions(t *testing.T) {
...
+
+			if !reflect.DeepEqual(got, tt.want) {
```
Comment (zhzhuang-zju) [inline pkg/controllers/binding/common_test.go]: If I understand correctly, what you want to test is actually the function `buildJobCompletionsMap`, right?

**Review by zhzhuang-zju — COMMENTED** [review]
@Ady0333 Thanks, others LGTM

File: pkg/controllers/binding/common_test.go (hunk 5 above)
Comment (zhzhuang-zju) [reply pkg/controllers/binding/common_test.go]: Agree

File: pkg/controllers/binding/common_test.go (hunk 7 above)
Comment (Ady0333) [reply pkg/controllers/binding/common_test.go]: Yes, that's right. TestBuildJobCompletionsMap tests buildJobCompletionsMap directly. Also added TestApplyJobCompletions for the other helper function.

**Comment by Ady0333** [comment]
@zhzhuang-zju and @XiShanYongYe-Chang , I have made the suggested changes. Review them once and let me know if anything needs to be changed.

**Comment by XiShanYongYe-Chang** [comment]
Thanks @Ady0333 can you help squash the commits into one?

**Comment by Ady0333** [comment]
> Thanks @Ady0333 can you help squash the commits into one?

Yes @XiShanYongYe-Chang, I'll squash the commits into one.

**Comment by Ady0333** [comment]
@XiShanYongYe-Chang I have squashed the commits. Check them once

**Comment by XiShanYongYe-Chang** [comment]
Thanks @Ady0333 the CI is failed, let's wait it finished and retest it.

**Comment by Ady0333** [comment]
> Thanks @Ady0333 the CI is failed, let's wait it finished and retest it.

Okay!!!

**Comment by XiShanYongYe-Chang** [comment]
I created a backport issue to track the cherry-pick thing #7393
After this pr merged, can you help do it? @Ady0333

**Comment by Ady0333** [comment]
> I created a backport issue to track the cherry-pick thing #7393
> After this pr merged, can you help do it? @Ady0333 

Yes , I would like to help you

**Comment by Ady0333** [comment]
@XiShanYongYe-Chang I think you forget to write "/lgtm" as this is not getting merged. Apologies if I am wrong!!!

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang I think you forget to write "/lgtm" as this is not getting merged. Apologies if I am wrong!!!

No, I want @zhzhuang-zju to take another look and see if he has any other opinions.
cc @zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
Thanks
/lgtm
