### PR TITLE
labels cannot be deleted via Karmada propagation

### LINKED ISSUE #4781: Unable to sync labels correctly
**What happened**:
I created a resource template to propagate to member clusters, but cannot delete any label which already exists via Karmada.
### ConfigMap of Karmada control-plane
image
### ConfigMap of Member clusters
image

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create any resource to propagate to member clusters.
2. Add any label to your resource via Karmada.
3. Delete the label via Karmada.

**Anything else we need to know?**:
I found the propagated resource is missing the annotation `resourcetemplate.karmada.io/managed-labels`, and the annotation was mistakenly added to the work object.
image

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #4781

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmada-controller-manager: Fix the problem that labels cannot be deleted via Karmada propagation.
```

### CODE REVIEW

File: pkg/util/helper/work.go [hunk 1]
```diff
@@ -82,7 +83,6 @@ func CreateOrUpdateWork(client client.Client, workMeta metav1.ObjectMeta, resour
 			if util.GetLabelValue(runtimeObject.Labels, workv1alpha2.WorkPermanentIDLabel) == "" {
 				runtimeObject.Labels = util.DedupeAndMergeLabels(runtimeObject.Labels, map[string]string{workv1alpha2.WorkPermanentIDLabel: uuid.New().String()})
 			}
-			util.RecordManagedLabels(runtimeObject)
```
Comment (chaunceyjiang) [inline pkg/util/helper/work.go:85]: Oh, great find! The `workv1alpha2.ManagedLabels` should be recorded on the `workload` rather than the `work`.

Can you post a screenshot of your fixed test results?


LGTM

/cc @RainbowMango @XiShanYongYe-Chang PTAL.

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/assign

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
Thanks~
I think we need to cherry-pick this patch to the preview v1.8 and v1.9, how do you think?

**Comment by XiShanYongYe-Chang** [comment]
@whitewindmills  can you help add the release-note?

File: pkg/util/helper/work.go (hunk 1 above)
Comment (RainbowMango) [reply pkg/util/helper/work.go:85]: LGTM
thanks.

Comment (whitewindmills) [reply pkg/util/helper/work.go:85]: > Can you post a screenshot of your fixed test results?

of course.
test label: `foo: bar`
exam

**Comment by whitewindmills** [comment]
@XiShanYongYe-Chang done.

**Review by RainbowMango — APPROVED** [review]
/approve
