### PR TITLE
fix: update service failed when reconcile

### LINKED ISSUE #4639: Update etcd-client service failed
**What happened**:
cf83c0d6415d26e66e38f875060e8e57

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
karmada-operator installs
**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.9.0-preview3
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
- Kubernetes version: v1.20.8

### PR DESCRIPTION
**Pull request by laihezhao**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

I deploy the karmada control plane by karmada-operator

when i modify the karmada CR, I hope the karmada-operator  redploy the karmada control plane

But I'm getting the following error

cf83c0d6415d26e66e38f875060e8e57

**Which issue(s) this PR fixes**:
Fixes #4639

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: operator/pkg/util/apiclient/idempotency.go [hunk 1]
```diff
@@ -107,6 +107,8 @@ func CreateOrUpdateService(client clientset.Interface, service *corev1.Service)
 		}
 
 		service.ResourceVersion = older.ResourceVersion
+		service.Spec.ClusterIP = older.Spec.ClusterIP
+		service.Spec.ClusterIPs = older.Spec.ClusterIPs
```
Comment (RainbowMango) [inline operator/pkg/util/apiclient/idempotency.go:111]: Looks good to me as we mostly use service with the `ClusterIP` type, and the IP can not be reset to none.
/assign @calvin0327

**Comment by RainbowMango** [comment]
Hi @laihezhao Seems GitHub still recognize you as the `first-time contributor`, please see the recommendation at https://github.com/karmada-io/karmada/pull/4645#issuecomment-1956060041.

**Comment by calvin0327** [comment]
thanks. it's good to me.

/lgtm

**Comment by laihezhao** [comment]
@RainbowMango https://github.com/karmada-io/karmada/issues/3362 Does the issues will be repaired in v1.9?

**Review by RainbowMango — APPROVED** [review]
/approve
I guess @calvin0327 forgot to approve it.
