### PR TITLE
fix issue that Scheduler do not schedule resourcebinding generated fr…

### LINKED ISSUE #373: The Scheduler not prepare for handling resourcebinding generated by clusterpropagationpolicy
**What happened**:
`Scheduler` do not schedule `resourcebinding` generated by `clusterpropagationpolicy`, since it expected `PropagationPolicyNameLabel` and `PropagationPolicyNamespaceLabel` do not existed(since by `clusterpropagationpolicy` not `propagationpolicy`)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

### PR DESCRIPTION
**Pull request by vincent-pli**
fix issue #373 

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #373 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -267,19 +267,40 @@ func (s *Scheduler) getScheduleType(key string) ScheduleType {
 			return FirstSchedule
 		}
 
-		policyNamespace := util.GetLabelValue(resourceBinding.Labels, util.PropagationPolicyNamespaceLabel)
-		policyName := util.GetLabelValue(resourceBinding.Labels, util.PropagationPolicyNameLabel)
+		var placement policyv1alpha1.Placement
+		var clusterPolicyName string
+		var policyName string
+		var policyNamespace string
```
Comment (mrlihanbo) [inline pkg/scheduler/scheduler.go:273]: var clusterPolicyName, policyName, policyNamespace string     
How about define the variables like this?

Comment (RainbowMango) [reply pkg/scheduler/scheduler.go:273]: We don't have such an agreement.

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -267,19 +267,40 @@ func (s *Scheduler) getScheduleType(key string) ScheduleType {
...
+			if clusterPolicyName != "" {
+				klog.Errorf("Failed to marshal placement of clusterPropagationPolicy %s, error: %v", clusterPolicyName, err)
+			} else {
+				klog.Errorf("Failed to marshal placement of propagationPolicy %s/%s, error: %v", policyNamespace, policyName, err)
+			}
+
 			return Unknown
 		}
-		policyPlacementStr := string(placement)
+		policyPlacementStr := string(placements)
```
Comment (RainbowMango) [inline pkg/scheduler/scheduler.go:303]: Can we abstract a method to get the `placementStr`?

Comment (RainbowMango) [reply pkg/scheduler/scheduler.go:303]: Then we can have unit testing to cover and more readable.

Comment (vincent-pli) [reply pkg/scheduler/scheduler.go]: make sense, please take a look the new version @RainbowMango

File: pkg/scheduler/scheduler.go [hunk 3]
```diff
@@ -267,19 +313,10 @@ func (s *Scheduler) getScheduleType(key string) ScheduleType {
...
 
-		policyNamespace := util.GetLabelValue(resourceBinding.Labels, util.PropagationPolicyNamespaceLabel)
-		policyName := util.GetLabelValue(resourceBinding.Labels, util.PropagationPolicyNameLabel)
-
-		policy, err := s.policyLister.PropagationPolicies(policyNamespace).Get(policyName)
-		if err != nil {
-			return Unknown
-		}
-		placement, err := json.Marshal(policy.Spec.Placement)
+		_, policyPlacementStr, err := s.getPlacement(resourceBinding)
```
Comment (RainbowMango) [inline pkg/scheduler/scheduler.go:316]: Yeah, much better now. 
We can use this function for `ClusterResourceBinding` below, right? why not?

**Comment by RainbowMango** [comment]
@mrlihanbo 
Can you help to test this patch locally? Seems there is no E2E case cover it yet (we can plan to add in the future).
v0.6 is coming soon, this path is important and should be in this release.

File: pkg/scheduler/scheduler.go (hunk 3 above)
Comment (vincent-pli) [reply pkg/scheduler/scheduler.go:316]: Yes, I consider it when implementing, no specific reason to not adopt it.
So you prefer to make them consistent?

Comment (vincent-pli) [reply pkg/scheduler/scheduler.go:316]: I consider it when implementing, since for `ClusterPropagationPolicy` case, it's `ClusterResourceBinding` rather than `ResourceBinding`, so it's will complex the util function. and the logic for `ClusterResourceBinding` is simple and straightforward, so I leave it there.

**Comment by mrlihanbo** [comment]
@RainbowMango ok, I will test it locally today

**Comment by mrlihanbo** [comment]
@RainbowMango @vincent-pli I have tested it locally,  and I found two bugs here.    
1. ResourceBinding can't be rescheduled when placement of ClusterPropagationPolicy update.   https://github.com/karmada-io/karmada/blob/master/pkg/scheduler/scheduler.go#L219-L246
2. ResourceBinding is not delete when ClusterPropagationPolicy is delete.   https://github.com/karmada-io/karmada/blob/master/pkg/util/detector/detector.go#L729-L756

**Comment by RainbowMango** [comment]
Yeah, nice catch. The two bugs aren't introduced by this patch, we still have things to do after this patch. right? 

If yes, I'm going to merge this patch first, and then fix them by following PRs, how do you think?

**Comment by mrlihanbo** [comment]
Yes, you can merge this patch first, and then fix them by following PRs
