### PR TITLE
Fix unreasonable informer manager stop behavior

### LINKED ISSUE #6598: Revisit Current Informer Stop Behavior
**What would you like to be added**:
Karmada, as a multi-cluster project, leverages the informer mechanism to handle resources from different member clusters as well as control plane resources. This approach significantly reduces the pressure on both karmada-apiserver and member cluster kube-apiservers.

Many informers are dynamically loaded, which greatly increases the complexity of informer management. Among these operations, `informer.Stop()` is particularly high-risk.

The current codebase contains various `informer.Stop()` calls that may have inconsistent or potentially problematic behavior patterns. This issue aims to comprehensively review and refactor the `informer.Stop()` behavior.

This presents an example of problematic informer shutdown behavior. Both the `execution controller` and `serviceExportController` share the same `MultiClusterInformerManager` instance obtained via `genericmanager.GetInstance()`. 
https://github.com/karmada-io/karmada/blob/b8f6874c5896b877b85b528f4e4b13ec0b59e615/pkg/util/fedinformer/genericmanager/multi-cluster-manager.go#L35-L40
When the `serviceExportController` encounters cache synchronization failures or timeouts for `serviceexports` and `endpointslices` resources, it terminates all informers for the affected cluster. 
https://github.com/karmada-io/karmada/blob/b8f6874c5896b877b85b528f4e4b13ec0b59e615/pkg/controllers/mcs/service_export_controller.go#L275-L290
This shutdown operation has a cascading effect on other controllers that are actively utilizing informers for the same cluster, thereby broadening the impact radius beyond the original failing component.

**Why is this needed**:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Ref to #6598, the unreasonable SingleClusterInformerManager stop behavior has a cascading effect on other controllers that are actively utilizing informers for the same cluster, thereby broadening the impact radius beyond the original failing component. So, in this pr, we try to remove the unreasonable SingleClusterInformerManager stop behaviors.

Fixed behavior:

1. pkg/controllers/mcs/service_export_controller.go#L275-L290
2. pkg/controllers/multiclusterservice/endpointslice_collect_controller.go#L212-L229
3. pkg/controllers/status/work_status_controller.go#L488-L502
4. pkg/controllers/status/cluster_status_controller.go#L380-L395

When `InformerManager.WaitForCacheSyncWithTimeout` returns a result that doesn't contain the target GVR, it will return an error and re-enter reconcile.

5. pkg/controllers/federatedhpa/federatedhpa_controller.go#L569-L582

When a single cluster's `InformerManager.WaitForCacheSyncWithTimeout` returns a result that doesn't contain the target GVR, this error will be ignored unless all target clusters encounter similar issues. The federated_hpa_controller will re-enter reconcile every HorizontalPodAutoscalerSyncPeriod, so it has the opportunity to re-execute `WaitForCacheSyncWithTimeout`.

In summary, all the above controllers have the opportunity to retry when the `WaitForCacheSyncWithTimeout` result doesn't meet expectations. And retries should be able to resolve most failures, except for the issues documented in https://github.com/karmada-io/karmada/issues/6598#issuecomment-3154216918. However, this issue was not introduced by this PR, so it's not considered in this PR.

**Which issue(s) this PR fixes**:

Fixes #6598

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager/karmada-agent`:  Fixed the issue that informer cache sync failures for specific resources incorrectly shut down all informers for that cluster, affecting resource distribution and work status synchronization.
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/assign

File: pkg/controllers/status/cluster_status_controller.go [hunk 1]
```diff
@@ -390,7 +390,6 @@ func (c *ClusterStatusController) buildInformerForCluster(clusterClient *util.Cl
 		return nil
 	}(); err != nil {
 		klog.ErrorS(err, "Failed to sync cache for cluster", "cluster", clusterClient.ClusterName)
-		c.TypedInformerManager.Stop(clusterClient.ClusterName)
```
Comment (RainbowMango) [inline pkg/controllers/status/cluster_status_controller.go:393]: PS:
The background of why it stops the informer is for disabling annoying warning logs :( 
https://github.com/karmada-io/karmada/pull/894#discussion_r1045377367

Obviously, it's not the right approach.

**Review by RainbowMango — COMMENTED** [review]
/approve

/hold
cc @lyuyun to take another look.

@snowplayfire We introduced `--cluster-cache-sync-timeout` flag at https://github.com/karmada-io/karmada/pull/1112, but it seems not enough, the fundamental flaw is due to close the entire informer factory abruptly . 

While adjusting timeout parameters may avoid this same issue described at #1112, but other users will encounter this problem again, because they might don't know this flag.

I don't know the configuration of `--cluster-cache-sync-timeout` in your environment, but I'm sure this issue is still concerning, for both you and other users. 

Any thoughs?

**Comment by RainbowMango** [comment]
/kind bug
@zhzhuang-zju Please add a release note and this should be backported to release branches.

**Comment by zhzhuang-zju** [comment]
> /kind bug @zhzhuang-zju Please add a release note and this should be backported to release branches.

Done~ I'll submit an issue to track the backport tasks once this pr is merged
