### PR TITLE
Fix segmentation violation error in `agent` component

### LINKED ISSUE #6213: Fix segmentation violation error in `agent` component
**What happened**:
When the [report-secrets](https://github.com/karmada-io/karmada/blob/release-1.13/cmd/agent/app/options/options.go#L202) flag is set to `None` in the `agent` component, cluster and cluster impersonator secrets will not be generated.  However, those secret pointers will still be dereferenced in the code, resulting in a segmentation violation.

**What you expected to happen**:
We should not dereference the secret pointers if no secrets were generated.

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce, run the `agent` component with the `report-secrets` flag set to `None`.

**Anything else we need to know?**:

**Environment**: N/A
- Karmada version: 1.13
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by jabellard**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
When the [report-secrets](https://github.com/karmada-io/karmada/blob/release-1.13/cmd/agent/app/options/options.go#L202) flag is set to `None` in the `agent` component, cluster and cluster impersonator secrets will not be generated.  However, those secret pointers will still be dereferenced in the code, resulting in a segmentation violation.

**Which issue(s) this PR fixes**:
Fixes #6213

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-agent`: Fixed a panic issue where the agent does not need to report secure when registering cluster.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @zhzhuang-zju can you help take a look?
/cc @zhzhuang-zju

File: cmd/agent/app/agent.go [hunk 1]
```diff
@@ -184,8 +184,12 @@ func run(ctx context.Context, opts *options.Options) error {
...
 		return err
 	}
-	registerOption.Secret = *clusterSecret
-	registerOption.ImpersonatorSecret = *impersonatorSecret
+	if clusterSecret != nil {
+		registerOption.Secret = *clusterSecret
+	}
+	if impersonatorSecret != nil {
+		registerOption.ImpersonatorSecret = *impersonatorSecret
+	}
```
Comment (RainbowMango) [inline cmd/agent/app/agent.go:192]: We might need to revisit the `util.ObtainCredentialsFromMemberCluster`, it looks weird because if the `karmada-agent` doesn't need to report secret , it doesn't have to `try obtain credentials` in the first place.

Comment (zhzhuang-zju) [reply cmd/agent/app/agent.go:192]: https://github.com/karmada-io/karmada/blob/236126bd984284d35088099e0d36697eba93ed26/pkg/util/credential.go#L121-L131

It also looks weird here. If it's in a dry-run mode, nothing should have been done previously.

Comment (RainbowMango) [reply cmd/agent/app/agent.go:192]: No.

We can take this as a minimal fix.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Thanks Joe, would you like to backport this to release-1.13, release-1.12, and release-1.11?

**Comment by jabellard** [comment]
> /lgtm /approve
> 
> Thanks Joe, would you like to backport this to release-1.13, release-1.12, and release-1.11?

Just summited PRs for that: [1.13](https://github.com/karmada-io/karmada/pull/6222), [1.12](https://github.com/karmada-io/karmada/pull/6223), and [1.11](https://github.com/karmada-io/karmada/pull/6224),

**Comment by RainbowMango** [comment]
Thanks Joe!
