### PR TITLE
When using MCS and MCI simultaneously, prevent resource residuce caused by deleting MCS and MCI

### LINKED ISSUE #6616: Orphaned EndpointSlice Works After Deleting Shared MCI/MCS
**What happened**:
When deleting both a MultiClusterIngress (MCI) and MultiClusterService (MCS) that share the same underlying Service resource, the Work objects created by Karmada to manage EndpointSlices occasionally fail to be cleaned up. This results in orphaned Work resources in the Karmada control plane.
After deleting the MCI and MCS objects, kubectl get work shows lingering Work resources (e.g., karmada-es-<clustername>/test-8tm9m-cd6f88594).

**What you expected to happen**:
All Work resources associated with the MCI/MCS objects (including those managing EndpointSlices) should be ​automatically deleted​ when the parent MCI or MCS is removed. The control plane should not retain orphaned resources.

**How to reproduce it (as minimally and precisely as possible)**:
1. **Deploy a shared Service**:

   ```yaml
   apiVersion: v1  
   kind: Service  
   metadata:  
     name: test  
     namespace: default  
   spec:  
     ports:  
     - port: 80  
     selector:  
       app: nginx  
   ```

   Propagate this `Service` to member clusters `m1` and `m2` using a `PropagationPolicy`.

2. **Create the MCS**:

   ```yaml
   apiVersion: networking.karmada.io/v1alpha1  
   kind: MultiClusterService  
   metadata:  
     name: test-mcs  
     namespace: default  
   spec:  
     consumerClusters:  
     - name: m1  
     providerClusters:  
     - name: m2  
     range: {}  
     types:  
     - CrossCluster  
   ```

3. **Create the MCI**:

   ```yaml
   apiVersion: networking.karmada.io/v1alpha1  
   kind: MultiClusterIngress  
   metadata:  
     name: test-mci  
     namespace: default  
   spec:  
     ingressClassName: public-elb  
     rules:  
     - http:  
         paths:  
         - backend:  
             service:  
               name: test  # Same Service as MCS  
               port:  
                 number: 80  
           path: /  
           pathType: Prefix  
   ```

4. **Delete both MCI and MCS**:

   ```bash
   kubectl delete mci test-mci  
   kubectl delete mcs test-mcs  
   ```

5. **Check for orphaned Work resources**:

   ```bash
   kubectl get work -A | grep "endpointslice"  
   # Example lingering Work:  
   # karmada-es-m1/test-8tm9m-cd6f88594  
   ```

   **Frequency**: Occurs in ~30% of deletion attempts.

**Anything else we need to know?**:
​Root Cause: Likely a race condition in Karmada's finalizer logic:
The EndpointSlice-related Work resources have finalizers (e.g., karmada.io/mcs-endpointslice-dispatch-controller) that fail to resolve when the shared Service is referenced by both MCI and MCS 

**Environment**:
- Karmada version: 1.14
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

ref https://github.com/karmada-io/karmada/issues/6616#issuecomment-3173153743

**Which issue(s) this PR fixes**:

Fixes #6616

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed the issue that endpointslice and work resources residuce when using MCS and MCI simultaneously and then deleting them.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
/cc @GitHubxsy @RainbowMango 
Hi, guys, can you help take a review?

**Comment by XiShanYongYe-Chang** [comment]
Test report:

When I create both MultiClusterIngress and MultiClusterService in the Karmada, the EndpointSlice Work which is collected from member cluster:

```
apiVersion: work.karmada.io/v1alpha1
kind: Work
metadata:
  creationTimestamp: "2025-08-11T12:01:08Z"
  finalizers:
  - karmada.io/endpointslice-controller
  - karmada.io/mcs-endpointslice-dispatch-controller
  generation: 2
  labels:
    endpointslice.karmada.io/managed-by: MultiClusterService.ServiceExport
    endpointslice.karmada.io/name: serve
    endpointslice.karmada.io/namespace: default
    multiclusterservice.karmada.io/name: serve
    multiclusterservice.karmada.io/namespace: default
    work.karmada.io/permanent-id: 2ca465d6-ff1d-41cc-a523-f4644e2a2517
  name: serve-nzq7q-66d9c4dbb
  namespace: karmada-es-member1
```

File: pkg/util/finalizer.go [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+	if len(finalizerSet) == 0 {
+		return []string{}
+	}
+
+	result := make([]string, 0, len(finalizerSet))
+	for f := range finalizerSet {
+		result = append(result, f)
+	}
+	sort.Strings(result)
+	return result
```
Comment (RainbowMango) [inline pkg/util/finalizer.go]:
```suggestion
	finalizers := sets.New[string](existFinalizers...).Insert(newFinalizers...)
	return sets.List[string](finalizers)
```
We can use the sets for convenience. Any thoughts?
