### PR TITLE
fix: use QuotaExceeded reason when FederatedResourceQuota is exceeded

### LINKED ISSUE #7069: QuotaExceeded reason is not being used when FRQ exceeded limits
**What happened**:
This is low-priority but thought I'd file an issue regardless. I noticed that the condition which is appended to the RB in cases of FRQ limits being exceeded is no longer using the `QuotaExceeded` reason, but rather using the generic `SchedulerError`. This feels incorrect since quota being exceeded isn't a scheduler error. 

This was changed during a refactor of the RB validation webhook: https://github.com/karmada-io/karmada/pull/6611/files#diff-b8020421c760e9ea07cb49bd49e3604078f0351faaa7f60e3b13e7f372ea73adL326

We can either fix the validating webhook to append this custom error reason, or change the way the error is handled in the scheduler to parse the error message, instead of checking for the `QuotaExceeded` reason. 

**What you expected to happen**:

Condition should be appended with the correct reason. Example:

```yaml
status:
  conditions:
  - lastTransitionTime: "2026-01-02T19:35:30Z"
    message: 'admission webhook "resourcebinding.karmada.io" denied the request: FederatedResourceQuota(s-spaaseng/federated-quota)
      exceeded for resource cpu: requested sum 32500m, limit 30.'
    reason: QuotaExceeded
    status: "False"
    type: Scheduled
```

**Environment**:
- Karmada version: 1.16

### PR DESCRIPTION
**Pull request by kajal-jotwani**
**What type of PR is this?**

**What this PR does / why we need it**:
Fixes the admission webhook to return the specific QuotaExceeded reason (and 403 status) when FRQ limits are hit, instead of a generic error. Added a buildDenyResponse helper to handle this case and updated tests to verify.

**Which issue(s) this PR fixes**:

Fixes #7069 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-webhook`: Fixed an issue where the `condition.reason` was not set to `QuotaExceeded` when FederatedResourceQuota is exceeded.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/retest
It is unrelated.
https://github.com/karmada-io/karmada/actions/runs/20720286612/job/59482638502?pr=7086
```
[FAILED] in [It] - /home/runner/work/karmada/karmada/test/e2e/suites/base/karmadactl_test.go:596 @ 01/05/26 15:53:31.367
  STEP: Removing PropagationPolicy(karmadatest-zrvdm/pod-6n7h6) @ 01/05/26 15:53:31.812
  STEP: Removing Pod(karmadatest-zrvdm/pod-bgfqq) @ 01/05/26 15:53:31.826
  << Timeline

  [FAILED] Unexpected error:
      <exec.CodeExitError>: 
      error running /home/runner/go/bin/karmadactl --kubeconfig=/home/runner/.kube/karmada.config --karmada-context=karmada-apiserver --namespace=karmadatest-zrvdm top pod pod-bgfqq -n karmadatest-zrvdm -C member1:
      Command stdout:
      
      stderr:
      error: cluster(member1): podmetrics.metrics.k8s.io "karmadatest-zrvdm/pod-bgfqq" not found
      
      error:
      exit status 1
      {
          Err: <*errors.errorString | 0xc000389030>{
              s: "error running /home/runner/go/bin/karmadactl --kubeconfig=/home/runner/.kube/karmada.config --karmada-context=karmada-apiserver --namespace=karmadatest-zrvdm top pod pod-bgfqq -n karmadatest-zrvdm -C member1:\nCommand stdout:\n\nstderr:\nerror: cluster(member1): podmetrics.metrics.k8s.io \"karmadatest-zrvdm/pod-bgfqq\" not found\n\nerror:\nexit status 1",
          },
          Code: 1,
      }
  occurred
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/suites/base/karmadactl_test.go:596 @ 01/05/26 15:53:31.367

  Full Stack Trace
    github.com/karmada-io/karmada/test/e2e/suites/base.init.func32.2.2.1()
    	/home/runner/work/karmada/karmada/test/e2e/suites/base/karmadactl_test.go:596 +0x98
    github.com/karmada-io/karmada/test/e2e/suites/base.init.func32.2.2()
    	/home/runner/work/karmada/karmada/test/e2e/suites/base/karmadactl_test.go:592 +0x90
```

File: pkg/webhook/resourcebinding/validating.go [hunk 1]
```diff
@@ -301,6 +302,23 @@ func (v *ValidatingAdmission) decodeRBs(req admission.Request) (
 	return decodedRB, decodedOldRB, nil
 }
 
+func buildDenyResponse(errMsg string) admission.Response {
+	if strings.Contains(errMsg, "FederatedResourceQuota") && strings.Contains(errMsg, "exceeded") {
```
Comment (RainbowMango) [inline pkg/webhook/resourcebinding/validating.go]: @zhzhuang-zju could you please help confirm if we need to match the error message here?

Comment (zhzhuang-zju) [reply pkg/webhook/resourcebinding/validating.go]: I'm afraid so. The scheduler distinguishes specific scenarios by the return code and predefined reason from the webhook. The corresponding return code for `quota exceeded` is 403, with the reason being **QuotaExceeded**. For this purpose, the corresponding return code and reason need to be set when the webhook denies a request.
https://github.com/karmada-io/karmada/blob/050353ee8fe8d73020db24d32eae7226ad9f9629/pkg/scheduler/helper.go#L140-L142

I can confirm this behavior is necessary, but I need to look over the implementation method again.

In addition, this also exposes an issue with the E2E test. At present, it only checks the `status` and `type` of the condition; other fields such as `condition.reason` also require attention.
https://github.com/karmada-io/karmada/blob/050353ee8fe8d73020db24d32eae7226ad9f9629/test/e2e/suites/base/federatedresourcequota_test.go#L446

Comment (RainbowMango) [reply pkg/webhook/resourcebinding/validating.go]: > In addition, this also exposes an issue with the E2E test. At present, it only checks the status and type of the condition; other fields such as condition.reason also require attention.

+1

**Comment by zhzhuang-zju** [comment]
@kajal-jotwani Thanks for your work! The AI review pointed out that using string matching is rather fragile, which is also a concern of mine.

Could we enhance the matching by using error types? For example:

1. Define `quotaExceededError`:
```go
type quotaExceededError struct {
	errMsg string
}

func (q *quotaExceededError) Error() string {
	return q.errMsg
}
```

2. Return `quotaExceededError` when the quota is exceeded:
```go
return nil, "", &quotaExceededError{errMsg: errMsg}
```

3. Check if the error is a `quotaExceededError` when the webhook denies a request:
```go
		var quotaExceededErr *quotaExceededError
		if !errors.As(err, &quotaExceededErr) {
			klog.Errorf("[QuotaExceeded] Admission denied for ResourceBinding %s/%s: %v", rb.Namespace, rb.Name, err)
			return quotaExceededDeniedResponse
		}
```

File: pkg/webhook/resourcebinding/validating.go (hunk 1 above)
Comment (zhzhuang-zju) [reply pkg/webhook/resourcebinding/validating.go]: > In addition, this also exposes an issue with the E2E test. At present, it only checks the status and type of the condition; other fields such as condition.reason also require attention.

@kajal-jotwani Would you be willing to fix this issue? If so, it would be great to address it in this PR to ensure the correctness of the code being merged.

Comment (kajal-jotwani) [reply pkg/webhook/resourcebinding/validating.go]: @zhzhuang-zju Yes, definitely. I’ll work on it and address all the issues in this PR.

**Comment by kajal-jotwani** [comment]
@zhzhuang-zju I’ve made the suggested changes. The quota-exceeded handling now uses a typed error instead of string matching, and the webhook returns the correct status code and reason. I’ve also updated the E2E tests to validate the condition reason along with the status.

File: test/e2e/suites/base/federatedresourcequota_test.go [hunk 2]
```diff
@@ -443,7 +443,11 @@ var _ = ginkgo.Describe("FederatedResourceQuota enforcement testing", func() {
 					if err != nil {
 						return false
 					}
-					return rb != nil && meta.IsStatusConditionPresentAndEqual(rb.Status.Conditions, workv1alpha2.Scheduled, metav1.ConditionFalse)
+					if rb == nil {
+						return false
+					}
+					cond := meta.FindStatusCondition(rb.Status.Conditions, workv1alpha2.Scheduled)
+					return cond != nil && cond.Status == metav1.ConditionFalse && cond.Reason == workv1alpha2.BindingReasonQuotaExceeded
```
Comment (zhzhuang-zju) [inline test/e2e/suites/base/federatedresourcequota_test.go:450]: We could try to wrap this in a function, but it's not a big deal.

**Review by zhzhuang-zju — COMMENTED** [review]
Thanks @kajal-jotwani 
/lgtm
cc @RainbowMango

**Comment by RainbowMango** [comment]
Looks good to me, but would you mind [squashing the commits](https://karmada.io/docs/next/contributor/github-workflow/#squash-commits)? @kajal-jotwani

**Comment by kajal-jotwani** [comment]
> Looks good to me, but would you mind [squashing the commits](https://karmada.io/docs/next/contributor/github-workflow/#squash-commits)? @kajal-jotwani

@RainbowMango Squashed the commits. Thanks for the review!

**Comment by zhzhuang-zju** [comment]
/kind bug

We might need to add a release note. How about
```release-note
`karmada-webhook`: Fixed an issue where the `condition.reason` was not set to `QuotaExceeded` when FederatedResourceQuota is exceeded.
```

**Comment by zhzhuang-zju** [comment]
This fix needs to be backported to `release-1.15` and `release-1.16`. 
@kajal-jotwani, would you be interested in submitting a PR for this? FYI: You can use the script `hack/cherry_pick_pull.sh` to help with the backport.

**Comment by kajal-jotwani** [comment]
> This fix needs to be backported to `release-1.15` and `release-1.16`. @kajal-jotwani, would you be interested in submitting a PR for this? FYI: You can use the script `hack/cherry_pick_pull.sh` to help with the backport.

@zhzhuang-zju Yes sure I'll submit a pr for it.

**Comment by zhzhuang-zju** [comment]
@kajal-jotwani Great thanks, I'll create an issue and assign it to you.
