### PR TITLE
fix spreadconstraints[i].MaxGroups Invalidation when scaleup replicas

### LINKED ISSUE #1323: spreadconstraints[i].MaxGroups invalidate when scaleup replicas
**What happened**:
spreadconstraints[i].MaxGroups invalidate when scaleup replicas and the target cluster number  is 3 > MaxGroups(2)
**What you expected to happen**:
the cluster number is in [minGroups, maxGroups]

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
step1: kubectl apply -f deploy.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 110
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```
step 2: kubectl apply -f pp.yaml and check the resource binding
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    spreadConstraints:
      - spreadByField: cluster
        maxGroups: 2
        minGroups: 1
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided
```
```
spec:
    clusters:
    - name: member1
      replicas: 56
    - name: member3
      replicas: 54
    replicas: 110
```
step 3: kubectl scale deployment nginx --replicas=180
            check the resouce binding and the cluster number is 3 > maxGroups
```
spec:
    clusters:
    - name: member3
      replicas: 76
    - name: member2
      replicas: 48
    - name: member1
      replicas: 56
    replicas: 180
```
**Environment**:
hack/local-up-karmada.sh and  add a cluster member4
```
[root@esc-hwx yaml]# kubectl get cluster
NAME      VERSION   MODE   READY   AGE
member1   v1.22.0   Push   True    6d3h
member2   v1.22.0   Push   True    6d3h
member3   v1.22.0   Pull   True    6d3h
member4   v1.21.1   Push   True    5d14h
```
- Karmada version: make images in branch master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- 
- Others:

### PR DESCRIPTION
**Pull request by huone1**
Signed-off-by: huone1 <huwanxing@huawei.com>

**What type of PR is this?**
/kind bug
**What this PR does / why we need it**:
because the spreadconstraints[i].maxgroup define the max cluster number, So the target cluster number  could not  be greater than it in any scenario.

The difference between the current cluster and the scheduled cluster is not considered when calculating the scheduled replicas
**Which issue(s) this PR fixes**:
Fixes #1323 

let's test it According to the issue #1323  operation

before scaleup
```
spec:
    clusters:
    - name: member1
      replicas: 55
    - name: member2
      replicas: 55
    replicas: 110
```

after scaleup
```
spec:
    clusters:
    - name: member2
      replicas: 95
    - name: member3
      replicas: 85
    replicas: 180
```
**Special notes for your reviewer**:
NONE
**Does this PR introduce a user-facing change?**:

```release-note
fix spreadconstraints[i].MaxGroups is invalidated in some scenarios
```

### CODE REVIEW

**Comment by Garrybest** [comment]
Thanks @huone1, I will check it later.

**Comment by Garrybest** [comment]
This PR generally LGTM. But I'm a little curious about how does the `spreadConstraint` choose the available clusters? 

Taken #1323 as an example. We divided 56 replicas into `member1` and 54 replicas `member3`. When scaling up additional 70 replicas, it seems like we can't accommodate more available replicas in `member1`. If resource is enough, we should scheduled all additional replicas in to member1 but the final replica is 56. 

How does the `spreadConstraint` choose the right clusters? Why not still choose `member1` and `member3` again?

/cc @mrlihanbo

**Comment by huone1** [comment]
> This PR generally LGTM. But I'm a little curious about how does the `spreadConstraint` choose the available clusters?
> 
> Taken #1323 as an example. We divided 56 replicas into `member1` and 54 replicas `member3`. When scaling up additional 70 replicas, it seems like we can't accommodate more available replicas in `member1`. If resource is enough, we should scheduled all additional replicas in to member1 but the final replica is 56.
> 
> How does the `spreadConstraint` choose the right clusters? Why not still choose `member1` and `member3` again?
> 
> /cc @mrlihanbo

the PR #1334   add dd plugin *clusterLocality* to favors cluster that already have requested

**Comment by Garrybest** [comment]
Got it, nice work👍
/lgtm

File: pkg/scheduler/core/util.go [hunk 1]
```diff
@@ -91,11 +93,13 @@ func findOutScheduledCluster(tcs []workv1alpha2.TargetCluster, candidates []*clu
...
 			if targetCluster.Name == cluster.Name {
 				res.Insert(targetCluster.Name)
+				validTarget = append(validTarget, targetCluster)
 				break
 			}
 		}
 	}
-	return res
+
+	return res, validTarget
```
Comment (RainbowMango) [inline pkg/scheduler/core/util.go:102]: The `res` could be calculated by `validTarget`, I suggest remove it.
```diff
diff --git a/pkg/scheduler/core/division_algorithm.go b/pkg/scheduler/core/division_algorithm.go
index e0b2c082..689b8231 100644
--- a/pkg/scheduler/core/division_algorithm.go
+++ b/pkg/scheduler/core/division_algorithm.go
@@ -210,7 +210,7 @@ func scaleUpScheduleByReplicaDivisionPreference(
        preference policyv1alpha1.ReplicaDivisionPreference,
 ) ([]workv1alpha2.TargetCluster, error) {
        // Step 1: Find the clusters that have old replicas, so we can prefer to assign new replicas towards them.
-       scheduledClusterNames, scheduledClusters := findOutScheduledCluster(spec.Clusters, clusters)
+       scheduledClusters := findOutScheduledCluster(spec.Clusters, clusters)

        // Step 2: calculate the assigned Replicas in scheduledClusters
        assignedReplicas := util.GetSumOfReplicas(scheduledClusters)
@@ -229,7 +229,7 @@ func scaleUpScheduleByReplicaDivisionPreference(
        // If not, the old replicas may be recreated which is not expected during scaling up.
        // The parameter `scheduledClusterNames` is used to make sure that we assign new replicas to them preferentially
        // so that all the replicas are aggregated.
-       result, err := divideReplicasByPreference(clusterAvailableReplicas, newSpec.Replicas, preference, scheduledClusterNames)
+       result, err := divideReplicasByPreference(clusterAvailableReplicas, newSpec.Replicas, preference, util.ConvertToClusterNames(scheduledClusters))
        if err != nil {
                return result, err
        }
diff --git a/pkg/scheduler/core/util.go b/pkg/scheduler/core/util.go
index 1ceab827..93e2b8e4 100644
--- a/pkg/scheduler/core/util.go
+++ b/pkg/scheduler/core/util.go
@@ -77,11 +77,10 @@ func calAvailableReplicas(clusters []*clusterv1alpha1.Cluster, spec *workv1alpha

 // findOutScheduledCluster will return a name set of clusters
 // which are a part of `feasibleClusters` and have non-zero replicas.
-func findOutScheduledCluster(tcs []workv1alpha2.TargetCluster, candidates []*clusterv1alpha1.Cluster) (sets.String, []workv1alpha2.TargetCluster) {
+func findOutScheduledCluster(tcs []workv1alpha2.TargetCluster, candidates []*clusterv1alpha1.Cluster) []workv1alpha2.TargetCluster {
        validTarget := make([]workv1alpha2.TargetCluster, 0)
-       res := sets.NewString()
        if len(tcs) == 0 {
-               return res, validTarget
+               return validTarget
        }

        for _, targetCluster := range tcs {
@@ -92,14 +91,13 @@ func findOutScheduledCluster(tcs []workv1alpha2.TargetCluster, candidates []*clu
                // must in `candidates`
                for _, cluster := range candidates {
                        if targetCluster.Name == cluster.Name {
-                               res.Insert(targetCluster.Name)
                                validTarget = append(validTarget, targetCluster)
                                break
                        }
                }
        }

-       return res, validTarget
+       return validTarget
 }

 // resortClusterList is used to make sure scheduledClusterNames are in front of the other clusters in the list of
```

File: pkg/scheduler/core/util.go [hunk 2]
```diff
@@ -77,11 +77,12 @@ func calAvailableReplicas(clusters []*clusterv1alpha1.Cluster, spec *workv1alpha
 
 // findOutScheduledCluster will return a name set of clusters
```
Comment (RainbowMango) [inline pkg/scheduler/core/util.go:78]: The comments should be updated as well. Sorry for missing it from my last comment.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Review by RainbowMango — COMMENTED** [review]
/lgtm

File: pkg/scheduler/core/util.go (hunk 1 above)
Comment (huone1) [reply pkg/scheduler/core/util.go]: it is better, and I have fixed it
