### PR TITLE
fix upgrade error with #5003

### LINKED ISSUE #5003: Upgrading karmada from v1.9 to v1.10 may cause karmada to lose management of member cluster resources
**What happened**:
When karmada upgrades from v1.9 to v1.10, if `karmada-controller-manager` is upgraded before `karmada-webhook`, karmada will lose the management of member resources.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Building a karmada cluster with release-1.9 images
- Use a PropagationPolicy and propagate deployment `nginx` to `member1`
```bash
(base) ➜  karmada git:(master) ✗ karmadactl get deployment
NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE   ADOPTION
nginx   member1   2/2     2            2           65m   Y
```
- upgrade the image verson of `karmada controller manager` to v1.10(built with the latest code from the master branch)
- upgrade the image verson of `karmada webhook` to v1.10(built with the latest code from the master branch)
- You can see in the logs of "karmada controller manager":
```bash
I0530 02:54:03.474570       1 recorder.go:104] "Failed to sync work(karmada-es-member1/nginx-687f7fb96f) to cluster(member1), err: resource(kind=Deployment, default/nginx) already exists in the cluster member1 and the work.karmada.io/conflict-resolution strategy value is empty, Karmada will not manage this resource" logger="events" type="Warning" object={"kind":"Work","namespace":"karmada-es-member1","name":"nginx-687f7fb96f","uid":"6df74394-f776-4b42-b665-c384a3248a8d","apiVersion":"work.karmada.io/v1alpha1","resourceVersion":"211388"} reason="SyncFailed"
```
- The label ` karmada.io/managed: "true"` of deployment  `nginx` in member1 will be lost 
```yaml
        labels:
          app: nginx
          propagationpolicy.karmada.io/name: nginx
          propagationpolicy.karmada.io/namespace: default
          propagationpolicy.karmada.io/permanent-id: e0f71209-7209-4d69-9eb9-b73c95f555d3
          resourcebinding.karmada.io/permanent-id: 2d061c1b-9f56-4b93-bfed-dcbb8c21780e
          work.karmada.io/permanent-id: be2d1218-0326-4092-9eb8-73a4157ad432
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind bug
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #5003

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/util/helper/work.go [hunk 1]
```diff
@@ -37,8 +37,21 @@ import (
...
+		resource = resource.DeepCopy()
+		// set labels
+		util.MergeLabel(resource, util.ManagedByKarmadaLabel, util.ManagedByKarmadaLabelValue)
+		// set annotations
+		util.MergeAnnotation(resource, workv1alpha2.ResourceTemplateUIDAnnotation, string(resource.GetUID()))
+		util.MergeAnnotation(resource, workv1alpha2.WorkNameAnnotation, workMeta.Name)
+		util.MergeAnnotation(resource, workv1alpha2.WorkNamespaceAnnotation, workMeta.Namespace)
+		if conflictResolution, ok := workMeta.GetAnnotations()[workv1alpha2.ResourceConflictResolutionAnnotation]; ok {
+			util.MergeAnnotation(resource, workv1alpha2.ResourceConflictResolutionAnnotation, conflictResolution)
+		}
```
Comment (RainbowMango) [inline pkg/util/helper/work.go:52]: Given that these labels and annotations will be re-generated per the resource template if we move this to webhook, they will be omitted if webhook is not running or not enabled(mis-configuration).

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
