### PR TITLE
uninstall metrics adapter when karmada cluster remove

### LINKED ISSUE #4030: When deleting a karmada instance, some pods (metrics-adapters) are still running.
**What happened**:
I deleted a karmada instance, BUT only metics-adapter pods are still running.

**What you expected to happen**:
When deleting a karmada instance, all pods related the karmada instance should be terminated. (is it right?)

**How to reproduce it (as minimally and precisely as possible)**:
I followed this guide (https://github.com/karmada-io/karmada/blob/master/operator/README.md).

I run this script.
```
kubectl apply -f - <<EOF
apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: karmada-demo
  namespace: test
EOF
```

And then I could check the karmada's pods as follows:
```
NAME                                                    READY   STATUS    RESTARTS   AGE                                                                                                                         
karmada-demo-aggregated-apiserver-cd8c685bb-2d8s5       1/1     Running   0          53s
karmada-demo-apiserver-6c74757b8b-54jnk                 1/1     Running   0          74s
karmada-demo-controller-manager-5cb655fc64-8kj8p        1/1     Running   0          48s
karmada-demo-etcd-0                                     1/1     Running   0          75s
karmada-demo-kube-controller-manager-68f5649c7b-7rnjt   1/1     Running   0          48s
karmada-demo-metrics-adapter-65cc4546d9-25crs           1/1     Running   0          48s
karmada-demo-metrics-adapter-65cc4546d9-x5r25           1/1     Running   0          48s
karmada-demo-scheduler-7cddd77f9-5p4mk                  1/1     Running   0          48s
karmada-demo-webhook-67d895c879-zdlzp                   1/1     Running   0          48s
```

And then I tried to delete the karmada instance.
```
$ kubectl delete karmada karmada-demo -n test
karmada.operator.karmada.io "karmada-demo" deleted
$
```

BUT I could see some pods in test namespace.
```
$ kubectl get pods -n test
NAME                                            READY   STATUS    RESTARTS   AGE
karmada-demo-metrics-adapter-65cc4546d9-25crs   1/1     Running   0          3m30s
karmada-demo-metrics-adapter-65cc4546d9-x5r25   1/1     Running   0          3m30s
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.8.0-alpha.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
```
$ karmadactl version
karmadactl version: version.Info{GitVersion:"v0.0.0-master", GitCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.21.0", Compiler:"gc", Platform:"linux/amd64"}
```
- Others:

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #4030

When the karmada instance is removed, the metrics-adapter does not have a corresponding de-init, causing the pod to remain. 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-operator`: Fixed the issue that karmada-metrics-adapter was not removed after deleting a Karmada instance.
```

### CODE REVIEW

File: operator/pkg/tasks/deinit/component.go [hunk 1]
```diff
@@ -26,6 +26,8 @@ func NewRemoveComponentTask() workflow.Task {
 			newRemoveComponentWithServiceSubTask(constants.KarmadaWebhookComponent, util.KarmadaWebhookName),
 			newRemoveComponentWithServiceSubTask(constants.KarmadaAggregatedAPIServerComponent, util.KarmadaAggregatedAPIServerName),
 			newRemoveComponentWithServiceSubTask(constants.KarmadaAPIserverComponent, util.KarmadaAPIServerName),
+			newRemoveComponentWithServiceSubTask(constants.KarmadaAPIserverComponent, util.KarmadaAPIServerName),
```
[the remark this answers is not in the document]
Comment (wawa0210) [reply operator/pkg/tasks/deinit/component.go]: Duplicate code,thx

File: operator/pkg/tasks/deinit/component.go [hunk 2]
```diff
@@ -26,6 +26,7 @@ func NewRemoveComponentTask() workflow.Task {
 			newRemoveComponentWithServiceSubTask(constants.KarmadaWebhookComponent, util.KarmadaWebhookName),
 			newRemoveComponentWithServiceSubTask(constants.KarmadaAggregatedAPIServerComponent, util.KarmadaAggregatedAPIServerName),
 			newRemoveComponentWithServiceSubTask(constants.KarmadaAPIserverComponent, util.KarmadaAPIServerName),
+			newRemoveComponentWithServiceSubTask(constants.KarmadaMetricsAdapterComponent, util.KarmadaMetricsAdapterName),
```
Comment (calvin0327) [inline operator/pkg/tasks/deinit/component.go:29]: We should remove the `karmada-metrcis-adapter` first and then remove the other components.

Comment (wawa0210) [reply operator/pkg/tasks/deinit/component.go]: Adopt a LIFO installation and removal strategy?

Comment (calvin0327) [reply operator/pkg/tasks/deinit/component.go]: Although it have little effect on this, but we'd better keep the uninstall order.

**Review by RainbowMango — COMMENTED** [review]
/assign

**Review by RainbowMango — APPROVED** [review]
/approve

I added a release-note to the PR description. 

@calvin0327 Do you think this patch should be backported to release branches?

**Comment by calvin0327** [comment]
@RainbowMango Yes, I think we should patch to v1.7 release branch, how do you think?

**Comment by RainbowMango** [comment]
+1

@wawa0210 Would you like to do this?  Here is the guide about how to cherry-pick a PR:
https://karmada.io/docs/contributor/cherry-picks

**Comment by wawa0210** [comment]
> +1
> 
> @wawa0210 Would you like to do this? Here is the guide about how to cherry-pick a PR: https://karmada.io/docs/contributor/cherry-picks

sure, let me do it
