### PR TITLE
only update object in member cluster by execution controller

### LINKED ISSUE #1362: Why use both executioncontroller and workstatuscontroller to create or update k8s object in member cluster
**Please provide an in-depth description of the question you have**:
I'm confused that the `executioncontroller` and the `wotkstatuscontroller` both can create or update k8s object in member cluster for each work. 

**What do you think about this question?**:
I think all the operation about work can be implemented in one controller. k8s object in member cluster is just subresource of the work as pod to deploy. 

**Environment**:
- Karmada version: v1.0.1
- Kubernetes version: 
- Others:

### LINKED ISSUE #3572: Cannot reflect status to work when retain failed
**What happened**:
Situation 1:  When I deploy a Pod to a Kubernetes cluster which may automatically inject some fields into the Pod (e.g a certain volume is auto mounted like `k8s-api-access`, or add some default resource requests and limit), now Karmada will do the `retain` operation because of the difference of the control plane and member clusters but this may be blocked by admission controller. For Pod, we can only update some limited fields, like image and so on. At this time, the retain failure will cause the control plane to fail to collect the status of the member clusters.

Situation 2:  When I configure the error retain rules, the situation of the above situation will happen, too.

Reference codebase:

    if needUpdate {
            if err := c.ObjectWatcher.Update(clusterName, desiredObj, observedObj); err != nil {
                    klog.Errorf("Update %s failed: %v", fedKey.String(), err)
                    return err
            }
            // We can't return even after a success updates, because that might lose the chance to collect status.
            // Not all updates are real, they might be no change, in that case there will be no more event for this update,
            // this usually happens with those resources not enables 'metadata.generation', like 'Service'.
            // When a Service's status changes, it's 'metadata.resourceVersion' will be increased, but 'metadata.generation'
            // not increased(defaults to 0), the ObjectWatcher can't easily tell what happened to the object, so ObjectWatcher
            // also needs to update again. The update operation will be a non-operation if the event triggered by Service's
            // status changes.
    }

    klog.Infof("reflecting %s(%s/%s) status to Work(%s/%s)", observedObj.GetKind(), observedObj.GetNamespace(), observedObj.GetName(), workNamespace, workName)
    return c.reflectStatus(workObject, observedObj)

**What you expected to happen**:
Even if the `retain` operation failed, Karmada can still collect the status of member clusters and keep them in sync.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### LINKED ISSUE #3587: After a resource is deleted, the resource fails to be delivered again. The work corresponding to the resource is not in the synchronization failure state.
**What happened**:
I created a service on the federation and successfully delivered a cluster. I deleted the service from the member cluster. Failed to deliver the federated data.
work status:
image

**What you expected to happen**:

Indicates the synchronization failure status of the work corresponding to the resource.

**How to reproduce it (as minimally and precisely as possible)**:

Create a service on the federation and successfully delivered a cluster.  
Delete the service from the cluster.
Occupy the port configured for the service
 Failed to deliver the federated data again.

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.5
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### LINKED ISSUE #3807: Workstatus Controller Should Only Focus on Status and Only Update Object in Member Cluster by Execution Controller
**What would you like to be added**:
Make `workstatus-controller` only focus on reflecting object status, and all operations on objects in member clusters should be finished by `execution-controller`.  

**Why is this needed**:  
Like in #1362   
1. When two controllers are attempting to update the same resource, the confict would occur easily, and it is a little hard to do some retries in one reconcile because we are not sure which one would be a later one clearly.  
2. Even both `execution-controller` and `workstatus-controller` are able to sync objects in member clusters, only `execution-controller` have a chance to update the `Applied` `condition` in `work status`. That seems a bit unreasonable. How would it be if the `workstatus-controller` failed to sync the object in member cluster and this condition last a time? The object in member cluster is not as expected, and status is wrong(old) in fed control plane, but what the `condition` in `work status` tells us is the resource is applied.

### PR DESCRIPTION
**Pull request by lxtywypc**
**What type of PR is this?**  
/kind feature  

**What this PR does / why we need it**:
As #3807   

**Which issue(s) this PR fixes**:
Fixes #3807   
Fixes #1362  
Fixes #3572   
Fixes #3587 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: 

```release-note
NONE  
```

### CODE REVIEW

File: pkg/controllers/execution/execution_controller.go [hunk 1]
```diff
@@ -77,31 +95,74 @@ func (c *Controller) Reconcile(ctx context.Context, req controllerruntime.Reques
...
+func generateKey(obj interface{}) (util.QueueKey, error) {
+	resource, ok := obj.(*unstructured.Unstructured)
+	if !ok {
+		return nil, fmt.Errorf("object is not unstructured")
+	}
+
+	workName := util.GetLabelValue(resource.GetLabels(), workv1alpha1.WorkNameLabel)
+	workNamespace := util.GetLabelValue(resource.GetLabels(), workv1alpha1.WorkNamespaceLabel)
+
+	if len(workName) == 0 || len(workNamespace) == 0 {
```
Comment (jwcesign) [inline pkg/controllers/execution/execution_controller.go:155]: `if workName == "" || workNamespace == ""` ?

File: pkg/controllers/status/work_status_controller.go [hunk 2]
```diff
@@ -202,85 +194,18 @@ func (c *WorkStatusController) syncWorkStatus(key util.QueueKey) error {
...
-	needUpdate, err := c.ObjectWatcher.NeedsUpdate(clusterName, desiredObj, observedObj)
-	if err != nil {
+	if !helper.IsResourceApplied(&workObject.Status) {
+		err = fmt.Errorf("work hadn't been applied yet")
+		klog.Errorf("Failed to reflect status of %s(%s/%s) to Work(%s/%s): %v.",
+			observedObj.GetKind(), observedObj.GetNamespace(), observedObj.GetName(), workNamespace, workName, err)
 		return err
 	}
 
-	if needUpdate {
```
Comment (jwcesign) [inline pkg/controllers/status/work_status_controller.go:223]: How is this part implemented in execution controller?

File: pkg/controllers/execution/execution_controller.go (hunk 1 above)
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go:155]: It was referenced from here:  
https://github.com/karmada-io/karmada/blob/d27faeac953043c2274bb8787bbbaaafa7d0dcd6/pkg/controllers/status/work_status_controller.go#L182-L187  

And I have found one more part like this, I will try to change them together.

File: pkg/controllers/status/work_status_controller_test.go [hunk 3]
```diff
@@ -757,156 +703,151 @@ func newWork(workName, workNs string, raw []byte, deletionTimestampIsZero ...boo
...
-		assert.Empty(t, err)
-	})
-
-	t.Run("failed to UnmarshalJSON", func(t *testing.T) {
-		work.Spec.Workload.Manifests[0].RawExtension.Raw = []byte(`{"apiVersion":"v1","kind":"Pod","metadata":{"name":"pod","namespace":"default"}},`)
-		err := c.recreateResourceIfNeeded(work, fedKey)
-		assert.NotEmpty(t, err)
-	})
-}
+// TODO: Move to resourceinformer_test
```
Comment (XiShanYongYe-Chang) [inline pkg/controllers/status/work_status_controller_test.go:706]: Can the move be completed in the current PR?

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Good job, thanks a lot~

File: pkg/controllers/execution/execution_controller.go [hunk 4]
```diff
@@ -65,6 +77,12 @@ func (c *Controller) Reconcile(ctx context.Context, req controllerruntime.Reques
 		return controllerruntime.Result{Requeue: true}, err
 	}
 
+	// Enqueue to try removing object in member cluster if work deleted.
+	if work.DeletionTimestamp != nil {
```
Comment (whitewindmills) [inline pkg/controllers/execution/execution_controller.go:81]: usually use `!work.DeletionTimestamp.IsZero()`.

**Comment by XiShanYongYe-Chang** [comment]
Invite people who may be interested in this issue to take a look.
/cc @chaunceyjiang @whitewindmills @Poor12 @RainbowMango @CuiDengdeng @likakuli

File: pkg/controllers/status/work_status_controller.go (hunk 2 above)
Comment (jwcesign) [reply pkg/controllers/status/work_status_controller.go:223]: needUpdate is decided by `c.ObjectWatcher.NeedsUpdate(clusterName, desiredObj, observedObj)`, and it checks the labels when the generation is the same, but `GenerationChangedPredicate` only checks the generation, is this expected?

File: pkg/controllers/status/work_status_controller.go [hunk 5]
```diff
@@ -374,109 +299,10 @@ func (c *WorkStatusController) mergeStatus(_ []workv1alpha1.ManifestStatus, newS
...
-			return nil, err
-		}
-		singleClusterInformerManager = c.InformerManager.ForCluster(dynamicClusterClient.ClusterName, dynamicClusterClient.DynamicClientSet, 0)
-	}
-	return singleClusterInformerManager, nil
-}
-
 // SetupWithManager creates a controller and register to controller manager.
 func (c *WorkStatusController) SetupWithManager(mgr controllerruntime.Manager) error {
+	c.eventHandler = fedinformer.NewHandlerOnEvents(c.onAdd, c.onUpdate, nil)
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:304]: In my opinion, when an object was deleted, the `execution controller` would take effect on the event to give a try to recreate the object. The `Applied` condition would be set to `False` if the synchronization failed. 

But maybe we can clear the `manifestStatuses` field when a synchronization failed, that could be completed in `execution controller`.

> BTW, can you help remove the unused NewHandlerOnAllEvents method?  

I'm glad to do this after we make sure it quite be no longer used.

[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/controllers/status/work_status_controller.go:304]: Ok, it's reasonable, thanks!

File: pkg/controllers/execution/execution_controller.go [hunk 6]
```diff
@@ -77,31 +95,74 @@ func (c *Controller) Reconcile(ctx context.Context, req controllerruntime.Reques
...
+
+func (c *Controller) onUpdate(old, cur interface{}) {
+	unstructuredOld := old.(*unstructured.Unstructured)
+	unstructuredCur := cur.(*unstructured.Unstructured)
+
+	unstructuredOldCopy := unstructuredOld.DeepCopy()
+	unstructuredCurCopy := unstructuredCur.DeepCopy()
+
+	_ = prune.RemoveIrrelevantField(unstructuredOldCopy, prune.RemoveJobTTLSeconds)
+	_ = prune.RemoveIrrelevantField(unstructuredCurCopy, prune.RemoveJobTTLSeconds)
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go:121]: Sounds great, I will take a try.

File: pkg/controllers/status/work_status_controller.go [hunk 7]
```diff
@@ -171,10 +157,16 @@ func (c *WorkStatusController) syncWorkStatus(key util.QueueKey) error {
...
+
+	observedObj, err := c.ResourceInformer.GetObjectFromCache(fedKey)
 	if err != nil {
 		if apierrors.IsNotFound(err) {
-			return c.handleDeleteEvent(fedKey)
+			executionSpace := names.GenerateExecutionSpaceName(fedKey.Cluster)
+			workName := names.GenerateWorkName(fedKey.Kind, fedKey.Name, fedKey.Namespace)
+			klog.Warningf("Skip reflecting %s(%s/%s) status to Work(%s/%s) for not applied successfully yet.",
+				fedKey.Kind, fedKey.Namespace, fedKey.Name, executionSpace, workName)
+			return nil
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:169]: Like this:  
https://github.com/karmada-io/karmada/pull/3808/files/cdbc943859f432dd125ca24c4fe2e3d7e468ae2e#r1267468944  

If the object should be managed by karmada, `execution controller` would take an effect and update the status of `work`, and this event could be received by `bindingstatus controller` to update the status in `binding` and resource on fed-control-plane

File: pkg/controllers/status/work_status_controller.go [hunk 8]
```diff
@@ -202,85 +194,18 @@ func (c *WorkStatusController) syncWorkStatus(key util.QueueKey) error {
...
-	}
-
-	// we should check if the observed status is consistent with the declaration to prevent accidental changes made
-	// in member clusters.
-	needUpdate, err := c.ObjectWatcher.NeedsUpdate(clusterName, desiredObj, observedObj)
-	if err != nil {
+	if !helper.IsResourceApplied(&workObject.Status) {
+		err = fmt.Errorf("work hadn't been applied yet")
+		klog.Errorf("Failed to reflect status of %s(%s/%s) to Work(%s/%s): %v.",
+			observedObj.GetKind(), observedObj.GetNamespace(), observedObj.GetName(), workNamespace, workName, err)
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:200]: It is necessary to return an error to trigger another reconcile, because this part may run after `execution controller` applied object successfully but before `execution controller` updated `Applied` condition in `work` successfully. That would cause we miss the chance to reflect the status until next update event.  

Or we have to watch the update event of the conditions of `work` and enqueue the object manually.  

How do you think about?

File: pkg/controllers/status/work_status_controller.go (hunk 2 above)
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:223]: Like this:  
https://github.com/karmada-io/karmada/pull/3808/files/cdbc943859f432dd125ca24c4fe2e3d7e468ae2e#r1267840563  

I will think more about this. 

Nice remind, thanks.

File: pkg/controllers/status/work_status_controller.go [hunk 9]
```diff
@@ -202,85 +194,18 @@ func (c *WorkStatusController) syncWorkStatus(key util.QueueKey) error {
...
-		// We can't return even after a success updates, because that might lose the chance to collect status.
-		// Not all updates are real, they might be no change, in that case there will be no more event for this update,
-		// this usually happens with those resources not enables 'metadata.generation', like 'Service'.
-		// When a Service's status changes, it's 'metadata.resourceVersion' will be increased, but 'metadata.generation'
-		// not increased(defaults to 0), the ObjectWatcher can't easily tell what happened to the object, so ObjectWatcher
-		// also needs to update again. The update operation will be a non-operation if the event triggered by Service's
-		// status changes.
-	}
-
+	// Now we only update object in member cluster by execution_controller.
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:204]: I just supposed to remind readers what I have done. Ofcourse it could be removed.

File: pkg/controllers/execution/execution_controller.go (hunk 4 above)
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go:81]: Nice remind, thanks.

File: pkg/controllers/status/work_status_controller.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/controllers/status/work_status_controller.go:169]: Shouldn't the work status condition be handled by the execution-controller and the work status manifestStatuses be handled by the work-status-controller, so that they don't conflict with each other?

File: pkg/controllers/status/work_status_controller.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/controllers/status/work_status_controller.go:200]: Thanks for explaining, I get this point. 
I have a new question, do we need to make this judgment?
```
if !helper.IsResourceApplied(&workObject.Status) {
```

File: cmd/agent/app/agent.go [hunk 10]
```diff
@@ -226,7 +227,7 @@ func run(ctx context.Context, opts *options.Options) error {
 	return nil
 }
 
-func setupControllers(mgr controllerruntime.Manager, opts *options.Options, stopChan <-chan struct{}) error {
+func setupControllers(ctx context.Context, mgr controllerruntime.Manager, opts *options.Options, stopChan <-chan struct{}) error {
```
Comment (chaunceyjiang) [inline cmd/agent/app/agent.go:230]: `stopChan <-chan ` seems to be a redundant parameter.

File: pkg/util/resourceinformer/resourceinformer.go [hunk 11]
```diff
@@ -0,0 +1,151 @@
...
+	"github.com/karmada-io/karmada/pkg/util/helper"
+	"github.com/karmada-io/karmada/pkg/util/restmapper"
+)
+
+var _ ResourceInformer = &resourceInformerImpl{}
+
+type ResourceInformer interface {
+	// BuildResourceInformers builds informer dynamically for managed resources in member cluster.
+	// The created informer watches resource change and then sync to the relevant Work object.
+	BuildResourceInformers(cluster *clusterv1alpha1.Cluster, work *workv1alpha1.Work, handler cache.ResourceEventHandler) (controllerruntime.Result, error)
```
[the remark this answers is not in the document]
Comment (chaunceyjiang) [reply pkg/util/resourceinformer/resourceinformer.go:29]: +1 

`controllerruntime.Result` doesn't seem to be a generic return type. I believe it would be beneficial to declare a new type for easier future expansion.

File: pkg/util/resourceinformer/resourceinformer.go [hunk 12]
```diff
@@ -0,0 +1,151 @@
...
+	ClusterCacheSyncTimeout     metav1.Duration
+}
+
+// BuildResourceInformers builds informer dynamically for managed resources in member cluster.
+// The created informer watches resource change and then sync to the relevant Work object.
+func (r *resourceInformerImpl) BuildResourceInformers(cluster *clusterv1alpha1.Cluster, work *workv1alpha1.Work, handler cache.ResourceEventHandler) (controllerruntime.Result, error) {
+	err := r.registerInformersAndStart(cluster, work, handler)
+	if err != nil {
+		klog.Errorf("Failed to register informer for Work %s/%s. Error: %v.", work.GetNamespace(), work.GetName(), err)
+		return controllerruntime.Result{Requeue: true}, err
```
Comment (chaunceyjiang) [inline pkg/util/resourceinformer/resourceinformer.go:60]: Whether to "Requeue" or not, should be determined by the caller.

File: pkg/controllers/status/work_status_controller.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:169]: Yes, it seems to be better. That's quite a nice advice.

File: pkg/controllers/status/work_status_controller.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:200]: In my opinion, if an object hadn't been synced successfully yet, it is unnecessary to reflect a real status in member cluster based on an unexpected object template. It is enough that the `execution controller` would set the `Applied` condition as `False` to reflect this unexpected situation on the fed-control-plane. After the object been synced successfully, the status is grate probable to change. Return in time would reduce unnecessary updating a lot.  

And about your advice on https://github.com/karmada-io/karmada/pull/3808/files/cdbc943859f432dd125ca24c4fe2e3d7e468ae2e#r1267481686, which do you think is better when `Applied` condition changed to `False`? To keep the old status, or clean up it?

[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/controllers/status/work_status_controller.go:200]: Ok thanks.

> To keep the old status,

File: pkg/controllers/status/work_status_controller.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:169]: Sorry, after re-read about this part, I find that it seems not necessary to clean up the status in `work`. 

When we try to sync status of an object but the object is missed in cache:  
- If the object is not managed by `karmada`, we don't need to process it.  
- Else, we could wait for the object re-created by `execution-controller`. It could be considered as what we should do when `Applied` condition is `False`. Then the `bindingstatus controller` would take an effect on `binding` and resource on fed-control-plane.  

Or maybe I mis-understood your intention. If so, please explain to me in detail. :)

[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/controllers/status/work_status_controller.go:169]: Ok, I agree with you.

File: pkg/controllers/execution/execution_controller.go [hunk 13]
```diff
@@ -77,31 +94,76 @@ func (c *Controller) Reconcile(ctx context.Context, req controllerruntime.Reques
...
-
 	if !util.IsClusterReady(&cluster.Status) {
 		klog.Errorf("Stop sync work(%s/%s) for cluster(%s) as cluster not ready.", work.Namespace, work.Name, cluster.Name)
 		return controllerruntime.Result{Requeue: true}, fmt.Errorf("cluster(%s) not ready", cluster.Name)
 	}
 
-	return c.syncWork(clusterName, work)
+	err = c.ResourceInformer.BuildResourceInformers(cluster, work, c.eventHandler)
+	if err != nil {
+		return controllerruntime.Result{Requeue: true}, err
```
Comment (whitewindmills) [inline pkg/controllers/execution/execution_controller.go:104]: The codes `Requeue: true` is unnecessary.

File: pkg/controllers/status/work_status_controller.go [hunk 14]
```diff
@@ -99,26 +91,25 @@ func (c *WorkStatusController) Reconcile(ctx context.Context, req controllerrunt
...
-func (c *WorkStatusController) getEventHandler() cache.ResourceEventHandler {
-	if c.eventHandler == nil {
-		c.eventHandler = fedinformer.NewHandlerOnAllEvents(c.worker.Enqueue)
+func (c *WorkStatusController) onAdd(obj interface{}) {
+	curObj := obj.(runtime.Object)
+	c.worker.Enqueue(curObj)
+}
+
+func (c *WorkStatusController) onUpdate(old, cur interface{}) {
+	// Still need compare the whole object because the interpreter is able to take any part of object to reflect status.
```
Comment (whitewindmills) [inline pkg/controllers/status/work_status_controller.go:108]: // Still need to compare...

File: pkg/util/objectwatcher/objectwatcher.go [hunk 15]
```diff
@@ -70,29 +66,21 @@ func (o *objectWatcherImpl) Create(clusterName string, desireObj *unstructured.U
...
-			klog.Errorf("Failed to get resource %v from member cluster, err is %v ", desireObj.GetName(), err)
-			return err
-		}
-
-		clusterObj, err := dynamicClusterClient.DynamicClientSet.Resource(gvr).Namespace(desireObj.GetNamespace()).Create(context.TODO(), desireObj, metav1.CreateOptions{})
-		if err != nil {
-			klog.Errorf("Failed to create resource(kind=%s, %s/%s) in cluster %s, err is %v ", desireObj.GetKind(), desireObj.GetNamespace(), desireObj.GetName(), clusterName, err)
-			return err
+		if apierrors.IsAlreadyExists(err) {
+			klog.Infof("Skip creating resource(kind=%s, %s/%s) in cluster %s as resource is already existing", desireObj.GetKind(), desireObj.GetNamespace(), desireObj.GetName(), clusterName)
```
Comment (whitewindmills) [inline pkg/util/objectwatcher/objectwatcher.go:72]: `Skip creating resource(kind=%s, %s/%s) in cluster %s because it already exists`

File: test/helper/resource.go [hunk 16]
```diff
@@ -765,3 +786,29 @@ func NewPodDisruptionBudget(namespace, name string, maxUnAvailable intstr.IntOrS
 		},
 	}
 }
+
+// NewWork will build a new Work object.
+func NewWork(workName, workNs string, raw []byte, deletionTimestampIsZero ...bool) *workv1alpha1.Work {
```
Comment (whitewindmills) [inline test/helper/resource.go:791]: `deletionTimestampIsZero` seems unused, even if reserved, `deletionTimestampIsZero bool` is enough.

File: pkg/controllers/execution/execution_controller.go (hunk 13 above)
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go:104]: Yes, I just follow the original style. We could fix all of parts in this style in a new pull-request if need. :)

File: pkg/controllers/execution/execution_controller.go (hunk 1 above)
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go]: Done.

File: pkg/util/resourceinformer/resourceinformer.go [hunk 17]
```diff
@@ -0,0 +1,151 @@
...
+type ResourceInformer interface {
+	// BuildResourceInformers builds informer dynamically for managed resources in member cluster.
+	// The created informer watches resource change and then sync to the relevant Work object.
+	BuildResourceInformers(cluster *clusterv1alpha1.Cluster, work *workv1alpha1.Work, handler cache.ResourceEventHandler) (controllerruntime.Result, error)
+
+	// GetObjectFromCache returns object in cache by federated key.
+	GetObjectFromCache(fedKey keys.FederatedKey) (*unstructured.Unstructured, error)
+}
+
+func NewResourceInformer(c client.Client, restMapper meta.RESTMapper, informerManager genericmanager.MultiClusterInformerManager, clusterCacheSyncTimeout metav1.Duration,
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/util/resourceinformer/resourceinformer.go]: Done.

File: pkg/util/resourceinformer/resourceinformer.go [hunk 18]
```diff
@@ -0,0 +1,151 @@
...
+		ClusterCacheSyncTimeout:     clusterCacheSyncTimeout,
+	}
+}
+
+type resourceInformerImpl struct {
+	client.Client               // used to get Cluster and Secret resources.
+	RESTMapper                  meta.RESTMapper
+	InformerManager             genericmanager.MultiClusterInformerManager
+	ClusterDynamicClientSetFunc func(clusterName string, client client.Client) (*util.DynamicClusterClient, error)
+	ClusterCacheSyncTimeout     metav1.Duration
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/util/resourceinformer/resourceinformer.go]: Done.

File: pkg/util/resourceinformer/resourceinformer.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/util/resourceinformer/resourceinformer.go]: Done.

File: pkg/controllers/status/work_status_controller_test.go (hunk 3 above)
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller_test.go]: Done. And I also added some unit test for `execution controller`.

File: pkg/controllers/execution/execution_controller.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go]: I decided to use `ObjectWatcher.NeedsUpdate` here to judge if an update event should trigger the synchronization. And https://github.com/karmada-io/karmada/pull/3804 is still a nice improvement.

File: pkg/controllers/execution/execution_controller.go (hunk 4 above)
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go]: Done.

File: cmd/agent/app/agent.go (hunk 10 above)
Comment (lxtywypc) [reply cmd/agent/app/agent.go]: I have removed this parameter and use ctx.Done instead.  

There are still some controllers own the element `stopChan`, maybe we could change them to `ctx` later.

File: pkg/util/resourceinformer/resourceinformer.go (hunk 12 above)
Comment (lxtywypc) [reply pkg/util/resourceinformer/resourceinformer.go]: Done.

File: pkg/controllers/execution/execution_controller.go [hunk 19]
```diff
@@ -111,20 +173,71 @@ func (c *Controller) SetupWithManager(mgr controllerruntime.Manager) error {
...
+	err = c.syncToClusters(clusterName, work)
 	metrics.ObserveSyncWorkloadLatency(err, start)
 	if err != nil {
 		msg := fmt.Sprintf("Failed to sync work(%s) to cluster(%s): %v", work.Name, clusterName, err)
 		klog.Errorf(msg)
 		c.EventRecorder.Event(work, corev1.EventTypeWarning, events.EventReasonSyncWorkloadFailed, msg)
-		return controllerruntime.Result{Requeue: true}, err
+		return err
 	}
 	msg := fmt.Sprintf("Sync work (%s) to cluster(%s) successful.", work.Name, clusterName)
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go]: Done.

File: pkg/controllers/status/work_status_controller.go (hunk 14 above)
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go]: Done.

File: pkg/util/objectwatcher/objectwatcher.go (hunk 15 above)
Comment (lxtywypc) [reply pkg/util/objectwatcher/objectwatcher.go]: Done.

File: test/helper/resource.go (hunk 16 above)
Comment (lxtywypc) [reply test/helper/resource.go]: Done.

**Comment by lxtywypc** [comment]
I have made some modification following the advices in a new commit, I will squash them into one commit and remove useless parts after the review is almost finished.

Kindly ping @XiShanYongYe-Chang @chaunceyjiang @jwcesign @whitewindmills to take a review again. :)

**Comment by XiShanYongYe-Chang** [comment]
@lxtywypc Thanks~ can you help to close the resolved questions?

**Comment by lxtywypc** [comment]
> @lxtywypc Thanks~ can you help to close the resolved questions?

I closed some questions that with no dispute, and I left some that would be done after the review is almost finished, or the reviewers may have further thought about. :)

File: pkg/controllers/execution/execution_controller.go [hunk 20]
```diff
@@ -77,31 +94,76 @@ func (c *Controller) Reconcile(ctx context.Context, req controllerruntime.Reques
...
+
+	oldObjCopy := oldObj.DeepCopy()
+	curObjCopy := curObj.DeepCopy()
+
+	clusterName, _ := names.GetClusterName(curObjCopy.GetLabels()[workv1alpha1.WorkNamespaceLabel])
+	if clusterName == "" {
+		return
+	}
+
+	if c.ObjectWatcher.NeedsUpdate(clusterName, oldObjCopy, curObjCopy) {
```
Comment (XiShanYongYe-Chang) [inline pkg/controllers/execution/execution_controller.go:124]: NeedsUpdate is used to determine the differences between resources on the control plane and resources in the member cluster. It may not be appropriate to use it directly here. Can we directly compare the spec, annotation, and label of the resource instead?

File: pkg/controllers/status/work_status_controller.go [hunk 21]
```diff
@@ -150,7 +141,7 @@ func generateKey(obj interface{}) (util.QueueKey, error) {
 // getClusterNameFromLabel gets cluster name from ownerLabel, if label not exist, means resource is not created by karmada.
 func getClusterNameFromLabel(resource *unstructured.Unstructured) (string, error) {
 	workNamespace := util.GetLabelValue(resource.GetLabels(), workv1alpha1.WorkNamespaceLabel)
-	if len(workNamespace) == 0 {
+	if workNamespace == "" {
```
Comment (XiShanYongYe-Chang) [inline pkg/controllers/status/work_status_controller.go:144]: This modification doesn't seem to have any changes.

File: pkg/util/objectwatcher/objectwatcher.go [hunk 22]
```diff
@@ -254,20 +262,20 @@ func (o *objectWatcherImpl) deleteVersionRecord(clusterName, resourceName string
 	delete(o.VersionRecord[clusterName], resourceName)
 }
 
-func (o *objectWatcherImpl) NeedsUpdate(clusterName string, desiredObj, clusterObj *unstructured.Unstructured) (bool, error) {
-	// get resource version
+func (o *objectWatcherImpl) NeedsUpdate(clusterName string, desiredObj, clusterObj *unstructured.Unstructured) bool {
```
Comment (XiShanYongYe-Chang) [inline pkg/util/objectwatcher/objectwatcher.go:265]: Perhaps we don't need this method.

File: pkg/controllers/execution/execution_controller.go (hunk 20 above)
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go:124]: The `ObjectWather.NeedsUpdate` is used in `workstatus controller` to determine if the object in member cluster needs to sync by comparing the `generation` in current object with that last updated recorded in RAM, and comparing the labels, (would be labels and annotations managed by `karmada` after #3804), between the object declared in `work` and that in member cluster. 

In fact, only labels(and annotations later) in desired object is useful for comparation. In a normal workflow, we consider the object in member cluster always the same with our desired. So if we treat the old object in an update event as the desired object, I think it matches the description you gave above.

Comment (XiShanYongYe-Chang) [reply pkg/controllers/execution/execution_controller.go:124]: Thanks for explaining. Now that we have the updated resources before and after, can we directly compare their generation? So can we consider deleting the version stored in memory?

File: pkg/util/objectwatcher/objectwatcher.go (hunk 22 above)
Comment (lxtywypc) [reply pkg/util/objectwatcher/objectwatcher.go:265]: As https://github.com/karmada-io/karmada/pull/3808#discussion_r1274514729, I still think comparing the `generation` between current object and recorded since last updating is a good and explicit way to tell us if the object has been modified unexpectly.

File: pkg/controllers/status/work_status_controller.go (hunk 21 above)
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:144]: It is just a cleanup, for https://github.com/karmada-io/karmada/pull/3808#discussion_r1267455597.

File: pkg/util/objectwatcher/objectwatcher.go (hunk 22 above)
Comment (XiShanYongYe-Chang) [reply pkg/util/objectwatcher/objectwatcher.go:265]: Yes, I agree with you. Sorry, I didn't make it clear. My point is that we can remove the version recorded in memory and directly compare the generations of the two objects.

File: pkg/controllers/execution/execution_controller.go [hunk 23]
```diff
@@ -153,7 +266,8 @@ func (c *Controller) tryDeleteWorkload(clusterName string, work *workv1alpha1.Wo
 		}
 
 		// Avoid deleting resources that not managed by karmada.
-		if util.GetLabelValue(clusterObj.GetLabels(), workv1alpha1.WorkNameLabel) != util.GetLabelValue(workload.GetLabels(), workv1alpha1.WorkNameLabel) {
+		if util.GetLabelValue(clusterObj.GetLabels(), workv1alpha1.WorkNameLabel) != util.GetLabelValue(workload.GetLabels(), workv1alpha1.WorkNameLabel) ||
+			util.GetLabelValue(clusterObj.GetLabels(), workv1alpha1.WorkNamespaceLabel) != util.GetLabelValue(workload.GetLabels(), workv1alpha1.WorkNamespaceLabel) {
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go:270]: It prevents some special cases. For example, if someone removed the `WorkNamespaceLabel` of object in member cluster, attempting to leave it alone in member cluster, and removed the object in fed-control-plane. Though this might not be a recommended usage, I think we had better do nothing.

**Comment by XiShanYongYe-Chang** [comment]
Ask @whitewindmills @chaunceyjiang @jwcesign to help have a look again.

File: pkg/util/objectwatcher/objectwatcher.go (hunk 22 above)
Comment (lxtywypc) [reply pkg/util/objectwatcher/objectwatcher.go:265]: Yes, you are right. I always imagine too much about some special cases not in a normal workflow. Maybe we could talk about these cases in a new issue. Here I will do some simple comparation. I still expect for #3804! :)

Comment (lxtywypc) [reply pkg/util/objectwatcher/objectwatcher.go:265]: Sorry, I just came up with that an important reason why I attempted to reuse this part:   

Comparing the `generation` in memory could prevent requeueing from the update event triggered by `karmada` self.

If we overlook this situation, we may have two attempts to update the object in a short time after once modification.   

What do you think about this situation?

Comment (XiShanYongYe-Chang) [reply pkg/util/objectwatcher/objectwatcher.go:265]: I'm sorry, I didn't understand that.

Comment (lxtywypc) [reply pkg/util/objectwatcher/objectwatcher.go:265]: For example, we have an object managed by `karmada` with `generation = 1` now in member cluster.  

Then I unexpectly modified the `spec` field of the object in member cluster. Now it is with `generation = 2`. This would trigger the updating from `execution controller` because of the changing of `generation`.  

The `execution controller` would sync the object in member cluster. Now the object is with `generation = 3`. This would immediately trigger another updating from `execution controller` again, and it is still because of the changing of `generation`.  

Besides, even the first updating is from the modification of `work`, the `execution controller` would attempt to update the  object twice because it would watch the changing of `generation` in object in member cluster caused by the modification by itself.

Comment (XiShanYongYe-Chang) [reply pkg/util/objectwatcher/objectwatcher.go:265]: Thanks, I got it.

Comment (lxtywypc) [reply pkg/util/objectwatcher/objectwatcher.go:265]: Do you have any advices about this? Or we had better keep use `ObjectWatcher.NeedsUpdate`?

Comment (XiShanYongYe-Chang) [reply pkg/util/objectwatcher/objectwatcher.go:265]: I think it can still be used, but the parameter names need to be modified in order to make them more consistent with their current meaning.

File: pkg/controllers/status/work_status_controller.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go]: Done.

File: pkg/controllers/status/work_status_controller.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/controllers/status/work_status_controller.go:308]: > BTW, can you help remove the unused NewHandlerOnAllEvents method?  

Done.

File: pkg/util/objectwatcher/objectwatcher.go (hunk 22 above)
Comment (lxtywypc) [reply pkg/util/objectwatcher/objectwatcher.go]: Done.  

And I also made some modifications on the way to record version, to prevent enqueueing object on update event too early when the updated version hasn't been recorded yet.

File: pkg/util/objectwatcher/objectwatcher.go [hunk 24]
```diff
@@ -203,71 +222,93 @@ func (o *objectWatcherImpl) genObjectKey(obj *unstructured.Unstructured) string
...
+	versionLock, exist := o.getVersionWithLockRecord(clusterName, resourceName)
+
+	if !exist {
+		versionLock = o.newVersionWithLockRecord(clusterName, resourceName)
+	}
+
+	versionLock.lock.Lock()
+	defer versionLock.lock.Unlock()
+
+	versionLock.version, err = fn()
```
[the remark this answers is not in the document]
Comment (lxtywypc) [reply pkg/util/objectwatcher/objectwatcher.go]: Done.  

That's quite a nice remind. Thanks~ :)

**Review by XiShanYongYe-Chang — COMMENTED** [review]
LGTM
Thanks a lot.
Ask @RainbowMango to help take a look.

**Comment by RainbowMango** [comment]
By the way, can we split this into some small PRs?

**Comment by lxtywypc** [comment]
> By the way, can we split this into some small PRs?

A little hard to.  

The core of this pr is moving the part of syncing object in member cluster from `workstatus controller` to `execution controller`, this part cannot be split into several parts.   

We might only be able to split this pr into several parts as following:  
1. Abstract the `resourceinformer` for later using.  
2. Move the part of syncing object in member cluster from `workstatus controller` to `execution controller`.  
3. Fill the unit tests.  

The second part might be still large. And it might be better to put the testing part and logic part together.

**Comment by RainbowMango** [comment]
Never mind, I'll take a look at it as soon as possible, perhaps this week.

**Review by RainbowMango — COMMENTED** [review]
/assign

File: pkg/util/resourceinformer/resourceinformer.go [hunk 25]
```diff
@@ -0,0 +1,155 @@
...
+	"github.com/karmada-io/karmada/pkg/util"
+	"github.com/karmada-io/karmada/pkg/util/fedinformer/genericmanager"
+	"github.com/karmada-io/karmada/pkg/util/fedinformer/keys"
+	"github.com/karmada-io/karmada/pkg/util/helper"
+	"github.com/karmada-io/karmada/pkg/util/restmapper"
+)
+
+var _ ResourceInformer = &resourceInformerImpl{}
+
+type ResourceInformer interface {
```
Comment (RainbowMango) [inline pkg/util/resourceinformer/resourceinformer.go:25]: I like the idea of abstracting the informer-related functionalities.
It is another informer manager based on [genericmanager.MultiClusterInformerManager](https://github.com/karmada-io/karmada/tree/master/pkg/util/fedinformer/genericmanager) with more context of Karmada resource types(such as it recognizes `Cluster`, `Work`).

 I just have a feeling that the name of it (`ResourceInformer`) seems `a little bit generic` and doesn't show its responsibility.
I'm not sure if `MemberClusterInformer` would be better. Looking forward to your opinions.

File: pkg/util/objectwatcher/objectwatcher.go [hunk 26]
```diff
@@ -29,31 +27,36 @@ type ObjectWatcher interface {
 	Create(clusterName string, desireObj *unstructured.Unstructured) error
 	Update(clusterName string, desireObj, clusterObj *unstructured.Unstructured) error
 	Delete(clusterName string, desireObj *unstructured.Unstructured) error
-	NeedsUpdate(clusterName string, desiredObj, clusterObj *unstructured.Unstructured) (bool, error)
+	NeedsUpdate(clusterName string, oldObj, currentObj *unstructured.Unstructured) bool
```
Comment (RainbowMango) [inline pkg/util/objectwatcher/objectwatcher.go:30]: If there is any specific reason for changing the signature here? The `desired` represents the expectation state, it's might not an `old` one.

Comment (XiShanYongYe-Chang) [reply pkg/util/objectwatcher/objectwatcher.go:30]: The modified logic compares the resources before and after the update on the member cluster, so I suggest changing the naming here. "NeedUpdate" is actually not suitable to be placed here anymore, it needs to be optimized in the future.

File: pkg/util/resourceinformer/resourceinformer.go (hunk 25 above)
Comment (lxtywypc) [reply pkg/util/resourceinformer/resourceinformer.go:25]: I just keep the name as what it was in `workstatus controller`.  
I think it is ok to use `MemberClusterInformer` to instead. I will fix it soon.

Comment (lxtywypc) [reply pkg/util/resourceinformer/resourceinformer.go]: Done.

**Comment by lxtywypc** [comment]
Kindly ping @RainbowMango   
Is there still any problem?

**Comment by RainbowMango** [comment]
Sorry for the delay, It's still on my TODO list. It's hard for me to have a big chunk of time to review it(that's exactly why I always suggested splitting PRs :)). But I'll try to take a look at it today if no comments from me controller owners (@XiShanYongYe-Chang @chaunceyjiang ) can help to move forward.

**Review by RainbowMango — APPROVED** [review]
/approve

Generally looks good to me, I believe this is a workable solution but didn't review it thoroughly, Please @chaunceyjiang and @XiShanYongYe-Chang make final decisions.

Sorry again for the delay.

**Comment by XiShanYongYe-Chang** [comment]
Thanks @lxtywypc! This is a significant improvement. It's LGTM. 
Ask @chaunceyjiang to help to have another review.
/cc @chaunceyjiang

File: pkg/util/memberclusterinformer/memberclusterinformer.go [hunk 27]
```diff
@@ -0,0 +1,155 @@
...
+			return nil, err
+		}
+		singleClusterInformerManager = m.informerManager.ForCluster(dynamicClusterClient.ClusterName, dynamicClusterClient.DynamicClientSet, 0)
+	}
+	return singleClusterInformerManager, nil
+}
+
+// getGVRsFromWork traverses the manifests in work to find groupVersionResource list.
+func (m *memberClusterInformerImpl) getGVRsFromWork(work *workv1alpha1.Work) (map[schema.GroupVersionResource]bool, error) {
+	gvrTargets := map[schema.GroupVersionResource]bool{}
```
Comment (chaunceyjiang) [inline pkg/util/memberclusterinformer/memberclusterinformer.go:134]:
```suggestion
	gvrTargets := sets.New[schema.GroupVersionResource]()
```

File: pkg/util/objectwatcher/objectwatcher.go [hunk 28]
```diff
@@ -70,30 +73,21 @@ func (o *objectWatcherImpl) Create(clusterName string, desireObj *unstructured.U
...
-	}
-	_, err = helper.GetObjectFromCache(o.RESTMapper, o.InformerManager, fedKey)
+	clusterObj, err := dynamicClusterClient.DynamicClientSet.Resource(gvr).Namespace(desireObj.GetNamespace()).Create(context.TODO(), desireObj, metav1.CreateOptions{})
 	if err != nil {
-		if !apierrors.IsNotFound(err) {
-			klog.Errorf("Failed to get resource %v from member cluster, err is %v ", desireObj.GetName(), err)
-			return err
+		if apierrors.IsAlreadyExists(err) {
+			klog.Infof("Skip creating resource(kind=%s, %s/%s) in cluster %s because it already exists", desireObj.GetKind(), desireObj.GetNamespace(), desireObj.GetName(), clusterName)
+			return nil
```
Comment (chaunceyjiang) [inline pkg/util/objectwatcher/objectwatcher.go:80]: I believe that an error should still be returned here. 
The situation where the resource already exists should not be ignored.

**Review by chaunceyjiang — COMMENTED** [review]
Stilling review.

File: pkg/util/memberclusterinformer/memberclusterinformer.go (hunk 27 above)
Comment (lxtywypc) [reply pkg/util/memberclusterinformer/memberclusterinformer.go]: Done.

File: pkg/util/objectwatcher/objectwatcher.go (hunk 28 above)
Comment (lxtywypc) [reply pkg/util/objectwatcher/objectwatcher.go]: Done.

File: pkg/controllers/execution/execution_controller.go [hunk 29]
```diff
@@ -111,20 +173,71 @@ func (c *Controller) SetupWithManager(mgr controllerruntime.Manager) error {
...
+	if !work.DeletionTimestamp.IsZero() {
+		// Abort deleting workload if cluster is unready when unjoining cluster, otherwise the unjoin process will be failed.
+		if util.IsClusterReady(&cluster.Status) {
+			err := c.tryDeleteWorkload(clusterName, work)
+			if err != nil {
+				klog.Errorf("Failed to delete work %v, namespace is %v, err is %v", work.Name, work.Namespace, err)
+				return err
+			}
+		} else if cluster.DeletionTimestamp.IsZero() { // cluster is unready, but not terminating
+			return fmt.Errorf("cluster(%s) not ready", cluster.Name)
```
Comment (chaunceyjiang) [inline pkg/controllers/execution/execution_controller.go:218]: https://github.com/karmada-io/karmada/blob/1d2028b10f9b9d9ca30fe8e963b4557d347c8f51/pkg/util/worker.go#L20-L21

https://github.com/karmada-io/karmada/blob/1d2028b10f9b9d9ca30fe8e963b4557d347c8f51/pkg/util/worker.go#L122-L128


Using the `AsyncWorker` pattern seems to have a problem.
 If a cluster is in the NotReady state for up to 2 hours, and during this period, a resource is deleted from Karmada. When the cluster recovers, it seems that the member resource will not be deleted.

Comment (XiShanYongYe-Chang) [reply pkg/controllers/execution/execution_controller.go:218]: Yes, there was already such a problem before this modification. I think it is necessary for the administrator to intervene manually. Otherwise, we will have to retry indefinitely because the time it takes for users to fix the cluster can vary and cannot be determined.

Comment (lxtywypc) [reply pkg/controllers/execution/execution_controller.go:218]: In fact, we have made the parameters about backoff or retry customized in our own environment.  
Maybe we could open another issue and invite @zach593 to talk about it.

Comment (chaunceyjiang) [reply pkg/controllers/execution/execution_controller.go:218]: >  there was already such a problem before this modification.

`Controller Runtime` uses `workqueue.DefaultControllerRateLimiter`, which does not have a limit on the number of times. It will perform exponential backoff.

Comment (XiShanYongYe-Chang) [reply pkg/controllers/execution/execution_controller.go:218]: Can we consider modifying the implementation of `asyncWorker`?

https://github.com/karmada-io/karmada/blob/bd0c511753a9f20a474af1777695483bf3e80d27/pkg/util/worker.go#L56

Comment (XiShanYongYe-Chang) [reply pkg/controllers/execution/execution_controller.go:218]: Maybe we can open a new issue to trace this problem.

Comment (chaunceyjiang) [reply pkg/controllers/execution/execution_controller.go:218]: > Can we consider modifying the implementation of asyncWorker?

For me, considering whether to use `asyncWorker` is the right thing to do. It's a significant change.

/cc @RainbowMango I can't make up my mind about this issue. Can you help me take another look at it? https://github.com/karmada-io/karmada/pull/3808#discussion_r1295679640

Comment (RainbowMango) [reply pkg/controllers/execution/execution_controller.go:218]: > Yes, there was already such a problem before this modification.

@XiShanYongYe-Chang Can you show me the code where the problem exists? 

> For me, considering whether to use asyncWorker is the right thing to do. It's a significant change.

Yeah, I agree with you, I'm still thinking if there is a better way, such as using the reconciliation mechanism provided by controller-runtime.

Comment (XiShanYongYe-Chang) [reply pkg/controllers/execution/execution_controller.go:218]: When using asyncWorker, if it fails to process a certain number of times due to its maximum retry limit, the event will be discarded.

https://github.com/karmada-io/karmada/blob/bd0c511753a9f20a474af1777695483bf3e80d27/pkg/controllers/status/work_status_controller.go#L131

https://github.com/karmada-io/karmada/blob/bd0c511753a9f20a474af1777695483bf3e80d27/pkg/controllers/status/work_status_controller.go#L224

The possible reason for the update error could be that the member cluster does not allow updates within a certain period of time, which exceeds the total retry time of the worker.

Comment (XiShanYongYe-Chang) [reply pkg/controllers/execution/execution_controller.go:218]: Therefore, I think that this issue can be considered separately and not addressed in this PR.

Comment (RainbowMango) [reply pkg/controllers/execution/execution_controller.go:218]: > Therefore, I think that this issue can be considered separately and not addressed in this PR.

I'm okay to address this problem with another PR, but shall we fix it before this PR?

My concern is that this problem is being magnified, before this PR it only affected the status collection(and the impact might automatically disappear by further events), but now it also affects the `Work` synchronization.

Comment (XiShanYongYe-Chang) [reply pkg/controllers/execution/execution_controller.go:218]: IMOP, the scope of impact has not expanded, but rather the problem has shifted (the synchronization of work from resourceBinding is not applicable to error scenarios such as cluster failures), and the conditions under which the problem itself occurs are relatively strict. It requires a situation where cluster failures occur during the synchronization of work triggered by changes in member cluster resources. Therefore, the scope of impact for this issue is limited.

Therefore, I think that the issue being discussed can be advanced separately. In addition, the `asyncWorker` tool is currently widely used by us and its improvement measures need to be considered as a whole.

**Review by chaunceyjiang — COMMENTED** [review]
Others LGTM, only this one. https://github.com/karmada-io/karmada/pull/3808/files#r1295679640.

**Comment by XiShanYongYe-Chang** [comment]
> Others LGTM, only this one. https://github.com/karmada-io/karmada/pull/3808/files#r1295679640.

Thanks, @chaunceyjiang Regarding the issue you mentioned, I have already raised issue #3959 to track it. Let's discuss the solution there.

Let us merge it first.
/lgtm
