### PR TITLE
Operator support work with crds v1.7.0

### LINKED ISSUE #4129: Operator can not run with crds of karmada v1.7.0
**What happened**:

error log from operator with crds of v1.7.0
```log
E1013 07:10:12.134181   38826 controller.go:324] "Reconciler error" err="failed to create karmada crds, err: open /var/lib/karmada/1.7.0/crds/bases/autoscaling.karmada.io_cronfederatedhpas.yaml: no such file or directory" controller="karmada" controllerGroup="operator.karmada.io" controllerKind="Karmada" Karmada="default/karmada-demo" namespace="default" name="karmada-demo" reconcileID=1acb15c7-97a8-4dac-b916-a549cc839c8d
```

```shell
lan@lan:~/work/v1.6.0$ tree .
.
├── crds
│   ├── bases
│   │   ├── autoscaling.karmada.io_federatedhpas.yaml
│   │   ├── config.karmada.io_resourceinterpretercustomizations.yaml
│   │   ├── config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
│   │   ├── multicluster.x-k8s.io_serviceexports.yaml
│   │   ├── multicluster.x-k8s.io_serviceimports.yaml
│   │   ├── networking.karmada.io_multiclusteringresses.yaml
│   │   ├── policy.karmada.io_clusteroverridepolicies.yaml
│   │   ├── policy.karmada.io_clusterpropagationpolicies.yaml
│   │   ├── policy.karmada.io_federatedresourcequotas.yaml
│   │   ├── policy.karmada.io_overridepolicies.yaml
│   │   ├── policy.karmada.io_propagationpolicies.yaml
│   │   ├── work.karmada.io_clusterresourcebindings.yaml
│   │   ├── work.karmada.io_resourcebindings.yaml
│   │   └── work.karmada.io_works.yaml
│   ├── kustomization.yaml
│   └── patches
│       ├── webhook_in_clusterresourcebindings.yaml
│       └── webhook_in_resourcebindings.yaml
└── crds.tar.gz

lan@lan:~/work/v1.7.0$ tree .
.
├── crds
│   ├── bases
│   │   ├── autoscaling
│   │   │   ├── autoscaling.karmada.io_cronfederatedhpas.yaml
│   │   │   └── autoscaling.karmada.io_federatedhpas.yaml
│   │   ├── config
│   │   │   ├── config.karmada.io_resourceinterpretercustomizations.yaml
│   │   │   └── config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
│   │   ├── multicluster
│   │   │   ├── multicluster.x-k8s.io_serviceexports.yaml
│   │   │   └── multicluster.x-k8s.io_serviceimports.yaml
│   │   ├── networking
│   │   │   ├── networking.karmada.io_multiclusteringresses.yaml
│   │   │   └── networking.karmada.io_multiclusterservices.yaml
│   │   ├── policy
│   │   │   ├── policy.karmada.io_clusteroverridepolicies.yaml
│   │   │   ├── policy.karmada.io_clusterpropagationpolicies.yaml
│   │   │   ├── policy.karmada.io_federatedresourcequotas.yaml
│   │   │   ├── policy.karmada.io_overridepolicies.yaml
│   │   │   └── policy.karmada.io_propagationpolicies.yaml
│   │   └── work
│   │       ├── work.karmada.io_clusterresourcebindings.yaml
│   │       ├── work.karmada.io_resourcebindings.yaml
│   │       └── work.karmada.io_works.yaml
│   ├── kustomization.yaml
│   └── patches
│       ├── webhook_in_clusterresourcebindings.yaml
│       └── webhook_in_resourcebindings.yaml
└── crds.tar.gz

```

The crd directory structure has changed.

/assign

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by liangyuanpeng**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #4129

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-operator`: Fixed can not load Karmada v1.7.0 crds issue.
```

### CODE REVIEW

File: operator/pkg/tasks/init/karmadaresource.go [hunk 1]
```diff
@@ -138,8 +138,8 @@ func createCrds(crdsClient *crdsclient.Clientset, crdsPath string) error {
 }
 
 func patchCrds(crdsClient *crdsclient.Clientset, patchPath string, caBundle string) error {
-	for _, file := range util.ListFiles(patchPath) {
-		if file.IsDir() || path.Ext(file.Name()) != ".yaml" {
+	for _, file := range util.ListFileWithSuffix(patchPath, ".yaml") {
+		if file.IsDir() {
```
Comment (chaosi-zju) [inline operator/pkg/tasks/init/karmadaresource.go:142]: may be this line is redundant, for your `ListFileWithSuffix` function has filtered `!info.IsDir()`

File: operator/pkg/tasks/init/karmadaresource.go [hunk 2]
```diff
@@ -115,12 +115,12 @@ func runCrds(r workflow.RunData) error {
 }
 
 func createCrds(crdsClient *crdsclient.Clientset, crdsPath string) error {
-	for _, file := range util.ListFiles(crdsPath) {
+	for _, file := range util.ListFileWithSuffix(crdsPath, ".yaml") {
 		if file.IsDir() || path.Ext(file.Name()) != ".yaml" {
```
Comment (chaosi-zju) [inline operator/pkg/tasks/init/karmadaresource.go:119]: > file.IsDir() || path.Ext(file.Name()) != ".yaml"

redundant ditto

**Review by chaosi-zju — COMMENTED** [review]
Hello, thank you for your important commit! Review is ongoing, and my viewpoint just for reference only.

File: operator/pkg/util/util_test.go [hunk 3]
```diff
@@ -0,0 +1,28 @@
+package util
+
+import (
+	"log"
+	"os"
+	"strings"
+	"testing"
+)
+
+func TestListFileWithSuffix(t *testing.T) {
```
Comment (RainbowMango) [inline operator/pkg/util/util_test.go:10]: Could you please show me the execution log of this test? I can't see it from [the unit test workflow log](https://github.com/karmada-io/karmada/actions/runs/6505927839/job/17670796208?pr=4130).

File: operator/pkg/util/util_test.go [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+	if os.Getenv("GITHUB_ACTIONS") == "true" {
```
Comment (RainbowMango) [inline operator/pkg/util/util_test.go:11]: Does this mean this test can only run in GitHub workflow or a machine that sets the environment?

File: operator/pkg/util/util_test.go [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+		suffix := ".yaml"
+		repo := os.Getenv("GITHUB_REPOSITORY")
+		log.Println("repo is:", repo)
+		files := ListFileWithSuffix("/home/runner/work/"+repo+"/charts/karmada/_crds/bases", suffix)
+		want := 16
```
Comment (RainbowMango) [inline operator/pkg/util/util_test.go:16]: What if run this test on a normal machine? There are probably no CRD files.

File: operator/pkg/util/util_test.go (hunk 3 above)
Comment (RainbowMango) [reply operator/pkg/util/util_test.go:10]: That is because we didn't enable unit tests for the operator. Just sent #4140 for it.

File: operator/pkg/util/util_test.go (hunk 4 above)
Comment (liangyuanpeng) [reply operator/pkg/util/util_test.go]: Have created a test files at folder testdata, runtest always.

**Comment by RainbowMango** [comment]
The lint is failing:
```
operator/pkg/util/util_test.go:21: unnecessary trailing newline (whitespace)

}
operator/pkg/tasks/init/karmadaresource.go:[11](https://github.com/karmada-io/karmada/actions/runs/6559028786/job/17813781641?pr=4130#step:5:12)8: unnecessary leading newline (whitespace)
	for _, file := range util.ListFileWithSuffix(crdsPath, ".yaml") {

operator/pkg/tasks/init/karmadaresource.go:[13](https://github.com/karmada-io/karmada/actions/runs/6559028786/job/17813781641?pr=4130#step:5:14)8: unnecessary leading newline (whitespace)
	for _, file := range util.ListFileWithSuffix(patchPath, ".yaml") {
```

**Review by RainbowMango — COMMENTED** [review]
/lgtm
leave final decisions to the owner. 
/assign @calvin0327

**Comment by chaosi-zju** [comment]
/lgtm
leave final decisions to @calvin0327

**Review by RainbowMango — APPROVED** [review]
/approve

on behalf of @calvin0327 
Please feel free to leave a comment if you have further comments.
