### PR TITLE
`karmadactl`: Fixed `init` commands can not select default release version issue.

### LINKED ISSUE #1340: [karmada init] prepare karmada failed.failed download file
**What happened**:
When installing Karmada by the following command:
```
kubectl karmada init
```

Getting the following error:
```
:I0131 10:46:44.646973   57124 deploy.go:201] download crds file name: /etc/karmada/crds.tar.gz
Error: prepare karmada failed.failed download file. url: https://github.com/karmada-io/karmada/releases/download/v1.0.0-43-g2060616c/crds.tar.gz code: 404
```

**What you expected to happen**:
From the error message we can tell that the version of `kubectl-karmada` is `v1.0.0-43-g2060616c`, not the released version but from built from the master branch. 

The version of `kubectl-karmada` should be shifted when building the URL, such as `v1.0.0-43-xxx` should be shifted to `v1.0.0`.
We can make a simple rule for this:
The version with the format of `vx.y.z-mm-nn` could be shifted to `vx.y.0` as no API change happens in the patched release.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.0.0-43-g2060616c
- Others:

cc @prodanlabs

### PR DESCRIPTION
**Pull request by prodanlabs**
Signed-off-by: prodan <pengshihaoren@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The images and crd versions of `karmadactl init` are consistent with the `karmadactl` version
**Which issue(s) this PR fixes**:
Fixes #1340

**Special notes for your reviewer**:

kubectl-karmada version is `v0.10.1-547-g0190fda9-dirty`
```
$ ./kubectl-karmada version
kubectl karmada version: version.Info{GitVersion:"v0.10.1-547-g0190fda9-dirty", GitCommit:"0190fda99632c04888ec52fc828985f601bd61a0", GitTreeState:"dirty", BuildDate:"2022-03-08T15:38:46Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```
crd and images version by default
```
Flags:
      --cert-external-dns string                         the external DNS of Karmada certificate (e.g localhost,localhost.com)
      --cert-external-ip string                          the external IP of Karmada certificate (e.g 192.168.1.2,172.16.1.2)
      --crds string                                      Karmada crds resource.(local file e.g. --crds /root/crds.tar.gz) (default "https://github.com/karmada-io/karmada/releases/download/v0.10.0/crds.tar.gz")
      --etcd-data string                                 etcd data path,valid in hostPath mode. (default "/var/lib/karmada-etcd")
      --etcd-image string                                etcd image (default "k8s.gcr.io/etcd:3.5.1-0")
      --etcd-init-image string                           etcd init container image (default "docker.io/alpine:3.14.3")
      --etcd-node-selector-labels string                 etcd pod select the labels of the node. valid in hostPath mode ( e.g. --etcd-node-selector-labels karmada.io/etcd=true)
      --etcd-pvc-size string                             etcd data path,valid in pvc mode. (default "5Gi")
      --etcd-replicas int32                              etcd replica set, cluster 3,5...singular (default 1)
      --etcd-storage-mode string                         etcd data storage mode(emptyDir,hostPath,PVC). value is PVC, specify --storage-classes-name (default "emptyDir")
  -h, --help                                             help for init
      --karmada-aggregated-apiserver-image string        karmada aggregated apiserver image (default "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:v0.10.1")
      --karmada-aggregated-apiserver-replicas int32      karmada aggregated apiserver replica set (default 1)
      --karmada-apiserver-image string                   Kubernetes apiserver image (default "k8s.gcr.io/kube-apiserver:v1.21.7")
      --karmada-apiserver-replicas int32                 karmada apiserver replica set (default 1)
      --karmada-controller-manager-image string          karmada controller manager  image (default "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:v0.10.1")
      --karmada-controller-manager-replicas int32        karmada controller manager replica set (default 1)
  -d, --karmada-data string                              karmada data path. kubeconfig cert and crds files (default "/etc/karmada")
      --karmada-kube-controller-manager-image string     Kubernetes controller manager image (default "k8s.gcr.io/kube-controller-manager:v1.21.7")
      --karmada-kube-controller-manager-replicas int32   karmada kube controller manager replica set (default 1)
      --karmada-scheduler-image string                   karmada scheduler image (default "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:latest:v0.10.1")
      --karmada-scheduler-replicas int32                 karmada scheduler replica set (default 1)
      --karmada-webhook-image string                     karmada webhook image (default "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-webhook:v0.10.1")
      --karmada-webhook-replicas int32                   karmada webhook replica set (default 1)
  -n, --namespace string                                 Kubernetes namespace (default "karmada-system")
  -p, --port int32                                       Karmada apiserver service node port (default 32443)
      --storage-classes-name string                      Kubernetes StorageClasses Name
```

**Does this PR introduce a user-facing change?**:

```release-note
`karmadactl`: Fixed `init` commands can not select default release version issue.
```
/cc @RainbowMango
@zach593

### CODE REVIEW

File: pkg/karmadactl/cmdinit/utils/util.go [hunk 1]
```diff
@@ -8,9 +8,38 @@ import (
...
+// GetInitVersion formatted version
+func GetInitVersion(version string) InitVersion {
+	// CRD version e.g. v0.10.1-547-g0190fda9-dirty -> v0.10.0
+	n := strings.LastIndex(version, ".") + 1
+
+	return InitVersion{
+		ImageVersion: initImageVersion(version),
+		CRDVersion:   fmt.Sprintf("%s%s", string([]byte(version)[:n]), "0"),
+	}
+}
```
Comment (RainbowMango) [inline pkg/karmadactl/cmdinit/utils/util.go:30]: I guess there will be some tools/packages to handle the git version thing. I'll try to investigate it.

File: pkg/karmadactl/cmdinit/cmdinit.go [hunk 2]
```diff
@@ -57,21 +60,21 @@ func NewCmdInit(cmdOut io.Writer, parentCommand string) *cobra.Command {
...
+	crdURL := fmt.Sprintf("https://github.com/karmada-io/karmada/releases/download/%s/crds.tar.gz", v.CRDVersion)
 	flags.StringVar(&opts.CRDs, "crds", crdURL, "Karmada crds resource.(local file e.g. --crds /root/crds.tar.gz)")
 	flags.Int32VarP(&opts.KarmadaAPIServerNodePort, "port", "p", 32443, "Karmada apiserver service node port")
 	flags.StringVarP(&opts.KarmadaDataPath, "karmada-data", "d", "/etc/karmada", "karmada data path. kubeconfig cert and crds files")
 	flags.StringVarP(&opts.KarmadaAPIServerImage, "karmada-apiserver-image", "", "k8s.gcr.io/kube-apiserver:v1.21.7", "Kubernetes apiserver image")
 	flags.Int32VarP(&opts.KarmadaAPIServerReplicas, "karmada-apiserver-replicas", "", 1, "karmada apiserver replica set")
-	flags.StringVarP(&opts.KarmadaSchedulerImage, "karmada-scheduler-image", "", "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:latest", "karmada scheduler image")
+	flags.StringVarP(&opts.KarmadaSchedulerImage, "karmada-scheduler-image", "", fmt.Sprintf("swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:latest:%s", v.ImageVersion), "karmada scheduler image")
```
Comment (zach593) [inline pkg/karmadactl/cmdinit/cmdinit.go:69]: `:latest:%s`

File: pkg/karmadactl/cmdinit/utils/util_test.go [hunk 3]
```diff
@@ -24,3 +25,11 @@ func TestDownloadFile(t *testing.T) {
 		panic(err)
 	}
 }
+
+// TestGetInitVersion test GetInitVersion
+func TestGetInitVersion(t *testing.T) {
```
Comment (zach593) [inline pkg/karmadactl/cmdinit/utils/util_test.go:30]: make it failable, so it could be useful in CI

Comment (prodanlabs) [reply pkg/karmadactl/cmdinit/utils/util_test.go:30]: oh my fault.

Comment (prodanlabs) [reply pkg/karmadactl/cmdinit/utils/util_test.go:30]: oh my fault.

File: pkg/karmadactl/cmdinit/cmdinit.go (hunk 2 above)
Comment (prodanlabs) [reply pkg/karmadactl/cmdinit/cmdinit.go:69]: oh my fault.

File: pkg/karmadactl/cmdinit/utils/util_test.go (hunk 3 above)
Comment (prodanlabs) [reply pkg/karmadactl/cmdinit/utils/util_test.go:30]: > make it failable, so it could be useful in CI
The version number is passed in when compiling, I feel like I can't do anything in go test.
https://github.com/karmada-io/karmada/blob/master/Makefile#L15

Comment (zach593) [reply pkg/karmadactl/cmdinit/utils/util_test.go:30]: `GetInitVersion()` get "GitVersion" from param, at least we could still check that the shift logic is correct or not

**Comment by zach593** [comment]
> The images and crd versions of karmadactl init are the same as the karmadactl version by default

and builds by makefile from master branch will refer to latest release version (with best effort)

**Comment by RainbowMango** [comment]
Hi @prodanlabs I appended a commit on yours, cloud you please help to confirm?

**Comment by prodanlabs** [comment]
Cool！

**Comment by RainbowMango** [comment]
/retitle `karmadactl`: Fixed `init` commands can not select default release version issue.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve
