### PR TITLE
fix: avoid delete the key with empty value in object (lua table)

### LINKED ISSUE #3617: argo rollout CRD resources submit member cluster to create Work resource field types are inconsistent
Environment:

Karmada version: v1.5.0
Kubernetes version: v1.20.8

use argo rollout， install crd and sample reference: 
https://argo-rollouts.readthedocs.io/en/stable/installation/
https://argo-rollouts.readthedocs.io/en/stable/features/canary/

First install argo rollout crd on karmada apiserver.

`k get crd rollouts.argoproj.io`

image

Then submit the argo rollout resource to karmada
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: nginx
  name: nginx-rollout
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    canary:
      maxSurge: 100%
      maxUnavailable: 0
      steps:
      - setWeight: 40
      - pause: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
Query Work resources event:

```
Events:
  Type     Reason      Age                   From                  Message
  ----     ------      ----                  ----                  -------
  Warning  SyncFailed  9m46s (x19 over 31m)  execution-controller  Failed to sync work(nginx-rollout-6fc47b96ff) to cluster(member-1): Rollout.argoproj.io "nginx-rollout" is invalid: spec.strategy.canary.steps: Invalid value: "array": spec.strategy.canary.steps in body must be of type object: "array"
```

Query Work resource Manifest spec.strategy.canary.steps definition

```
apiVersion: work.karmada.io/v1alpha1
kind: Work
metadata:
   ....
spec:
  workload:
    manifests:
    - apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"argoproj.io/v1alpha1","kind":"Rollout","metadata":{"annotations":{},"labels":{"app":"nginx"},"name":"nginx-rollout","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{"canary":{"maxSurge":"100%","maxUnavailable":0,"steps":[{"setWeight":40},{"pause":{}}]}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx","imagePullPolicy":"Always","name":"nginx","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
            ....
      spec:
        ...
        strategy:
          canary:
            maxSurge: 100%
            maxUnavailable: 0
            steps:
            - setWeight: 40
            - []
     ......
status:
  conditions:
  - lastTransitionTime: "2023-06-01T09:31:38Z"
    message: 'Failed to apply all manifests (0/1): Rollout.argoproj.io "nginx-rollout"
      is invalid: spec.strategy.canary.steps: Invalid value: "array": spec.strategy.canary.steps
      in body must be of type object: "array"'
    reason: AppliedFailed
    status: "False"
    type: Applied
```
Through the definition of Work Manifest spec.strategy.canary.steps, it is found that the type of 'object'{} has changed to 'array'[], which does not conform to the original type definition, so the submission will fail.

### LINKED ISSUE #4449: argocd ComparisonError <string>:100: bad argument #1 to ipairs (table expected, got nil) stack traceback: [G]: in function 'ipairs' <string>:100: in main chunk [G]: ?
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
Deploying workload rollout through argocd results in an error as follows：
ComparisonError
<string>:100: bad argument #1 to ipairs (table expected, got nil) stack traceback: [G]: in function 'ipairs' <string>:100: in main chunk [G]: ?

image

Please take a look, thx

**Environment**:
- Karmada version: v1.8
- Kubernetes version: 1.26.5
- Others:  argo-rollout:v1.5.1  argo server:v2.4.28

### LINKED ISSUE #4653: Pod restarted when promote a existing deployment from member cluster to Karmada
**What happened**:

A deployment already existed in member1 cluster.

The user want to promote the existing deployment from member1 cluster to Karmada using `conflictResolution: Overwrite`.

In the case when Customization ResourceInterpreter is used in Karmada and empty filed like `affinity: {}` is used in ResourceTemplate,
the promotion run suceess but the related pod has restarted.

**What you expected to happen**:

The existing deployment will be promoted by Karmada without related pod restarted.

**How to reproduce it (as minimally and precisely as possible)**:

1. write `nginx.yaml` as follows

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity: {}
      terminationGracePeriodSeconds: 0
      securityContext: {}
      containers:
        - image: nginx
          lifecycle: {}
          name: nginx
          resources:
            limits:
              cpu: 25m
              memory: 64Mi
          securityContext: {}
```

2. write `pp.yaml` as follows

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: pp
spec:
  conflictResolution: Overwrite
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```

3. write `resource-interpreter-customization.yaml` as follows

```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: member-cluster-deploy
spec:
  customizations:
    retention:
      luaScript: |
        function Retain(desiredObj, observedObj)
          local observedAnnotations = observedObj.spec.template.metadata.annotations
          if observedAnnotations ~= nil and observedAnnotations["k8s.haier.net/timestamp"] ~= nil then
            if desiredObj.spec.template.metadata.annotations == nil then
              desiredObj.spec.template.metadata.annotations = {}
            end
            desiredObj.spec.template.metadata.annotations["k8s.haier.net/timestamp"] = observedAnnotations["k8s.haier.net/timestamp"]
          end
          if observedObj.metadata.annotations ~= nil and observedObj.metadata.annotations["karmada.haier.net/retain-replicas"] == "true" then
            desiredObj.spec.replicas = observedObj.spec.replicas
          end
          print("desiredObj ", desiredObj)
          return desiredObj
        end
  target:
    apiVersion: apps/v1
    kind: Deployment
```

4. **apply `nginx.yaml` directly to member1 cluster, and watch the changes of pod in member1**

```shell
kubectl --context member1 apply -f nginx.yaml
kubectl --context member1 get po -w
```

5. apply `resource-interpreter-customization.yaml` to Karmada

```shell
kubectl --context karmada-apiserver apply -f resource-interpreter-customization.yaml
```

6. apply `nginx.yaml` and `pp.yaml` to Karmada

```shell
kubectl --context karmada-apiserver apply -f pp.yaml
kubectl --context karmada-apiserver apply -f nginx.yaml
```

7. check the result

    **the existing deployment will be promoted by Karmada, but the related pod has restarted, which is expected not to restart.**

***

**Original Problem**：

Previous Implementation:
Empty struct field({}) -> LuaTable{} -> json encode ([]) -> json (delete []) -> unmarshal -> Field(nil)
Empty slice field([]) -> LuaTable{} -> json encode ([]) -> json (delete []) -> unmarshal -> Field(nil)

Expected Result:
Empty struct field({}) -> LuaTable{} -> json encode ([]) -> json (convert [] to {}) -> unmarshal ->  Field({})
Empty slice field([]) -> LuaTable{} -> json encode ([]) -> json (keep []) -> unmarshal ->  Field([])

In a word: empty lua.LTable{} can not be distinguished from empty slice or empty struct when encoding.

**Solution**：

Empty object value are not generated out of thin air, take `Retain(desired, observed)` for example,
empty object value may come from three sources:
    1. originally from desired object
    2. originally from observed object
    3. user added in Custom ResourceInterpreter (the probability is low and not recommended)

We just need to traverse the fields of luaResult, compared to the traversal result of `disired` and `observed` objects,
    1. if an empty object field exists as a **slice** in the `disired`/`observed` object, keep [] unchanged.
    2. if an empty object field exists as a **struct** in the `disired`/`observed` object, convert [] back to {}.
    3. if an empty object field doesn't exist in `disired`/`observed` object, compatible with previous implementations, remove this field.

***

**Anything else we need to know?**:

**Environment**:
- Karmada version: latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): latest
- Others:

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

A deployment already existed in member1 cluster.

The user want to promote the existing deployment from member1 cluster to Karmada using conflictResolution: Overwrite.

In the case when Customization ResourceInterpreter is used in Karmada and empty filed like affinity: {} is used in ResourceTemplate, the promotion run suceess but the related pod has restarted.

**What we expected** is that the existing deployment will be promoted by Karmada without related pod restarted.

**The reason lies in** the `Retain` process of Custom ResourceInterpreter, after Lua script is executed, the empty filed like `affinity: {}` has been deleted, so the `Work` synchronized to member cluster is different from previous configuration, which lead to the member cluster's pod restarted.

**The resolution is** avoid  deleting the key with empty value in object (lua table), keep the same as previously configurated.

**Which issue(s) this PR fixes**:

Fixes #4653

Fixes #3617

Fixes #4449

**Special notes for your reviewer**:

* Original Problem:

Previous Implementation:
Empty struct field({}) -> LuaTable{} -> json encode ([]) -> json (delete []) -> unmarshal -> Field(nil)
Empty slice field([]) -> LuaTable{} -> json encode ([]) -> json (delete []) -> unmarshal -> Field(nil)

Expected Result:
Empty struct field({}) -> LuaTable{} -> json encode ([]) -> json (convert [] to {}) -> unmarshal ->  Field({})
Empty slice field([]) -> LuaTable{} -> json encode ([]) -> json (keep []) -> unmarshal ->  Field([])

In a word: empty lua.LTable{} can not be distinguished from empty slice or empty struct when encoding.

* Solution

Empty object value are not generated out of thin air, take `Retain(desired, observed)` for example,
empty object value may come from three sources:
    1. originally from desired object
    2. originally from observed object
    3. user added in Custom ResourceInterpreter (the probability is low and not recommended)

We just need to traverse the fields of luaResult, compared to the traversal result of `disired` and `observed` objects,
    1. if an empty object field exists as a **slice** in the `disired`/`observed` object, keep [] unchanged.
    2. if an empty object field exists as a **struct** in the `disired`/`observed` object, convert [] back to {}.
    3. if an empty object field doesn't exist in `disired`/`observed` object, compatible with previous implementations, remove this field.

**Does this PR introduce a user-facing change?**:

```release-note
fix: avoid delete the key with empty value in object (lua table)
```

### CODE REVIEW

**Comment by chaosi-zju** [comment]
> Does it solve this issue #3617?

Hi @ikaven1024, it seems that it is the same problem as #3617~

And, I have tested that this PR can also solve #3617 !

```shell
➜  argo kubectl --context karmada-apiserver get rb                                                                            
NAME                    SCHEDULED   FULLYAPPLIED   AGE
nginx-rollout-rollout   True        True           65s
```

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 1]
```diff
@@ -47,50 +49,40 @@ func ConvertLuaResultInto(luaResult lua.LValue, obj interface{}) error {
...
 	if err != nil {
 		return fmt.Errorf("json Encode obj eroor %v", err)
 	}
 
+	// Only if `[]` is the value of a field, it will be converted to `{}`,
+	// otherwise, for example, if `[]` is a substring in a string value, it needs to be ignored
+	//
+	// e.g: assuming the given jsonBytes is: {"one-field":[],"one-label":"\"hello\":[]"}
+	// it is expected to convert to: {"one-field":{},"one-label":"\"hello\":[]"}
+	re, _ := regexp.Compile(`"([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]":\[]`)
```
Comment (zhzhuang-zju) [inline pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:80]: I'm a little skeptical about this regexp. If ```"hello":[]``` is used as the value of a field, it can actually match this regexp. etc, ```"{\"one-field\":`\"hello\":[]`}"```.
```go
func main() {
	re, _ := regexp.Compile(`"([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]":\[]`)
	fmt.Println(re.MatchString("{\"one-field\":`\"hello\":[]`}"))
}
```
```shell
PS C:\Users\Administrator\GolandProjects\awesomeProject> go run main.go
true
```

Comment (zhzhuang-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:80]: never mind, the above example string is formatted incorrectly, the correct one should be `{"one_filed":"\"hello\":[]"}`. It is verified that the match fails, as expected

Comment (chaosi-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:80]: thanks all the same~

[the remark this answers is not in the document]
Comment (chaosi-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:80]: Got it, you are absolutely right~

done

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 2]
```diff
@@ -47,50 +49,40 @@ func ConvertLuaResultInto(luaResult lua.LValue, obj interface{}) error {
...
-	}
-	walkValue(luaResult)
-
+	//
+	//  Notes: don't worry that the value of a field is `[]`, and it originally represents an empty slice.
+	//  Because this situation will not appear in the following `jsonBytes`.
+	//  Supposing the value of a field is originally an empty slice:
+	//    1. if this field is omitempty, the key and value will both been removed in `jsonBytes`.
+	//    2. if this field is not omitempty, but required, empty slice is impossible to be created.
+	//    3. if this field is not omitempty, but optional, it has been verified also be removed in `jsonBytes`, e.g: `Rules` field in `Role` Type.
```
[the remark this answers is not in the document]
Comment (chaosi-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go]: You got the point, this is the most critical part.

I can't explain it either, based solely on experimental results

At first I experimented with `Role` resource, in which a `rules`  field is defined as:

```go
// Rules holds all the PolicyRules for this Role
// +optional
Rules []PolicyRule `json:"rules" protobuf:"bytes,2,rep,name=rules"`
```

I applied a `Role` to karmada-apiserver, the yaml is as:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo
rules: []
```

Then I get the resource and got:

```yaml
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"demo","namespace":"default"},"rules":[]}
    creationTimestamp: "2024-02-28T03:53:29Z"
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:rules: {}
      manager: kubectl
      operation: Update
      time: "2024-02-28T03:53:29Z"
    name: demo
    namespace: default
    resourceVersion: "11352"
    uid: 1e101630-5ec0-43e7-8dec-5a4851f3278d
  rules: null
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Pay attention to the field `rules: null`.

Then, I log the `jsonBytes` in `ConvertLuaResultInto` function, and found after `luajson.Encode(luaResult)` executed, that `rules: null` is not existed.

I recklessly thought that all case were like this, but I just found out that I was wrong.

**Comment by chaosi-zju** [comment]
I find a unsatisfied case.

1. Apply `Rollout` CRDs on both Karmada APIserver and member1 as per https://argo-rollouts.readthedocs.io/en/stable/installation/#controller-installation.
2. Apply a `ResourceInterpreterCustomization` to Karmada APIserver.
```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: declarative-configuration-argo-rollout
spec:
  target:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
  customizations:
    retention:
      luaScript: |
        function Retain(desiredObj, observedObj)
          print("[DEBUG] desiredObj ", desiredObj)
          return desiredObj
        end

```
3. Apply the Rollout yaml to Karmada APIserver (modified on the basis of #3617)
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: nginx
  name: nginx-rollout
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    canary:
      maxSurge: 100%
      maxUnavailable: 0
      steps:
        - setWeight: 40
        - pause: {}
        - experiment:
            templates: []
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
4. Apply a PropagationPolicy as follows:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      name: nginx-rollout
  placement:
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
    clusterAffinity:
      clusterNames:
        - member1
```

Pay attention to the `Rollout` resource, there is a `spec.strategy.canary.steps[2].experiment.templates` filed, its value is a slice with zero size, the filed is defined as:

```go
// Templates what templates that should be added to the experiment. Should be non-nil
// +patchMergeKey=name
// +patchStrategy=merge
Templates []RolloutExperimentTemplate `json:"templates" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,1,rep,name=templates"`
```

However, in the process of `ConvertLuaResultInto`, the key-pair `templates: []` will keep existed in `jsonBytes` variable, and would be incorrectly converted to `templates: {}` by my this PR.

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 3]
```diff
@@ -17,90 +17,208 @@ limitations under the License.
...
+}
+
+// traverseToFindEmptyFieldNeededModify find the field with empty values which needed to be modified by traverse a gjson.Result
+//
+// e.g: root={"spec":{"aa":[],"bb":[],"cc":["x"],"dd":{"ee":[],"ff":[]}}}
+// fieldOfEmptySlice={"spec.bb": {}}, fieldOfEmptyStruct={"spec.aa": {}, "spec.dd.ee": {}}
+//
+// we traverse the root and record every level filed name into `fieldPath`、`fieldPathWithArrayIndex` variable,
+// then judge whether the field path exist in `fieldOfEmptySlice` or `fieldOfEmptyStruct` variable:
+//  1. when travese to the field `spec.aa`, we got an empty slice, but this filed exists in `fieldOfEmptyStruct`,
```
Comment (XiShanYongYe-Chang) [inline pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:181]: type `travese ` -> `traverse`

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 4]
```diff
@@ -17,90 +17,208 @@ limitations under the License.
...
+// For the first two cases, we just need to iterate through the json bytes of `disired` and `observed` objects (called as references),
+// and record the empty slice fields in map `fieldOfEmptySlice`, record the empty struct fields in map `fieldOfEmptyStruct`,
+// finally iterate through the given json bytes:
+//  1. if an empty field ever existed in `fieldOfEmptySlice`, then it originally is slice, should keep unchanged.
+//  2. if an empty field ever existed in `fieldOfEmptyStruct`, then it originally is struct, should be change back to struct.
+//  3. if an empty field not ever existed in either map, is user added in Custom ResourceInterpreter,
+//     we still remove this redundant field (compatible with previous).
+func convertSomeEmptySliceBackToEmptyStruct(objBytes []byte, isStruct bool, references []*unstructured.Unstructured) ([]byte, error) {
+	objJSONStr := string(objBytes)
+	fieldOfEmptySlice, fieldOfEmptyStruct := make(map[string]struct{}), make(map[string]struct{})
```
Comment (XiShanYongYe-Chang) [inline pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:98]: I suggest using sets instead of maps.

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 5]
```diff
@@ -17,90 +17,208 @@ limitations under the License.
...
+	fieldOfEmptySliceToStruct, fieldOfEmptySliceToDelete := make(map[string]struct{}), make(map[string]struct{})
+
+	// 3. iterate through the given json bytes, and check an empty slice field whether ever existed in referenced objects.
+	traverseToFindEmptyFieldNeededModify(objJSON, nil, nil, fieldOfEmptySlice,
+		fieldOfEmptyStruct, fieldOfEmptySliceToStruct, fieldOfEmptySliceToDelete)
+
+	// 4. if an empty slice field is originally a struct, change it back to {}; if originally not exist, delete the field.
+	var err error
+	for fieldPath := range fieldOfEmptySliceToStruct {
+		objJSONStr, err = sjson.Set(objJSONStr, fieldPath, map[string]interface{}{})
```
[the remark this answers is not in the document]
Comment (chaosi-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:126]: does you mean this ?

```suggestion
		objJSONStr, err = sjson.Set(objJSONStr, fieldPath, struct{}{})
```

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go (hunk 4 above)
Comment (chaosi-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:98]: nice comment!

**Comment by chaosi-zju** [comment]
Hi @XiShanYongYe-Chang, all your comments have been resolved, do you have time to check again?

Hi @ikaven1024, Do you have any further comments?

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
LGTM

**Comment by chaosi-zju** [comment]
kindly ping @ikaven1024 ~ ٩(๑❛ᴗ❛๑)۶

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 6]
```diff
@@ -17,90 +17,221 @@ limitations under the License.
...
+// finally iterate through the given json bytes:
+//  1. if an empty field ever existed in `fieldOfEmptySlice`, then it originally is slice, should keep unchanged.
+//  2. if an empty field ever existed in `fieldOfEmptyStruct`, then it originally is struct, should be change back to struct.
+//  3. if an empty field not ever existed in either map, is user added in Custom ResourceInterpreter,
+//     we still remove this redundant field (compatible with previous).
+func convertEmptySliceToEmptyStructPartly(objBytes []byte, isStruct bool, references []*unstructured.Unstructured) ([]byte, error) {
+	// 1. if an empty lua object is originally struct type (not slice), just return {}
+	if bytes.Equal(objBytes, []byte("[]")) && isStruct {
+		return []byte("{}"), nil
 	}
```
[the remark this answers is not in the document]
Comment (chaosi-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go]: You are absolutely right. I have fixed it and add a unit test case.

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 7]
```diff
@@ -17,90 +17,221 @@ limitations under the License.
...
 	luajson "layeh.com/gopher-json"
 )
 
 // ConvertLuaResultInto convert lua result to obj
-func ConvertLuaResultInto(luaResult lua.LValue, obj interface{}) error {
-	t, err := conversion.EnforcePtr(obj)
+// @param references: the method of encoding a lua table is flawed and needs to be referenced by the same Kind object.
+// take `Retain(desired, observed)` for example, we have problem to convert empty fields, but empty fields is most likely
+// from desired or observed object, so take {desired, observed} object as references to obtain more accurate encoding values.
+func ConvertLuaResultInto(luaResult *lua.LTable, obj interface{}, references []*unstructured.Unstructured) error {
```
[the remark this answers is not in the document]
Comment (chaosi-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:39]: do you mean this: 

```suggestion
func ConvertLuaResultInto[T any](luaResult *lua.LTable, obj interface{}, references []T) error {
```

[the remark this answers is not in the document]
Comment (chaosi-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go]: > ```go
> func ConvertLuaResultInto(luaResult *lua.LTable, obj interface{}, references ...any) error 
> ```

nice suggestion, thanks !

updated, done~

**Comment by chaosi-zju** [comment]
Is there any further comments?

File: pkg/resourceinterpreter/customized/declarative/luavm/lua.go [hunk 8]
```diff
@@ -237,7 +237,7 @@ func (vm *VM) Retain(desired *unstructured.Unstructured, observed *unstructured.
 	luaResult := results[0]
 	retainResult := &unstructured.Unstructured{}
 	if luaResult.Type() == lua.LTTable {
-		err := ConvertLuaResultInto(luaResult, retainResult)
+		err := ConvertLuaResultInto(luaResult.(*lua.LTable), retainResult, []*unstructured.Unstructured{desired, observed})
```
[the remark this answers is not in the document]
Comment (chaosi-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua.go]: great finding, thanks, done~

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~ @ikaven1024 
/approve

**Comment by XiShanYongYe-Chang** [comment]
Hi @chaosi-zju, can you help fill out the release note?

/cc @RainbowMango

**Comment by chaosi-zju** [comment]
> Hi @chaosi-zju, can you help fill out the release note?

done

File: go.mod [hunk 9]
```diff
@@ -21,6 +21,8 @@ require (
 	github.com/spf13/cobra v1.7.0
 	github.com/spf13/pflag v1.0.5
 	github.com/stretchr/testify v1.8.3
+	github.com/tidwall/gjson v1.17.1
+	github.com/tidwall/sjson v1.2.5
```
Comment (RainbowMango) [inline go.mod:25]: The last commit of `sjson` happened 2 years ago, do we have any other alternatives?

Comment (chaosi-zju) [reply go.mod:25]: We need json library to read and write json string directly, skip serialization.

Comment (chaosi-zju) [reply go.mod:25]: We need json library to read and write json string directly, skip serialization.

As for **get json string** function, here are several alternative, like:
* https://github.com/buger/jsonparser
* https://github.com/Jeffail/gabs
* https://github.com/bitly/go-simplejson
* https://github.com/antonholmquist/jason

However, only  `go-simplejson` is closer to the last update time, others are also several years no update. But they all have lower star number than `gjson`. 

As for **set json string** function, I haven't found any other alternatives yet.

Comment (RainbowMango) [reply go.mod:25]: I talked to some users about their practices regarding inactive dependencies, they generally do not allow to use dependencies that have been inactive for more than 3 years.

So, I think we can use the `github.com/tidwall/sjson` for now, and if still no new releases next year, we can replace it with go-simplejson.

What do you say?

Comment (chaosi-zju) [reply go.mod:25]: makes perfect sense !
