### PR TITLE
fixed the issue where pp-related claimMetadata was not properly cleaned up

### LINKED ISSUE #6513: ClaimMetadata not properly cleaned on deletion of Lazy activationPreference propagationpolicy
**What happened**:
When I first deploy a Deployment and then deploy a PropagationPolicy with `Lazy` activationPreference, no corresponding ResourceBinding is generated. This is normal. 
However, if I then delete this PropagationPolicy, the Deployment still retains the PropagationPolicy-related labels and metadata. Subsequently, when I deploy a new PropagationPolicy with a non-`Lazy` activationPreference, the Deployment fails to match this newly created PropagationPolicy.

**What you expected to happen**:
When a PropagationPolicy with `Lazy` activationPreference is deleted, the ClaimMetadata should be properly cleaned up so that it does not prevent the Resource Template from binding to a new PropagationPolicy.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up a Karmada environment:
```bash
$ hack/local-up-karmada.sh
```

2. Deploy a Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```

3. Deploy a PropagationPolicy with `Lazy` activationPreference:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  activationPreference: Lazy
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
  placement:
    clusterAffinity:
      clusterNames:
      - member1
      - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - member1
          weight: 1
        - targetCluster:
            clusterNames:
            - member2
          weight: 1
```
At this point, no ResourceBinding is generated, and the Deployment already has PropagationPolicy-related ClaimMetadata:
```yaml
  annotations:
    propagationpolicy.karmada.io/name: nginx-propagation
    propagationpolicy.karmada.io/namespace: default
  labels:
    app: nginx
    propagationpolicy.karmada.io/permanent-id: 537816cb-e95b-45ca-96c8-e7d5cfadae6e
```

4. Delete the PropagationPolicy with `Lazy` activationPreference:
The Deployment still retains the PropagationPolicy-related ClaimMetadata.

5. Deploy a new PropagationPolicy with non-`Lazy` activationPreference:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation-new
spec:
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
  placement:
    clusterAffinity:
      clusterNames:
      - member1
      - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - member1
          weight: 1
        - targetCluster:
            clusterNames:
            - member2
          weight: 1
```
At this point, the Deployment does not bind to the new PropagationPolicy to generate a ResourceBinding.

**Anything else we need to know?**:

- **Note**: The issue described above only occurs when you first deploy a Deployment and then deploy a PropagationPolicy with `Lazy` activationPreference.

- **Root Cause**: When a PropagationPolicy is deleted, the detector uses the PropagationPolicy-related labels to list ResourceBindings first. It then looks up the ResourceTemplate based on `resourcebindingSpec.Resource` to clean up the PropagationPolicy-related ClaimMetadata on both the ResourceTemplate and ResourceBinding. The process is illustrated below:

  However, if you first deploy a Deployment and then a PropagationPolicy with `Lazy` activationPreference, no ResourceBinding is generated. As a result, during the cleanup process for PropagationPolicy-related ClaimMetadata, the ResourceTemplate is overlooked, leading to residual metadata.

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixed the issue where pp-related claimMetadata was not properly cleaned up

**Which issue(s) this PR fixes**:

Fixes #6513

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed the issue where pp-related claimMetadata was not properly cleaned up when deleting propagationpolicy with Lazy activationPreference.
```

### CODE REVIEW

File: pkg/detector/detector.go [hunk 1]
```diff
@@ -955,6 +955,12 @@ func (d *ResourceDetector) ReconcilePropagationPolicy(key util.QueueKey) error {
 		if err = d.HandlePropagationPolicyDeletion(propagationObject.Labels[policyv1alpha1.PropagationPolicyPermanentIDLabel]); err != nil {
 			return err
 		}
+		if util.IsLazyActivationEnabled(propagationObject.Spec.ActivationPreference) {
+			claimMetadata := labels.Set{policyv1alpha1.PropagationPolicyPermanentIDLabel: propagationObject.Labels[policyv1alpha1.PropagationPolicyPermanentIDLabel]}
+			if err = d.cleanupResidualResourceTemplateClaimMetadata(claimMetadata, propagationObject.Spec.ResourceSelectors, CleanupPPClaimMetadata); err != nil {
+				return err
+			}
+		}
```
Comment (RainbowMango) [inline pkg/detector/detector.go]: Is there any particular reason not to put this logic into `HandlePropagationPolicyDeletion()`?

The current approach would miss the chance to clean up the claimed label when reconciling the resource template: 
https://github.com/karmada-io/karmada/blob/d0f74642463df113fb1cd207e8662074bdd39a78/pkg/detector/policy.go#L116.

File: pkg/detector/detector.go [hunk 2]
```diff
@@ -1143,6 +1161,69 @@ func (d *ResourceDetector) HandleClusterPropagationPolicyDeletion(policyID strin
...
+					workload.GetKind(), workload.GetNamespace(), workload.GetName(), err)
+				errs = append(errs, err)
+			}
+		}
+	}
+
+	return errors.NewAggregate(errs)
+}
+
+func (d *ResourceDetector) cleanupResourceTemplateClaimMetadata(gvr schema.GroupVersionResource, obj *unstructured.Unstructured, targetClaimMetadata map[string]string, cleanupFunc func(obj metav1.Object)) error {
```
Comment (RainbowMango) [inline pkg/detector/detector.go]: The methods `cleanupResourceTemplateClaimMetadata` and `CleanupResourceTemplateClaimMetadata` are ambiguous; why not just use the previous one? Seems all you need to build a `workv1alpha2.ObjectReference`.

File: pkg/detector/detector.go [hunk 3]
```diff
@@ -1143,6 +1161,69 @@ func (d *ResourceDetector) HandleClusterPropagationPolicyDeletion(policyID strin
 	return errors.NewAggregate(errs)
 }
 
+func (d *ResourceDetector) cleanupResidualResourceTemplateClaimMetadata(targetClaimMetadata labels.Set, resourceSelector []policyv1alpha1.ResourceSelector, cleanupFunc func(obj metav1.Object)) error {
```
Comment (RainbowMango) [inline pkg/detector/detector.go]: Need another name for clarity. 

`cleanupResidualResourceTemplateClaimMetadata` similar to `cleanupResourceTemplateClaimMetadata`

File: pkg/detector/detector.go (hunk 1 above)
Comment (zhzhuang-zju) [reply pkg/detector/detector.go]: > Is there any particular reason not to put this logic into HandlePropagationPolicyDeletion()?

Yes, the input parameters of function `HandlePropagationPolicyDeletion` do not include `ActivationPreference` information. Given that the current approach is only an interim solution, I don't want to modify the existing `HandlePropagationPolicyDeletion`.

> The current approach would miss the chance to clean up the claimed label when reconciling the resource template:

Good point! I also noticed this, but I think this is not an issue with the new logic, but rather that when the resource template detects that the pp has been deleted, it should not call `HandlePropagationPolicyDeletion` in the first place - it's expensive and unnecessary. The resource template should focus on its own cleanup. When the resource template detects that the pp is no longer present, it just needs to clean up its own remaining labels. Actually, this approach is more reasonable. First: it reduces the overhead of calling `HandlePropagationPolicyDeletion` and avoids redundant cleanup operations for the same set of objects; Second: if resource binding generation fails, it won't block the resource template's own cleanup.

File: pkg/detector/detector.go (hunk 2 above)
Comment (zhzhuang-zju) [reply pkg/detector/detector.go]: > why not just use the previous one? Seems all you need to build a workv1alpha2.ObjectReference.

Because the current `CleanupResourceTemplateClaimMetadata` first uses a `GET` request to retrieve the ResourceTemplate and then `Update` it. However, the new logic retrieves all ResourceTemplates through `List` and then cleans them up one by one. Therefore, `GET` requests are not needed.

File: pkg/detector/detector.go [hunk 4]
```diff
@@ -1143,6 +1167,68 @@ func (d *ResourceDetector) HandleClusterPropagationPolicyDeletion(policyID strin
...
+							if apierrors.IsNotFound(getErr) {
+								return nil
+							}
+							return getErr
+						}
+						workload = newWorkload
+					}
+					return err
+				}
+				klog.V(2).Infof("Updated resource template(kind=%s, %s/%s) successfully", workload.GetKind(), workload.GetNamespace(), workload.GetName())
```
Comment (RainbowMango) [inline pkg/detector/detector.go]:
```suggestion
				klog.V(2).Infof("Clean claimed label for resource template(kind=%s, %s/%s) successfully", workload.GetKind(), workload.GetNamespace(), workload.GetName())
```

**Comment by zhzhuang-zju** [comment]
cc @gemini-code-assist

**Review by RainbowMango — COMMENTED** [review]
/assign

File: pkg/detector/policy.go [hunk 5]
```diff
@@ -110,11 +110,19 @@ func (d *ResourceDetector) getAndApplyPolicy(object *unstructured.Unstructured,
 	resourceChangeByKarmada bool, policyNamespace, policyName, claimedID string) error {
 	matchedPropagationPolicy := &policyv1alpha1.PropagationPolicy{}
 	err := d.Client.Get(context.TODO(), client.ObjectKey{Namespace: policyNamespace, Name: policyName}, matchedPropagationPolicy)
-	if err != nil {
-		if apierrors.IsNotFound(err) {
-			klog.V(4).Infof("PropagationPolicy(%s/%s) has been removed.", policyNamespace, policyName)
-			return d.HandlePropagationPolicyDeletion(claimedID)
+	if apierrors.IsNotFound(err) || (err == nil && !matchedPropagationPolicy.DeletionTimestamp.IsZero()) {
+		// Policy not found or being deleted, clean up metadata
```
Comment (RainbowMango) [inline pkg/detector/policy.go]: > (err == nil && !matchedPropagationPolicy.DeletionTimestamp.IsZero()

It does not sound right to get involved in the lifecycle management of PropagationPolicy. 
When PropagationPolicy is deleted, there is a workflow to clean up labels on resource templates.

File: pkg/detector/detector.go [hunk 6]
```diff
@@ -690,6 +690,64 @@ func (d *ResourceDetector) GetUnstructuredObject(objectKey keys.ClusterWideKey)
 	return unstructuredObj.DeepCopy(), nil
 }
 
+// fetchResourceBinding fetches a ResourceBinding from the client or dynamic client.
+func (d *ResourceDetector) fetchResourceBinding(rbNamespace, rbName string) (*workv1alpha2.ResourceBinding, error) {
+	// First try to get ResourceBinding using client
```
Comment (RainbowMango) [inline pkg/detector/detector.go]:
```suggestion
	// First try to get ResourceBinding using cached client
```

File: pkg/detector/detector.go [hunk 7]
```diff
@@ -690,6 +690,64 @@ func (d *ResourceDetector) GetUnstructuredObject(objectKey keys.ClusterWideKey)
...
+			unstructuredRB, dynamicErr := d.DynamicClient.Resource(gvr).Namespace(rbNamespace).Get(context.TODO(), rbName, metav1.GetOptions{})
+			if dynamicErr != nil {
+				return nil, dynamicErr
+			}
+
+			// Convert unstructured to ResourceBinding
+			if err := helper.ConvertToTypedObject(unstructuredRB, rb); err != nil {
+				klog.Errorf("Failed to convert unstructured to ResourceBinding(%s/%s): %v", rbNamespace, rbName, err)
+				return nil, err
+			}
```
Comment (RainbowMango) [inline pkg/detector/detector.go]: We might need to introduce a typed client for retrieving RB/CRB resources.
We can take this as a follow up.

File: pkg/detector/detector.go [hunk 8]
```diff
@@ -690,6 +690,64 @@ func (d *ResourceDetector) GetUnstructuredObject(objectKey keys.ClusterWideKey)
...
+
+			return rb, nil
+		}
+		klog.Errorf("Failed to get ResourceBinding(%s/%s): %v", rbNamespace, rbName, err)
+		return nil, err
+	}
+
+	return rb.DeepCopy(), nil
```
Comment (RainbowMango) [inline pkg/detector/detector.go]: Do we have to return a copy? 
The `Client` returns a copy by default.

File: pkg/detector/detector.go [hunk 9]
```diff
@@ -690,6 +690,64 @@ func (d *ResourceDetector) GetUnstructuredObject(objectKey keys.ClusterWideKey)
...
+}
+
+// fetchClusterResourceBinding fetches a ClusterResourceBinding from the client or dynamic client.
+func (d *ResourceDetector) fetchClusterResourceBinding(crbName string) (*workv1alpha2.ClusterResourceBinding, error) {
```
Comment (RainbowMango) [inline pkg/detector/detector.go]: ditto.

File: pkg/detector/detector.go (hunk 8 above)
Comment (zhzhuang-zju) [reply pkg/detector/detector.go]: Thank you for correcting me.

https://github.com/karmada-io/karmada/blob/17caa1bc7d8b27ad9ccd99d5ddbd20f6b95af5b0/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go#L84-L90

File: pkg/detector/policy.go (hunk 5 above)
Comment (zhzhuang-zju) [reply pkg/detector/policy.go]: I'm afraid we need to pay attention to whether `matchedPropagationPolicy.DeletionTimestamp` is nil.
Let me give an example:
Suppose a policy matches 1000 deployments. When the policy is being deleted, only 999 deployments are listed, so only the claimMetadata of these 999 deployments are cleaned up. The last deployment enters reconciliation, but at this time, since the policy deletion takes a relatively long time, the policy still exists, and thus this deployment will not enter the cleanup process. As a result, the policy-related claimMetadata of this deployment will remain indefinitely until the next reconciliation occurs.

Comment (RainbowMango) [reply pkg/detector/policy.go]: We can check the state of the PropagationPolicy before applying it; if it is being deleted, we can return and wait   . Again, it is not the responsibility and shouldn't get involved in the lifecycle management of PropagationPolicy.

Comment (zhzhuang-zju) [reply pkg/detector/policy.go]: Thanks for the suggestion! Update as recommened

File: pkg/detector/policy.go [hunk 10]
```diff
@@ -110,14 +110,28 @@ func (d *ResourceDetector) getAndApplyPolicy(object *unstructured.Unstructured,
 	resourceChangeByKarmada bool, policyNamespace, policyName, claimedID string) error {
 	matchedPropagationPolicy := &policyv1alpha1.PropagationPolicy{}
 	err := d.Client.Get(context.TODO(), client.ObjectKey{Namespace: policyNamespace, Name: policyName}, matchedPropagationPolicy)
-	if err != nil {
-		if apierrors.IsNotFound(err) {
-			klog.V(4).Infof("PropagationPolicy(%s/%s) has been removed.", policyNamespace, policyName)
-			return d.HandlePropagationPolicyDeletion(claimedID)
+	if apierrors.IsNotFound(err) {
+		// Policy not found or being deleted, clean up metadata
```
Comment (RainbowMango) [inline pkg/detector/policy.go]: The Policy now is not being deleted.

```suggestion
		// The expected PropagationPolicy has been removed, indicating the cleanup process has completed.
		// However, if the claimed data still exists in the resource template, it likely means the cleanup
		// for the resource template was missed. This can happen if the claimed data was added to the resource
		// template and then the PropagationPolicy was removed very shortly after.
		// When cleaning up resource templates based on PropagationPolicy deletion, the cache may not have received
		// the resource template update in time, resulting in a missed cleanup.
```
Please check if the reason on above that we need to do the cleanup.

File: pkg/detector/policy.go [hunk 11]
```diff
@@ -142,15 +156,28 @@ func (d *ResourceDetector) getAndApplyClusterPolicy(object *unstructured.Unstruc
 	resourceChangeByKarmada bool, policyName, policyID string) error {
 	matchedClusterPropagationPolicy := &policyv1alpha1.ClusterPropagationPolicy{}
 	err := d.Client.Get(context.TODO(), client.ObjectKey{Name: policyName}, matchedClusterPropagationPolicy)
-	if err != nil {
-		if apierrors.IsNotFound(err) {
-			klog.V(4).Infof("ClusterPropagationPolicy(%s) has been removed.", policyName)
-			return d.HandleClusterPropagationPolicyDeletion(policyID)
+	if apierrors.IsNotFound(err) {
+		// cluster Policy not found or being deleted, clean up metadata
```
Comment (RainbowMango) [inline pkg/detector/policy.go]: ditto

File: pkg/detector/detector.go [hunk 12]
```diff
@@ -1069,66 +1120,63 @@ func (d *ResourceDetector) HandlePropagationPolicyDeletion(policyID string) erro
...
-			}
+func (d *ResourceDetector) handleResourceTemplateAndBindingCleanup(template *unstructured.Unstructured, objRef workv1alpha2.ObjectReference, targetClaimMetadata map[string]string, cleanupFunc func(obj metav1.Object)) error {
+	bindingName := names.GenerateBindingName(template.GetKind(), template.GetName())
+	if template.GetNamespace() != "" {
+		// Clean up the claim metadata from the reference binding so that the karmada scheduler won't reschedule the binding.
+		// Must remove the claim metadata, such as labels and annotations, from the ResourceBinding ahead of resource template,
+		// otherwise might lose the chance to do that in a retry loop (in particular, the claim metadata was successfully removed
+		// from resource template, but ResourceBinding not), since the resource template will not be listed again.
+		if err := d.CleanupResourceBindingClaimMetadata(template.GetNamespace(), bindingName, targetClaimMetadata, cleanupFunc); err != nil {
+			klog.Errorf("Failed to clean up claim metadata from resource binding(%s/%s) when propagationPolicy removed, error: %v",
```
Comment (RainbowMango) [inline pkg/detector/detector.go]: The log is inaccurate; no such context indicates it is called due to the PropagationPolicy deletion.
```suggestion
			klog.Errorf("Failed to clean up claim metadata from ResourceBinding(%s/%s), error: %v",
```

Same as below.

File: pkg/detector/detector.go [hunk 13]
```diff
@@ -1069,66 +1121,64 @@ func (d *ResourceDetector) HandlePropagationPolicyDeletion(policyID string) erro
...
 
-			// Clean up the claim metadata from the reference binding so that the Karmada scheduler won't reschedule the binding.
-			if err := d.CleanupClusterResourceBindingClaimMetadata(&crbs.Items[index], labelSet); err != nil {
-				klog.Errorf("Failed to clean up claim metadata from clusterResourceBinding(%s) when clusterPropagationPolicy removed, error: %v",
-					binding.Name, err)
+		rawObjects, err := helper.FetchResourceTemplatesByLabelSelector(d.DynamicClient, d.InformerManager, d.RESTMapper, objRef, labels.SelectorFromSet(claimMetadata))
+		if err != nil {
+			errs = append(errs, err)
+			continue
+		}
```
Comment (RainbowMango) [inline pkg/detector/detector.go:1139]: It is the place where we introduced issue #6913.
