### PR TITLE
Enhanced forced deletion on karmadactl unjoin

### LINKED ISSUE #4431: Enhanced forced deletion on karmadactl unjoin
**What would you like to be added**:
When ```karmadactl unjoin```, if the cluster object cannot be deleted because the resources of the member clusters cannot be deleted, provide the parameter ```force``` to complete the forced deletion of the cluster capability.

**Why is this needed**:
The following figure shows the flow of execution behind the ```karmadactl unjoin``` command. When unjoining a cluster, in order to ensure that the resource can be deleted properly, the finalizers mechanism is used, and the deletion of the resource can only be completed when the task corresponding to the finalizers is completed.
image

This also results in karmadactl unjoin failing all the time if one of the steps doesn't complete properly. In particular, the process involves two clusters: the control cluster as well as the member clusters. Therefore I would like to add the ability to force unjoin to karmadactl unjoin, so that when a delete keeps failing at a certain time, if the ability to force delete is turned on, the finalizers that are blocking the process are deleted so that the process can continue.

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
When karmadactl unjoin a member cluster, the unjoin may fail all the time because the resource deletion of the member cluster fails. By enhancing the forced deletion on karmadactl unjoin, if the resource deletion of the member cluster fails also force unjoin
**Which issue(s) this PR fixes**:
Fixes #4431

**Special notes for your reviewer**:
1. delete clusterRole of member1
```shell
➜  karmada git:(master) km1 delete clusterrole karmada-controller-manager:karmada-member1 
clusterrole.rbac.authorization.k8s.io "karmada-controller-manager:karmada-member1" deleted
```
2. karmadactl unjoin member1
```shell
➜  karmada git:(master) karmadactl unjoin member1 --cluster-kubeconfig=/root/.kube/members.config
I1219 15:56:28.602959   54698 unjoin.go:264] Waiting for the cluster object member1 to be deleted
...
I1219 15:57:27.605630   54698 unjoin.go:264] Waiting for the cluster object member1 to be deleted
E1219 15:57:27.605651   54698 unjoin.go:268] Failed to delete cluster object. cluster name: member1, error: timed out waiting for the condition
E1219 15:57:27.605675   54698 unjoin.go:191] Failed to delete cluster object. cluster name: member1, error: timed out waiting for the condition
error: timed out waiting for the condition
```
3. karmadactl unjoin member1 --force
```shell
➜  karmada git:(master) karmadactl unjoin member1 --cluster-kubeconfig=/root/.kube/members.config --force
I1219 15:57:48.816159   54808 unjoin.go:264] Waiting for the cluster object member1 to be deleted
...
I1219 15:58:47.822262   54808 unjoin.go:264] Waiting for the cluster object member1 to be deleted
E1219 15:58:47.822290   54808 unjoin.go:268] Failed to delete cluster object. cluster name: member1, error: timed out waiting for the condition
E1219 15:58:47.822305   54808 unjoin.go:191] Failed to delete cluster object. cluster name: member1, error: timed out waiting for the condition
I1219 15:58:47.822310   54808 unjoin.go:193] Start forced deletion by remove work finalizer. cluster name: member1
I1219 15:58:47.847819   54808 unjoin.go:200] Succeeded to remove work's finalizer. After confirming the success of the unjoin, manually delete remaining resources on the cluster member1.
➜  karmada git:(master) ka get cluster
NAME      VERSION   MODE   READY   AGE
member2   v1.27.3   Push   True    4h3m
member3   v1.27.3   Pull   True    4h3m
```
4. rejoin
```shell
➜  karmada git:(master) karmadactl join member1 --cluster-kubeconfig=/root/.kube/members.config             
cluster(member1) is joined successfully
➜  karmada git:(master) ka get cluster
NAME      VERSION   MODE   READY   AGE
member1   v1.27.3   Push   True    5s
member2   v1.27.3   Push   True    4h15m
member3   v1.27.3   Pull   True    4h15m
```
**Does this PR introduce a user-facing change?**:

```release-note
`karmadactl`: The `--force` option of `unjoin` command now try to clean up resources propagated in member clusters.
```

### CODE REVIEW

**Review by chaunceyjiang — COMMENTED** [review]
This request I think is reasonable, but I don't think just deleting the cluster can solve it, it should also forcibly delete the `work` under this cluster. It should also forcibly delete other resources like `token`,`secret`,etc.

**Comment by zhzhuang-zju** [comment]
> This request I think is reasonable, but I don't think just deleting the cluster can solve it, it should also forcibly delete the `work` under this cluster. It should also forcibly delete other resources like `token`,`secret`,etc.

In fact, I achieve the purpose of forced deletion by deleting the `finalizer` that blocks the deletion step. If the cluster object can be deleted successfully, then resources such as secrets and tokens can also be deleted successfully.

**Comment by zhzhuang-zju** [comment]
The issue can be resolved by setting `PropagationPolicy.Spec.PreserveResourcesOnDeletion`.

**Comment by zhzhuang-zju** [comment]
> The issue can be resolved by setting `PropagationPolicy.Spec.PreserveResourcesOnDeletion`.

Apologies for the confusion between the two scenarios earlier. `PropagationPolicy.Spec.PreserveResourcesOnDeletion` is used to retain resources in the member cluster when a workload is deleted. Meanwhile, `karmadactl join --force` is used to delete cluster and secret resources even if resources in the cluster targeted for unjoin are not removed successfully. I will track the progress of this feature through #5477.

**Comment by zhzhuang-zju** [comment]
cc @chaunceyjiang @chaosi-zju

File: pkg/karmadactl/unjoin/unjoin.go [hunk 1]
```diff
@@ -324,3 +349,58 @@ func deleteNamespaceFromUnjoinCluster(clusterKubeClient kubeclient.Interface, na
...
+
+	for i := range list.Items {
+		work := &list.Items[i]
+		if !controllerutil.ContainsFinalizer(work, util.ExecutionControllerFinalizer) {
+			continue
+		}
+		controllerutil.RemoveFinalizer(work, util.ExecutionControllerFinalizer)
+		_, err = controlPlaneKarmadaClient.WorkV1alpha1().Works(executionSpaceName).Update(context.TODO(), work, metav1.UpdateOptions{})
+		if err != nil {
+			return err
```
[the remark this answers is not in the document]
Comment (zhzhuang-zju) [reply pkg/karmadactl/unjoin/unjoin.go]: done~

**Comment by zhzhuang-zju** [comment]
Enhanced forced deletion on karmadactl unjoin

> you shall resolve the conflict and do a rebase.

done

File: pkg/karmadactl/util/cluster.go [hunk 2]
```diff
@@ -58,10 +63,84 @@ func DeleteClusterObject(controlPlaneKarmadaClient karmadaclientset.Interface, c
...
+	executionSpace, err := controlPlaneKubeClient.CoreV1().Namespaces().Get(context.TODO(), executionSpaceName, metav1.GetOptions{})
+	if err != nil {
+		return fmt.Errorf("failed to get Namespace(%s)", executionSpaceName)
+	}
+
+	if !controllerutil.ContainsFinalizer(executionSpace, "kubernetes") {
+		return nil
+	}
+
+	controllerutil.RemoveFinalizer(executionSpace, "kubernetes")
```
Comment (RainbowMango) [inline pkg/karmadactl/util/cluster.go:125]: Why not refer to the constant defined in Kubernetes?
https://github.com/kubernetes/kubernetes/blob/2cdcaf1e8f5e85a20ffb63e3bbff15eb6e862e92/staging/src/k8s.io/api/core/v1/types.go#L6387-L6391

File: pkg/karmadactl/util/cluster.go [hunk 3]
```diff
@@ -24,14 +24,19 @@ import (
...
 
 	karmadaclientset "github.com/karmada-io/karmada/pkg/generated/clientset/versioned"
+	"github.com/karmada-io/karmada/pkg/util"
+	"github.com/karmada-io/karmada/pkg/util/names"
 )
 
 // DeleteClusterObject deletes the cluster object from the Karmada control plane.
-func DeleteClusterObject(controlPlaneKarmadaClient karmadaclientset.Interface, clusterName string,
-	timeout time.Duration, dryRun bool) error {
+// If the operation times out and `forceDeletion` is true, then force deletion begins, which involves sequentially deleting the `work`, `executionSpace`, and `cluster` finalizers.
```
Comment (RainbowMango) [inline pkg/karmadactl/util/cluster.go:37]:
```suggestion
```
Move comment into the function.

File: pkg/karmadactl/util/cluster.go [hunk 4]
```diff
@@ -58,10 +63,84 @@ func DeleteClusterObject(controlPlaneKarmadaClient karmadaclientset.Interface, c
 		klog.Infof("Waiting for the cluster object %s to be deleted", clusterName)
 		return false, nil
 	})
+
+	if err != nil && forceDeletion {
```
Comment (RainbowMango) [inline pkg/karmadactl/util/cluster.go:67]:
```suggestion
	// If the Cluster object not be deleted within the timeout period, it is likely due to the resources in the member
	// cluster can not be cleaned up. With the option force deletion, we will try to clean up the Cluster object by
	// removing the finalizers from related resources. This behavior may result in some resources remain in the member
	// clusters.
	if err != nil && forceDeletion {
```

File: pkg/karmadactl/unjoin/unjoin.go [hunk 5]
```diff
@@ -147,7 +147,7 @@ func (j *CommandUnjoinOption) AddFlags(flags *pflag.FlagSet) {
 	flags.StringVar(&j.ClusterKubeConfig, "cluster-kubeconfig", "",
 		"Path of the cluster's kubeconfig.")
 	flags.BoolVar(&j.forceDeletion, "force", false,
-		"Delete cluster and secret resources even if resources in the cluster targeted for unjoin are not removed successfully.")
+		"If true, when the unjoin process fails due to a timeout, force unjoin the member cluster by removing the finalizer from the related work, namespace, and cluster resources. Note that forcing the unjoin of a member cluster may result in residual resources and requires confirmation.")
```
Comment (RainbowMango) [inline pkg/karmadactl/unjoin/unjoin.go:150]:
```suggestion
		"When set, the unjoin command will attempt to clean up resources in the member cluster before deleting the Cluster object. If the cleanup fails within the timeout period, the Cluster object will still be deleted, potentially leaving some resources behind in the member cluster.")
```

**Review by RainbowMango — COMMENTED** [review]
Just some nits, otherwise LGTM.

File: pkg/karmadactl/unregister/unregister.go [hunk 6]
```diff
@@ -305,7 +319,8 @@ func (j *CommandUnregisterOption) RunUnregisterCluster() error {
 	}
 
 	// 1. delete the cluster object from the Karmada control plane
-	if err := cmdutil.DeleteClusterObject(j.ControlPlaneClient, j.ClusterName, j.Wait, j.DryRun); err != nil {
+	//TODO: add flag --force to implement force deletaion.
```
[the remark this answers is not in the document]
Comment (zhzhuang-zju) [reply pkg/karmadactl/unregister/unregister.go]: https://github.com/karmada-io/karmada/issues/5477 tracks the TODO item

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
