### PR TITLE
karmada-webhook: fix the no such host error

### LINKED ISSUE #4893: operator: dial tcp: lookup karmada-webhook.karmada-system.svc on x.x.x.x: no such host
**What happened**:
when deploying karmada instance by operator，`karmada-apiserver` will report `dial tcp: lookup karmada-webhook.karmada-system.svc on x.x.x.x: no such host` error if the namespace of karmada instance is not `karmada-system`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Follow Tutorial https://github.com/karmada-io/karmada/blob/master/operator/README.md and deploy karmada instance in namespace `test` 
- print the log of `karmada-apiserver`

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.9.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
when deploying karmada instance by operator or `karmadactl init`，karmada-apiserver will report `dial tcp: lookup karmada-webhook.karmada-system.svc on x.x.x.x: no such host` error if the namespace of karmada instance is not `karmada-system`.
```bash
E0208 07:01:36.926856       1 watcher.go:567] failed to prepare current and previous objects: conversion webhook for work.karmada.io/v1alpha2, Kind=ResourceBinding failed: Post "https://karmada-webhook.karmada-system.svc:443/convert?timeout=30s": dial tcp: lookup karmada-webhook.karmada-system.svc on 100.136.0.10:53: no such host
I0208 07:01:36.927733       1 reflector.go:481] storage/cacher.go:/work.karmada.io/resourcebindings: retrying watch of work.karmada.io/v1alpha1, Kind=ResourceBinding internal error: Internal error occurred: conversion webhook for work.karmada.io/v1alpha2, Kind=ResourceBinding failed: Post "https://karmada-webhook.karmada-system.svc:443/convert?timeout=30s": dial tcp: lookup karmada-webhook.karmada-system.svc on 100.136.0.10:53: no such host
E0208 07:02:07.875403       1 cacher.go:478] cacher (resourcebindings.work.karmada.io): unexpected ListAndWatch error: failed to list work.karmada.io/v1alpha1, Kind=ResourceBinding: conversion webhook for work.karmada.io/v1alpha2, Kind=ResourceBinding failed: Post "https://karmada-webhook.karmada-system.svc:443/convert?timeout=30s": dial tcp: lookup karmada-webhook.karmada-system.svc on 100.136.0.10:53: no such host; reinitializing...
W0208 07:02:07.875388       1 reflector.go:561] storage/cacher.go:/work.karmada.io/resourcebindings: failed to list work.karmada.io/v1alpha1, Kind=ResourceBinding: conversion webhook for work.karmada.io/v1alpha2, Kind=ResourceBinding failed: Post "https://karmada-webhook.karmada-system.svc:443/convert?timeout=30s": dial tcp: lookup karmada-webhook.karmada-system.svc on 100.136.0.10:53: no such host
```

https://github.com/karmada-io/karmada/blob/211351bb0f9f50b95205c5da698defaebc08499f/charts/karmada/_crds/patches/webhook_in_resourcebindings.yaml#L1-L14
The webhook url is hardcoded and actually needs to be entered via a variable.

**Which issue(s) this PR fixes**:
Fixes #4893

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-operator`: fix the "no such host" error when accessing the /convert webhook.
```

### CODE REVIEW

File: pkg/karmadactl/cmdinit/karmada/deploy_test.go [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			tmpfile, err := os.CreateTemp("", "example")
+			if err != nil {
+				t.Fatalf("failed to create temp file: %v", err)
+			}
+			defer os.Remove(tmpfile.Name()) // 清理临时文件
```
Comment (RainbowMango) [inline pkg/karmadactl/cmdinit/karmada/deploy_test.go:49]: comment

File: hack/deploy-karmada.sh [hunk 2]
```diff
@@ -302,7 +302,11 @@ TEMP_PATH_CRDS=$(mktemp -d)
 trap '{ rm -rf ${TEMP_PATH_CRDS}; }' EXIT
 cp -rf "${REPO_ROOT}"/charts/karmada/_crds "${TEMP_PATH_CRDS}"
 util::fill_cabundle "${ROOT_CA_FILE}" "${TEMP_PATH_CRDS}/_crds/patches/webhook_in_resourcebindings.yaml"
+sed -i'' -e "s/{{name}}/karmada-webhook/g" "${TEMP_PATH_CRDS}/_crds/patches/webhook_in_resourcebindings.yaml"
+sed -i'' -e "s/{{namespace}}/karmada-namespace/g" "${TEMP_PATH_CRDS}/_crds/patches/webhook_in_resourcebindings.yaml"
```
Comment (XiShanYongYe-Chang) [inline hack/deploy-karmada.sh:306]: `karmada-namespace` is it wrong?

File: operator/pkg/util/util.go [hunk 3]
```diff
@@ -241,6 +241,21 @@ func ReplaceYamlForReg(path, destResource string, reg *regexp.Regexp) ([]byte, e
 	return yaml.YAMLToJSON([]byte(repl))
 }
 
+// ReplaceYamlForRegs replace content of yaml file with Regexps
```
Comment (XiShanYongYe-Chang) [inline operator/pkg/util/util.go:244]: Is the `ReplaceYamlForReg` function no longer needed?

File: operator/pkg/util/util.go [hunk 4]
```diff
@@ -241,6 +241,21 @@ func ReplaceYamlForReg(path, destResource string, reg *regexp.Regexp) ([]byte, e
...
+func ReplaceYamlForRegs(path string, replacements map[*regexp.Regexp]string) ([]byte, error) {
```
Comment (XiShanYongYe-Chang) [inline operator/pkg/util/util.go:245]: Is it convenient to add a ut to this function?

File: pkg/karmadactl/cmdinit/karmada/deploy_test.go [hunk 5]
```diff
@@ -0,0 +1,68 @@
+/*
+Copyright 2024 The Karmada Authors.
```
Comment (XiShanYongYe-Chang) [inline pkg/karmadactl/cmdinit/karmada/deploy_test.go:2]: 2024 -> 2025

Comment (zhzhuang-zju) [reply pkg/karmadactl/cmdinit/karmada/deploy_test.go:2]: How time flies

File: hack/deploy-karmada.sh (hunk 2 above)
Comment (zhzhuang-zju) [reply hack/deploy-karmada.sh:306]: Nice catch

File: operator/pkg/util/util.go (hunk 3 above)
Comment (zhzhuang-zju) [reply operator/pkg/util/util.go:244]: Yes, do we need to remove this function?

File: operator/pkg/util/util.go (hunk 4 above)
Comment (zhzhuang-zju) [reply operator/pkg/util/util.go:245]: I'll give it a try

File: operator/pkg/util/util.go (hunk 3 above)
Comment (XiShanYongYe-Chang) [reply operator/pkg/util/util.go:244]: I think so.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks, other parts LGTM

File: operator/pkg/util/util.go (hunk 3 above)
Comment (zhzhuang-zju) [reply operator/pkg/util/util.go:244]: Get it~

Comment (zhzhuang-zju) [reply operator/pkg/util/util.go:233]: done~

**Review by RainbowMango — COMMENTED** [review]
/assign

**Comment by zhzhuang-zju** [comment]
As for why the conversion webhooks are called, I found an [issue](https://github.com/kubernetes/kubernetes/issues/129979) in the Kubernetes repository with a similar phenomenon, and the logs match the situation.
