### PR TITLE
fix bug: score plugin does not work

### LINKED ISSUE #571: scheduler: score plugin does not work
**What happened**:
Score plugin does not work, the plugin list is nil. Here is the bug code.
https://github.com/karmada-io/karmada/blob/3a8a0afa0de6fccf42aa7cd48c8048b587cb052d/pkg/scheduler/framework/runtime/framework.go#L42-L48

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #571

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/scheduler/framework/runtime/framework.go [hunk 1]
```diff
@@ -68,17 +63,26 @@ func (frw *frameworkImpl) RunFilterPlugins(ctx context.Context, placement *polic
...
 	result := make(framework.PluginToClusterScores, len(frw.filterPlugins))
 	for _, p := range frw.scorePlugins {
-		for i, cluster := range clusters {
+		var scoreList framework.ClusterScoreList
+		for _, cluster := range clusters {
 			score, res := p.Score(ctx, placement, cluster)
 			if !res.IsSuccess() {
 				return nil, fmt.Errorf("plugin %q failed with: %w", p.Name(), res.AsError())
 			}
-			result[p.Name()][i] = framework.ClusterScore{
```
Comment (RainbowMango) [inline pkg/scheduler/framework/runtime/framework.go:76]: Wow, just noticed that the `result[p.Name()]` is not initialized(nil slice), right?

Comment (Garrybest) [reply pkg/scheduler/framework/runtime/framework.go:76]: Right, this bug has not been triggered because the score plugin does not work😂.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Thanks.
