### PR TITLE
hack/local-up-karmada.sh supports WSL2

### LINKED ISSUE #6572: hack/local-up-karmada.sh does not work on WSL2
**What happened**:

Starting a karmada cluster with kind locally using the `hack/local-up-karmada.sh` does not work.

It hangs at the following step:

```
Waiting for the clusters to be ready...
Waiting for kubeconfig file /home/yifan/.kube/karmada.config and clusters karmada-host to be ready...
Context "kind-karmada-host" renamed to "karmada-host".
Cluster "kind-karmada-host" set.
Waiting for ok..
```

**What you expected to happen**: Karmada server and member clusters should be started successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Run `hack/local-up-karmada.sh` on a WSL 2 linux.

**Anything else we need to know?**:

This issue was already mentioned in https://github.com/karmada-io/karmada/issues/3140. As @RainbowMango pointed out, the root cause was the following code snippet (https://github.com/karmada-io/karmada/blob/3024d3321e9e5a934767314be7e60eb7ac49b74d/hack/util.sh#L550-L556).

A simple workaround is to change it to:

```sh
case $os_name in
    #linux) container_ip_port=$(util::get_docker_native_ipaddress "${context_name}-control-plane")":6443"
    #;;
    linux) container_ip_port=$(util::get_docker_host_ip_port "${context_name}-control-plane")
    ;;
    darwin) container_ip_port=$(util::get_docker_host_ip_port "${context_name}-control-plane")
    ;;
    *)
```

However this implies that everyone who tries to spin up karmada on WSL 2 would have to manually changing thee `hack/util.sh` file. I believe a better option is to further check the output of `uname -r` when `os_name` is `linux`. For example on my WSL environment the output is:

```sh
$ uname -r
6.6.87.2-microsoft-standard-WSL2
```

and use `util::get_docker_host_ip_port` but not `util::get_docker_native_ipaddress` when the output of `uname -r` contains a substring `WSL2`.

If you believe this change makes sense, I'm more than happy to contribute a PR. Thanks!

**Environment**: Ubuntu on WSL 2
- Karmada version: latest master branch
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): N/A
- Others:

### PR DESCRIPTION
**Pull request by zclyne**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Previously `hack/local-up-karmada.sh` does not work on WSL2 environment. This issue was already mentioned in https://github.com/karmada-io/karmada/issues/3140 and a solution was proposed there. This PR merged the solution into the shell script and therefore fixed the issue.

**Which issue(s) this PR fixes**:

Fixes #6572 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: 

```release-note
NONE
```

### CODE REVIEW

**Comment by zclyne** [comment]
Not sure why helm tests are failing as I haven't touched those files at all.. Will look into it

File: hack/util.sh [hunk 1]
```diff
@@ -683,6 +699,12 @@ function util::add_routes() {
   unset IFS
 }
 
+# util::get_wsl2_ipaddress will get ip address on wsl2, store to 'WSL2_HOST_IP_ADDRESS' if available
+WSL2_HOST_IP_ADDRESS=''
+function util::get_wsl2_ipaddress() {
```
Comment (zhzhuang-zju) [inline hack/util.sh:704]: @zclyne We can refer to `util::get_macos_ipaddress` to add some print output.

https://github.com/karmada-io/karmada/blob/46495a227ca872208f8b2d930748784df26f071a/hack/util.sh#L691-L693

https://github.com/karmada-io/karmada/blob/46495a227ca872208f8b2d930748784df26f071a/hack/util.sh#L707

Comment (zclyne) [reply hack/util.sh:704]: Added logs similar to the one in `util::get_macos_ipaddress`. Could you please have a look again when you get a chance? Thank you!

File: hack/util.sh [hunk 2]
```diff
@@ -683,6 +699,15 @@ function util::add_routes() {
...
+  echo "" 
+  echo " Detected that you are installing Karmada on WSL2 " 
+  echo "" 
+  WSL2_HOST_IP_ADDRESS=$(hostname -I | awk '{print $1}')
```
Comment (zhzhuang-zju) [inline hack/util.sh:708]:
```suggestion
  WSL2_HOST_IP_ADDRESS=$(hostname -I | awk '{print $1}')
  util::verify_ip_address "${WSL2_HOST_IP_ADDRESS}"
  echo "Using IP address: ${WSL2_HOST_IP_ADDRESS}"
```

**Comment by zhzhuang-zju** [comment]
@zclyne Thanks~ I have no further comment
cc @mohamedawnallah for another look

**Comment by moawnallah** [comment]
> @zclyne Thanks~ I have no further comment cc @mohamedawnallah for another look

Thanks guys, I will take another look EOD. I have an old windows server and I can test before/after this PR

EDIT:
Unfortunately I wasn't able to spin up that windows server because of hardware issues

File: hack/util.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (moawnallah) [reply hack/util.sh:708]: Seems gemini proposed the same one as this one https://github.com/karmada-io/karmada/pull/6581#discussion_r2253034894 👍

File: hack/util.sh [hunk 3]
```diff
@@ -533,6 +533,16 @@ function util::get_docker_host_ip_port(){
   docker inspect --format='{{range $key, $value := index .NetworkSettings.Ports "6443/tcp"}}{{if eq $key 0}}{{$value.HostIp}}:{{$value.HostPort}}{{end}}{{end}}' "${container_name}"
 }
 
+# util::is_wsl2 checks if the current environment is WSL2.
+# Returns:
+#   0 if running in WSL2, 1 otherwise.
+# Usage:
+#   util::is_wsl2 && echo "WSL2 detected" || echo "Not WSL2"
+function util::is_wsl2(){
```
Comment (moawnallah) [inline hack/util.sh:541]: 👍

File: hack/util.sh [hunk 4]
```diff
@@ -683,6 +699,15 @@ function util::add_routes() {
   unset IFS
 }
 
+# util::get_wsl2_ipaddress will get ip address on wsl2, store to 'WSL2_HOST_IP_ADDRESS' if available
+WSL2_HOST_IP_ADDRESS=''
+function util::get_wsl2_ipaddress() {
+  echo ""
```
Comment (moawnallah) [inline hack/util.sh]: nit: not sure but I find those emojis confusing. Using `` emoji signals that it is running on apple devices but it actually runs on WSL2 (Linux env in windows). I think we can remove them and just echo

Comment (zhzhuang-zju) [reply hack/util.sh]: @mohamedawnallah Why does the `` emoji signal that it is running on Apple devices?

Comment (moawnallah) [reply hack/util.sh]: > @mohamedawnallah Why does the `` emoji signal that it is running on Apple devices?

Apple chooses it on their websites and same logo on physical devices. I don't have strong feelings for changing it but just listed my observation. It feels like apple "owns" this emoji forever 😁
Screenshot 2025-08-06 at 8 49 33 AM

Comment (zhzhuang-zju) [reply hack/util.sh]: Hah, that's interesting. I want to know what this emoji displays as on your end? What I see is a square with a question mark inside. So I think it's device-independent.

Comment (moawnallah) [reply hack/util.sh]: >  I want to know what this emoji displays as on your end? 

On my apple device it is displayed this 
Screenshot 2025-08-06 at 9 23 27 AM

On my ubuntu device it is displayed this
Screenshot 2025-08-06 at 9 24 24 AM

> What I see is a square with a question mark inside. So I think it's device-independent.

When device can't recognize unicode character it uses this sort of square with question mark. but I think for devices that has this unicode character it will be an apple emoji.

Comment (zhzhuang-zju) [reply hack/util.sh]: Thank you for your detailed description. If that's the case, we indeed cannot directly copy this emoji for use in WSL2.

Comment (zclyne) [reply hack/util.sh]: Oh I didn't realize that this is a special character on mac. Would you recommend using a different character instead or simply remove it?

Comment (zhzhuang-zju) [reply hack/util.sh]: I saw your latest modification, it's fine~

**Comment by zhzhuang-zju** [comment]
@zclyne Great job! I have no further comments. Once we squash the commits, we can prepare for the merge.

**Comment by moawnallah** [comment]
Hey @zhzhuang-zju, It seems this PR is ready for merge?

**Comment by zhzhuang-zju** [comment]
> Hey @zhzhuang-zju, It seems this PR is ready for merge?

Sure, sorry for the delay
/lgtm
/approve
