### PR TITLE
fix: cannot access ResourceRegistry with its singularName

### LINKED ISSUE #4141: bug: cannot access ResourceRegistry  with its singularName
**What happened**:
when executing ```kubectl get ResourceRegistry``` will failed with ```doesn't have a resource type "ResourceRegistry"```, but executing ```kubectl get resourceregistries``` will success.
```bash
➜  /home export KUBECONFIG=~/.kube/karmada.config                                               
➜  /home ka get ResourceRegistry   
error: the server doesn't have a resource type "ResourceRegistry"
➜  /home ka get ResourceRegistries
NAME                CREATED AT
deployment-search   2023-09-28T03:07:10Z

```

**What you expected to happen**:
when executing ```kubectl get ResourceRegistry``` should also succeed.

**How to reproduce it (as minimally and precisely as possible)**:
For reproduce the problem, your can do as follows:
1.Launch Karmada with hack/local-up-karmada.sh
2.Create ResourceRegistry with command ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver create -f deployment-search.yaml```
```
### deployment-search.yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: deployment-search
spec:
  targetCluster:
    clusterNames:
      - member1
      - member2
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
```
3.Execute ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get ResourceRegistry```

**Anything else we need to know?**:
none
**Environment**: Ubuntu 22.04
- Karmada version: master branch latest code
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): none
- Others: none

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**

**What this PR does / why we need it**:
Referring to #4141
we cannot access resource ```ResourceRegistry``` with its ```singularName```.

**Which issue(s) this PR fixes**:
Fixes #4141

**Special notes for your reviewer**:
none

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-search`:  fix cannot access ResourceRegistry with its singularName.
```

### CODE REVIEW

File: pkg/registry/search/storage/resourceregistry.go [hunk 1]
```diff
@@ -28,8 +28,8 @@ func NewResourceRegistryStorage(scheme *runtime.Scheme, optsGetter generic.RESTO
 		NewFunc:                   func() runtime.Object { return &searchapis.ResourceRegistry{} },
 		NewListFunc:               func() runtime.Object { return &searchapis.ResourceRegistryList{} },
 		PredicateFunc:             searchregistry.MatchResourceRegistry,
-		DefaultQualifiedResource:  searchapis.Resource("resourceRegistries"),
-		SingularQualifiedResource: searchapis.Resource("resourceRegistry"),
+		DefaultQualifiedResource:  searchapis.Resource("resourceregistries"),
+		SingularQualifiedResource: searchapis.Resource("resourceregistry"),
```
Comment (XiShanYongYe-Chang) [inline pkg/registry/search/storage/resourceregistry.go:32]: How about adding some comments to explain it?

Comment (zhzhuang-zju) [reply pkg/registry/search/storage/resourceregistry.go:32]: Nice suggestion!

**Comment by XiShanYongYe-Chang** [comment]
Can you help post your test report?

**Comment by zhzhuang-zju** [comment]
> Can you help post your test report?

Certainly!
```bash
➜  karmada git:(master) ✗ ka get resourceRegistry                      
NAME                CREATED AT
deployment-search   2023-10-17T11:40:36Z
➜  karmada git:(master) ✗ ka get resourceRegistries
NAME                CREATED AT
deployment-search   2023-10-17T11:40:36Z
```
Executing ```kubectl get resourceregisty``` runs as well as executing `kubectl get resourceregistries`.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot~
/lgtm
/approve

**Comment by XiShanYongYe-Chang** [comment]
We need to cherry-pick this patch to the previous branch, I will create an issue to track this.

**Comment by RainbowMango** [comment]
@zhzhuang-zju Have you ever thought about if this patch would block the upgrade?
For example, there is a ResourceRegistry resource that was created in the previous version, like v1.7.0, I'm not sure if there is a problem when upgrading the `karmada-aggregated-apiserver`.

Can you help to confirm that?

**Comment by zhzhuang-zju** [comment]
Nice finding! It is necessary to verify the upgrade scenario, and I‘d like to confirm it.

**Comment by zhzhuang-zju** [comment]
I did some experiments and found that there is indeed a problem in the upgrade scenario. 
Specific steps are as follows，
1. use version release-1.7.0 to build the karmada environment
2. Create ResourceRegistry with command ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver create -f deployment-search.yaml```
```
### deployment-search.yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: deployment-search
spec:
  targetCluster:
    clusterNames:
      - member1
      - member2
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
```
3.Execute ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get ResourceRegistry```
```bash
➜  templates kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get ResourceRegistry
error: the server doesn't have a resource type "ResourceRegistry"
```
4.Upgrade the component ```karmada-search``` with the latest image.
5.Execute ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get ResourceRegistry```
```bash
➜  karmada git:(master) ✗ kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get ResourceRegistry
No resources found
```
It seems that it can't find the resource with ```kind: ResourceRegistry```  that was released before the upgrade.
In addition, I found that when the code in line  ```31``` of file ```pkg/registry/search/storage/resourceregistry.go``` is changed to ```DefaultQualifiedResource:  searchapis.Resource("resourceRegistries"),```, the upgrade problem seems to be solved.
```bash
➜  karmada git:(master) ✗ kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get ResourceRegistry  
NAME                CREATED AT
deployment-search   2023-10-21T11:20:04Z
➜  karmada git:(master) ✗ kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get resourceregistries
NAME                CREATED AT
deployment-search   2023-10-21T11:20:04Z
```
