### PR TITLE
`karmada-controller-manager`: Fixed the panic when cluster ImpersonatorSecretRef is nil.

### LINKED ISSUE #2674: controller manager crashes when cluster ImpersonatorSecretRef is nil
**What happened**:

When cluster ImpersonatorSecretRef is nil, controller manager crashes. 

**What you expected to happen**:

Controller manager should not crash at any time.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster object with ImpersonatorSecretRef is nil
2. Controller manager crashes

**Anything else we need to know?**:

**Environment**:
- Karmada version:
1.3.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
karmadactl version: version.Info{GitVersion:"v0.0.0-master", GitCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
- Others:

### PR DESCRIPTION
**Pull request by stingshen**
**What type of PR is this?**

**What this PR does / why we need it**:

Do nil check before using cluster ImpersonatorSecretRef

**Which issue(s) this PR fixes**:
Fixes #2674

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

```release-note
- `karmada-controller-manager`: Fixed the panic when cluster ImpersonatorSecretRef is nil.
```

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
I can reproduce it.

image


Thank you for your contribution.

**Comment by chaunceyjiang** [comment]
we need to pick this patch for release-1.1

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks, @stingshen, we need to cherry-pick this bug fix to release-1.1, release-1.2, and release-1.3.

Just a question: Are you manually creating the cluster object with nil ImpersonatorSecretRef?

**Comment by stingshen** [comment]
> Thanks, @stingshen, we need to cherry-pick this bug fix to release-1.1, release-1.2, and release-1.3.
> 
> Just a question: Are you manually creating the cluster object with nil ImpersonatorSecretRef?

Yes. The use case is described [here](https://github.com/karmada-io/karmada/issues/1621#issuecomment-1101943380)

**Comment by XiShanYongYe-Chang** [comment]
> Yes. The use case is described [here](https://github.com/karmada-io/karmada/issues/1621#issuecomment-1101943380)

Ok, thanks~

/lgtm
/kind bug

**Comment by XiShanYongYe-Chang** [comment]
Hi @stingshen, can you help fill the release note?

**Comment by stingshen** [comment]
> Hi @stingshen, can you help fill the release note?

done

File: pkg/controllers/unifiedauth/unified_auth_controller.go [hunk 1]
```diff
@@ -149,6 +150,9 @@ func (c *Controller) buildImpersonationClusterRole(cluster *clusterv1alpha1.Clus
 }
 
 func (c *Controller) buildImpersonationClusterRoleBinding(cluster *clusterv1alpha1.Cluster) error {
+	if cluster.Spec.ImpersonatorSecretRef == nil {
+		return fmt.Errorf("cluster %s does not have an impersonator secret", cluster.Name)
```
Comment (RainbowMango) [inline pkg/controllers/unifiedauth/unified_auth_controller.go:154]: If we return an error here, that will lead to an endless retry loop. Is it what we expected?

Comment (RainbowMango) [reply pkg/controllers/unifiedauth/unified_auth_controller.go:154]: Given the `cluster.Spec.ImpersonatorSecretRef` is an optional field, so it makes sense to unset this field if users don't need this feature, the controller should be able to ignore syncing the RBAC in this situation.

Comment (XiShanYongYe-Chang) [reply pkg/controllers/unifiedauth/unified_auth_controller.go:154]: This error may directly indicate that the current feature is unavailable. If users don't need this feature, they maybe need to disable the current controller.

Comment (RainbowMango) [reply pkg/controllers/unifiedauth/unified_auth_controller.go:154]: Is there a possibility that the users only allow some of the clusters can be accessed by aggregated API, and the others can't?

Comment (XiShanYongYe-Chang) [reply pkg/controllers/unifiedauth/unified_auth_controller.go:154]: It seems reasonable.
Do we need to send a warning here?

**Comment by XiShanYongYe-Chang** [comment]
Hi @stingshen, maybe we can directly skip reconciling like this:

```diff
--- a/pkg/controllers/unifiedauth/unified_auth_controller.go
+++ b/pkg/controllers/unifiedauth/unified_auth_controller.go
@@ -63,6 +63,11 @@ func (c *Controller) Reconcile(ctx context.Context, req controllerruntime.Reques
                return controllerruntime.Result{}, nil
        }

+       if cluster.Spec.ImpersonatorSecretRef == nil {
+               klog.Infof("cluster %s does not have an impersonator secret", cluster.Name)
+               return controllerruntime.Result{}, nil
+       }
+
        err := c.syncImpersonationConfig(cluster)
        if err != nil {
                klog.Errorf("Failed to sync impersonation config for cluster %s. Error: %v.", cluster.Name, err)
``` 
This avoids other unnecessary operations in the reconcile, and we log info to remind the user.

**Comment by stingshen** [comment]
> Hi @stingshen, maybe we can directly skip reconciling like this:
> 
> ```diff
> --- a/pkg/controllers/unifiedauth/unified_auth_controller.go
> +++ b/pkg/controllers/unifiedauth/unified_auth_controller.go
> @@ -63,6 +63,11 @@ func (c *Controller) Reconcile(ctx context.Context, req controllerruntime.Reques
>                 return controllerruntime.Result{}, nil
>         }
> 
> +       if cluster.Spec.ImpersonatorSecretRef == nil {
> +               klog.Infof("cluster %s does not have an impersonator secret", cluster.Name)
> +               return controllerruntime.Result{}, nil
> +       }
> +
>         err := c.syncImpersonationConfig(cluster)
>         if err != nil {
>                 klog.Errorf("Failed to sync impersonation config for cluster %s. Error: %v.", cluster.Name, err)
> ```
> 
> This avoids other unnecessary operations in the reconcile, and we log info to remind the user.

done

**Comment by XiShanYongYe-Chang** [comment]
Thanks for your quick response~
cc @RainbowMango

File: pkg/controllers/unifiedauth/unified_auth_controller.go [hunk 2]
```diff
@@ -63,6 +63,11 @@ func (c *Controller) Reconcile(ctx context.Context, req controllerruntime.Reques
 		return controllerruntime.Result{}, nil
 	}
 
+	if cluster.Spec.ImpersonatorSecretRef == nil {
+		klog.Infof("cluster %s does not have an impersonator secret", cluster.Name)
```
Comment (RainbowMango) [inline pkg/controllers/unifiedauth/unified_auth_controller.go:67]: Much better now.
```suggestion
		klog.Infof("Aggregated API feature is disabled on cluster %s as it does not have an impersonator secret", cluster.Name)
```
We should give a more detail description of the effect.

Comment (stingshen) [reply pkg/controllers/unifiedauth/unified_auth_controller.go]: done

File: pkg/controllers/unifiedauth/unified_auth_controller.go [hunk 3]
```diff
@@ -256,8 +261,9 @@ func (c *Controller) newClusterRoleBindingMapFunc() handler.MapFunc {
 }
 
 // found out which clusters need to sync impersonation config from rules like:
-//   resources: ["cluster/proxy"]
-//   resourceNames: ["cluster1", "cluster2"]
+//
```
Comment (RainbowMango) [inline pkg/controllers/unifiedauth/unified_auth_controller.go:264]: Why add the blank line here?
Since we are going to cherry-pick this to release branches, we should keep this patch minimal to avoid conflict.

**Comment by RainbowMango** [comment]
/retitle `karmada-controller-manager`: Fixed the panic when cluster ImpersonatorSecretRef is nil.

File: pkg/controllers/unifiedauth/unified_auth_controller.go [hunk 4]
```diff
@@ -256,8 +261,9 @@ func (c *Controller) newClusterRoleBindingMapFunc() handler.MapFunc {
...
+//	resources: ["cluster/proxy"]
+//	resourceNames: ["cluster1", "cluster2"]
```
Comment (XiShanYongYe-Chang) [inline pkg/controllers/unifiedauth/unified_auth_controller.go:266]: This updation seems unnecessary.

File: pkg/controllers/unifiedauth/unified_auth_controller.go (hunk 3 above)
Comment (stingshen) [reply pkg/controllers/unifiedauth/unified_auth_controller.go]: Sorry, vscode auto formatted the file. I reverted the change.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
Now, we can start to [cherry-pick](https://karmada.io/docs/contributor/cherry-picks) this patch to release branches?
- release-1.1
- release-1.2
- release-1.3

**Comment by XiShanYongYe-Chang** [comment]
Hi @stingshen, would mind helping cherry-pick this patch, If you have time, you can cherry-pick refer to https://karmada.io/docs/contributor/cherry-picks.

**Comment by stingshen** [comment]
> Hi @stingshen, would mind helping cherry-pick this patch, If you have time, you can cherry-pick refer to https://karmada.io/docs/contributor/cherry-picks.

sure
