### PR TITLE
propagate `Secret` of type `kubernetes.io/service-account-token`

### LINKED ISSUE #4752: Propagate Service Account Token Secret
**What happened**:
I made a PropagationPolicy for a secret with type `kubernetes.io/service-account-token` and it's ServiceAccount.
It appears [PR 1525](https://github.com/karmada-io/karmada/pull/1525) was made to ignore the secret. However, since 1.24 these secrets aren't automatically created anymore. 

**What you expected to happen**:
I'd expect for karmada to copy my secret and use my ResourceInterpreterCustomization to not copy the secret data.
Additionally i'd like karmada to handle this case and and always remove the cluster specific secret data.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl create ns test
kubectl apply -n test -f - <<EOF
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: secret-propagation
  namespace: test
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      namespace: test
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
EOF 
kubectl create sa -n test sa-test
kubectl get secrets -n test  # NOTE no secrets different functionality from the pr linked above due to 1.24
kubectl apply -n test -f - <<EOF
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: sa-test-token
  annotations:
    kubernetes.io/service-account.name: sa-test
EOF
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.9.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by a7i**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
Prior to kubernetes 1.24, Kubernetes controller-manager automatically created a Secret (with a long-lived token). Starting with 1.24, in order to create a Secret with long-lived token, you have to manually create a Secret and link it to the Service Account. Karmada currently doesn't support propagating this Secret as it is explicitly disabled.

**Which issue(s) this PR fixes**:
Fixes #4752

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

Yes
```release-note
karmada-controller-manager: propagate `Secret` of type `kubernetes.io/service-account-token`
```

### CODE REVIEW

**Review by chaunceyjiang — COMMENTED** [review]
Great work, you provided a new perspective. 

However, this comment https://github.com/karmada-io/karmada/issues/4752#issuecomment-2024468420 also reminded me that is your change backward compatible with k8s versions below v1.24?

**Review by chaunceyjiang — COMMENTED** [review]
Looks good to me.

**Comment by XiShanYongYe-Chang** [comment]
You can add the component name `karmada-controller-manager` to the release-note.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
The retain logic is modified in the current PR. However, retain is used when resources in member clusters are updated. If resources are created, will the UID and token information in the secret on the control plane be carried to the member cluster?

**Comment by a7i** [comment]
@XiShanYongYe-Chang Yes it will but we observed in our case that the member cluster kube-controller-manager will fix up the values and get ignored by karmada on update.

Is there a "global" level ignore for CREATE as well?

**Comment by XiShanYongYe-Chang** [comment]
Maybe we can do it in the `karmada-webhook`:

https://github.com/karmada-io/karmada/blob/eadf919b6f25dc77873178e88a55983d05b03867/pkg/webhook/work/mutating.go#L61

**Comment by a7i** [comment]
@XiShanYongYe-Chang done, I kept as two separate commits for easier review. Happy to rebase and squash if needed.

**Comment by XiShanYongYe-Chang** [comment]
It occurs a lint error:
```
pkg/resourceinterpreter/default/native/prune/prune.go:33:1: cyclomatic complexity 18 of func `RemoveIrrelevantField` is high (> 15) (gocyclo)
```

**Comment by a7i** [comment]
@XiShanYongYe-Chang let me take a stab at refactoring this function in a separate PR and I'll come back to this after that's reviewed/merged

**Comment by XiShanYongYe-Chang** [comment]
Hi @a7i, CI errors may prevent PRs from being merged.

**Comment by a7i** [comment]
> Hi @a7i, CI errors may prevent PRs from being merged.

I understand, hence why I'm suggesting to put a hold on this PR, until we refactor this function first (in a separate PR).

**Comment by XiShanYongYe-Chang** [comment]
> I understand, hence why I'm suggesting to put a hold on this PR, until we refactor this function first (in a separate PR).

Thanks @a7i, I got it :)

**Comment by XiShanYongYe-Chang** [comment]
Hi @a7i , now we can go on this PR.

**Review by chaunceyjiang — COMMENTED** [review]
Nice~

/lgtm

File: pkg/resourceinterpreter/default/native/retain_test.go [hunk 1]
```diff
@@ -101,10 +102,77 @@ func Test_retainK8sWorkloadReplicas(t *testing.T) {
 		t.Run(tt.name, func(t *testing.T) {
 			got, err := retainWorkloadReplicas(tt.args.desired, tt.args.observed)
 			if (err != nil) != tt.wantErr {
-				t.Errorf("reflectPodDisruptionBudgetStatus() error = %v, wantErr %v", err, tt.wantErr)
+				t.Errorf("retainWorkloadReplicas() error = %v, wantErr %v", err, tt.wantErr)
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/default/native/retain_test.go:105]: nice catch. thanks.

File: pkg/resourceinterpreter/default/native/retain.go [hunk 2]
```diff
@@ -160,3 +162,28 @@ func retainWorkloadReplicas(desired, observed *unstructured.Unstructured) (*unst
...
 	return desired, nil
 }
+
+func retainSecretServiceAccountToken(desired *unstructured.Unstructured, observed *unstructured.Unstructured) (retained *unstructured.Unstructured, err error) {
+	if secretType, exists, _ := unstructured.NestedString(desired.Object, "type"); exists && secretType == string(corev1.SecretTypeServiceAccountToken) {
+		// retain service-account.uid which is a unique per cluster
+		serviceAccountUIDPath := []string{"metadata", "annotations", corev1.ServiceAccountUIDKey}
+		uid, _, err := unstructured.NestedString(observed.Object, serviceAccountUIDPath...)
+		if err != nil {
+			return nil, fmt.Errorf("failed to get %s from desired.Object: %+v", corev1.ServiceAccountUIDKey, err)
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/default/native/retain.go:172]: Given this error, it could lead to sync failure.
Can we assume the `.metadata.annotations.kubernetes.io/service-account.uid` must exist?

I guess the logic should be:
- raise the error in case there is a concrete exception, like trying to find the value with a wrong path
- skip the retention if the uuid not found(not populate yet).

File: pkg/resourceinterpreter/default/native/retain.go [hunk 3]
```diff
@@ -160,3 +162,28 @@ func retainWorkloadReplicas(desired, observed *unstructured.Unstructured) (*unst
...
+		}
+		if err := unstructured.SetNestedField(desired.Object, uid, serviceAccountUIDPath...); err != nil {
+			return nil, fmt.Errorf("failed to set %s for %s %s/%s", strings.Join(serviceAccountUIDPath, "."), desired.GetKind(), desired.GetNamespace(), desired.GetName())
+		}
+
+		// retain token generated by cluster kube-controller-manager
+		data, _, err := unstructured.NestedStringMap(observed.Object, "data")
+		if err != nil {
+			return nil, fmt.Errorf("failed to get .data from desired.Object: %+v", err)
+		}
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/default/native/retain.go:182]: ditto.

File: pkg/resourceinterpreter/default/native/retain.go (hunk 2 above)
Comment (XiShanYongYe-Chang) [reply pkg/resourceinterpreter/default/native/retain.go:172]: I make a test. If the annotation `kubernetes.io/service-account.uid` of the secret in the member cluster is deleted, an empty annotation `kubernetes.io/service-account.uid` is added during retain. Like this:

image

No error will occur. I still recommend to process the returned bool value. If the bool refers to false, there is no need to SetNestedField.

**Comment by RainbowMango** [comment]
LGTM 
Thanks for your quick response! 

But would you mind [squash commits](https://karmada.io/docs/contributor/github-workflow#squash-commits)?

**Comment by a7i** [comment]
> LGTM Thanks for your quick response!
> 
> But would you mind [squash commits](https://karmada.io/docs/contributor/github-workflow#squash-commits)?

I do not mind at all! Was keeping them separate for easier review

**Comment by RainbowMango** [comment]
haha, your code is so clear that I don't have to review it by commits~

/lgtm
/approve

**Comment by RainbowMango** [comment]
gonna heading home now, good morning to you

**Comment by a7i** [comment]
> gonna heading home now, good morning to you

long day! I appreciate the thorough review and all the great feedback 🎉

**Comment by RainbowMango** [comment]
I really really hope people like you join us in maintaining this project, can we get started from [the org membership](https://github.com/karmada-io/community/blob/main/community-membership.md#requirements)?

**Comment by a7i** [comment]
Hi @RainbowMango and @XiShanYongYe-Chang I hope you would consider sponsoring me ❤️ 

https://github.com/karmada-io/community/issues/68

**Comment by a7i** [comment]
>I have verified that my sponsors are from different member companies

perhaps @chaunceyjiang would consider 🙇🏼

**Comment by RainbowMango** [comment]
> Hi @RainbowMango and @XiShanYongYe-Chang I hope you would consider sponsoring me ❤️

definitly!
