### PR TITLE
skip cleanup when the poliy claim metadata changed

### LINKED ISSUE #5307: PolicyMarkedLabels and policyMarkedAnnotations of rb/crb may be lost when deleting the old pp/cpp and binding a new one
**What happened**:
Through investigating failed [e2e test: delete the old ClusterPropagationPolicy to unbind and create a new one](https://github.com/karmada-io/karmada/actions/runs/10242265387/job/28331814043) , I found that the rb's annotation `clusterpropagationpolicy.karmada.io/name` was lost during the process of unbinding the old cpp and binding a new one.
The overall process can be roughly divided into the following steps:

① delete the old cpp and create a new one
② `detector` delete the labels and annotations associated with cpp in resource template 
③ `detector` delete the labels and annotations associated with cpp in rb
④ `resource template` bind to the new cpp
⑤ update the labels and annotations associated with cpp in rb

In practice, steps 3 and 5 occur synchronously, so it's possible that what step 3 deletes are the labels and annotations updated by step 5, ultimately leading to the loss of rb/crb's `policyMarkedLabels` and `policyMarkedAnnotations`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Since step 3 often completes before steps 4 and 5, the occurrence of this issue is relatively rare. To increase the likelihood of it happening, a delay can be added in step 3.
https://github.com/karmada-io/karmada/blob/b4b6d692ca963c3d53de4a61077f4380613be0a5/pkg/detector/detector.go#L1186-L1199
and then, running command `ginkgo -v --race --trace -p  --focus="delete the old ClusterPropagationPolicy to unbind and create a new one" ./test/e2e/` will reproduce the issue.

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Refer to #5307, there is a chance that poliy marks be lost when deleting the old pp/cpp and binding a new one. When performing a clean up of marks on rb/crb, we can compare the value of the label `policyv1alpha1.ClusterPropagationPolicyPermanentIDLabel/policyv1alpha1.PolicyPermanentIDLabel` on the cb/crb with the policyId value of the deleted CPP/PP. If they are not the same, it indicates that the rb/crb has already claimed to a new CPP/PP, and there is no need to clean up the label/annotation.

**Which issue(s) this PR fixes**:
Fixes #5307

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed an issue that policy claim metadata might be lost during the rapid deletion and creation of PropagationPolicy(s)/ClusterPropagationPolicy(s)
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
cc @whitewindmills @XiShanYongYe-Chang

File: pkg/detector/detector.go [hunk 1]
```diff
@@ -1103,9 +1103,14 @@ func (d *ResourceDetector) HandlePropagationPolicyDeletion(policyID string) erro
 		return err
 	}
 
-	cleanupMarksFunc := func(obj metav1.Object) {
+	cleanupMarksFunc := func(obj metav1.Object) bool {
+		if obj.GetLabels()[policyv1alpha1.PropagationPolicyPermanentIDLabel] != policyID {
+			klog.Infof("Expected value of label 'propagationpolicy.karmada.io/permanent-id' is: %s, but got %s", policyID, obj.GetLabels()[policyv1alpha1.PropagationPolicyPermanentIDLabel])
```
Comment (whitewindmills) [inline pkg/detector/detector.go:1108]: you'd better explain why the unexpected label value ​​might ocur.

File: pkg/detector/detector.go [hunk 2]
```diff
@@ -1365,9 +1378,12 @@ func (d *ResourceDetector) CleanupResourceTemplateMarks(objRef workv1alpha2.Obje
 }
 
 // CleanupResourceBindingMarks removes marks, such as labels and annotations, from resource binding.
-func (d *ResourceDetector) CleanupResourceBindingMarks(rb *workv1alpha2.ResourceBinding, cleanupFunc func(obj metav1.Object)) error {
+func (d *ResourceDetector) CleanupResourceBindingMarks(rb *workv1alpha2.ResourceBinding, cleanupFunc func(obj metav1.Object) bool) error {
 	return retry.RetryOnConflict(retry.DefaultRetry, func() (err error) {
-		cleanupFunc(rb)
+		if !cleanupFunc(rb) {
+			klog.Infof("The marks on resource binding %s/%s have changed, and no need to be cleaned up", rb.GetNamespace(), rb.GetName())
```
Comment (whitewindmills) [inline pkg/detector/detector.go:1384]: `resource binding` => `ResourceBinding`

File: pkg/detector/detector.go [hunk 3]
```diff
@@ -1384,9 +1400,12 @@ func (d *ResourceDetector) CleanupResourceBindingMarks(rb *workv1alpha2.Resource
 }
 
 // CleanupClusterResourceBindingMarks removes marks, such as labels and annotations, from cluster resource binding.
-func (d *ResourceDetector) CleanupClusterResourceBindingMarks(crb *workv1alpha2.ClusterResourceBinding, cleanupFunc func(obj metav1.Object)) error {
+func (d *ResourceDetector) CleanupClusterResourceBindingMarks(crb *workv1alpha2.ClusterResourceBinding, cleanupFunc func(obj metav1.Object) bool) error {
 	return retry.RetryOnConflict(retry.DefaultRetry, func() (err error) {
-		cleanupFunc(crb)
+		if !cleanupFunc(crb) {
+			klog.Infof("The marks on cluster resource binding %s have changed, and no need to be cleaned up", crb.GetName())
```
Comment (whitewindmills) [inline pkg/detector/detector.go:1406]: `cluster resource binding` => `ClusterResourceBinding`

**Review by whitewindmills — COMMENTED** [review]
some nits, LGTM otherwise.

File: pkg/detector/detector.go (hunk 2 above)
Comment (zhzhuang-zju) [reply pkg/detector/detector.go:1384]: I also think this might be better, but choosing to write it this way is to maintain consistency with
https://github.com/karmada-io/karmada/blob/b4b6d692ca963c3d53de4a61077f4380613be0a5/pkg/detector/detector.go#L1380

Comment (whitewindmills) [reply pkg/detector/detector.go:1388]: don't mind it, of course, you can also change the others if it is convenient for you. :hugs:

**Comment by whitewindmills** [comment]
let @XiShanYongYe-Chang make the final decision.
/assign @XiShanYongYe-Chang

File: pkg/detector/detector.go [hunk 4]
```diff
@@ -1103,9 +1103,16 @@ func (d *ResourceDetector) HandlePropagationPolicyDeletion(policyID string) erro
 		return err
 	}
 
-	cleanupMarksFunc := func(obj metav1.Object) {
+	cleanupMarksFunc := func(obj metav1.Object) bool {
+		// When cleaning up the marks, the resource template may have already been bound to a new propagationPolicy, causing the marks' values to change.
```
Comment (zhzhuang-zju) [inline pkg/detector/detector.go:1107]: @whitewindmills Here is the comment I added to explain why unexpected label values might occur. Do you think it's clear enough?

File: pkg/detector/detector.go (hunk 2 above)
Comment (XiShanYongYe-Chang) [reply pkg/detector/detector.go:1388]: I expected to write like this: `resourceBinding(%s/%s)` ^-^
A matter of style, a thousand faces.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Some discussion of the log. :)

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/lgtm

**Comment by zhzhuang-zju** [comment]
cc @RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
Hi @whitewindmills can we merge this pr?

**Comment by whitewindmills** [comment]
yes

**Comment by XiShanYongYe-Chang** [comment]
It's ready to merge. Ask @RainbowMango to help make a check again.
/assign @RainbowMango

**Comment by RainbowMango** [comment]
Does this need to be included in the coming patch release?  #5373

**Comment by zhzhuang-zju** [comment]
> Does this need to be included in the coming patch release? #5373

In terms of the frequency and severity of the issue, it's not very urgent. However, if needed, I can cherry-pick it to the corresponding release branch as soon as possible.

**Comment by zhzhuang-zju** [comment]
kindly ping @RainbowMango

**Comment by zhzhuang-zju** [comment]
kindly ping @RainbowMango

File: pkg/detector/detector.go [hunk 5]
```diff
@@ -1103,9 +1103,15 @@ func (d *ResourceDetector) HandlePropagationPolicyDeletion(policyID string) erro
 		return err
 	}
 
-	cleanupMarksFunc := func(obj metav1.Object) {
+	cleanupMarksFunc := func(obj metav1.Object) bool {
```
Comment (RainbowMango) [inline pkg/detector/detector.go:1106]: The root cause of this issue is that `cleanupMarksFuncs` mistakenly removed the labels it was not supposed to.
The reason is that `cleanupMarksFuncs` just have the label keys, but can't verify the values.

This patch forces the `cleanupMarksFuncs` to couple with business logic, in another world, it makes it harder to test it with a unit test.

Another approach is to feed enough info(label key and value) to the `cleanupMarksFuncs`, and let it focus on removing certain things.

File: pkg/detector/detector.go [hunk 6]
```diff
@@ -1157,15 +1170,15 @@ func (d *ResourceDetector) HandleClusterPropagationPolicyDeletion(policyID strin
 			// ClusterResourceBinding, otherwise might lose the chance to do that in a retry loop (in particular, the
 			// marks was successfully removed from ClusterResourceBinding, but resource template not), since the
 			// ClusterResourceBinding will not be listed again.
-			if err := d.CleanupResourceTemplateMarks(binding.Spec.Resource, cleanupMarksFun); err != nil {
+			if err := d.CleanupResourceTemplateMarks(binding.Spec.Resource, policyv1alpha1.ClusterPropagationPolicyPermanentIDLabel, policyID, cleanupMarksFun); err != nil {
```
Comment (RainbowMango) [inline pkg/detector/detector.go:1173]: Can we generate the list of labels/annotations that need to be removed? The list can be generated inside of the `CleanupResourceTemplateMarks` or passed into it.

Comment (zhzhuang-zju) [reply pkg/detector/detector.go:1173]: Do you mean
https://github.com/karmada-io/karmada/blob/920ac8931e7aeccae87b7bc123c2b001060dcda0/pkg/detector/detector.go#L66-L78

Comment (zhzhuang-zju) [reply pkg/detector/detector.go:1172]: @RainbowMango How about now?

Comment (zhzhuang-zju) [reply pkg/detector/detector.go:1172]: You can review the code first, and I'll verify the functionality locally tomorrow

File: pkg/detector/detector.go [hunk 7]
```diff
@@ -1103,7 +1104,13 @@ func (d *ResourceDetector) HandlePropagationPolicyDeletion(policyID string) erro
 		return err
 	}
 
-	cleanupMarksFunc := func(obj metav1.Object) {
+	cleanupMarksFunc := func(obj metav1.Object, targetPolicyLabel string, targetPolicyID string) {
+		// When cleaning up the marks, the resource template may have already been bound to a new clusterPropagationPolicy, causing the marks' values to change.
+		// More info can refer to https://github.com/karmada-io/karmada/issues/5307.
```
Comment (RainbowMango) [inline pkg/detector/detector.go:1109]:
```suggestion
		// We need to ensure that the labels/annotations being deleted belong to the current PropagationPolicy,
		// otherwise, there is a risk of mistakenly deleting the ones belonging to another PropagationPolicy.
		// This situation could occur during the rapid deletion and creation of PropagationPolicy(s).
		// More info can refer to https://github.com/karmada-io/karmada/issues/5307.
```

File: pkg/detector/detector.go [hunk 8]
```diff
@@ -1141,7 +1150,14 @@ func (d *ResourceDetector) HandleClusterPropagationPolicyDeletion(policyID strin
 		policyv1alpha1.ClusterPropagationPolicyPermanentIDLabel: policyID,
 	}
 
-	cleanupMarksFun := func(obj metav1.Object) {
+	cleanupMarksFun := func(obj metav1.Object, targetPolicyLabel string, targetPolicyID string) {
+		// We need to ensure that the labels/annotations being deleted belong to the current ClusterPropagationPolicyDeletion,
```
Comment (RainbowMango) [inline pkg/detector/detector.go:1154]:
```suggestion
		// We need to ensure that the labels/annotations being deleted belong to the current ClusterPropagationPolicy,
```

**Comment by zhzhuang-zju** [comment]
/hold 
util #5563 merged

**Comment by RainbowMango** [comment]
> /hold util #5563 merged

Whis this PR should wait for #5563?

**Comment by zhzhuang-zju** [comment]
in #5563, I have extracted some common methods, which will affect this PR.

**Comment by zhzhuang-zju** [comment]
#5563 has been merged, so this PR can now proceed

cc @whitewindmills @RainbowMango @XiShanYongYe-Chang

File: pkg/detector/detector.go [hunk 9]
```diff
@@ -1310,8 +1316,12 @@ func (d *ResourceDetector) CleanupResourceTemplateClaimMetadata(objRef workv1alp
 }
 
 // CleanupResourceBindingClaimMetadata removes claim metadata, such as labels and annotations, from resource binding.
-func (d *ResourceDetector) CleanupResourceBindingClaimMetadata(rb *workv1alpha2.ResourceBinding, cleanupFunc func(obj metav1.Object)) error {
+func (d *ResourceDetector) CleanupResourceBindingClaimMetadata(rb *workv1alpha2.ResourceBinding, targetClaimMetadata map[string]string, cleanupFunc func(obj metav1.Object)) error {
 	return retry.RetryOnConflict(retry.DefaultRetry, func() (err error) {
+		if !NeedCleanupClaimMetadata(rb, targetClaimMetadata) {
+			klog.Infof("No need to clean up the claim metadata on resourceBinding(%s/%s) since they have changed", rb.GetNamespace(), rb.GetName())
```
Comment (RainbowMango) [inline pkg/detector/detector.go:1322]:
```suggestion
			klog.Infof("No need to clean up the claim metadata on ResourceBinding(%s/%s) since they have changed", rb.GetNamespace(), rb.GetName())
```

File: pkg/detector/detector.go [hunk 10]
```diff
@@ -1322,15 +1332,19 @@ func (d *ResourceDetector) CleanupResourceBindingClaimMetadata(rb *workv1alpha2.
 		if err = d.Client.Get(context.TODO(), client.ObjectKey{Namespace: rb.GetNamespace(), Name: rb.GetName()}, updated); err == nil {
 			rb = updated.DeepCopy()
 		} else {
-			klog.Errorf("Failed to get updated resource binding %s/%s: %v", rb.GetNamespace(), rb.GetName(), err)
+			klog.Errorf("Failed to get updated resourceBinding(%s/%s): %v", rb.GetNamespace(), rb.GetName(), err)
```
Comment (RainbowMango) [inline pkg/detector/detector.go:1335]:
```suggestion
			klog.Errorf("Failed to get updated ResourceBinding(%s/%s): %v", rb.GetNamespace(), rb.GetName(), err)
```

File: pkg/detector/detector.go [hunk 11]
```diff
@@ -1322,15 +1332,19 @@ func (d *ResourceDetector) CleanupResourceBindingClaimMetadata(rb *workv1alpha2.
...
 		}
 		return updateErr
 	})
 }
 
 // CleanupClusterResourceBindingClaimMetadata removes claim metadata, such as labels and annotations, from cluster resource binding.
-func (d *ResourceDetector) CleanupClusterResourceBindingClaimMetadata(crb *workv1alpha2.ClusterResourceBinding, cleanupFunc func(obj metav1.Object)) error {
+func (d *ResourceDetector) CleanupClusterResourceBindingClaimMetadata(crb *workv1alpha2.ClusterResourceBinding, targetClaimMetadata map[string]string, cleanupFunc func(obj metav1.Object)) error {
```
Comment (RainbowMango) [inline pkg/detector/detector.go:1342]:
```suggestion
func (d *ResourceDetector) CleanupClusterResourceBindingClaimMetadata(crb *workv1alpha2.ClusterResourceBinding, targetClaimMetadata map[string]string)) error {
```
Please inline the cleanupFunc as there is only one cleanupFunc will be passed in.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
