### PR TITLE
Fix `karmadactl init` can not read KUBECONFIG environment variable issue

### LINKED ISSUE #1430: [karmadactl init] can not read KUBECONFIG environment variable
**What happened**:

When I set KUBECONFIG, `karmadctl init` can not read KUBECONFIG environment variable, error msg:
```
# kubectl karmada init
Error: error loading config file "/root/.kube/config": read /root/.kube/config: is a directory
```

**What you expected to happen**:

Use KUBECONFIG environment variable.

**How to reproduce it (as minimally and precisely as possible)**:

```
karmadactl init
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.1.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
```
karmadactl version: version.Info{GitVersion:"v1.1.0", GitCommit:"0b73c6b4e9c84a4ef702f9f7af87d6bfb038fb56", GitTreeState:"clean", BuildDate:"2022-03-04T01:57:33Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Others:

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1430 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix `karmadactl init` can not read KUBECONFIG environment variable issue
```
/cc @RainbowMango  @XiShanYongYe-Chang @prodanlabs

### CODE REVIEW

**Comment by RainbowMango** [comment]
@huone1 @XiShanYongYe-Chang 
https://github.com/karmada-io/karmada/runs/5443201929?check_suite_focus=true
```
OverridePolicy with nil resourceSelectors
/home/runner/work/karmada/karmada/test/e2e/overridepolicy_test.go:235
  Deployment override testing
  /home/runner/work/karmada/karmada/test/e2e/overridepolicy_test.go:236
    deployment imageOverride testing
    /home/runner/work/karmada/karmada/test/e2e/overridepolicy_test.go:281
------------------------------
failover testing Deployment propagation testing 
  deployment failover testing
  /home/runner/work/karmada/karmada/test/e2e/failover_test.go:62
STEP: Creating PropagationPolicy(karmadatest-hvd/deploy-rwd)
STEP: Creating Deployment(karmadatest-hvd/deploy-rwd)
I0307 04:43:31.529947   37166 deployment.go:124] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) schedule result is: member1
STEP: set one cluster condition status to false
I0307 04:43:31.530207   37166 failover_test.go:73] Set cluster member1 to disable.
STEP: check whether deployment of failed cluster is rescheduled to other available cluster
I0307 04:45:06.912277   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:11.921584   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:16.929873   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:21.945206   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:26.96[1151](https://github.com/karmada-io/karmada/runs/5443201929?check_suite_focus=true#step:5:1151)   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:31.970542   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:36.991220   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:42.000291   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:47.008024   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:52.014640   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:45:57.023043   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:46:02.030664   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:46:07.039217   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:46:12.055902   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:46:17.066281   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:46:22.074774   37166 deployment.go:114] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) hasn't been scheduled.
I0307 04:46:27.087882   37166 deployment.go:124] The ResourceBinding(karmadatest-hvd/deploy-rwd-deployment) schedule result is: member1

• Failure [180.624 seconds]
failover testing
/home/runner/work/karmada/karmada/test/e2e/failover_test.go:27
  Deployment propagation testing
  /home/runner/work/karmada/karmada/test/e2e/failover_test.go:28
    deployment failover testing [It]
    /home/runner/work/karmada/karmada/test/e2e/failover_test.go:62

    Expected
        <bool>: true
    to be false

    /home/runner/work/karmada/karmada/test/e2e/failover_test.go:93
------------------------------
S

Summarizing 1 Failure:

[Fail] failover testing Deployment propagation testing [It] deployment failover testing 
/home/runner/work/karmada/karmada/test/e2e/failover_test.go:93

Ran 40 of 41 Specs in 927.083 seconds
FAIL! -- 39 Passed | 1 Failed | 0 Pending | 1 Skipped
```

**Comment by XiShanYongYe-Chang** [comment]
Hi @lonelyCZ, can you rebase the latest code, we have solved the CI failed.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

This pr will be conflict with #1455

**Comment by lonelyCZ** [comment]
> This pr will be conflict with #1455

Got it. Thanks. :)

**Comment by RainbowMango** [comment]
Please add a release note on the PR description.

By the way, should we cherry-pick this to release branches?

cc @prodanlabs might want to know what we are going to do.

**Comment by prodanlabs** [comment]
> Please add a release note on the PR description.
> 
> By the way, should we cherry-pick this to release branches?
> 
> cc @prodanlabs might want to know what we are going to do.

I'll take a look when I'm free, I have no problem here. thx

**Comment by lonelyCZ** [comment]
Do I need to cheery-pick this now? @RainbowMango

**Comment by RainbowMango** [comment]
> Do I need to cheery-pick this now? @RainbowMango

Hold on until this is merged to master. I haven't looked at this yet, will do it ASAP.

File: pkg/karmadactl/cmdinit/kubernetes/deploy.go [hunk 1]
```diff
@@ -95,6 +92,16 @@ func (i *CommandInitOption) Validate(parentCommand string) error {
 
 // Complete Initialize k8s client
 func (i *CommandInitOption) Complete() error {
+	// check config path of host kubernetes cluster
+	env := os.Getenv("KUBECONFIG")
+	if env != "" {
+		i.KubeConfig = env
+	}
```
Comment (RainbowMango) [inline pkg/karmadactl/cmdinit/kubernetes/deploy.go:99]: Does this mean `KUBECONFIG` environment would override `--kubeconfig`? 

The kubectl get config according to following rules, that we can't violate :
  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

Comment (lonelyCZ) [reply pkg/karmadactl/cmdinit/kubernetes/deploy.go:99]: Ok, I will fix it as these rules.

**Comment by lonelyCZ** [comment]
Abide by the rules and the conflict has been fixed.

**Comment by RainbowMango** [comment]
cc @XiShanYongYe-Chang

**Review by RainbowMango — APPROVED** [review]
/approve

Leave LGTM to @XiShanYongYe-Chang 

retitle Fix `karmadactl init` can not read KUBECONFIG environment variable issue

**Comment by RainbowMango** [comment]
/retitle Fix `karmadactl init` can not read KUBECONFIG environment variable issue

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
Hi @lonelyCZ Would you like cherry-pick this patch to `release-1.0` and `release-1.1` branch?
You can do that by [this cherry-pick script](https://github.com/karmada-io/karmada/blob/master/hack/cherry_pick_pull.sh).

**Comment by lonelyCZ** [comment]
Yes, thanks. I will try to do it.
