### PR TITLE
Account for unschedulable plugin result during maxreplica estimation

### LINKED ISSUE #5011: Unschedulable result treated as failure during max replica estimation
**What happened**:
While testing CRD scheduling with the accurate estimator + resourcequota plugin enabled, I noticed that Karmada would still schedule applications to a cluster's namespace even if that namespace did not have sufficient resources available. 

**What you expected to happen**:
When using accurate estimator with resourcequota plugin enabled, Karmada should not schedule replicas to clusters that do not have sufficient namespaced resources. 

**Why does this happen**:

1. When finding selected clusters, Karmada scheduler will loop through all enabled estimators and get the minimum score for each cluster during [calAvailableReplicas](https://github.com/karmada-io/karmada/blob/master/pkg/scheduler/core/util.go#L71).

2. When estimating using `accurate estimator`,  the ResourceQuota plugin can return Unschedulable. This means that the replica's resource requirements are greater than the available resources on the desired namespace. Unschedulable **does not** get treated as a success, so the estimator will keep the score for that cluster as math.MaxInt32 (2147483647) in [RunEstimateReplicasPlugins](https://github.com/karmada-io/karmada/blob/master/pkg/estimator/server/framework/runtime/framework.go#L124). 

3. Since accurate estimator returns math.MaxInt32 as the cluster score when unschedulable, the cluster scores will default to the generic estimator. This can result in incorrect scheduling.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable accurate estimator with the ResourceQuotaEstimate feature gate set to true. 

2. Fill the desired amespace on one of your member clusters (lets say member A) to capacity, so that the replica cannot be scheduled. 

3. Apply the resource to Karmada control-plane. Looking at logs, you should see the scheduler rely on generic scheduler scores rather than using the accurate estimator scores. 

**Environment**:
- Karmada version: v1.9.0

### PR DESCRIPTION
**Pull request by mszacillo**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Bugfix related to maxReplica estimation.

**Testing**

Local:
```
mszacillo@HXQDWP921L estimator % go test ./...
?   	github.com/karmada-io/karmada/pkg/estimator/client	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/pb	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/framework	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/framework/plugins	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/metrics	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/nodes	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/replica	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/service	[no test files]
ok  	github.com/karmada-io/karmada/pkg/estimator/server	1.626s
ok  	github.com/karmada-io/karmada/pkg/estimator/server/framework/plugins/resourcequota	2.148s
ok  	github.com/karmada-io/karmada/pkg/estimator/server/framework/runtime	1.244s
```
E2E test with added logs:
```
I0601 16:19:48.700057       1 generic_scheduler.go:95] Feasible clusters scores: [{cluster-A 0} {cluster-B 0}]
I0601 16:19:48.700159       1 util.go:76] Running score for estimator: general-estimator
I0601 16:19:48.700212       1 general.go:77] cluster cluster-A has max available replicas: 8 according to cluster resource models
I0601 16:19:48.700234       1 general.go:77] cluster cluster-B has max available replicas: 8 according to cluster resource models
I0601 16:19:48.700257       1 util.go:83] Result for cluster: cluster-A was score 8
I0601 16:19:48.700270       1 util.go:83] Result for cluster: cluster-B was score 8
I0601 16:19:48.700282       1 util.go:76] Running score for estimator: scheduler-estimator
I0601 16:19:48.704222       1 util.go:83] Result for cluster: cluster-A was score 0
I0601 16:19:48.704248       1 util.go:83] Result for cluster: cluster-B was score 4
I0601 16:19:48.704253       1 util.go:101] Target cluster calculated by estimators (available cluster && maxAvailableReplicas): [{cluster-A 0} {cluster-B 4}]
I0601 16:19:48.704275       1 generic_scheduler.go:101] Selected clusters: [cluster-B]
```

**Which issue(s) this PR fixes**:
Fixes #5011

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
`karmada-scheduler-estimator`: Fixed the `Unschedulable` result returned by plugins to be treated as an exception issue.
```

### CODE REVIEW

**Review by whitewindmills — COMMENTED** [review]
/assign

**Review by RainbowMango — COMMENTED** [review]
/assign

File: pkg/scheduler/core/util.go [hunk 1]
```diff
@@ -72,8 +72,9 @@ func calAvailableReplicas(clusters []*clusterv1alpha1.Cluster, spec *workv1alpha
 	estimators := estimatorclient.GetReplicaEstimators()
 	ctx := context.WithValue(context.TODO(), util.ContextKeyObject,
 		fmt.Sprintf("kind=%s, name=%s/%s", spec.Resource.Kind, spec.Resource.Namespace, spec.Resource.Name))
-	for _, estimator := range estimators {
+	for name, estimator := range estimators {
 		res, err := estimator.MaxAvailableReplicas(ctx, clusters, spec.ReplicaRequirements)
+		klog.V(5).Infof("MaxAvailableReplica scores calculated by estimator %s: %v", name, availableTargetClusters)
```
Comment (RainbowMango) [inline pkg/scheduler/core/util.go:77]: It would be great if this log carries the referring workload, like:
https://github.com/karmada-io/karmada/blob/957e50b2cf55c2bdd8eeabafcc1cde3da480f686/pkg/scheduler/core/util.go#L66

otherwise, we can't figure out which workload/resource the log belongs to.

File: pkg/estimator/server/estimate.go [hunk 2]
```diff
@@ -76,6 +76,11 @@ func (es *AccurateSchedulerEstimatorServer) estimateReplicas(
 
 	var res int32
 	replicas, ret := es.estimateFramework.RunEstimateReplicasPlugins(ctx, snapshot, &requirements)
+
+	if ret.IsUnschedulable() {
+		return replicas, nil
+	}
```
Comment (RainbowMango) [inline pkg/estimator/server/estimate.go:82]: This is a short path, meaning we have the minimal replica (0) and don't need to run the following checks.
Shall we add a comment on it?

Comment (mszacillo) [reply pkg/estimator/server/estimate.go:82]: Makes sense, I can add this.

File: pkg/scheduler/core/util.go (hunk 1 above)
Comment (mszacillo) [reply pkg/scheduler/core/util.go]: Updated log shows:
```
I0604 15:56:07.114751       1 util.go:78] MaxAvailableReplica scores calculated by estimator general-estimator for workload(kind=FlinkDeployment, test-namespace/mszacillo-karmada-test-2): [{cluster-A 8} {cluster-B 8}]
```

**Review by RainbowMango — COMMENTED** [review]
/lgtm

@whitewindmills Do you have any further comments?

File: pkg/estimator/server/framework/interface.go [hunk 3]
```diff
@@ -155,6 +155,11 @@ func (s *Result) IsSuccess() bool {
 	return s == nil || s.code == Success
 }
 
+// IsUnschedulable return true if "Result" is not nil and Code is "Unschedulable".
```
Comment (whitewindmills) [inline pkg/estimator/server/framework/interface.go:158]: //  IsUnschedulable returns ...

File: pkg/estimator/server/estimate.go [hunk 4]
```diff
@@ -76,6 +76,12 @@ func (es *AccurateSchedulerEstimatorServer) estimateReplicas(
 
 	var res int32
 	replicas, ret := es.estimateFramework.RunEstimateReplicasPlugins(ctx, snapshot, &requirements)
+
+	// No replicas can be scheduled on the cluster, skip further checks and return 0
+	if ret.IsUnschedulable() {
+		return replicas, nil
```
Comment (whitewindmills) [inline pkg/estimator/server/estimate.go:82]: I'm afraid some readers may be confused about what the value of the `replicas` field is. can you return 0 explicitly here?

File: pkg/scheduler/core/util.go [hunk 5]
```diff
@@ -62,18 +62,21 @@ func calAvailableReplicas(clusters []*clusterv1alpha1.Cluster, spec *workv1alpha
...
 	}
 
 	// Get the minimum value of MaxAvailableReplicas in terms of all estimators.
 	estimators := estimatorclient.GetReplicaEstimators()
 	ctx := context.WithValue(context.TODO(), util.ContextKeyObject,
 		fmt.Sprintf("kind=%s, name=%s/%s", spec.Resource.Kind, spec.Resource.Namespace, spec.Resource.Name))
-	for _, estimator := range estimators {
+	for name, estimator := range estimators {
 		res, err := estimator.MaxAvailableReplicas(ctx, clusters, spec.ReplicaRequirements)
+		klog.V(4).Infof("MaxAvailableReplica scores calculated by estimator %s for workload(kind=%s, %s): %v", name,
```
Comment (whitewindmills) [inline pkg/scheduler/core/util.go:78]: it's not score, move to line 83.
suggest:
```go
klog.V(4).Infof("Invoke MaxAvailableReplicas of estimator %s for workload(%s, kind=%s, %s): %v", name, spec.Resource.APIVersion, spec.Resource.Kind, namespacedKey, res)
```

**Comment by whitewindmills** [comment]
others LGTM

**Comment by mszacillo** [comment]
Thanks for all the comments!

**Comment by RainbowMango** [comment]
/lgtm
I see comments have been addressed. 
@whitewindmills would you like to take another look?

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
@mszacillo Great thanks for helping fix this! 
Just a suggestion that you might need to add your email to [GitHub Emails](https://github.com/settings/emails), otherwise, GitHub can't recognize you and count your contributions.

**Comment by RainbowMango** [comment]
Filed an issue(https://github.com/karmada-io/karmada/issues/5024) to track the backport tasks.
