### PR TITLE
fix wrong GO_LDFLAGS when the git tree status is dirty

### LINKED ISSUE #2155: gitTreeState
**Task description**:
When there are files uncommit(i.e. git status is dirty), e.g.
```diff
diff --git a/README.md b/README.md
index c4b12c21..81cc751b 100644
--- a/README.md
+++ b/README.md
@@ -1,3 +1,4 @@
+
 # Karmada
 
 ![Karmada-logo](docs/images/Karmada-logo-horizontal-color.png)
```
While building binary, the `gitTreeState` is  `clean`. It shall be `dirty`.

```shell
$ make karmada-aggregated-apiserver
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-263-gdb4fdc14-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=db4fdc14740b8729d7759d030657e003b778e443 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-08T06:30:09Z' BUILD_PLATFORMS=darwin/arm64 hack/build.sh karmada-aggregated-apiserver
!!! Building karmada-aggregated-apiserver for darwin/arm64:
```

The reason is wrong here.
https://github.com/karmada-io/karmada/blob/821a18542e57ae5ecf5fdc44bd3fa14c586f4a66/hack/util.sh#L616

`$$`  the PID of shell. `$?` shall be used here, indicating the exit code of last command.

**Solution**:
```diff
diff --git a/hack/util.sh b/hack/util.sh
index 86591481..e571d810 100755
--- a/hack/util.sh
+++ b/hack/util.sh
@@ -613,7 +613,7 @@ function util::get_GO_LDFLAGS() {
   GIT_VERSION=$(git describe --tags --dirty)
   GIT_COMMIT_HASH=$(git rev-parse HEAD)
   GIT_TREESTATE="clean"
-  GIT_DIFF=$(git diff --quiet >/dev/null 2>&1; if [[ $$ = 1 ]]; then echo "1"; fi)
+  GIT_DIFF=$(git diff --quiet >/dev/null 2>&1; if [[ $? = 1 ]]; then echo "1"; fi)
   if [[ "${GIT_DIFF}" == "1" ]];then
       GIT_TREESTATE="dirty"
   fi
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by carlory**
Signed-off-by: carlory <baofa.fan@daocloud.io>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

`git diff` does not normally reflect whether the current git repository has been modified, for example, adding a new file into repo.

FYI https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L61

```sh
(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) make karmadactl
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-310-g156e329f -X github.com/karmada-io/karmada/pkg/version.gitCommit=156e329f447bf60426b64c4a3441ff194319b288 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:26:37Z' BUILD_PLATFORMS=darwin/arm64 hack/build.sh karmadactl
!!! Building karmadactl for darwin/arm64:
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=arm64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-310-g156e329f -X github.com/karmada-io/karmada/pkg/version.gitCommit=156e329f447bf60426b64c4a3441ff194319b288 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:26:37Z' -o _output/bin/darwin/arm64/karmadactl github.com/karmada-io/karmada/cmd/karmadactl
+ set +x

(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) touch dirty
(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) ✗ make karmadactl
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-310-g156e329f -X github.com/karmada-io/karmada/pkg/version.gitCommit=156e329f447bf60426b64c4a3441ff194319b288 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=dirty -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:27:06Z' BUILD_PLATFORMS=darwin/arm64 hack/build.sh karmadactl
!!! Building karmadactl for darwin/arm64:
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=arm64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-310-g156e329f -X github.com/karmada-io/karmada/pkg/version.gitCommit=156e329f447bf60426b64c4a3441ff194319b288 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=dirty -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:27:06Z' -o _output/bin/darwin/arm64/karmadactl github.com/karmada-io/karmada/cmd/karmadactl
+ set +x

(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) ✗ git add .
(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) ✗ make karmadactl
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-310-g156e329f-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=156e329f447bf60426b64c4a3441ff194319b288 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=dirty -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:28:06Z' BUILD_PLATFORMS=darwin/arm64 hack/build.sh karmadactl
!!! Building karmadactl for darwin/arm64:
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=arm64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-310-g156e329f-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=156e329f447bf60426b64c4a3441ff194319b288 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=dirty -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:28:06Z' -o _output/bin/darwin/arm64/karmadactl github.com/karmada-io/karmada/cmd/karmadactl
+ set +x

(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) make karmadactl
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-311-g5d01a002 -X github.com/karmada-io/karmada/pkg/version.gitCommit=5d01a00281f9e519b196b824003b4d1ed8480b00 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:28:45Z' BUILD_PLATFORMS=darwin/arm64 hack/build.sh karmadactl
!!! Building karmadactl for darwin/arm64:
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=arm64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-311-g5d01a002 -X github.com/karmada-io/karmada/pkg/version.gitCommit=5d01a00281f9e519b196b824003b4d1ed8480b00 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:28:45Z' -o _output/bin/darwin/arm64/karmadactl github.com/karmada-io/karmada/cmd/karmadactl
+ set +x

(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) echo "hello" > dirty
(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) ✗ make karmadactl
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-311-g5d01a002-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=5d01a00281f9e519b196b824003b4d1ed8480b00 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=dirty -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:29:38Z' BUILD_PLATFORMS=darwin/arm64 hack/build.sh karmadactl
!!! Building karmadactl for darwin/arm64:
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=arm64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-311-g5d01a002-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=5d01a00281f9e519b196b824003b4d1ed8480b00 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=dirty -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:29:38Z' -o _output/bin/darwin/arm64/karmadactl github.com/karmada-io/karmada/cmd/karmadactl
+ set +x

(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) ✗ rm dirty
(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) ✗ make karmadactl
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-311-g5d01a002-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=5d01a00281f9e519b196b824003b4d1ed8480b00 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=dirty -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:30:09Z' BUILD_PLATFORMS=darwin/arm64 hack/build.sh karmadactl
!!! Building karmadactl for darwin/arm64:
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=arm64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-311-g5d01a002-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=5d01a00281f9e519b196b824003b4d1ed8480b00 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=dirty -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:30:09Z' -o _output/bin/darwin/arm64/karmadactl github.com/karmada-io/karmada/cmd/karmadactl
+ set +x
```

**Which issue(s) this PR fixes**:

Fixes #2155

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @ikaven1024 I remember you opened a good-first issue for this similar things.

**Comment by ikaven1024** [comment]
> cc @ikaven1024 I remember you opened a good-first issue for this similar things.

Yes, it's same to https://github.com/karmada-io/karmada/issues/2155

File: hack/util.sh [hunk 1]
```diff
@@ -612,10 +612,11 @@ function util::get_GO_LDFLAGS() {
   # Git information
   GIT_VERSION=$(git describe --tags --dirty)
   GIT_COMMIT_HASH=$(git rev-parse HEAD)
-  GIT_TREESTATE="clean"
-  GIT_DIFF=$(git diff --quiet >/dev/null 2>&1; if [[ $$ = 1 ]]; then echo "1"; fi)
-  if [[ "${GIT_DIFF}" == "1" ]];then
-      GIT_TREESTATE="dirty"
+  # Check if the tree is dirty. defaults to dirty
```
Comment (RainbowMango) [inline hack/util.sh:615]: What's the meaning of `defaults to dirty`?

Comment (carlory) [reply hack/util.sh:615]: @RainbowMango 

It‘s copied from https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L63

Comment (mrlihanbo) [reply hack/util.sh:615]: > @RainbowMango
> 
> It‘s copied from https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L63
> 
> I guess that it refer to the `else` code block

It makes me confused as we don't have default value for `GIT_TREESTATE`.

Comment (carlory) [reply hack/util.sh]: @mrlihanbo It's removed.

Comment (RainbowMango) [reply hack/util.sh]: Thanks.

**Review by RainbowMango — COMMENTED** [review]
Please add a `Fixes` director to indicate that this PR will close #2155.

And, please give a test report for this patch. Then we are ready to go. Thanks.

**Review by RainbowMango — COMMENTED** [review]
/lgtm
/approve
Thanks.
