### PR TITLE
fixed the issue where resource scheduling suspension may become ineffective

### LINKED ISSUE #6354: Resource scheduling suspension will become ineffective when the cluster changes
**What happened**:
When the cluster changes, a scheduling result will still be generated even if `rb.spec.suspension.scheduling` is set to true. 

https://github.com/karmada-io/karmada/blob/cad6ad5dfa29a73d64233a0fe29d12e88ad393c0/pkg/scheduler/event_handler.go#L354-L363

The scheduler will watch the cluster changes and reschedule the affected resourcebindings. However, when filtering the affected resourcebindings, it does not determine whether the scheduling suspension has been set.  

**What you expected to happen**:
When the cluster changes, Karmada-scheduler will not schedule the resourcebinding if `rb.spec.suspension.scheduling` is set to true. 

**How to reproduce it (as minimally and precisely as possible)**:
1. add a mutating webhook to set `rb.spec.suspension.scheduling` to true when a rb created
2. deploy a deployment nginx
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
```
3. deploy a propagationpolicy 
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx 
```
4. As expected, no scheduling result has been generated.
```bash
$ kubectl --context karmada-apiserver get rb nginx-deployment 
NAME               SCHEDULED   FULLYAPPLIED   AGE
nginx-deployment               False          4s
$ karmadactl get deployments.apps --operation-scope members
No resources found in default namespace.
```
5. Join a new member cluster member4
6. Resource scheduling suspension became ineffective
```bash
$ karmadactl get deployments.apps --operation-scope members                                        
NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE   ADOPTION
nginx   member1   0/1     1            0           3s    Y
nginx   member3   1/1     1            1           3s    Y
nginx   member2   1/1     1            1           3s    Y
nginx   member4   0/1     1            0           2s    Y
$ kubectl get rb nginx-deployment 
NAME               SCHEDULED   FULLYAPPLIED   AGE
nginx-deployment   True        True           3m52s
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Ref to #6354, karmada-scheduler should not enqueue rbs/crbs when the cluster is updated if `binding.spec.suspension.scheduling` is set to true.

**Which issue(s) this PR fixes**:
Fixes #6354

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-scheduler`: Fixed the issue where resource scheduling suspension may become ineffective during a cluster update.
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/lgtm
/assign @whitewindmills 
for another look and approve

File: pkg/scheduler/event_handler.go [hunk 1]
```diff
@@ -340,7 +340,7 @@ func (s *Scheduler) enqueueAffectedBindings(cluster *clusterv1alpha1.Cluster) er
 				// for scheduling or its status has not been synced to the
 				// cache. Just enqueue the binding to avoid missing the cluster
 				// update event.
-				if schedulerNameFilter(s.schedulerName, binding.Spec.SchedulerName) {
+				if schedulerNameFilter(s.schedulerName, binding.Spec.SchedulerName) && !binding.Spec.SchedulingSuspended() {
```
Comment (whitewindmills) [inline pkg/scheduler/event_handler.go:343]: I prefer to add it here.
```go
for _, binding := range bindings {
	if binding.Spec.SchedulingSuspended() {
                continue
        }
        ... ...
```

Comment (zhzhuang-zju) [reply pkg/scheduler/event_handler.go:343]: How about moving the schedulerNameFilter here as well?
```go
	for _, binding := range bindings {
		placementPtr := binding.Spec.Placement
		if placementPtr == nil {
			// never reach here
			continue
		}
		if !schedulerNameFilter(s.schedulerName, binding.Spec.SchedulerName) {
			continue
		}
		if binding.Spec.SchedulingSuspended(){
			continue
		}
```

Comment (whitewindmills) [reply pkg/scheduler/event_handler.go:343]: +1
