### PR TITLE
Ensure the latest schedulerObservedGeneration if do not need to schedule

### LINKED ISSUE #3454: After workload is scheduled, binding.status.schedulerObservedGeneration and generation are inconsistent
**What happened**:
When I deploy a workload to multiple clusters with `divided` type and the workload is successfully scheduled, I found that binding.status.schedulerObservedGeneration and generation are inconsistent. Generation is 2 whereas schedulerObservedGeneration is 1. Because binding.Spec has undergone two changes, the binding is generated for the first time, and the scheduling result is written into the binding for the second. However, the second change will not be scheduled because the following three rules are not met.

https://github.com/karmada-io/karmada/blob/48e93dccb6b6ecce984175a37e06bc674424f24a/pkg/scheduler/scheduler.go#L312-L334

Binding.status.schedulerObservedGeneration equal to generation is a access requirement for eviction controller. This may influence failover process.

https://github.com/karmada-io/karmada/blob/48e93dccb6b6ecce984175a37e06bc674424f24a/pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go#L95

**What you expected to happen**:
After workload is scheduled, binding.status.schedulerObservedGeneration and generation should be the same.

**How to reproduce it (as minimally and precisely as possible)**:
Just use the sample in the Karmada repo.

**Anything else we need to know?**:
This may also exist in the latest three version.

**Environment**:
- Karmada version: v1.5
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### LINKED ISSUE #3467: graceful-eviction does not work.
**What happened**:
graceful-eviction does not work.

depoly.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: docker.m.daocloud.io/nginx
        name: nginx
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
```

pp.yaml

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinities:
      - affinityName: default
        clusterNames:
          - member1
          - member2
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        dynamicWeight: AvailableReplicas

```

Add taints.
``` shell
./_output/bin/darwin/arm64/karmadactl taint clusters member1 key1=value1:NoExecute 
```

RB.yaml
```
spec:
  clusters:
  - name: member2
    replicas: 4
  gracefulEvictionTasks:
  - fromCluster: member1
    producer: TaintManager
    reason: TaintUntolerated
    replicas: 2
  placement:
    clusterAffinities:
    - affinityName: default
      clusterNames:
      - member1
      - member2
    clusterTolerations:
    - effect: NoExecute
      key: cluster.karmada.io/not-ready
      operator: Exists
      tolerationSeconds: 30
    - effect: NoExecute
      key: cluster.karmada.io/unreachable
      operator: Exists
      tolerationSeconds: 30
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
  replicaRequirements:
    resourceRequest:
      cpu: 250m
      memory: 512Mi
  replicas: 4
  resource:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
    namespace: default
    resourceVersion: "6942"
    uid: 78aff1f4-ddf4-40f9-9880-5d5f8ea23f33
  schedulerName: default-scheduler
status:
  aggregatedStatus:
  - applied: true
    clusterName: member1
    health: Healthy
    status:
      availableReplicas: 2
      readyReplicas: 2
      replicas: 2
      updatedReplicas: 2
  - applied: true
    clusterName: member2
    health: Healthy
    status:
      availableReplicas: 4
      readyReplicas: 4
      replicas: 4
      updatedReplicas: 4
  conditions:
  - lastTransitionTime: "2023-04-26T03:20:45Z"
    message: Binding has been scheduled
    reason: BindingScheduled
    status: "True"
    type: Scheduled
  - lastTransitionTime: "2023-04-26T03:20:46Z"
    message: All works have been successfully applied
    reason: FullyAppliedSuccess
    status: "True"
    type: FullyApplied
  schedulerObservedGeneration: 3
  schedulerObservingAffinityName: default

```

```
  gracefulEvictionTasks:
  - fromCluster: member1
    producer: TaintManager
    reason: TaintUntolerated
    replicas: 2

```

The `gracefulEvictionTasks` queue is never empty.

Restart `karmada-controller-manager` doesn't work either.

**What you expected to happen**:

graceful-eviction can work.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: release-1.5
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by Poor12**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Ensure the latest schedulerObservedGeneration if do not need to schedule.

**Which issue(s) this PR fixes**:
Fixes #3454 
Fixes #3467 

**Special notes for your reviewer**:
This PR need to cherry-pick.

**Does this PR introduce a user-facing change?**:
```
`karmada-scheduler`: Fixed the issue of inconsistent Generation and SchedulerObservedGeneration.
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Comment by XiShanYongYe-Chang** [comment]
Maybe we need to describe the components in the release-note.

**Comment by Poor12** [comment]
> Maybe we need to describe the components in the release-note.

Done.

**Review by RainbowMango — COMMENTED** [review]
The root cause of this issue is that we are [using patch](https://github.com/karmada-io/karmada/blob/2ef01942f17d51216decd97c72749c05dcfa7b3e/pkg/scheduler/scheduler.go#L702-L718) to update the status `after we updated the `.spec` part which will lead generation increasing`. 

I believe this patch could work around this problem, but it looks like a redundancy design. I wonder if we have another alternative solution. cc @Garrybest for help.

**Comment by Poor12** [comment]
> The root cause of this issue is that we are [using patch](https://github.com/karmada-io/karmada/blob/2ef01942f17d51216decd97c72749c05dcfa7b3e/pkg/scheduler/scheduler.go#L702-L718) to update the status `after we updated the `.spec` part which will lead generation increasing`.
> 
> I believe this patch could work around this problem, but it looks like a redundancy design. I wonder if we have another alternative solution. cc @Garrybest for help.

Another optional idea is that we need to distinguish the situation of scheduler filling in the scheduling result.

**Comment by Garrybest** [comment]
I guess [this fucntion](https://github.com/karmada-io/karmada/blob/2ef01942f17d51216decd97c72749c05dcfa7b3e/pkg/scheduler/scheduler.go#L515) could return the latest rb here but we ignore the return value.

**Comment by Poor12** [comment]
> I guess [this fucntion](https://github.com/karmada-io/karmada/blob/2ef01942f17d51216decd97c72749c05dcfa7b3e/pkg/scheduler/scheduler.go#L515) could return the latest rb here but we ignore the return value.

I agree with @Garrybest. Ensuring that the binding is the latest binding before patching status is a good solution.

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -512,11 +512,13 @@ func (s *Scheduler) patchScheduleResultForResourceBinding(oldBinding *workv1alph
 		return nil
 	}
 
-	_, err = s.KarmadaClient.WorkV1alpha2().ResourceBindings(newBinding.Namespace).Patch(context.TODO(), newBinding.Name, types.MergePatchType, patchBytes, metav1.PatchOptions{})
+	result, err := s.KarmadaClient.WorkV1alpha2().ResourceBindings(newBinding.Namespace).Patch(context.TODO(), newBinding.Name, types.MergePatchType, patchBytes, metav1.PatchOptions{})
 	if err != nil {
```
Comment (chaunceyjiang) [inline pkg/scheduler/scheduler.go:516]: image

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -512,11 +512,13 @@ func (s *Scheduler) patchScheduleResultForResourceBinding(oldBinding *workv1alph
...
 		klog.Errorf("Failed to patch schedule to ResourceBinding(%s/%s): %v", oldBinding.Namespace, oldBinding.Name, err)
+		return err
 	}
 
+	*oldBinding = *result
```
Comment (chaunceyjiang) [inline pkg/scheduler/scheduler.go:521]: https://github.com/karmada-io/karmada/blob/5bb8eae68f8c7d94181fecd651c7f54a04765211/pkg/scheduler/scheduler.go#L301

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (Poor12) [reply pkg/scheduler/scheduler.go:516]: Does this phenomenon still occur with this fix? Would you like to share your steps to reproduce?

Comment (chaunceyjiang) [reply pkg/scheduler/scheduler.go:516]: You can  reproduce it using the steps in [the issue](https://github.com/karmada-io/karmada/issues/3467) description.

I tried using your patch to fix [the issue](https://github.com/karmada-io/karmada/issues/3467) I encountered, but it doesn't seem to have solved it.

File: pkg/scheduler/scheduler.go [hunk 3]
```diff
@@ -512,11 +512,13 @@ func (s *Scheduler) patchScheduleResultForResourceBinding(oldBinding *workv1alph
 		return nil
 	}
 
-	_, err = s.KarmadaClient.WorkV1alpha2().ResourceBindings(newBinding.Namespace).Patch(context.TODO(), newBinding.Name, types.MergePatchType, patchBytes, metav1.PatchOptions{})
```
Comment (chaunceyjiang) [inline pkg/scheduler/scheduler.go:515]: Note: restart `karmada-controller-manager` will also increment the `generation` of RB, but it will not enter the scheduling process at this time.

Comment (RainbowMango) [reply pkg/scheduler/scheduler.go:515]: > restart karmada-controller-manager will also increment the generation of RB

Why?

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (Poor12) [reply pkg/scheduler/scheduler.go:516]: I'm trying to reproduce it using the steps in the issue, but it seems the generation and the schedulerObservedGeneration is the same.

File: pkg/scheduler/scheduler.go (hunk 3 above)
Comment (Poor12) [reply pkg/scheduler/scheduler.go:515]: @chaunceyjiang is right. Through my analyze, it's mainly because of detector. For resource templates, we add it to the queue directly for adding events. However, for update events, we only add it to queue if spec of resource templates changes for performance. 

https://github.com/karmada-io/karmada/blob/ec7b3b14c66de00b43b11b517cad89baa8bbc382/pkg/detector/detector.go#L280-L308

After the status is aggregated into the resource template, the resourceVersion in rb.spec.resource is inconsistent with that in the actual resource template. It's currently working without issue. However, when controller-manager restarts, detector will add all resource templates again. So we will update rb.spec.resource.resourceVersion to the latest and then generation +1. But for scheduler, it think it do not need to schedule and not enter the scheduling process. So generation and schedulerObservedGeneration is not the same.

Comment (Poor12) [reply pkg/scheduler/scheduler.go:515]: In this case, return the latest binding after patching scheduler results will not work but the former redundancy design works.

Comment (chaunceyjiang) [reply pkg/scheduler/scheduler.go:515]: > but the former redundancy design works.

Yes.

Comment (RainbowMango) [reply pkg/scheduler/scheduler.go:515]: > However, when controller-manager restarts, detector will add all resource templates again. So we will update rb.spec.resource.resourceVersion to the latest and then generation +1. But for scheduler, it think it do not need to schedule and not enter the scheduling process. So generation and schedulerObservedGeneration is not the same.

Got it. Thanks.

**Comment by Poor12** [comment]
@chaunceyjiang, could you please help verify whether this fix can solve your problem? Great thanks.

File: pkg/scheduler/scheduler.go (hunk 3 above)
Comment (chaunceyjiang) [reply pkg/scheduler/scheduler.go:515]: > After the status is aggregated into the resource template, the resourceVersion in rb.spec.resource is inconsistent with that in the actual resource template. It's currently working without issue. However, when controller-manager restarts, detector will add all resource templates again. So we will update rb.spec.resource.resourceVersion to the latest and then generation +1.


By the way, currently the graceful-eviction-controller relies too much on this mechanism. I think the graceful-eviction-controller should also handle create event. 

https://github.com/karmada-io/karmada/pull/3475


@RainbowMango @Poor12 @RainbowMango What do you think?

**Comment by chaunceyjiang** [comment]
> @chaunceyjiang, could you please help verify whether this fix can solve your problem? Great thanks.

Yes.  I also used this patch in my local env.

File: pkg/scheduler/scheduler.go (hunk 3 above)
Comment (RainbowMango) [reply pkg/scheduler/scheduler.go:515]: > I think the graceful-eviction-controller should also handle create event.

What do you mean `handle create event`?

Comment (RainbowMango) [reply pkg/scheduler/scheduler.go:515]: Do we need to do something else during this PR?

Comment (chaunceyjiang) [reply pkg/scheduler/scheduler.go:515]: > handle create event.

https://github.com/karmada-io/karmada/blob/master/pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go#L87

Comment (chaunceyjiang) [reply pkg/scheduler/scheduler.go:515]: > Do we need to do something else during this PR?

No, This PR can solve my problem .

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
