### PR TITLE
fix the issue that the binding's suspension persists when the policy deletes the suspension configuration

### LINKED ISSUE #6660: [Suspension] .spec.suspension of ResourceBinding not removed after .spec.suspension of PropagationPolicy has been removed
**What happened**:
.spec.suspension of ResourceBinding not removed after .spec.suspension of PropagationPolicy has been removed

**What you expected to happen**:
.spec.suspension of ResourceBinding will be removed after .spec.suspension of PropagationPolicy has been removed

**How to reproduce it (as minimally and precisely as possible)**:
1. Add suspension into PropagationPolicy
2. Suspension is added automatically into ResourceBinding
3. Remove suspension of PropagationPolicy
4. Suspension of ResourceBinding  cannot be removed automatically, which makes Suspension still take effect.
5. After removed Suspension of ResourceBinding manually, the Suspension effect is gone.

**Anything else we need to know?**:

**Environment**: 
- Karmada version: v1.14.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
ref to https://github.com/karmada-io/karmada/issues/6660#issuecomment-3232352171

**Which issue(s) this PR fixes**:

Fixes #6660

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed the issue that the binding's suspension persists when the policy deletes the suspension configuration.
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Would handing the suspension this way make it look simpler:
```go
tmpSuspension := bindingCopy.Spec.Suspension
bindingCopy.Spec.Suspension = binding.Spec.Suspension
if tmpSuspension != nil && tmpSuspension.Scheduling != nil {
	if bindingCopy.Spec.Suspension == nil {
		bindingCopy.Spec.Suspension = &workv1alpha2.Suspension{}
	}
	bindingCopy.Spec.Suspension.Scheduling = tmpSuspension.Scheduling
}
```

**Comment by zhzhuang-zju** [comment]
> We probably didn't have E2E coverage for this use case before. If it can't be included in this PR, should we create an issue to track it?

I'll add the e2e test in this PR.

> Would handing the suspension this way make it look simpler:

Thanks for your suggestion! I'll evaluate it and adopt it if needed.

File: pkg/util/binding.go [hunk 1]
```diff
@@ -110,3 +110,23 @@ func RescheduleRequired(rescheduleTriggeredAt, lastScheduledTime *metav1.Time) b
...
+
+	if existSuspension != nil && existSuspension.Scheduling != nil {
+		if updated == nil {
+			updated = &workv1alpha2.Suspension{}
+		}
+		updated.Scheduling = existSuspension.Scheduling
+	}
+
+	return updated
+}
```
[the remark this answers is not in the document]
Comment (zhzhuang-zju) [reply pkg/util/binding.go]: When `newSuspension == nil, existSuspension != nil, and existSuspension.Scheduling == nil`, the expected value of updated should be nil.

File: pkg/util/binding.go [hunk 2]
```diff
@@ -110,3 +110,17 @@ func RescheduleRequired(rescheduleTriggeredAt, lastScheduledTime *metav1.Time) b
...
```
[the remark this answers is not in the document]
Comment (zhzhuang-zju) [reply pkg/util/binding.go]: I don't think this is a problem as binding should be consistent with policy

**Comment by zhzhuang-zju** [comment]
cc @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Thanks
/assign

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
/cc @RainbowMango @Monokaix

File: pkg/util/binding.go [hunk 3]
```diff
@@ -110,3 +110,29 @@ func RescheduleRequired(rescheduleTriggeredAt, lastScheduledTime *metav1.Time) b
...
+			Suspension: policyv1alpha1.Suspension{},
+			Scheduling: existingRBSuspension.Scheduling,
+		}
+	}
+
+	return &workv1alpha2.Suspension{
+		Suspension: *policySuspension,
+		Scheduling: existingRBSuspension.Scheduling,
+	}
+}
```
Comment (RainbowMango) [inline pkg/util/binding.go]:
```suggestion
// MergePolicySuspension merges the suspension configuration from policy to binding suspension.
func MergePolicySuspension(bindingSuspension, policySuspension *workv1alpha2.Suspension) *workv1alpha2.Suspension {
	if bindingSuspension == nil && policySuspension == nil {
		return nil
	}

	if policySuspension != nil { // have to sync policy suspension to binding
		if bindingSuspension == nil {
			bindingSuspension = &workv1alpha2.Suspension{}
		}
		bindingSuspension.Suspension = policySuspension.Suspension
	} else { // have to clean suspension previous synced to binding if any
		bindingSuspension.Suspension = policyv1alpha1.Suspension{}

		if bindingSuspension.Scheduling == nil { // if the scheduling not set, no need to keep an empty struct
			bindingSuspension = nil
		}
	}

	return bindingSuspension
}
```

File: pkg/util/binding_test.go [hunk 4]
```diff
@@ -419,3 +420,89 @@ func TestRescheduleRequired(t *testing.T) {
 		})
 	}
 }
+
+func TestUpdateBindingSuspension(t *testing.T) {
```
Comment (RainbowMango) [inline pkg/util/binding_test.go]: Update the function name accordingly.

File: pkg/util/binding_test.go [hunk 5]
```diff
@@ -419,3 +420,89 @@ func TestRescheduleRequired(t *testing.T) {
...
+			policySuspension: &policyv1alpha1.Suspension{
+					Dispatching: ptr.To(true),
+				},
+			want: &workv1alpha2.Suspension{
+				Suspension: policyv1alpha1.Suspension{
+					Dispatching: ptr.To(true),
+				},
+			},
+		},
+		{
```
Comment (RainbowMango) [inline pkg/util/binding_test.go:482]: The test in previous version is useful:
```golang
		{
			name: "remove Suspension.Suspension",
			existSuspension: &workv1alpha2.Suspension{
				Suspension: policyv1alpha1.Suspension{
					Dispatching: ptr.To(true),
				},
			},
			newSuspension: nil,
			want:          nil,
		},
```

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

This should be backported to previous releases, right?

**Comment by zhzhuang-zju** [comment]
> /lgtm /approve
> 
> This should be backported to previous releases, right?

Yes, it should be backported to release 1.14 and release 1.13
