### PR TITLE
replace colon with point in the rbac resource name

### LINKED ISSUE #2392: resource with specific name not sync to member cluster
**What happened**:

I'm trying to install [OLM](https://olm.operatorframework.io/) with karmada, but got following error message:
```
time="2022-08-19T00:11:31Z" level=fatal msg="couldn't clean previous release" error="catalogsources.operators.coreos.com \"olm-operators\" is forbidden: User \"system:serviceaccount:olm:olm-operator-serviceaccount\" cannot delete resource \"catalogsources\" in API group \"operators.coreos.com\" in the namespace \"olm\": RBAC: clusterrole.rbac.authorization.k8s.io \"system:controller:operator-lifecycle-manager\" not found"
```

seems `system:controller:operator-lifecycle-manager` not sync to member cluster?

cc @XiShanYongYe-Chang 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind bug
/kind feature

**What this PR does / why we need it**:

As talked about in #2392, when we propagate RBAC resources, whose names contain colon characters, it will report err.

The reason is that colons are allowed in names in validations for these resources, but this is different from name validations for CRD resources:

https://github.com/kubernetes/kubernetes/blob/f0823c0f59d6ea8e2ad0dc4e3fe0f2b396c9185f/pkg/apis/rbac/validation/validation.go#L124

https://github.com/kubernetes/kubernetes/blob/f0823c0f59d6ea8e2ad0dc4e3fe0f2b396c9185f/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/validator.go#L60

**Which issue(s) this PR fixes**:
Fixes #2392 

**Special notes for your reviewer**:

Replace colon with point in the RBAC resource name.

**Does this PR introduce a user-facing change?**:

```release-note
karmada-controller-manager: fix the error of resources whose name contains colons failing to be created.
```

### CODE REVIEW

File: pkg/util/names/names.go [hunk 1]
```diff
@@ -134,3 +137,12 @@ func GeneratePolicyName(namespace, name, gvk string) string {
 
 	return strings.ToLower(fmt.Sprintf("%s-%s", name, rand.SafeEncodeString(fmt.Sprint(hash.Sum32()))))
 }
+
+var rbacKindStrings = sets.NewString("Role", "ClusterRole", "RoleBinding", "ClusterRoleBinding")
+
+func replaceColonWithPointInNameIfNeeded(kind, name string) string {
```
Comment (jwcesign) [inline pkg/util/names/names.go:143]: add some comment like other functions?

Comment (XiShanYongYe-Chang) [reply pkg/util/names/names.go:143]: ok, I will update it, thanks~.

**Review by zirain — COMMENTED** [review]
lgtm

File: pkg/util/names/names.go [hunk 2]
```diff
@@ -134,3 +137,14 @@ func GeneratePolicyName(namespace, name, gvk string) string {
 
 	return strings.ToLower(fmt.Sprintf("%s-%s", name, rand.SafeEncodeString(fmt.Sprint(hash.Sum32()))))
 }
+
+var rbacKindStrings = sets.NewString("Role", "ClusterRole", "RoleBinding", "ClusterRoleBinding")
```
Comment (RainbowMango) [inline pkg/util/names/names.go:141]: Can you explain why we need the preset list?
It looks weird to me because for those resource types that don't support `:` in name, they never get a chance to be applied in karmada-apiserver, and for resource types that support `:` in the name(other than RBAC resources, if there is any), why don't we support them?

File: pkg/util/names/names.go [hunk 3]
```diff
@@ -55,6 +56,7 @@ func GetClusterName(executionSpaceName string) (string, error) {
 
 // GenerateBindingName will generate binding name by kind and name
 func GenerateBindingName(kind, name string) string {
+	name = replaceColonWithPointInNameIfNeeded(kind, name)
```
Comment (RainbowMango) [inline pkg/util/names/names.go:59]: We should comment on the reason.

File: pkg/util/names/names.go (hunk 2 above)
Comment (XiShanYongYe-Chang) [reply pkg/util/names/names.go]: It seems superfluous, I remove this list.

File: pkg/util/names/names.go (hunk 3 above)
Comment (XiShanYongYe-Chang) [reply pkg/util/names/names.go]: Updated.

File: pkg/util/names/names.go [hunk 4]
```diff
@@ -55,6 +55,13 @@ func GetClusterName(executionSpaceName string) (string, error) {
 
 // GenerateBindingName will generate binding name by kind and name
 func GenerateBindingName(kind, name string) string {
+	// For some resources (resources currently known are Role, ClusterRole, RoleBinding,
+	// ClusterRoleBinding), their names may contain symbols other than "." and "-", which is
+	// not allowed during the creation of CustomResource, so we need to replace them.
+	// After investigation, ":" is used in these rbac resources, such as "system:node", so we
+	// replace it first and then process other symbols if they are found later.
```
Comment (RainbowMango) [inline pkg/util/names/names.go:62]:
```suggestion
	// The name of resources, like 'Role'/'ClusterRole'/'RoleBinding'/'ClusterRoleBinding',
	// may contain symbols(like ':') that are not allowed by CRD resources which require the
	// name can be used as a DNS subdomain name. So, we need to replace it.
	// These resources may also allow for other characters(like '&','$') that are not allowed
	// by CRD resources, we only handle the most common ones now for performance concerns.
	// For more information about the DNS subdomain name, please refer to
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names.
```

**Comment by XiShanYongYe-Chang** [comment]
Test with benchmark test with the following code:
```go
func GetName01(name string) string {
	return strings.ReplaceAll(name, ":", ".")
}

func GetName02(name string) string {
	if strings.Contains(name, ":") {
		return strings.ReplaceAll(name, ":", ".")
	}
	return name
}

func BenchmarkGetName01(b *testing.B) {
	names := []string{"aaa-111", "bbb-222", "ccc-333", "ddd-444", "eee-555", "ttt:000", "ooo.666", "ppp.777", "qqq.888", "mmm.999"}

	for i := 0; i < b.N; i++ {
		for _, name := range names {
			GetName01(name)
		}
	}
}

func BenchmarkGetName02(b *testing.B) {
	names := []string{"aaa-111", "bbb-222", "ccc-333", "ddd-444", "eee-555", "ttt:000", "ooo.666", "ppp.777", "qqq.888", "mmm.999"}

	for i := 0; i < b.N; i++ {
		for _, name := range names {
			GetName02(name)
		}
	}
}
```

Test result:
```
goos: windows
goarch: amd64
pkg: github.com/karmada-io/karmada/pkg/util/names
cpu: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
BenchmarkGetName01
BenchmarkGetName01-12    	 6945460	       174.8 ns/op
PASS

goos: windows
goarch: amd64
pkg: github.com/karmada-io/karmada/pkg/util/names
cpu: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
BenchmarkGetName02
BenchmarkGetName02-12    	 9404542	       113.5 ns/op
PASS
```

**Comment by XiShanYongYe-Chang** [comment]
Test 10 times:
```
$ go test -bench="." -count 10
goos: windows
goarch: amd64
pkg: github.com/karmada-io/karmada/pkg/util/names
cpu: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
BenchmarkGetName01-12            7352548               155.4 ns/op
BenchmarkGetName01-12            7366518               158.6 ns/op
BenchmarkGetName01-12            7736853               157.9 ns/op
BenchmarkGetName01-12            8215824               161.6 ns/op
BenchmarkGetName01-12            8245869               161.6 ns/op
BenchmarkGetName01-12            7543009               156.5 ns/op
BenchmarkGetName01-12            8124388               158.6 ns/op
BenchmarkGetName01-12            8274423               159.8 ns/op
BenchmarkGetName01-12            7917421               158.1 ns/op
BenchmarkGetName01-12            8086982               161.0 ns/op
BenchmarkGetName02-12           10591256               108.7 ns/op
BenchmarkGetName02-12           11280982               108.9 ns/op
BenchmarkGetName02-12           11021712               109.8 ns/op
BenchmarkGetName02-12           11333691               107.8 ns/op
BenchmarkGetName02-12           10991103               110.0 ns/op
BenchmarkGetName02-12           10892484               104.0 ns/op
BenchmarkGetName02-12           10644733               108.0 ns/op
BenchmarkGetName02-12           11716118               105.5 ns/op
BenchmarkGetName02-12           11356237               109.9 ns/op
BenchmarkGetName02-12           11076076               114.6 ns/op
PASS
ok      github.com/karmada-io/karmada/pkg/util/names    27.423s
```

File: pkg/util/names/names.go (hunk 4 above)
Comment (XiShanYongYe-Chang) [reply pkg/util/names/names.go]: Update.

**Comment by RainbowMango** [comment]
LGTM.
@Garrybest would you like to take a look?

**Comment by Garrybest** [comment]
LGTM, just one question. What if a RBAC have both colon and point?

**Comment by RainbowMango** [comment]
> What if a RBAC have both colon and point?

Good question. If I remember correctly, we don't use the name of `RB` or `Work` name to find the `resource template`, so  there is no problem. Please @XiShanYongYe-Chang confirm.  A test for this would be awsome.

**Comment by XiShanYongYe-Chang** [comment]
> LGTM, just one question. What if a RBAC have both colon and point?

Just as @RainbowMango, this updation only changes the rb and work names of related resources, and does not change the names propagated to member clusters.

> A test for this would be awsome.

An E2E test？

**Comment by XiShanYongYe-Chang** [comment]
I update the resource name as follows in E2E:
```
Role: system:test:%s
RoleBinding: system:test.%s
ClusterRole: system:test-%s
ClusterRoleBinding: system:test.tt:%s
```

**Comment by Garrybest** [comment]
> We don't use the name of RB or Work name to find the resource template.

I don't remember exactly. Do we use labels or annotations to target the corresponding RB and original resource? If so, there is no problem here.

**Comment by XiShanYongYe-Chang** [comment]
The rb finds the resource template based on the `.spec.resource` field. The label is used between the rb and the work.

**Review by RainbowMango — APPROVED** [review]
/approve
