### PR TITLE
fix bug that spreadconstraints are not validated correctly

### LINKED ISSUE #3231: pp/cpp's spreadconstraints are not validated correctly
**What happened**:
Error pp/cpp's spreadconstraints can be create and affect the scheduling process.
0880c4c80710fad0c20c

0880c4c80710fad0a20c

**What you expected to happen**:
`minGroups` and `maxGroup` should not be less that zero, and `maxGroup` should also get default value(I think it should be `minGroups`)
**How to reproduce it (as minimally and precisely as possible)**:
Create pp or cpp with incorrect `minGroups` and `maxGroup`.
**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind feature
/kind cleanup

**What this PR does / why we need it**:
fix bug that spreadconstraints are not validated correctly
**Which issue(s) this PR fixes**:
Fixes #3231
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-webhook`: Introduced validation to ensure the `.spec.placement.spreadConstraints.maxGroups/minGroups` in PropagationPolicy is declared with a reasonable value.
```

### CODE REVIEW

File: pkg/util/validation/validation.go [hunk 1]
```diff
@@ -102,6 +102,16 @@ func ValidateSpreadConstraint(spreadConstraints []policyv1alpha1.SpreadConstrain
...
+		// If MinGroups provided, it should not be lower than 0.
+		if constraint.MinGroups < 0 {
+			allErrs = append(allErrs, field.Invalid(fldPath.Index(index), constraint, "minGroups lower than 0 is not allowed"))
+		}
+
+		// If MaxGroups provided, it should not be lower than 0.
+		if constraint.MaxGroups < 0 {
+			allErrs = append(allErrs, field.Invalid(fldPath.Index(index), constraint, "maxGroups lower than 0 is not allowed"))
+		}
+
```
Comment (XiShanYongYe-Chang) [inline pkg/util/validation/validation.go:114]: Do we need to check that `MaxGroups` cannot be less than `MinGroups`?

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Perhaps we need to specify in the API declaration as well:

https://github.com/karmada-io/karmada/blob/0652cfbe2c87946e2c6ca8ab3a6d5f22ff9a3740/pkg/apis/policy/v1alpha1/propagation_types.go#L233-L240

File: pkg/util/helper/policy.go [hunk 2]
```diff
@@ -25,6 +25,11 @@ func SetDefaultSpreadConstraints(spreadConstraints []policyv1alpha1.SpreadConstr
 			klog.Infof("Setting default MinGroups to 1")
 			spreadConstraints[i].MinGroups = 1
 		}
+
+		if spreadConstraints[i].MaxGroups == 0 && spreadConstraints[i].MinGroups > 0 {
```
[the remark this answers is not in the document]
Comment (whitewindmills) [reply pkg/util/helper/policy.go:29]: > 

If minGroups is less than zero? This part of the judgment is necessary.

**Comment by whitewindmills** [comment]
> Perhaps we need to specify in the API declaration as well:
> 
> https://github.com/karmada-io/karmada/blob/0652cfbe2c87946e2c6ca8ab3a6d5f22ff9a3740/pkg/apis/policy/v1alpha1/propagation_types.go#L233-L240

You're right.

File: pkg/util/helper/policy.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/util/helper/policy.go:29]: Isn't this a situation that has been intercepted by validate?

[the remark this answers is not in the document]
Comment (whitewindmills) [reply pkg/util/helper/policy.go:29]: > intercepted

No, mutating webhook works first!

File: pkg/util/validation/validation.go (hunk 1 above)
Comment (XiShanYongYe-Chang) [reply pkg/util/validation/validation.go:114]: Sorry, I missed it. There's already a judgment in the logic.

File: pkg/util/helper/policy.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (chaunceyjiang) [reply pkg/util/helper/policy.go:29]: I recommend using `+kubebuilder:validation:Minimum=1`.

[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/util/helper/policy.go:29]: > No, mutating webhook works first!

Ok

> I recommend using `+kubebuilder:validation:Minimum=1`.

Does this conflict with `// +optional`?

[the remark this answers is not in the document]
Comment (whitewindmills) [reply pkg/util/helper/policy.go:29]: > I recommend using `+kubebuilder:validation:Minimum=1` and `+kubebuilder:default=1`.

I don't see any difference in performance, because the webhook will always be called, but this part of the verification is done by the apiserver.

**Comment by whitewindmills** [comment]
Sorry, I accidentally clicked the close button.

File: pkg/util/validation/validation.go (hunk 1 above)
Comment (jwcesign) [reply pkg/util/validation/validation.go:114]: `MaxGroups` could equal 0? If so, it means what? i.e., HPA minReplicas could only be >=1. I also think `MinGroups` should >=1

**Comment by XiShanYongYe-Chang** [comment]
> // Defaults to MinGroups.

IMOP, it will be enough.

File: pkg/util/validation/validation.go (hunk 1 above)
Comment (whitewindmills) [reply pkg/util/validation/validation.go:114]: No, after mutating, `MaxGroups` could be more than 0 or less than 0, never be 0.

File: pkg/apis/policy/v1alpha1/propagation_types.go [hunk 3]
```diff
@@ -231,6 +231,7 @@ type SpreadConstraint struct {
 	SpreadByLabel string `json:"spreadByLabel,omitempty"`
 
 	// MaxGroups restricts the maximum number of cluster groups to be selected.
+	// Defaults to MinGroups.
```
Comment (RainbowMango) [inline pkg/apis/policy/v1alpha1/propagation_types.go:234]: I don't think the `MaxGroups` deserves a default value.
In general, the default value should be a common one that meets most of the use cases.
Here, the valid range of `MinGroups` is [1, max(int)], in order to let the scheduler works out(or, try to) a result we set the defaults to `1`, it seems reasonable, but for `MaxGroups` which is essentially a limitation to the scheduler that can't spread the group that much, we don't have enough evidence to show that users always set `MaxGroups` with the same value as `MinGroups`.

**Review by RainbowMango — COMMENTED** [review]
The validation part sounds good to me. And I believe this PR is more like focus on the validation instead of the default value:)

File: pkg/apis/policy/v1alpha1/propagation_types.go (hunk 3 above)
Comment (whitewindmills) [reply pkg/apis/policy/v1alpha1/propagation_types.go:234]: @RainbowMango Hi, thanks for your replies!
I agree with most of your thoughts, but `MaxGroups` would be zero which is an incomprehensible value for ` karmada-scheduler` without a default value. In other words, how should we(or ` karmada-scheduler` does) understand `MaxGroups` without a default value?

Comment (RainbowMango) [reply pkg/apis/policy/v1alpha1/propagation_types.go:234]: > how should we(or  karmada-scheduler does) understand MaxGroups without a default value?

It perhaps can't happen because there is a validation to ensure `MaxGroups` can't be lower than `MinGroups`(1).
right?

**Comment by whitewindmills** [comment]
@RainbowMango I don't know if you have any other suggestions, if not, I think this PR can be closed.

**Comment by RainbowMango** [comment]
I'm still thinking if the `MaxGroups` should be set with a default value.
Can we focus on the validation part for this PR?

**Comment by whitewindmills** [comment]
> I'm still thinking if the `MaxGroups` should be set with a default value.
> Can we focus on the validation part for this PR?

Okay, I'll only retain the validation part for this PR due to the difference of opinion for `MaxGroups`.

**Comment by RainbowMango** [comment]
OK, thanks.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Thanks.
