### PR TITLE
fix RB may not be created when delete and create the same object immediately

### LINKED ISSUE #2090: RB may not be created when delete and create the same object immediately
**What happened**:
1. Create a deployment and wait it until running.
```bash
# kubectl create -f samples/nginx/
```

```bash
# kubectl get deployments.apps 
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   2/2     2            2           3m4s
```

2. Delete this deployment and create it again immediately, we could use `kubectl replace`

```bash
# kubectl replace --force -f samples/nginx/deployment.yaml                         
deployment.apps "nginx" deleted
deployment.apps/nginx replaced
```

3. RB will not be created

```bash
# kubectl get rb                    
NAME            SCHEDULED   FULLYAPPLIED   AGE
```

**What you expected to happen**:
Recreate RB.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Procedure:
1. We delete deployment.
2. RB tends to be `GC` but not yet deleted.
3. We create deployment, controller could just update the former RB.
4. RB is deleted by `GC`.
5. The controller could not create RB because no more events received.

I think we could watch the deletion event for RB and enqueue the object into detector.

/cc @XiShanYongYe-Chang @pigletfly @RainbowMango 

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #2090

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dddddai** [comment]
Oh sorry for the delay actually I'm working on another solution, let me file a PR now
I think this fix makes sense, we can keep it util we _enforce_ the new naming rule

**Comment by Garrybest** [comment]
No problem, this PR could be a temporary fix until your final solution.

**Comment by RainbowMango** [comment]
Oh, I just saw you sent another PR https://github.com/karmada-io/karmada/pull/2969.

**Comment by dddddai** [comment]
> Do you mean to move this forward?

Yes

> Your solution actually solves https://github.com/karmada-io/karmada/issues/2099.

It solves #2090 as well, because we will create a new binding for the new object instead of updating the old one

File: pkg/detector/detector.go [hunk 1]
```diff
@@ -466,6 +473,12 @@ func (d *ResourceDetector) ApplyClusterPolicy(object *unstructured.Unstructured,
 		bindingCopy := binding.DeepCopy()
 		err = retry.RetryOnConflict(retry.DefaultRetry, func() (err error) {
 			operationResult, err = controllerutil.CreateOrUpdate(context.TODO(), d.Client, bindingCopy, func() error {
+				// If this binding exists and its owner is not the input object, return error and let garbage collector
+				// delete this binding and try again later. See https://github.com/karmada-io/karmada/issues/2090.
+				if ownerRef := metav1.GetControllerOfNoCopy(bindingCopy); ownerRef != nil && ownerRef.UID != object.GetUID() {
```
Comment (dddddai) [inline pkg/detector/detector.go:478]: I think we should add this for L516 as well?

nit: maybe `bindingCopy.Spec.Resource.UID != object.GetUID()` is shorter?

Comment (RainbowMango) [reply pkg/detector/detector.go:478]: > nit: maybe bindingCopy.Spec.Resource.UID != object.GetUID() is shorter?

It is. But I think we should use `ownerRef` because it is designed for representing the dependency.

Comment (RainbowMango) [reply pkg/detector/detector.go:478]: > I think we should add this for L516 as well?

Please @Garrybest check.

Comment (Garrybest) [reply pkg/detector/detector.go:478]: > I think we should add this for L516 as well?
Indeed, thanks for reminding.

> nit: maybe bindingCopy.Spec.Resource.UID != object.GetUID() is shorter?
Nice finding👍. Both are OK but maybe using ownerRef is more distinct literally.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
