### PR TITLE
[e2e] add wait for proxy ready

### LINKED ISSUE #2488: [karmada-search] search failed when get the node with proxy
#### Which jobs are flaking:

https://github.com/karmada-io/karmada/runs/8243112587?check_suite_focus=true

#### Which test(s) are flaking:

```log
[karmada-search] karmada search testing
/home/runner/work/karmada/karmada/test/e2e/search_test.go:30
  karmada proxy testing
  /home/runner/work/karmada/karmada/test/e2e/search_test.go:347
    access resources testings
    /home/runner/work/karmada/karmada/test/e2e/search_test.go:516
      caching nodes
      /home/runner/work/karmada/karmada/test/e2e/search_test.go:517
        [It] could get node
        /home/runner/work/karmada/karmada/test/e2e/search_test.go:552
```

#### Anything else we need to know:

This is supposed to be an occasional error.

```log
Begin Captured GinkgoWriter Output >>
    STEP: Creating ResourceRegistry(rr-qzw9h) 09/08/22 06:53:19.172
    STEP: Removing ResourceRegistry(rr-qzw9h) 09/08/22 06:53:19.369
  << End Captured GinkgoWriter Output

  Unexpected error:
      <*errors.StatusError | 0xc0009ac960>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "nodes \"member1-control-plane\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "member1-control-plane",
                  Group: "",
                  Kind: "nodes",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
      nodes "member1-control-plane" not found
  occurred
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/search_test.go:556

  Full Stack Trace
    github.com/karmada-io/karmada/test/e2e.glob..func27.8.3.1.4()
    	/home/runner/work/karmada/karmada/test/e2e/search_test.go:556 +0x286
```

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As say in https://github.com/karmada-io/karmada/issues/2488#issuecomment-1240452424, add wait proxy ready before test.

**Which issue(s) this PR fixes**:
Fixes #2488

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: test/e2e/search_test.go [hunk 1]
```diff
@@ -621,8 +631,13 @@ var _ = ginkgo.Describe("[karmada-search] karmada search testing", ginkgo.Ordere
...
-					gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
+					var listObj *corev1.NodeList
+					gomega.Eventually(func(g gomega.Gomega) {
+						var err error
+						listObj, err := proxyClient.CoreV1().Nodes().List(context.TODO(), metav1.ListOptions{})
+						g.Expect(err).ShouldNot(gomega.HaveOccurred())
+						g.Expect(listObj.Items).ShouldNot(gomega.BeEmpty())
+					}, pollTimeout, pollInterval).Should(gomega.Succeed())
 
 					watcher, err := proxyClient.CoreV1().Nodes().Watch(context.TODO(), metav1.ListOptions{ResourceVersion: listObj.ResourceVersion})
```
Comment (XiShanYongYe-Chang) [inline test/e2e/search_test.go:642]: Get an panic here:
```log
  Test Panicked
  In [It] at: /opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:220

  runtime error: invalid memory address or nil pointer dereference

  Full Stack Trace
    github.com/karmada-io/karmada/test/e2e.glob..func27.8.3.1.7()
    	/home/runner/work/karmada/karmada/test/e2e/search_test.go:642 +0x2b6
```

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/approve
