### PR TITLE
Fix/clustertaintpolicy optimistic lock

### LINKED ISSUE #7346: ClusterTaintPolicyController: Silent Health Taints Loss Due to Non-Atomic JSON Merge Patch
**What happened**:
ClusterTaintPolicyController silently drops concurrent taint modifications from other controllers (like cluster-controller's health taints: not-ready:NoSchedule, unreachable:NoSchedule) when patching cluster taints, because client.MergeFrom() without optimistic locking uses JSON Merge Patch that replaces the entire taints array instead of merging it.

---

**What you expected to happen**:
Concurrent taint modifications should be preserved or the patch should detect conflicts and retry with fresh data.

---

**How to reproduce it (as minimally and precisely as possible)**:
1. ClusterTaintPolicyController Gets Cluster with empty taints
2. cluster-controller adds not-ready:NoSchedule taint
3. ClusterTaintPolicyController patches with stale snapshot
4. not-ready:NoSchedule taint is silently dropped

This happens on every cluster health transition. Three unit tests in pkg/controllers/taint/clustertaintpolicy_race_test.go confirm the bug.

---

**Anything else we need to know?**:
Fix: Change line 100 in pkg/controllers/taint/clustertaintpolicy_controller.go from:
`objPatch := client.MergeFrom(clusterObj)`
to:
`objPatch := client.MergeFromWithOptions(clusterObj 
client.MergeFromWithOptimisticLock{})`

This pattern is already used correctly elsewhere in the codebase. With optimistic locking, conflicts are detected and retried automatically.

---

**Environment**:
- Karmada version: All versions using non-atomic MergeFrom in ClusterTaintPolicyController

### PR DESCRIPTION
**Pull request by Ady0333**
/kind bug

**What this PR does / why we need it**:
Fixes a critical race condition in ClusterTaintPolicyController where concurrent taint modifications (specifically health taints like `not-ready:NoSchedule` added by cluster-controller) are silently dropped due to non-atomic JSON Merge Patch operations without optimistic locking. This can cause the scheduler to place workloads on unhealthy clusters.

---

**Which issue(s) this PR fixes**:
Fixes #7346 

---

**Special notes for your reviewer**:
- Single-line fix: Changed `client.MergeFrom()` to `client.MergeFromWithOptions(clusterObj, client.MergeFromWithOptimisticLock{})` at line 100 of pkg/controllers/taint/clustertaintpolicy_controller.go
- Pattern already used successfully in gracefuleviction controller
- Regression test `TestReconcilePatchRejectsStaleData` included to verify concurrent modifications are detected and rejected instead of silently lost
- No behavioral changes in non-race scenarios; conflicts are automatically retried by controller-runtime
- All existing tests pass

---

```release-note
karmada-controller-manager: Fixed ClusterTaintPolicyController silently dropping concurrent cluster health taints (not-ready:NoSchedule, unreachable:NoSchedule) during taint patches, which could cause workload scheduling to degraded clusters
```****

### CODE REVIEW

**Comment by Ady0333** [comment]
@XiShanYongYe-Chang , Please review the pr and let me know if any changes are needed. Also i have added an unit test.

**Comment by XiShanYongYe-Chang** [comment]
The format of the release notes doesn't look quite right. Also, could you help compress the commits?

File: pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
Comment (XiShanYongYe-Chang) [inline pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go]: This should have been merged already.

**Comment by XiShanYongYe-Chang** [comment]
Hi @Ady0333 It seems that the commit message is still incorrect.

**Comment by Ady0333** [comment]
> Hi @Ady0333 It seems that the commit message is still incorrect.

Hello @XiShanYongYe-Chang , my local system ran into some problem....i will this this commit shortly within today

Apologise for the inconvenience happened!

**Comment by XiShanYongYe-Chang** [comment]
It's okay, take it easy

**Comment by Ady0333** [comment]
@XiShanYongYe-Chang I have corrected the commit. Please check it once and let me know if any changes are needed.

File: pkg/controllers/taint/clustertaintpolicy_race_test.go [hunk 1]
```diff
@@ -0,0 +1,146 @@
+/*
+Copyright 2025 The Karmada Authors.
```
Comment (XiShanYongYe-Chang) [inline pkg/controllers/taint/clustertaintpolicy_race_test.go]: 2025 -> 2026

**Comment by XiShanYongYe-Chang** [comment]
Other parts LGTM, thx~

**Comment by Ady0333** [comment]
@XiShanYongYe-Chang I have fixed the 2025 -> 2026. Check it once.

File: pkg/controllers/taint/clustertaintpolicy_race_test.go (hunk 1 above)
Comment (XiShanYongYe-Chang) [inline pkg/controllers/taint/clustertaintpolicy_race_test.go]: Hi @Ady0333 It doesn't seem to have been fixed yet.

Comment (Ady0333) [reply pkg/controllers/taint/clustertaintpolicy_race_test.go]: @XiShanYongYe-Chang , check it once. I have fixed it.

**Comment by XiShanYongYe-Chang** [comment]
The release note format seems wrong, can you help fix it?
