### PR TITLE
changed the installation mode of k8s kind

### LINKED ISSUE #1141: install with local-up-karmada.sh, cannot be deleted with delete-cluster.sh
**What happened**:
I use local-up-karma.sh to test, then I want to recycle resources, I found delete-cluste.sh.
When I use it to delete a cluster. such as member1, I use it to delete a cluster, an error is returned.
```shell
hack/delete-cluster.sh member1 /root/.kube/karmada.config
>>> error: cannot rename the context "member1", it's not in /root/.kube/karmada.config
```
when i used "kubectl config use-context member1" first
hack/delete-cluster.sh member1 /root/.kube/karmada.config is work.
also
https://github.com/karmada-io/karmada/blob/b57b7235044fea6ecec4b5ed7907ae0dcef582ab/hack/util.sh#L137
the next time I come in, I find that kind can't find it.

**What you expected to happen**:
First I can delete the cluster correctly
Second I can use kind correctly, or guide me for adding a directory to my PATH
**How to reproduce it (as minimally and precisely as possible)**:
```shell
git clone https://github.com/karmada-io/karmada
cd karmada
hack/local-up-karmada.sh
```
Execute the kind command
Execute hack/delete-cluster.sh
**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by leonharetd**
**What type of PR is this?**
/kind bug
**What this PR does / why we need it**:
Changed the installation mode of kind

**Which issue(s) this PR fixes**:
Fixes #1141 
**Special notes for your reviewer**:
@lfbear @RainbowMango

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: hack/util.sh [hunk 1]
```diff
@@ -25,7 +25,7 @@ MIN_Go_VERSION=go1.16.0
 function util::install_tools() {
 	local package="$1"
 	local version="$2"
-
+  echo "go install ${package}@${version}"
```
Comment (lfbear) [inline hack/util.sh:28]: Maybe you can help to keep the space style the same. Seems some bad `tab`s here:)

**Comment by lfbear** [comment]
Thanks for your first contribution. And it looks generally good to me.
For uninstalling the Karmada, I just have an idea, shall we have a `one line` uninstall as we installed. For example, when I run `hack/delete-cluster.sh all` it deletes all clusters created by our script and is free from finding clusters' names and kubeconfig files. That's just an idea.

**Comment by leonharetd** [comment]
> 
It's a good idea. how about local-up-karmada.sh install/uninstall/add/delete? Then change the name of local-up-karmada.sh to local-karmada.sh. Use local-karmada.sh to manage locally created clusters.

**Comment by lfbear** [comment]
> 

afaik, the responsibility of the script `local-up-karmada.sh` is that start up a local Karmada environment with `kind` quickly for development. And the prefix of the name `local-up` gradually become a  conventional name for quickly installing tools, just like `setup`, I have never seen the way like `local-up-karmada.sh install/uninstall`, that maybe not compliance with public habits I think.
And the uninstalling operation most likely possibility is for debugging the installation, you know, install and uninstall all over. So I do not suggest integrating into one shell script for these different user purposes.

**Comment by leonharetd** [comment]
> > 
> 
> afaik, the responsibility of the script `local-up-karmada.sh` is that start up a local Karmada environment with `kind` quickly for development. And the prefix of the name `local-up` gradually become a conventional name for quickly installing tools, just like `setup`, I have never seen the way like `local-up-karmada.sh install/uninstall`, that maybe not compliance with public habits I think. And the uninstalling operation most likely possibility is for debugging the installation, you know, install and uninstall all over. So I do not suggest integrating into one shell script for these different user purposes.

Let me see.

File: hack/delete-cluster.sh [hunk 2]
```diff
@@ -26,9 +26,14 @@ if [[ -z "${KUBECONFIG}" ]]; then
...
 
+REPO_ROOT=$(dirname "${BASH_SOURCE[0]}")/..
+source "${REPO_ROOT}"/hack/util.sh
+# befor delete cluster, check kind command exist, Ensure that it can be deleted directly after renaming
+util::cmd_must_exist "kind"
+
 # The context name has been changed when creating clusters by 'create-cluster.sh'.
 # This will result in the context can't be removed by kind when deleting a cluster.
 # So, we need to change context name back and let kind take care about it.
+kubectl config use-context "${CLUSTER_NAME}" --kubeconfig="${KUBECONFIG}"
```
Comment (lfbear) [inline hack/delete-cluster.sh:37]: why need `use-context` first?

File: README.md [hunk 3]
```diff
@@ -146,9 +146,21 @@ There are two contexts about karmada:
 
 The `karmada-apiserver` is the **main kubeconfig** to be used when interacting with karmada control plane, while `karmada-host` is only used for debugging karmada installation with the host cluster. You can check all clusters at any time by running: `kubectl config view`. To switch cluster contexts, run `kubectl config use-context [CONTEXT_NAME]`
 
+### Uninstall karmada control plane
```
Comment (lfbear) [inline README.md:149]: Those docs should be in `hack/README.md` not in `/README.md`, it will take users more puzzle at getting started.

File: hack/delete-cluster.sh [hunk 4]
```diff
@@ -6,29 +6,36 @@ set -o pipefail
...
+# befor delete cluster, check kind command exist, Ensure that it can be deleted directly after renaming
+util::cmd_must_exist "kind"
 
-# The context name has been changed when creating clusters by 'create-cluster.sh'.
-# This will result in the context can't be removed by kind when deleting a cluster.
-# So, we need to change context name back and let kind take care about it.
-kubectl config rename-context "${CLUSTER_NAME}" "kind-${CLUSTER_NAME}" --kubeconfig="${KUBECONFIG}"
+case $1 in
+    all)
+        kind delete clusters --all
```
Comment (lfbear) [inline hack/delete-cluster.sh:21]: That's great to provide the `all` parameter, I think lots of people will use it.
But I am a little worried about deleting all clusters if I have other 'kind clusters' unrelated to Karmada, those will delete too. Shall we just delete the clusters that we will create?

Comment (lfbear) [reply hack/delete-cluster.sh:21]: BTW, the others changes seem all right.

Comment (leonharetd) [reply hack/delete-cluster.sh]: I filtered by name，Maybe there's something better.

**Comment by lfbear** [comment]
It seems more puzzled for me than the previous version, because I feel deleting clusters should be more direct. Just give me the name of the cluster to be deleted, then we'll delete it.
Let's review this requirement together, `hack/delete-cluster.sh` is a tool script for deleting some cluster created by `hack/local-up-karmada.sh`, actually deleting container created by `Kubernetes-sigs/kind`, so could we directly delete cluster by name, because the `host-cluster` has the fixed name and `member-clusters` have the same prefix in the name. 
In a word, we need a more easy tool to use.
