### PR TITLE
Disable the preemption matching of pp/cpp priority

### LINKED ISSUE #2727: The pp/cpp can preempt the matching resource template
**What happened**:

When a low-priority pp is created and a resource profile is matched,
```yaml
# deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
# pp-label.yaml 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation-label
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          app: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
```
Deployment will be propagated to `member1`, and then create a high-priority pp to match deployment nginx:
```yaml
# pp-name.yaml 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation-name
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member2
```
And Update Deployment nginx's replicas to 3, Deployment nginx will be propagated to `member2`.

**What you expected to happen**:

The pp/cpp can not preempt the matching resource template.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: master branch
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Disable the preemption matching of pp/cpp priority.

**Which issue(s) this PR fixes**:
Fixes #2727 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmada-controller-manager: Disable the preemption matching of pp/cpp priority.
```

### CODE REVIEW

File: pkg/detector/policy.go [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+
+	policyv1alpha1 "github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1"
+	workv1alpha2 "github.com/karmada-io/karmada/pkg/apis/work/v1alpha2"
+	"github.com/karmada-io/karmada/pkg/util"
+	"github.com/karmada-io/karmada/pkg/util/fedinformer/keys"
+	"github.com/karmada-io/karmada/pkg/util/helper"
+)
+
+func (d *ResourceDetector) propagateResource(object *unstructured.Unstructured, objectKey keys.ClusterWideKey) error {
+	// 1. attempt to find the matched PropagationPolicy.
```
Comment (RainbowMango) [inline pkg/detector/policy.go:18]: The comment seems misleading. The following block actually tries to find if there is a PP claimed the resource template.

File: pkg/detector/policy.go [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+	policyLabels := object.GetLabels()
+	claimedNamespace := util.GetLabelValue(policyLabels, policyv1alpha1.PropagationPolicyNamespaceLabel)
+	claimedName := util.GetLabelValue(policyLabels, policyv1alpha1.PropagationPolicyNameLabel)
+	if claimedNamespace != "" && claimedName != "" {
+		return d.reapplyPropagationPolicy(object, objectKey, claimedNamespace, claimedName)
```
Comment (RainbowMango) [inline pkg/detector/policy.go:23]: `reapply`, do we have other alternatives for the naming?

**Review by RainbowMango — COMMENTED** [review]
Why don't your just find the previous PP/CPP at [LookForMatchedPolicy](https://github.com/karmada-io/karmada/blob/7c8f237d299ad4b6062d14317b6894ff1aa49faa/pkg/detector/detector.go#L350-L354), like:
```diff
diff --git a/pkg/detector/detector.go b/pkg/detector/detector.go
index c662c94c..b325b666 100644
--- a/pkg/detector/detector.go
+++ b/pkg/detector/detector.go
@@ -352,6 +352,9 @@ func (d *ResourceDetector) LookForMatchedPolicy(object *unstructured.Unstructure
                return nil, nil
        }

+       // Just return the PropagationPolicy if the resource template already be claimed.
+       // do something here...
+
        klog.V(2).Infof("attempts to match policy for resource(%s)", objectKey)
        policyObjects, err := d.propagationPolicyLister.ByNamespace(objectKey.Namespace).List(labels.Everything())
        if err != nil {
```

**Comment by XiShanYongYe-Chang** [comment]
> Why don't your just find the previous PP/CPP at [LookForMatchedPolicy](https://github.com/karmada-io/karmada/blob/7c8f237d299ad4b6062d14317b6894ff1aa49faa/pkg/detector/detector.go#L350-L354),

The object maybe matched by PropagationPolicy or ClusterPropagationPolicy. It's not fit for ClusterPropagationPolicy here.

File: pkg/detector/policy.go (hunk 2 above)
Comment (XiShanYongYe-Chang) [reply pkg/detector/policy.go:23]: How about `applyPolicyWithNamespaceName` and `applyClusterPolicyWithName`.

File: pkg/detector/policy.go [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+
+func (d *ResourceDetector) propagateResource(object *unstructured.Unstructured, objectKey keys.ClusterWideKey) error {
+	// 1. check whether a PropagationPolicy has been matched with the object.
+	// If yes, apply the matched PropagationPolicy.
+	policyLabels := object.GetLabels()
+	claimedNamespace := util.GetLabelValue(policyLabels, policyv1alpha1.PropagationPolicyNamespaceLabel)
+	claimedName := util.GetLabelValue(policyLabels, policyv1alpha1.PropagationPolicyNameLabel)
+	if claimedNamespace != "" && claimedName != "" {
+		return d.applyPolicyWithNamespaceName(object, objectKey, claimedNamespace, claimedName)
+	}
```
Comment (RainbowMango) [inline pkg/detector/policy.go:25]:
```suggestion
	// 1. Check if the object has been claimed by a PropagationPolicy,
	// if so, just apply it.
	policyLabels := object.GetLabels()
	claimedNamespace := util.GetLabelValue(policyLabels, policyv1alpha1.PropagationPolicyNamespaceLabel)
	claimedName := util.GetLabelValue(policyLabels, policyv1alpha1.PropagationPolicyNameLabel)
	if claimedNamespace != "" && claimedName != "" {
		return d.getAndApplyPropagationPolicy(object, objectKey, claimedNamespace, claimedName)
	}
```

File: pkg/detector/policy.go [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+
+	// put it into waiting list and retry once in case the resource and propagation policy come at the same time
+	// see https://github.com/karmada-io/karmada/issues/1195
+	d.AddWaiting(objectKey)
+	return fmt.Errorf("no matched propagation policy")
+}
+
+func (d *ResourceDetector) applyPolicyWithNamespaceName(object *unstructured.Unstructured, objectKey keys.ClusterWideKey, policyNamespace, policyName string) error {
+	policyObjects, err := d.propagationPolicyLister.ByNamespace(policyNamespace).Get(policyName)
```
Comment (RainbowMango) [inline pkg/detector/policy.go:79]:
```suggestion
	policyObject, err := d.propagationPolicyLister.ByNamespace(policyNamespace).Get(policyName)
```

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
