### PR TITLE
Fixed the issue that reporting repeat EndpointSlice resources leads to duplicate backend IPs

### LINKED ISSUE #6522: When MultiClusterService and MultiClusterIngress are used for the same Service, the repeated reporting of EndpointSlice resources leads to duplicate backend IPs
**What happened**:

When user use `CrossCluster` type `MultiClusterService` and `MultiClusterIngress` resource for the same `Service`, the controller will report the repeated `EndpointSlice` resource to the Karmada control-plane, which will lead to duplicate backend IPs.

**What you expected to happen**:

Even when both `MultiClusterService` and `MultiClusterIngress` are use simultaneously for the same `Service`, the controller will not redundantly report `EndpointSlice` resources to the Karmada control-plane.

**How to reproduce it (as minimally and precisely as possible)**:

0. Install ServiceExport CRD on the member clusters.

<details>
<summary>unfold me to see the yaml</summary>

```yaml
# propagate ServiceExport CRD
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: serviceexport-policy
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: serviceexports.multicluster.x-k8s.io
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
---
# propagate ServiceImport CRD
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: serviceimport-policy
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: serviceimports.multicluster.x-k8s.io
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```

</details>

1, Apply the deployment and service resource to the `member1` cluster.

<details>
<summary>unfold me to see the yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serve
  template:
    metadata:
      labels:
        app: serve
    spec:
      containers:
      - name: serve
        image: jeremyot/serve:0a40de8
        args:
        - "--message='hello from cluster member1 (Node: {{env \"NODE_NAME\"}} Pod: {{env \"POD_NAME\"}} Address: {{addr}})'"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: serve
  labels:
    cz: test
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mcs-workload
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: serve
    - apiVersion: v1
      kind: Service
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member1
```
</details>

2. Apply the MultiClusterService to export the service from member1 to member2:

```yaml
apiVersion: networking.karmada.io/v1alpha1
kind: MultiClusterService
metadata:
  name: serve
spec:
  consumerClusters:
  - name: member2
  providerClusters:
  - name: member1
  types:
  - CrossCluster
```

3. Apply ServiceExport resource to the `member1` cluster to export the target service.

```yaml
kind: ServiceExport
metadata:
  name: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: serve-export-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceExport
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member2
```

And then you can find that the same EndpointSlices are collected to the Karmada control-plane:

```cmd
# kubectl get endpointslices.discovery.k8s.io
NAME                                   ADDRESSTYPE   PORTS     ENDPOINTS    AGE
imported-member1-serve-9q7bv           IPv4          8080      10.10.0.9    56s
imported-member2-member1-serve-9q7bv   IPv4          8080      10.10.0.9    55s
```

**Anything else we need to know?**:

In the replication steps, it is not necessary to actually create the `MultiClusterIngress` resource. The connflict actually lies in the process of reporting the EndpointSlice resource. Therefore, creating the `ServiceExport` resource to export the target `Service` is sufficient.

**Environment**:
- Karmada version: karmada v1.14
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Root Cause**

This error is caused by the `service-export-controller` redundantly reporting EndpointSlices on the member clusters.

When the `endpointslice-collect-controller` collects EndpointSlices from the source cluster to the Karmada control plane, and then the `endpointslice-dispatch-controller` distributes them to the destination cluster, the `service-export-controller` also collects EndpointSlices on this destination cluster. However, it does not distinguish whether the EndpointSlices on the cluster are issued by Karmada, ultimately leading to redundancy in these EndpointSlice resources.

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

ref #6522

**Which issue(s) this PR fixes**:

Fixes #6522

**Special notes for your reviewer**:

image

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed the issue that reporting repeat EndpointSlice resources leads to duplicate backend IPs
```

### CODE REVIEW

File: pkg/util/constants.go [hunk 1]
```diff
@@ -93,6 +91,12 @@ const (
 
 	// PropagationInstructionSuppressed indicates that the resource should not be propagated.
 	PropagationInstructionSuppressed = "suppressed"
+
+	// EndpointSliceDispatchControllerLabelValue indicates the endpointSlice is controlled by Karmada endpointslice-dispatch-controller
+	EndpointSliceDispatchControllerLabelValue = "endpointslice-dispatch-controller.karmada.io"
+
+	// EndpointSliceControllerLabelValue indicates the endpointSlice is controller by Karmada endpointslice-controller
+	EndpointSliceControllerLabelValue = "endpoitslice-controller.karmada.io"
```
Comment (RainbowMango) [inline pkg/util/constants.go]:
```suggestion
	EndpointSliceControllerLabelValue = "endpointslice-controller.karmada.io"
```

File: pkg/controllers/mcs/service_export_controller.go [hunk 2]
```diff
@@ -386,6 +386,12 @@ func (c *ServiceExportController) handleEndpointSliceEvent(ctx context.Context,
 		return err
 	}
 
+	// Exclude EndpoitSlice resources not managed by Karmada system to avoid duplicate reporting.
```
Comment (RainbowMango) [inline pkg/controllers/mcs/service_export_controller.go]:
```suggestion
	// Exclude EndPointSlice resources managed by the Karmada system to avoid duplicate reporting.
```

File: pkg/controllers/mcs/service_export_controller.go [hunk 3]
```diff
@@ -421,7 +427,14 @@ func (c *ServiceExportController) reportEndpointSliceWithServiceExportCreate(ctx
 	}
 
 	for index := range endpointSliceObjects {
-		if err = reportEndpointSlice(ctx, c.Client, endpointSliceObjects[index].(*unstructured.Unstructured), serviceExportKey.Cluster); err != nil {
+		endpointSlice := endpointSliceObjects[index].(*unstructured.Unstructured)
+		// Exclude EndpoitSlice resources not managed by Karmada system to avoid duplicate reporting.
```
Comment (RainbowMango) [inline pkg/controllers/mcs/service_export_controller.go]: ditto

File: pkg/controllers/multiclusterservice/endpointslice_collect_controller.go [hunk 4]
```diff
@@ -297,7 +297,9 @@ func (c *EndpointSliceCollectController) handleEndpointSliceEvent(ctx context.Co
 		return err
 	}
 
-	if util.GetLabelValue(endpointSliceObj.GetLabels(), discoveryv1.LabelManagedBy) == util.EndpointSliceDispatchControllerLabelValue {
+	// Exclude EndpoitSlice resources not managed by Karmada system to avoid duplicate reporting.
```
Comment (RainbowMango) [inline pkg/controllers/multiclusterservice/endpointslice_collect_controller.go]: ditto

File: pkg/controllers/multiclusterservice/endpointslice_collect_controller.go [hunk 5]
```diff
@@ -356,7 +358,9 @@ func (c *EndpointSliceCollectController) collectTargetEndpointSlice(ctx context.
 			klog.Errorf("Failed to convert object to EndpointSlice, error: %v", err)
 			return err
 		}
-		if util.GetLabelValue(eps.GetLabels(), discoveryv1.LabelManagedBy) == util.EndpointSliceDispatchControllerLabelValue {
+		// Exclude EndpoitSlice resources not managed by Karmada system to avoid duplicate reporting.
```
Comment (RainbowMango) [inline pkg/controllers/multiclusterservice/endpointslice_collect_controller.go]: ditto

File: pkg/util/constants.go (hunk 1 above)
Comment (XiShanYongYe-Chang) [reply pkg/util/constants.go]: thanks, updated.

**Comment by RainbowMango** [comment]
> Error: pkg/controllers/multiclusterservice/endpointslice_collect_controller.go:361:38: `taht` is a misspelling of `that` (misspell)

Glad to see the link check works.

**Comment by ipigwings** [comment]
this modified validation is working as expected in my case

File: pkg/controllers/mcs/service_export_controller.go [hunk 6]
```diff
@@ -427,7 +433,14 @@ func (c *ServiceExportController) reportEndpointSliceWithServiceExportCreate(ctx
 	}
 
 	for index := range endpointSliceObjects {
-		if err = reportEndpointSlice(ctx, c.Client, endpointSliceObjects[index].(*unstructured.Unstructured), serviceExportKey.Cluster); err != nil {
+		endpointSlice := endpointSliceObjects[index].(*unstructured.Unstructured)
+		// Exclude EndpointSlice resources that are managed by Karmada system to avoid duplicate reporting.
+		if util.GetLabelValue(endpointSlice.GetLabels(), discoveryv1.LabelManagedBy) == util.EndpointSliceDispatchControllerLabelValue ||
+			util.GetLabelValue(endpointSlice.GetLabels(), discoveryv1.LabelManagedBy) == util.EndpointSliceControllerLabelValue {
+			return nil
+		}
```
[the remark this answers is not in the document]
Comment (RainbowMango) [reply pkg/controllers/mcs/service_export_controller.go]: +1
@XiShanYongYe-Chang

File: pkg/controllers/mcs/service_export_controller.go [hunk 7]
```diff
@@ -385,6 +385,12 @@ func (c *ServiceExportController) handleEndpointSliceEvent(ctx context.Context,
 		return err
 	}
 
+	// Exclude EndpointSlice resources that are managed by Karmada system to avoid duplicate reporting.
+	if util.GetLabelValue(endpointSliceObj.GetLabels(), discoveryv1.LabelManagedBy) == util.EndpointSliceDispatchControllerLabelValue ||
+		util.GetLabelValue(endpointSliceObj.GetLabels(), discoveryv1.LabelManagedBy) == util.EndpointSliceControllerLabelValue {
+		return nil
+	}
```
[the remark this answers is not in the document]
Comment (RainbowMango) [reply pkg/controllers/mcs/service_export_controller.go]: +1

File: pkg/controllers/multiclusterservice/endpointslice_collect_controller.go [hunk 8]
```diff
@@ -300,7 +300,9 @@ func (c *EndpointSliceCollectController) handleEndpointSliceEvent(ctx context.Co
 		return err
 	}
 
-	if util.GetLabelValue(endpointSliceObj.GetLabels(), discoveryv1.LabelManagedBy) == util.EndpointSliceDispatchControllerLabelValue {
+	// Exclude EndpointSlice resources that are managed by Karmada system to avoid duplicate reporting.
+	if util.GetLabelValue(endpointSliceObj.GetLabels(), discoveryv1.LabelManagedBy) == util.EndpointSliceDispatchControllerLabelValue ||
+		util.GetLabelValue(endpointSliceObj.GetLabels(), discoveryv1.LabelManagedBy) == util.EndpointSliceControllerLabelValue {
 		return nil
 	}
```
[the remark this answers is not in the document]
Comment (RainbowMango) [reply pkg/controllers/multiclusterservice/endpointslice_collect_controller.go]: +1

File: pkg/controllers/mcs/service_export_controller.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/controllers/mcs/service_export_controller.go]: Thanks a lot. It's indeed a bug.

File: pkg/controllers/multiclusterservice/endpointslice_collect_controller.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/controllers/multiclusterservice/endpointslice_collect_controller.go]: I extracted this judgment logic into a function.

**Comment by XiShanYongYe-Chang** [comment]
Hi @RainbowMango, can you help review it again?
/cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
