### PR TITLE
fix(search/proxy/controller): resourceregistry merge ns

### LINKED ISSUE #6064: karmada-search ResourceRegistry resourceSelectors can not merge the same GVK's namespace
**What happened**:
I have two yaml config of resourceregistry,they just namespace different
```yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: secret-search-ns1
spec:
  targetCluster:
    clusterNames:
      - cluster-1
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      namespace: ns1
```
```yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: secret-search-ns2
spec:
  targetCluster:
    clusterNames:
      - cluster-1
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      namespace: ns2
```
when I apply them ,karmada-search just cached one namespace resource,the latter one override the previous one namespace
get ResourceRegistry:
Image
get secret,juet get ns1's secret:
Image

**What you expected to happen**:
I think karmada-search should merge these namespace,
it should cached ns1 and ns2,this should be a bug.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.12.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by JimDevil**
**What type of PR is this?**

**What this PR does / why we need it**:
karmada-search resourceregistry can merge the same cluster gvk's namespaces
get ResourceRegistry:
image
get secret:
image

**Which issue(s) this PR fixes**:
Fixes #6064

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-search`: Fixed the issue that namespaces in different ResourceRegistry might be overwritten.
```

### CODE REVIEW

File: pkg/search/proxy/controller.go [hunk 1]
```diff
@@ -228,29 +228,36 @@ func (ctl *Controller) reconcile(util.QueueKey) error {
...
-				resourcesByClusters[cluster.Name][resource] = multiNS
-			}
+			ctl.reconcileResourcesByClusters(resourcesByClusters, cluster, matchedResources)
 		}
 	}
 
 	return ctl.store.UpdateCache(resourcesByClusters, registeredResources)
 }
 
+func (ctl *Controller) reconcileResourcesByClusters(resourcesByClusters map[string]map[schema.GroupVersionResource]*store.MultiNamespace, cluster *clusterv1alpha1.Cluster, matchedResources map[schema.GroupVersionResource]*store.MultiNamespace) {
```
Comment (RainbowMango) [inline pkg/search/proxy/controller.go:238]:
```suggestion
func (ctl *Controller) reconcileResourcesByClusters(resourcesByClusters map[string]map[schema.GroupVersionResource]*store.MultiNamespace, cluster *clusterv1alpha1.Cluster, matchedResources map[schema.GroupVersionResource]*store.MultiNamespace) {
```
Does the name `MergeResourcesByCluster` look better?

Comment (RainbowMango) [reply pkg/search/proxy/controller.go:238]: I'm glad to see that you added a new method which makes it easier to have a unit test.
Can we try to add some unit tests on it this time?

**Review by RainbowMango — COMMENTED** [review]
Generally looks good to me.
But also invite guys who might be interested in this
cc @yanfeng1992

**Comment by RainbowMango** [comment]
This is a bug I think, and added a release note to the PR description.
/kind bug

File: pkg/search/proxy/controller.go (hunk 1 above)
Comment (RainbowMango) [reply pkg/search/proxy/controller.go:238]: > ok!by the way,your suggestion no changes

My bad, updated! Thanks for the reminder.

Comment (RainbowMango) [reply pkg/search/proxy/controller.go:238]: > Do you mean adding unit tests for MergeResourcesByCluster? I saw there are already unit test for reconcile

Oh, right! I didn't notice it. But the unit test missed this bug, right? Shall we add a test to it?

Comment (RainbowMango) [reply pkg/search/proxy/controller.go]: That's another story. Now focus on fixing the bug, even if the resourceSelector.namespace uses a slice, this issue also needs to be fixed.

Comment (RainbowMango) [reply pkg/search/proxy/controller.go]: Thanks in advance. We probably need to explain the reason and the real-world use case. Welcome to propose a new feature or enhancement if you like.

By the way, are you using karmada-search now?

File: pkg/search/proxy/controller_test.go [hunk 2]
```diff
@@ -104,19 +102,26 @@ func TestController(t *testing.T) {
 }
 
 func TestController_reconcile(t *testing.T) {
-	echoStrings := func(ss ...string) string {
-		sort.Strings(ss)
-		return strings.Join(ss, ",")
+	newMultiNs := func(namespaces ...string) *store.MultiNamespace {
+		multiNs := store.NewMultiNamespace()
+		if len(namespaces) == 0 {
+			multiNs.Add("")
```
Comment (RainbowMango) [inline pkg/search/proxy/controller_test.go:108]:
```suggestion
			multiNs.Add(metav1.NamespaceAll)
```
for readability :)

**Review by RainbowMango — COMMENTED** [review]
Just a nits, otherwise LGTM.

**Review by RainbowMango — COMMENTED** [review]
/lgtm

File: pkg/search/proxy/controller.go (hunk 1 above)
Comment (RainbowMango) [reply pkg/search/proxy/controller.go]: Sounds good!

**Comment by RainbowMango** [comment]
Let's wait for a while and see if others have any comments.

**Comment by yanfeng1992** [comment]
lgtm

**Comment by RainbowMango** [comment]
Thank you @yanfeng1992 .

@JimDevil I wonder have you tested it on your side? Even though we tested by unit test, it would be great to have another test.
And do you want this fix to be backported to release branches? Like release 1.12, so this patch would be included in v1.12.3.

**Comment by yanfeng1992** [comment]
> @JimDevil I wonder have you tested it on your side? Even though we tested by unit test, it would be great to have another test. 

How about adding a related test case in e2e testing? @JimDevil @RainbowMango

**Comment by RainbowMango** [comment]
> How about adding a related test case in e2e testing? @JimDevil @RainbowMango

+1

**Comment by RainbowMango** [comment]
Opened #6075 to track the cherry-pick and E2E.
@JimDevil Would you like to help?

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
