### PR TITLE
Fix depended-by label value exceed 63 characters in dependencies-distributor

### LINKED ISSUE #1741: The label value of the dependent resoucebinding over 63 characters
The dependent resourcebinding label value consists of three components namspace+"_"+name+"-"+kind. it is easy to over 63 characters. we need to split it into three labels:
resourcebinding.karmada.io/depended-by-hash.namespace: namespace
resourcebinding.karmada.io/depended-by-hash.name: name
resourcebinding.karmada.io/depended-by-hash.kind: kind

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1741

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmada-controller-manager: fix depended-by label value exceed 63 characters in dependencies-distributor
```

### CODE REVIEW

**Review by chaunceyjiang — COMMENTED** [review]
>  label value exceed 63 characters 

Can you write an e2e to test this situation?

**Comment by XiShanYongYe-Chang** [comment]
> Can you write an e2e to test this situation?

Sure, Let me write the logic for E2E to guard this logic. 

Let me contribute this in a separate PR, because I want to design the E2E related to #4711 together.

**Review by whitewindmills — COMMENTED** [review]
/lgtm

**Comment by whitewindmills** [comment]
it seems that supplementing UT is enough.

File: pkg/dependenciesdistributor/dependencies_distributor.go [hunk 1]
```diff
@@ -687,8 +683,6 @@ func buildAttachedBinding(independentBinding *workv1alpha2.ResourceBinding, obje
 		Clusters:  independentBinding.Spec.Clusters,
 	})
 
-	bindingID := util.GetLabelValue(independentBinding.Labels, workv1alpha2.ResourceBindingPermanentIDLabel)
-	dependedLabels = util.DedupeAndMergeLabels(dependedLabels, map[string]string{dependedIDLabelKey: bindingID})
```
Comment (chaunceyjiang) [inline pkg/dependenciesdistributor/dependencies_distributor.go:691]: Why was this `dependedIDLabelKey` label removed?

Comment (XiShanYongYe-Chang) [reply pkg/dependenciesdistributor/dependencies_distributor.go:691]: Currently, this ID is not used and may be overwritten. To prevent more incorrect use, delete this ID.

Comment (chaunceyjiang) [reply pkg/dependenciesdistributor/dependencies_distributor.go:691]: I think this can be submitted as a separate PR.

Then clearly write in the release-notes that this label needs to be removed.

Comment (XiShanYongYe-Chang) [reply pkg/dependenciesdistributor/dependencies_distributor.go:691]: Good idea!

**Review by chaunceyjiang — COMMENTED** [review]
Thanks~

/lgtm
