### PR TITLE
fix dynamicScaleDown uses stale clusters for scale-down operations

### LINKED ISSUE #7109: dynamicScaleDown uses stale clusters for scale-down operations
**What happened**:
In the dynamic divided scheduling mode, the `dynamicScaleDown` function incorrectly uses clusters from the previous scheduling result without verifying they are still available in the current candidate list. This can lead to incorrect replica distribution during scale-down operations.

https://github.com/karmada-io/karmada/blob/d9abe6907035717bf1653fcbdb96ca2be171aecc/pkg/scheduler/core/division_algorithm.go#L112-L117

**What you expected to happen**:
`dynamicScaleDown` should use clusters that are still available in the candidate list for scale-down operations

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a deployment with 6 replicas, and set the clusterAffinity to `member1`, `member2` and `member3`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
``` 
2. The scheduling result will be: `member1: 2; member2: 2; member3: 2`
3. Then set `bindingSpec.suspension.scheduling` to true to pause the scheduling process
4. Scale down the deployment replicas to 3, and remove member3 from the clusterAffinity.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
``` 
5. Set `bindingSpec.suspension.scheduling` to false to resume the scheduling process
6. The scheduling result will be: `member1: 1; member2: 1; member3: 1`

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
In the dynamic divided scheduling mode, the dynamicScaleDown function incorrectly uses clusters from the previous scheduling result without verifying they are still available in the current candidate list. This can lead to incorrect replica distribution during scale-down operations.

**Which issue(s) this PR fixes**:

Fixes #7109

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-scheduler`: Fixed the issue that `dynamicScaleDown` used stale clusters for scale-down operations
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
The test report:
Following the steps in #7109, the final result is:
Scheduling result: `member1: 2; member2: 1`, as expected.

**Review by RainbowMango — COMMENTED** [review]
/assign

File: pkg/scheduler/core/division_algorithm.go [hunk 1]
```diff
@@ -105,16 +105,16 @@ func dynamicScaleDown(state *assignState) ([]workv1alpha2.TargetCluster, error)
...
+	// 2. availableClusters is set to the filtered scheduled clusters (only clusters still in candidates).
 	// 3. scheduledClusters and assignedReplicas are not set, which implicates we consider this action as a first schedule.
 	state.targetReplicas = state.spec.Replicas
-	state.scheduledClusters = nil
-	state.buildAvailableClusters(func(_ []spreadconstraint.ClusterDetailInfo, spec *workv1alpha2.ResourceBindingSpec) []workv1alpha2.TargetCluster {
-		availableClusters := make(TargetClustersList, len(spec.Clusters))
-		copy(availableClusters, spec.Clusters)
+	state.buildAvailableClusters(func(_ []spreadconstraint.ClusterDetailInfo, _ *workv1alpha2.ResourceBindingSpec) []workv1alpha2.TargetCluster {
+		availableClusters := make(TargetClustersList, len(state.scheduledClusters))
+		copy(availableClusters, state.scheduledClusters)
```
Comment (RainbowMango) [inline pkg/scheduler/core/division_algorithm.go:113]: Can you help add some comments to `scheduledClusters`, `assignedReplicas`, `availableClusters`, and `availableReplicas` in the `assignState struct`? They feel not easy to tell the difference between them.

Comment (RainbowMango) [reply pkg/scheduler/core/division_algorithm.go:113]: In addition, can we simply this code like:
```golang
	state.targetReplicas = state.spec.Replicas
	copy(state.availableClusters, state.scheduledClusters)
	state.availableReplicas = util.GetSumOfReplicas(state.availableClusters)
	state.scheduledClusters = nil
```
Please consider whether we need to sort the cluster.

Comment (zhzhuang-zju) [reply pkg/scheduler/core/division_algorithm.go:113]: > Please consider whether we need to sort the cluster.

I'm afraid yes. Sorting is intended to ensure that clusters with higher weights appear earlier, thereby enabling the subsequent `AggregatedStrategy` to select as few clusters as possible. Please note: the `resortAvailableClusters` used in the `AggregatedStrategy` process merely moves the clusters from the previous scheduling result to the front of `availableClusters`; it does not perform any actual sorting of the clusters themselves.

Comment (zhzhuang-zju) [reply pkg/scheduler/core/division_algorithm.go:113]: > Can you help add some comments 

Done! Please check if they are clear and precise
