### PR TITLE
[e2e] Fix trigger rescheduling when replicaSchedulingType is duplicated

### LINKED ISSUE #3302: [flake] ReplicaSchedulingType is Duplicated, trigger rescheduling when replicas have changed.
#### Which jobs are flaking:

Occassional errors:

https://github.com/karmada-io/karmada/actions/runs/4468311953/jobs/7849119935?pr=3290

#### Which test(s) are flaking:

- [ReplicaScheduling] ReplicaSchedulingStrategy testing

   - ReplicaSchedulingType is Duplicated, trigger rescheduling when replicas have changed.

#### Reason for failure:
When updating the deployment's replica, we did not use the latest deployment as the expected deployment.
```
// UpdateDeploymentReplicas update deployment's replicas.
func UpdateDeploymentReplicas(client kubernetes.Interface, deployment *appsv1.Deployment, replicas int32) {
	ginkgo.By(fmt.Sprintf("Updating Deployment(%s/%s)'s replicas to %d", deployment.Namespace, deployment.Name, replicas), func() {
		gomega.Eventually(func() error {
			deploy, err := client.AppsV1().Deployments(deployment.Namespace).Get(context.TODO(), deployment.Name, metav1.GetOptions{})
			if err != nil {
				return err
			}
			deploy.Spec.Replicas = &replicas
			_, err = client.AppsV1().Deployments(deploy.Namespace).Update(context.TODO(), deploy, metav1.UpdateOptions{})
			return err
		}, pollTimeout, pollInterval).ShouldNot(gomega.HaveOccurred())
	})
}
```
```
framework.UpdateDeploymentReplicas(kubeClient, deployment, updateDeploymentReplicas)
klog.Infof("check if deployment's replicas have been updated on member clusters")
framework.WaitDeploymentPresentOnClustersFitWith(framework.ClusterNames(), deployment.Namespace, deployment.Name,
      func(deploy *appsv1.Deployment) bool {
	      klog.Infof("Deployment(%s/%s)'s replcas is %d, expected: %d.",
		      deploy.Namespace, deploy.Name, *deploy.Spec.Replicas, *deployment.Spec.Replicas)
	      return *deploy.Spec.Replicas == *deployment.Spec.Replicas
      })
```

### PR DESCRIPTION
**Pull request by Poor12**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Fix trigger rescheduling when replicaSchedulingType is duplicated.

**Which issue(s) this PR fixes**:
Fixes #3302 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

### CODE REVIEW

File: test/e2e/scheduling_test.go [hunk 1]
```diff
@@ -419,7 +419,7 @@ var _ = ginkgo.Describe("[ReplicaScheduling] ReplicaSchedulingStrategy testing",
 				func(deploy *appsv1.Deployment) bool {
 					klog.Infof("Deployment(%s/%s)'s replcas is %d, expected: %d.",
 						deploy.Namespace, deploy.Name, *deploy.Spec.Replicas, *deployment.Spec.Replicas)
```
Comment (XiShanYongYe-Chang) [inline test/e2e/scheduling_test.go:421]: Can you help update the log info meanwhile?
