### PR TITLE
e2e: Should ignore conflict when updating resources

### LINKED ISSUE #6842: [Flack] Karmada Operator E2E test: PriorityClass configuration testing
#### Which jobs are flaking:
Operator e2e test

#### Which test(s) are flaking:
PriorityClass configuration testing

#### Reason for failure:

Should ignore conflict when updating Karmada resources.

https://github.com/karmada-io/karmada/blob/4e592c1bee6f29a029f46991e251ef7ca6b01929/test/e2e/framework/resource/operator/karmada.go#L74

#### Anything else we need to know:
https://github.com/karmada-io/karmada/actions/runs/18561467239/job/52911926879

```
PriorityClass configuration testing PriorityClass configuration testing [It] Custom priorityClass configuration
/home/runner/work/karmada/karmada/test/e2e/suites/operator/priorityclass_test.go:47

  Captured StdOut/StdErr Output >>
  I1016 12:55:13.697454   45511 karmada.go:39] Waiting for karmada instance operatortest-wq9qn/karmadatest-lxbsg ready
  << Captured StdOut/StdErr Output

  Timeline >>
  STEP: Waiting for karmada instance operatortest-wq9qn/karmadatest-lxbsg ready @ 10/16/25 12:55:13.697
  STEP: Check if default value is system-node-critical @ 10/16/25 12:55:48.756
  STEP: Set priorityClass to system-cluster-critical @ 10/16/25 12:55:48.765
  STEP: Updating Karmada(operatortest-wq9qn/karmadatest-lxbsg) spec @ 10/16/25 12:55:48.78
  [FAILED] in [It] - /home/runner/work/karmada/karmada/test/e2e/framework/resource/operator/karmada.go:75 @ 10/16/25 12:55:48.804
  << Timeline

  [FAILED] Unexpected error:
      <*errors.StatusError | 0xc00001fae0>: 
      Operation cannot be fulfilled on karmadas.operator.karmada.io "karmadatest-lxbsg": the object has been modified; please apply your changes to the latest version and try again
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "Operation cannot be fulfilled on karmadas.operator.karmada.io \"karmadatest-lxbsg\": the object has been modified; please apply your changes to the latest version and try again",
              Reason: "Conflict",
              Details: {
                  Name: "karmadatest-lxbsg",
                  Group: "operator.karmada.io",
                  Kind: "karmadas",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 409,
          },
      }
  occurred
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/framework/resource/operator/karmada.go:75 @ 10/16/25 12:55:48.804
```

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
When updating resources and a conflict occurs, the operation should retry instead of returning an error directly. This prevents unexpected e2e test failures.

**Which issue(s) this PR fixes**:

Fixes #6842 
Parts of #6841 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None.
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Under parallel operation, update conflicts are relatively common, so it is acceptable to retry operations in case of update conflicts. Is there similar logic elsewhere?

**Comment by zhzhuang-zju** [comment]
In e2e tests, common resource operations include create, update, delete, and patch. Among these, create and delete do not have this issue, and patch operations have a relatively lower chance of conflict. However, if needed, I can also enhance the patch operations in this PR to handle conflicts more robustly.

File: test/e2e/framework/resourceregistry.go [hunk 1]
```diff
@@ -47,7 +47,9 @@ func RemoveResourceRegistry(client karmada.Interface, name string) {
 // UpdateResourceRegistry patch ResourceRegistry with karmada client.
 func UpdateResourceRegistry(client karmada.Interface, rr *searchv1alpha1.ResourceRegistry) {
 	ginkgo.By(fmt.Sprintf("Update ResourceRegistry(%s)", rr.Name), func() {
-		_, err := client.SearchV1alpha1().ResourceRegistries().Update(context.TODO(), rr, metav1.UpdateOptions{})
-		gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
+		gomega.Eventually(func() error {
+			_, err := client.SearchV1alpha1().ResourceRegistries().Update(context.TODO(), rr, metav1.UpdateOptions{})
+			return err
+		}, PollTimeout, PollInterval).ShouldNot(gomega.HaveOccurred())
```
[the remark this answers is not in the document]
Comment (zhzhuang-zju) [reply test/e2e/framework/resourceregistry.go]: +1

File: test/e2e/framework/clusterpropagationpolicy.go [hunk 2]
```diff
@@ -61,23 +61,29 @@ func PatchClusterPropagationPolicy(client karmada.Interface, name string, patch
...
-		gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
+		gomega.Eventually(func() error {
+			newPolicy, err := client.PolicyV1alpha1().ClusterPropagationPolicies().Get(context.TODO(), name, metav1.GetOptions{})
+			if err != nil {
+				return err
+			}
+			newPolicy.Spec = policySpec
+			_, err = client.PolicyV1alpha1().ClusterPropagationPolicies().Update(context.TODO(), newPolicy, metav1.UpdateOptions{})
+			return err
+		}, PollTimeout, PollInterval).ShouldNot(gomega.HaveOccurred())
```
Comment (RainbowMango) [inline test/e2e/framework/clusterpropagationpolicy.go]: This pattern would slow down the test from reporting real errors until the timeout is reached. Concerning.
For instance, when you are trying to update a non-existent resource, it is supposed to fail quickly, because that usually means something is wrong with the test steps.

File: test/e2e/framework/resourceregistry.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (RainbowMango) [reply test/e2e/framework/resourceregistry.go]: +1

File: test/e2e/framework/clusterpropagationpolicy.go (hunk 2 above)
Comment (zhzhuang-zju) [reply test/e2e/framework/clusterpropagationpolicy.go]: Good concern. Retrying can reduce end-to-end (e2e) test failures caused by transient issues like conflicts or network problems, but it can also slow down the test's ability to report real errors.  

My thoughts are:  
1. The impact is limited—this issue rarely occurs in new feature scenarios. It’s more common when adding new e2e tests that aren’t properly initialized.  
2. I can limit retries to only happen when the error is specifically a conflict error.

WDYT?

Comment (zhzhuang-zju) [reply test/e2e/framework/clusterpropagationpolicy.go]: How about:
```go
func UpdateKarmadaInstanceWithSpec(client operator.Interface, namespace, name string, karmadaSpec operatorv1alpha1.KarmadaSpec) {
	ginkgo.By(fmt.Sprintf("Updating Karmada(%s/%s) spec", namespace, name), func() {
		gomega.Eventually(func(g gomega.Gomega) error {
			karmada, err := client.OperatorV1alpha1().Karmadas(namespace).Get(context.TODO(), name, metav1.GetOptions{})
			g.Expect(err).NotTo(gomega.HaveOccurred())
			karmada.Spec = karmadaSpec
			_, err = client.OperatorV1alpha1().Karmadas(namespace).Update(context.TODO(), karmada, metav1.UpdateOptions{})
			if err != nil && !apierrors.IsConflict(err) {
				klog.Errorf("Failed to update Karmada(%s/%s), err: %v", namespace, name, err)
				g.Expect(err).NotTo(gomega.HaveOccurred())
			}
			return err
		}, framework.PollTimeout, framework.PollInterval).ShouldNot(gomega.HaveOccurred())
	})
}
```

Comment (zhzhuang-zju) [reply test/e2e/framework/clusterpropagationpolicy.go]: > How about:
> 
> ```go
> func UpdateKarmadaInstanceWithSpec(client operator.Interface, namespace, name string, karmadaSpec operatorv1alpha1.KarmadaSpec) {
> 	ginkgo.By(fmt.Sprintf("Updating Karmada(%s/%s) spec", namespace, name), func() {
> 		gomega.Eventually(func(g gomega.Gomega) error {
> 			karmada, err := client.OperatorV1alpha1().Karmadas(namespace).Get(context.TODO(), name, metav1.GetOptions{})
> 			g.Expect(err).NotTo(gomega.HaveOccurred())
> 			karmada.Spec = karmadaSpec
> 			_, err = client.OperatorV1alpha1().Karmadas(namespace).Update(context.TODO(), karmada, metav1.UpdateOptions{})
> 			if err != nil && !apierrors.IsConflict(err) {
> 				klog.Errorf("Failed to update Karmada(%s/%s), err: %v", namespace, name, err)
> 				g.Expect(err).NotTo(gomega.HaveOccurred())
> 			}
> 			return err
> 		}, framework.PollTimeout, framework.PollInterval).ShouldNot(gomega.HaveOccurred())
> 	})
> }
> ```

If it's a non-conflict error, it will return immediately, causing the test to fail.

Comment (RainbowMango) [reply test/e2e/framework/clusterpropagationpolicy.go]: Is the `gomega.Eventually` designed for this case?  It looks correct, but it just does not so straightforward as tools like RetryOnConflict.

Comment (zhzhuang-zju) [reply test/e2e/framework/clusterpropagationpolicy.go]: >  It looks correct, but it just does not so straightforward as tools like RetryOnConflict.

+1. I'll give it a try.

**Comment by zhzhuang-zju** [comment]
cc @RainbowMango @XiShanYongYe-Chang How does it look now?
