### PR TITLE
fix: The PULL mode cluster cannot be deleted immediately

### LINKED ISSUE #1847: The PULL mode cluster cannot be deleted immediately
**What happened**:
When the status of PULL mode cluster is `Unknow`

```
[root@master67 karmada]# kubectl get clusters
NAME      VERSION   MODE   READY     AGE
member1   v1.22.3   Pull   Unknown   5d18h
member2   v1.19.1   Push   True      14d
```

The deleting process is stuck.
```
[root@master67 karmada]# kubectl delete clusters member1
cluster.cluster.karmada.io "member1" deleted
^C
```

Then needing to remove manually `finalizers` filed of `cluster` and all `work` objects, the cluster can be deleted.
```
[root@master67 karmada]# kubectl get work -A
NAMESPACE            NAME                              APPLIED   AGE
karmada-es-member1   cert-manager-674b866f4c           True      5d18h
karmada-es-member1   karmada-impersonator-7cbb6bd5c9   True      5d18h
karmada-es-member1   karmada-impersonator-84f8c8f8c6   True      5d18h
karmada-es-member1   nginx-687f7fb96f                  True      5d18h
```

```
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: "2022-05-05T04:12:42Z"
  finalizers:
  - karmada.io/cluster-controller
```

```
apiVersion: work.karmada.io/v1alpha1
kind: Work
metadata:
  creationTimestamp: "2022-05-05T04:12:42Z"
  finalizers:
  - karmada.io/execution-controller
```

**What you expected to happen**:
The PULL mode cluster can be deleted immediately, not need to remove `finalizers` manually.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): master
- kubectl version: 1.23.5
- Others:

### PR DESCRIPTION
**Pull request by JadeFlute0127**
**What type of PR is this?**

**What this PR does / why we need it**:  
Avoid removing clusters that are not ready or in an unknown state in pull mode, resulting in blockages and stuck failures. When the syncmode mode is pull and the cluster is not ready or in an unknown state, delete the finalizers of the work object directly

**Which issue(s) this PR fixes**:
Fixes #1847 

**Special notes for your reviewer**:
@lonelyCZ 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by JadeFlute0127** [comment]
@lonelyCZ  The preliminary effect is shown in the figure above. Could you provide some suggestions?

**Comment by lonelyCZ** [comment]
I will look it ASAP.

/assign

File: pkg/controllers/cluster/cluster_controller.go [hunk 1]
```diff
@@ -321,6 +326,40 @@ func (c *Controller) ExecutionSpaceExistForCluster(clusterName string) (bool, er
 	return true, nil
 }
 
+func (c *Controller) deleteFinalizerForWorks(cluster *clusterv1alpha1.Cluster, workSpace *corev1.Namespace) error {
+	//delete finalizers of work objects When the sync-mode is pull mode and cluster status is notready or unknown state
+	if cluster.Spec.SyncMode == clusterv1alpha1.Pull && !util.IsClusterReady(&cluster.Status) {
```
Comment (lonelyCZ) [inline pkg/controllers/cluster/cluster_controller.go:331]: Suggest to put the `if` at the function out, this function `deleteFinalizerForWorks` focus on action.

Like
```
if cluster.Spec.SyncMode == clusterv1alpha1.Pull && !util.IsClusterReady(&cluster.Status) {
    if err := c.deleteFinalizerForWorks(cluster, executionSpaceObj); err != nil {
		klog.Errorf("Error while deleting finalizers of work which in %s: %s", executionSpaceName, err)
		return err
	}
}
```

**Comment by lonelyCZ** [comment]
What do you think of this solution?

/cc @RainbowMango  @XiShanYongYe-Chang

File: pkg/controllers/cluster/cluster_controller.go (hunk 1 above)
Comment (JadeFlute0127) [reply pkg/controllers/cluster/cluster_controller.go]: fix it

**Comment by lonelyCZ** [comment]
Hi, @JadeFlute0127 , please rebase this pr, we can push it forward.

**Comment by lonelyCZ** [comment]
I just tested it in my env and it worked as expected!

image

/lgtm

cc @XiShanYongYe-Chang @RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
Hi @lonelyCZ Sorry to respond late, I will come later.

**Comment by RainbowMango** [comment]
Echo the CI logs here:
https://github.com/karmada-io/karmada/actions/runs/6364565813/job/17280988635?pr=3998#step:5:2382
```
Karmadactl promote testing Test promoting namespaced resource: service Test promoting a service from cluster member
Error: -30T18:16:36.0682023-09-30T18:16:36.3850151Z ##[error]No space left on device : '/home/runner/runners/2.309.0/_diag/pages/3c4f99bb-30d5-4a8c-8235-8d44763e0036_20338726-f59a-5af9-b649-883abbdf9d6e_1.log'
```

**Comment by JadeFlute0127** [comment]
CI logs seem to indicate insufficient testing server space

```
[error]No space left on device

**Comment by XiShanYongYe-Chang** [comment]
> CI logs seem to indicate insufficient testing server space
> 
> ```
> [error]No space left on device
> ```

Hi @JadeFlute0127, we have resolved this error, can you help rebase the master branch and push again?

**Comment by JadeFlute0127** [comment]
> > CI logs seem to indicate insufficient testing server space
> > ```
> > [error]No space left on device
> > ```
> 
> Hi @JadeFlute0127, we have resolved this error, can you help rebase the master branch and push again?

ok, i will rebase this patch as soon as possible

File: pkg/controllers/cluster/cluster_controller.go [hunk 2]
```diff
@@ -321,6 +329,38 @@ func (c *Controller) ExecutionSpaceExistForCluster(clusterName string) (bool, er
 	return true, nil
 }
 
+// Delete finalizers of work objects
+func (c *Controller) deleteFinalizerForWorks(cluster *clusterv1alpha1.Cluster, workSpace *corev1.Namespace) error {
```
Comment (RainbowMango) [inline pkg/controllers/cluster/cluster_controller.go:333]:
```suggestion
func (c *Controller) deleteFinalizerForWorks(workSpace *corev1.Namespace) error {
```
Unused parameter `cluster`.

**Review by RainbowMango — COMMENTED** [review]
The idea is that when deleting a `Pull` mode cluster, remove the finalizer `karmada.io/execution-controller` first so that the execution namespace and the cluster object can be removed.
Generally looks good to me.

/assign @chaunceyjiang @XiShanYongYe-Chang

File: pkg/controllers/cluster/cluster_controller.go [hunk 3]
```diff
@@ -321,6 +329,38 @@ func (c *Controller) ExecutionSpaceExistForCluster(clusterName string) (bool, er
...
+	workList := &workv1alpha1.WorkList{}
+	err := c.Client.List(context.TODO(), workList, &client.ListOptions{
+		Namespace: workSpace.Name,
+	})
+	if err != nil {
+		klog.Errorf("Failed to list works in %s: %s", workSpace.Name, err)
+		return err
+	}
+	for i := range workList.Items {
```
Comment (chaunceyjiang) [inline pkg/controllers/cluster/cluster_controller.go:342]: There is no need to return immediately upon encountering an error, as it may only be a temporary situation where a single work cannot be removed from `Finalizer`, without affecting the removal of other works.

How about this?

``` go
       var  errors []error
	for i := range workList.Items {
		work := &workList.Items[i]
		err = c.removeWorkFinalizer(work)
		if err != nil {
			errors = append(errors,fmt.Errorf("Error while removing finalizers of works %s: %w", work.Name, err))
		}
	}

    return utilerrors.NewAggregate(errors)

```

Comment (JadeFlute0127) [reply pkg/controllers/cluster/cluster_controller.go:344]: fixed

File: pkg/controllers/cluster/cluster_controller.go (hunk 2 above)
Comment (JadeFlute0127) [reply pkg/controllers/cluster/cluster_controller.go]: fixed

**Comment by RainbowMango** [comment]
I'm trying to figure out the reason of lint test:
```
golangci/golangci-lint info installed /home/runner/go/bin/golangci-lint
pkg/controllers/cluster/cluster_controller.go:34[8](https://github.com/karmada-io/karmada/actions/runs/6585180935/job/17891123923?pr=3998#step:5:9): File is not `gci`-ed with --skip-generated -s Standard,Default,Prefix(github.com/karmada-io/karmada) (gci)
			errors = append(errors,fmt.Errorf("error while removing finalizers of works %s: %v", work.Name, err))
```
I can't see anything wrong with the imported packages.

**Comment by JadeFlute0127** [comment]
> I'm trying to figure out the reason of lint test:
> 
> ```
> golangci/golangci-lint info installed /home/runner/go/bin/golangci-lint
> pkg/controllers/cluster/cluster_controller.go:34[8](https://github.com/karmada-io/karmada/actions/runs/6585180935/job/17891123923?pr=3998#step:5:9): File is not `gci`-ed with --skip-generated -s Standard,Default,Prefix(github.com/karmada-io/karmada) (gci)
> 			errors = append(errors,fmt.Errorf("error while removing finalizers of works %s: %v", work.Name, err))
> ```
> 
> I can't see anything wrong with the imported packages.

Yeah, I compared other files in Karmada that also use this code and did not detect any alarms or errors.
This makes me a bit confused.

**Comment by RainbowMango** [comment]
We met a similar issue today at #4157, that probably due to a gofmt issue. 

```diff
diff pkg/controllers/cluster/cluster_controller.go.orig pkg/controllers/cluster/cluster_controller.go
--- pkg/controllers/cluster/cluster_controller.go.orig
+++ pkg/controllers/cluster/cluster_controller.go
@@ -345,7 +345,7 @@
 		work := &workList.Items[i]
 		err = c.removeWorkFinalizer(work)
 		if err != nil {
-			errors = append(errors,fmt.Errorf("error while removing finalizers of works %s: %v", work.Name, err))
+			errors = append(errors, fmt.Errorf("error while removing finalizers of works %s: %v", work.Name, err))
 		}
 	}
 	return utilerrors.NewAggregate(errors)
```
Can you help to resolve the `gofmt` issue and try again?

**Comment by JadeFlute0127** [comment]
> We met a similar issue today at #4157, that probably due to a gofmt issue.
> 
> ```diff
> diff pkg/controllers/cluster/cluster_controller.go.orig pkg/controllers/cluster/cluster_controller.go
> --- pkg/controllers/cluster/cluster_controller.go.orig
> +++ pkg/controllers/cluster/cluster_controller.go
> @@ -345,7 +345,7 @@
>  		work := &workList.Items[i]
>  		err = c.removeWorkFinalizer(work)
>  		if err != nil {
> -			errors = append(errors,fmt.Errorf("error while removing finalizers of works %s: %v", work.Name, err))
> +			errors = append(errors, fmt.Errorf("error while removing finalizers of works %s: %v", work.Name, err))
>  		}
>  	}
>  	return utilerrors.NewAggregate(errors)
> ```
> 
> Can you help to resolve the `gofmt` issue and try again?

Okay, I will handle it as soon as possible

**Comment by RainbowMango** [comment]
Hi @JadeFlute0127 Just an update: after fixing the gofmt issue, the' gci' problem was also solved in #4157.

**Comment by RainbowMango** [comment]
Hi @chaunceyjiang Please take another look.

**Comment by JadeFlute0127** [comment]
@chaunceyjiang Hi, Could you please help me check again so that we can proceed with the merge.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

All comments have been resolved.

**Comment by wm775825** [comment]
Why only remove finalizers for pull-mode clusters? If karmada lost connection to push-mode clusters, will "karmada unjoin" stuck?

**Comment by RainbowMango** [comment]
That's a good question. 
> If karmada lost connection to push-mode clusters, will "karmadactl unjoin" stuck?

Yes, I guess. 
@wm775825 Can you help run a test to confirm it?
