### PR TITLE
correct context name.

### LINKED ISSUE #392: Context naming
**What happened**:
Faulty context is returned by commands

**What you expected to happen**:
Context fetched from config file should be returned

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ karmada/hack/create-cluster.sh baremetal /root/standalone.yml 
kubeconfig file is existed, new config will append to it.
Creating cluster "baremetal" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Waiting ≤ 2m0s for control-plane = Ready ⏳ 
 • Ready after 30s 💚
Set kubectl context to "kind-baremetal"
You can now use your cluster with:

kubectl cluster-info --context kind-baremetal --kubeconfig /root/standalone.yml
```

```bash
$ kubectl cluster-info --context kind-baremetal --kubeconfig /root/standalone.yml
error: context "kind-baremetal" does not exist
```

**Anything else we need to know?**:
Thank's for developping such an ambitious tool :)

**Environment**:
- Karmada version: master
- Others: kubernetes 1.19.11

### PR DESCRIPTION
**Pull request by ikaven1024**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #392

**Special notes for your reviewer**:

Run successfully:
```bash
> hack/create-cluster.sh host ~/.kube/karmada.config
Creating cluster "host" ...
Context "kind-host" renamed to "host".
Cluster "kind-host" set.
cluster "host" is created successfully!
You can now use your cluster with:
kubectl cluster-info --context host --kubeconfig /home/yjh/.kube/karmada.config
```

When `kind` run failed:
```
> hack/create-cluster.sh host ~/.kube/karmada.config
Creating cluster "host" ...
Creating cluster host failed, see detail log in /tmp/tmp.EfC6i2XMNN-kind.log.
```

**Does this PR introduce a user-facing change?**:

```release-note
`hack`: correct context name in `hack/create-cluster.sh`
```

### CODE REVIEW

File: hack/create-cluster.sh [hunk 1]
```diff
@@ -79,7 +79,13 @@ cp -rf "${REPO_ROOT}"/artifacts/kindClusterConfig/general-config.yaml "${TEMP_PA
 sed -i'' -e "s#{{pod_cidr}}#${POD_CIDR}#g" "${TEMP_PATH}"/"${CLUSTER_NAME}"-config.yaml
 sed -i'' -e "s#{{service_cidr}}#${SERVICE_CIDR}#g" "${TEMP_PATH}"/"${CLUSTER_NAME}"-config.yaml
 
-kind create cluster --name "${CLUSTER_NAME}" --kubeconfig="${KUBECONFIG}" --image="${CLUSTER_VERSION}" --config="${TEMP_PATH}"/"${CLUSTER_NAME}"-config.yaml
+kind_log="$(mktemp --suffix=-kind.log)"
+echo "Creating cluster \"${CLUSTER_NAME}\" ..."
+kind create cluster --name "${CLUSTER_NAME}" --kubeconfig="${KUBECONFIG}" --image="${CLUSTER_VERSION}" --config="${TEMP_PATH}"/"${CLUSTER_NAME}"-config.yaml > ${kind_log} 2>&1 || (
+  echo "Creating cluster ${CLUSTER_NAME} failed, see detail log in ${kind_log}."
```
Comment (RainbowMango) [inline hack/create-cluster.sh:85]: I love this, so nice!

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
