### PR TITLE
fix: ensure APIEnablement plugin never deletes scheduled resources

### LINKED ISSUE #6461: For the scheduler APIEnablement plugin, scheduled resources are never deleted under any situation
**What would you like to be added**:

For the scheduler `APIEnablement` plugin, scheduled resources are never deleted under any situation.

**Why is this needed**:

The current logic of the `APIEnablement` plugin is that when the cluster API list is trusted, if the GVK (Group, Version, Kind) of a resource is not in the API list, the cluster will be filtered out. If the previous scheduling result included this cluster, the target resource in the cluster will be deleted.

This handling logic may not be suitable in the following scenario: A user maintains a CRD (Custom Resource Definition) resource in a member cluster and then propagates the CR (Custom Resource) of that CRD through the Karmada control plane. If the user accidentally deletes the CRD resource in the cluster and triggers the scheduler to reschedule the CR resource, even if the user reinstall the CRD resource in the member cluster, the CR resource will not be able to be recreated in the member cluster.

Therefore, to make the user's resources more stable, we can modify the logic of the `APIEnablement` plugin so that it never deletes scheduled resources under any circumstances.

### PR DESCRIPTION
**Pull request by abhinav-1305**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Modifies the `APIEnablement` plugin to never delete scheduled resources, even if their API (CRD) is temporarily unavailable. This prevents resource deletion when users accidentally delete and reinstall CRDs in member clusters.

**Which issue(s) this PR fixes**:
Fixes #6461 

**Special notes for your reviewer**: NA

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by abhinav-1305** [comment]
Hi @kevin-wangzefeng - messed up the PR a bit ;/ , could use your help with the DCO sign-off. Let me know if it all looks good overall. Thanks!

**Comment by XiShanYongYe-Chang** [comment]
Hi @abhinav-1305, thanks for your contribution.

The behavior state in #6461 affects user behavior, so it  still needs some feedback from the end users.

Besides, you can sign off refer to https://github.com/karmada-io/karmada/pull/6462/checks?check_run_id=44175872796

**Comment by XiShanYongYe-Chang** [comment]
Hi @abhinav-1305 it seems that this pr containts the other commits, can you help remove them? then we can continue this pr.

**Comment by abhinav-1305** [comment]
Hi @XiShanYongYe-Chang , those commits have already been removed from this PR. or should I open a new PR if that works for you?

**Comment by RainbowMango** [comment]
Maybe don't have to open another PR, just squash and rebase this would be ok.
https://karmada.io/docs/contributor/github-workflow/#squash-commits

**Comment by XiShanYongYe-Chang** [comment]
Hi @abhinav-1305 are you still working on the pr?

I'm not trying to rush you, just checking if you need any help with anything.

**Comment by abhinav-1305** [comment]
Hi @XiShanYongYe-Chang - Yes, I’m still working on this. Let me know if you’re okay with the current implementation or if there’s anything you’d like me to adjust.

**Comment by XiShanYongYe-Chang** [comment]
Hi @abhinav-1305, thanks~

Can you help squash the commits into one?

**Comment by abhinav-1305** [comment]
Hi @XiShanYongYe-Chang, I’ve squashed the commits as asked. Please review.

**Comment by XiShanYongYe-Chang** [comment]
Thanks @abhinav-1305 
/assign

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~ 
/lgtm

Ask some double check from @whitewindmills @RainbowMango 
/cc @whitewindmills @RainbowMango

File: pkg/scheduler/framework/plugins/apienablement/api_enablement.go [hunk 1]
```diff
@@ -55,15 +54,14 @@ func (p *APIEnablement) Filter(
 	_ *workv1alpha2.ResourceBindingStatus,
 	cluster *clusterv1alpha1.Cluster,
 ) *framework.Result {
-	if helper.IsAPIEnabled(cluster.Status.APIEnablements, bindingSpec.Resource.APIVersion, bindingSpec.Resource.Kind) {
+	// If the cluster is already in the target list, always allow it to pass
+	// This ensures we never delete scheduled resources
```
Comment (RainbowMango) [inline pkg/scheduler/framework/plugins/apienablement/api_enablement.go]:
```suggestion
	// If the cluster is already in the target list, always allow it to pass
	// This ensures we never delete scheduled resources.
	// In case of the corresponding APIs(CRDs) are accidentally deleted from member cluster, Karmada 
	// controllers will try recreating these resources once the API becomes available again.
```

File: pkg/scheduler/framework/plugins/apienablement/api_enablement.go [hunk 2]
```diff
@@ -55,15 +54,14 @@ func (p *APIEnablement) Filter(
...
+	if bindingSpec.TargetContains(cluster.Name) {
 		return framework.NewResult(framework.Success)
 	}
 
-	// Let the cluster pass if it is already on the list of schedule result and the cluster's
-	// API enablements is incomplete, to avoid the issue that cluster be accidentally removed
-	// due to untrusted API enablements.
-	if bindingSpec.TargetContains(cluster.Name) &&
-		!meta.IsStatusConditionTrue(cluster.Status.Conditions, clusterv1alpha1.ClusterConditionCompleteAPIEnablements) {
+	// For new scheduling decisions, check if the API is enabled
```
Comment (RainbowMango) [inline pkg/scheduler/framework/plugins/apienablement/api_enablement.go]:
```suggestion
	// For new scheduling decisions, check if the API is enabled to ensure the application
	// is deployed to a cluster that supports all required APIs.
	// Note: Although controllers may not always retrieve the complete API list,
	// we enforce strict checks to maintain consistency. This may occasionally
	// exclude clusters prematurely. Users requiring a specific number of target
	// clusters should use SpreadConstraints(in PropagationPolicy) to meet their requirements.
```

**Comment by XiShanYongYe-Chang** [comment]
Hi @abhinav-1305 sorry I missed this task, there are still some issues with the imports in lint. Can you help fix it? When pushing again, you can merge the PR into one commit. Thanks~

**Comment by abhinav-1305** [comment]
> Hi @abhinav-1305 sorry I missed this task, there are still some issues with the imports in lint. Can you help fix it? When pushing again, you can merge the PR into one commit. Thanks~

done, please review - @XiShanYongYe-Chang

File: pkg/scheduler/framework/plugins/apienablement/api_enablement.go (hunk 1 above)
Comment (XiShanYongYe-Chang) [reply pkg/scheduler/framework/plugins/apienablement/api_enablement.go]: The suggested logs do not seem to have been added all.

File: pkg/scheduler/framework/plugins/apienablement/api_enablement.go (hunk 2 above)
Comment (XiShanYongYe-Chang) [reply pkg/scheduler/framework/plugins/apienablement/api_enablement.go]: The suggested logs do not seem to have been added all.

File: pkg/scheduler/framework/plugins/apienablement/api_enablement.go (hunk 1 above)
Comment (RainbowMango) [reply pkg/scheduler/framework/plugins/apienablement/api_enablement.go]: I guess it might be removed accidentally during the squashing.
I can help to push again

File: pkg/scheduler/framework/plugins/apienablement/api_enablement.go [hunk 3]
```diff
@@ -55,15 +54,21 @@ func (p *APIEnablement) Filter(
...
-	// API enablements is incomplete, to avoid the issue that cluster be accidentally removed
-	// due to untrusted API enablements.
-	if bindingSpec.TargetContains(cluster.Name) &&
-		!meta.IsStatusConditionTrue(cluster.Status.Conditions, clusterv1alpha1.ClusterConditionCompleteAPIEnablements) {
+	// For new scheduling decisions, check if the API is enabled to ensure the application
+	// is deployed to a cluster that supports all required APIs.
+	// Note: Although controllers may not always get the complete API list,
+	// we enforce strict checks to maintain consistency. This may occasionally
+	// exclude clusters prematurely. Users requiring a specific number of target
+	// clusters should use SpreadConstraints(in PropagationPolicy) to meet their requirements.
```
[the remark this answers is not in the document]
Comment (RainbowMango) [reply pkg/scheduler/framework/plugins/apienablement/api_enablement.go:70]: -1
a little bit too verbose.

File: pkg/scheduler/framework/plugins/apienablement/api_enablement.go (hunk 1 above)
Comment (RainbowMango) [reply pkg/scheduler/framework/plugins/apienablement/api_enablement.go]: Done

**Comment by RainbowMango** [comment]
/remove-kind bug
/kind cleanup

@XiShanYongYe-Chang Please take another look, thanks.

**Comment by XiShanYongYe-Chang** [comment]
All seems great, thanks~ @abhinav-1305 @RainbowMango 
/lgtm
/approve
