### PR TITLE
Remove work label on the member cluster resource

### LINKED ISSUE #4683: Failed to create or update resource longer than 63 chars
**What happened**:

we have a role called `kube-system/compute-controller-manager-leader-election-rolebinding`, given that karmada adds it in the label, it cannot be longer than 63 characters
```
4m55s       Warning   SyncFailed               rolebinding/compute-controller-manager-leader-election-rolebinding   Failed to create or update resource(kube-system/compute-controller-manager-leader-election-rolebinding) in member cluster(eks-sandbox): RoleBinding.rbac.authorization.k8s.io "compute-controller-manager-leader-election-rolebinding" is invalid: metadata.labels: Invalid value: "compute-controller-manager-leader-election-rolebinding-9d54c6969": must be no more than 63 characters
```

**What you expected to happen**:
I would have expected to only use annotations, but not sure what should happent to the label

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a role or rolebinding called `compute-controller-manager-leader-election-rolebinding`
2. Create a PropagationPolicy for it
3. Observe event failures / no resourcebinding getting created

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.9.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Karmada will generate the work namespace/name labels on the resources propagated to member clusters:

- work.karmada.io/namespace
- work.karmada.io/name

When the created resource name is longer than 63 characters, those labels will cause the resource to fail to be created successfully in the member cluster.

So we need to remove those labels from resources propagated to member clusters.

**Which issue(s) this PR fixes**:
Fixes #4683 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmada-controller-manager: remove the work namespace/name labels from resources propagated to member clusters
```

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by a7i** [comment]
Thank you @XiShanYongYe-Chang 🏆 
We'll give this a try over the next day or two

**Comment by XiShanYongYe-Chang** [comment]
> We'll give this a try over the next day or two

Looking forward to your feedback :)

File: pkg/controllers/status/work_status_controller.go [hunk 1]
```diff
@@ -165,8 +166,8 @@ func generateKey(obj interface{}) (util.QueueKey, error) {
 
 // getClusterNameFromLabel gets cluster name from ownerLabel, if label not exist, means resource is not created by karmada.
 func getClusterNameFromLabel(resource *unstructured.Unstructured) (string, error) {
```
Comment (yizhang-zen) [inline pkg/controllers/status/work_status_controller.go:168]: Should rename to getClusterNameFromAnnotation? i am just nitpicking...

**Comment by yizhang-zen** [comment]
Confirm the change fixes our issue on sync failure for resource name > 63 chars. Thanks, team! ❤️

File: pkg/controllers/status/work_status_controller.go (hunk 1 above)
Comment (XiShanYongYe-Chang) [reply pkg/controllers/status/work_status_controller.go:168]: Nice finding! Would you be willing to submit a pr to update it?

Comment (XiShanYongYe-Chang) [reply pkg/controllers/status/work_status_controller.go:168]: Kindly ping @yizhang-zen

Comment (yizhang-zen) [reply pkg/controllers/status/work_status_controller.go:168]: https://github.com/karmada-io/karmada/pull/4800
