### PR TITLE
escape the dot and colon characters when convert the lua result

### LINKED ISSUE #6747: SyncWorkFailed: [convert empty object back to empty slice failed: sjson set empty slice to empty struct failed: cannot set array element for non-numeric key 'f:mountPath', ...]
**What happened**:
I'm trying to dispatch ReplicaSet by Karmada, some error events exist, like below.
Image

But the workloads can be dispatched successfully although the error events exist. It looks like it has something to do with the `.metadata.managedFields` field.

**What you expected to happen**:
No error events take place.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.14.4
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Ref to https://github.com/karmada-io/karmada/issues/6747#issuecomment-3283308945, we should escape the dot and colon characters when convert the lua result.

**Which issue(s) this PR fixes**:

Fixes #6747

**Special notes for your reviewer**:

We should backport this to release1.13, release1.14 and release1.15.

**Does this PR introduce a user-facing change?**:

```release-note
`ResourceInterpreter`: Fixed the issue that when an object API field name contains dots or colons, it would cause the resource interpreter to fail.
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
cc @ryanwuer

**Comment by ryanwuer** [comment]
waiting for this PR to be merged and a new release

**Comment by zhzhuang-zju** [comment]
> waiting for this PR to be merged and a new release

@ryanwuer According to the [Karmada release cycle](https://karmada.io/docs/releases#release-timeline), the karmada patch release will be published at the end of this month and should include this fix.

**Review by RainbowMango — COMMENTED** [review]
/assign

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 1]
```diff
@@ -181,6 +181,16 @@ func traverseToFindEmptyField(root gjson.Result, fieldPath []string) (sets.Set[s
 	return fieldOfEmptySlice, fieldOfEmptyStruct
 }
 
+// escapeJSONPathKey escape the special character in json key, like '.'、':'.
+// sjson package use '.' and '.:' to split the json path, so if a json key contains these characters,
+// we need to escape them by '\' first.
+// More details can refer to https://pkg.go.dev/github.com/tidwall/sjson#readme-path-syntax.
+func escapeJSONPathKey(field string) string {
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go]:
```suggestion
func escapeSJSONPath(field string) string {
```

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 2]
```diff
@@ -181,6 +181,16 @@ func traverseToFindEmptyField(root gjson.Result, fieldPath []string) (sets.Set[s
 	return fieldOfEmptySlice, fieldOfEmptyStruct
 }
 
+// escapeJSONPathKey escape the special character in json key, like '.'、':'.
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go]:
```suggestion
// escapeJSONPathKey escape the special character in json key, like '.', ':'.
```

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go [hunk 3]
```diff
@@ -181,6 +181,16 @@ func traverseToFindEmptyField(root gjson.Result, fieldPath []string) (sets.Set[s
 	return fieldOfEmptySlice, fieldOfEmptyStruct
 }
 
+// escapeJSONPathDotAndColon escape the dot and colon characters in json path key.
+// sjson package use '.' and '.:' to split the json path, so if a json key contains these characters,
+// we need to escape them by '\' first.
+// More details can refer to https://pkg.go.dev/github.com/tidwall/sjson#readme-path-syntax.
+func escapeJSONPathDotAndColon(field string) string {
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go:188]: This will do.

File: pkg/resourceinterpreter/customized/declarative/luavm/lua_convert_test.go [hunk 4]
```diff
@@ -374,6 +393,32 @@ func Test_traverseToFindEmptyFieldNeededModify(t *testing.T) {
...
+				fieldPath:               nil,
+				fieldPathWithArrayIndex: nil,
+				fieldOfEmptySlice:       sets.New[string]("spec.\\.dots"),
+				fieldOfEmptyStruct:      sets.New[string]("spec.\\:colons", "spec.\\:\\.colonAndDot", "spec.\\.\\:dotAndColon"),
+			},
+			wants: wants{
+				fieldOfEmptySliceToStruct: sets.New[string](
+					`spec.\:colons`,
+					`spec.\:\.colonAndDot`,
+					`spec.\.\:dotAndColon`,
```
[the remark this answers is not in the document]
Comment (zhzhuang-zju) [reply pkg/resourceinterpreter/customized/declarative/luavm/lua_convert_test.go:417]: `"spec.\\:colons"` and `spec.\:colons` are actually equivalent in effect, but to avoid confusion, I can standardize the format.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
