### PR TITLE
Fix issues with running multiple Karmada instances in the same namespace

### LINKED ISSUE #6179: Fix issues with running multiple Karmada instances in the same namespace
**What happened**:
When attempting to provision multiple Karmada instances in the same namespace, issues relating to client certificate verification will surface either when the operator tries to contact the new provisioned API server as it's provisioning the instance, or after the instance has reached ready state.

These issues occur because more label selectors are needed to uniquely identify the resources linked to a Karmada instance when more than one instance is deployed to the namespace.

**What you expected to happen**:
I expected to use the Karmada operator to provision multiple Karmada instances in the same namespace, but ran into issues.

**How to reproduce it (as minimally and precisely as possible)**:
Try to provision more than one Karmada instance in the same namespace.

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.13
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by jabellard**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
When attempting to provision multiple Karmada instances in the same namespace, issues relating to client certificate verification will surface either when the operator tries to contact the new provisioned API server as it's provisioning the instance (e.g., to install CRDs), or after the instance has reached ready state.

These issues occur because more label selectors are needed to uniquely identify the resources linked to a Karmada instance when more than one instance is deployed to the namespace.

### Scope of Changes
- Introduction of `app.kubernetes.io/name` and `app.kubernetes.io/instance` [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) to uniquely identify resources linked to Karmada instances.
-  `karmada-app` label => `app.kubernetes.io/name` label per [recommendations](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels).

### Results after Changes

```
mc -n karmada-system get endpoints t1-karmada-apiserver 
NAME                   ENDPOINTS          AGE
t1-karmada-apiserver   10.244.0.17:5443   87m
```

```
mc -n karmada-system get endpoints t2-karmada-apiserver 
NAME                   ENDPOINTS          AGE
t2-karmada-apiserver   10.244.0.26:5443   81m
```

```
mc get karmadas.operator.karmada.io -A
NAMESPACE        NAME   READY   AGE
karmada-system   t1     True    86m
karmada-system   t2     True    80m
```

```
t1 get crds
NAME                                                         CREATED AT
clusteroverridepolicies.policy.karmada.io                    2025-03-01T20:31:17Z
clusterpropagationpolicies.policy.karmada.io                 2025-03-01T20:31:17Z
clusterresourcebindings.work.karmada.io                      2025-03-01T20:31:18Z
...
```

```
t2 get crds 
NAME                                                         CREATED AT
clusteroverridepolicies.policy.karmada.io                    2025-03-01T20:37:50Z
clusterpropagationpolicies.policy.karmada.io                 2025-03-01T20:37:50Z
clusterresourcebindings.work.karmada.io                      2025-03-01T20:37:51Z
...
```

**Which issue(s) this PR fixes**:
Fixes #6179

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
The `karmada-app` label key previously used for control plane components and for the components of the operator itself has been changed to the more idiomatic `app.kubernetes.io/name` label key.
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
@jabellard Thanks for pointing out this issue. Currently, components under two Karmada instances share the same label, both formatted as `karmada-app:xxx`. This will cause the label selector to lose its due function within the same namespace.
Take etcd for example:
```yaml
# deployment/aggregated-apiserver.yaml
        - --etcd-servers=https://karmada-demo-1-etcd-client.test.svc.cluster.local:2379
# svc/etcd-client.yaml
  selector:
    karmada-app: etcd
```
When the component `aggregated - apiserver` connects to the etcd service, it will connect to the etcd components under multiple Karmada instances, which leads to certificate verification failure and then causes the component to restart.
```bash
W0303 02:05:45.772422       1 logging.go:55] [core] [Channel #40 SubChannel #41]grpc: addrConn.createTransport failed to connect to {Addr: "karmada-demo-1-etcd-client.test.svc.cluster.local:2379", ServerName: "karmada-demo-1-etcd-client.test.svc.cluster.local:2379", }. Err: connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is valid for *.karmada-demo-etcd.test.svc.cluster.local, karmada-demo-etcd-client.test.svc.cluster.local, localhost, not karmada-demo-1-etcd-client.test.svc.cluster.local"
```

This PR should be able to solve the above problem. Apart from this issue, have you encountered other problems when running multiple Karmada instances in the same namespace?

**Comment by jabellard** [comment]
> This PR should be able to solve the above problem. Apart from this issue, have you encountered other problems when running multiple Karmada instances in the same namespace?

All the issues should now be resolved. Please refer to this [section in the PR description](https://github.com/karmada-io/karmada/pull/6180#:~:text=Results%20after%20Changes) to see some E2E test  results.

**Comment by zhzhuang-zju** [comment]
> All the issues should now be resolved. Please refer to this https://github.com/karmada-io/karmada/pull/6180#:~:text=Results%20after%20Changes to see some E2E test results.

Get it. Currently, the operator e2e tests do not cover the scenario of deploying multiple Karmada instances in the same namespace. We can wait for this PR to be merged and then supplement the tests.

**Comment by zhzhuang-zju** [comment]
/lgtm
This is the first attempt of the karmada-operator to install multiple instances in the same namespace. Currently, I haven't found any other blocking points, and this PR is already sufficient to address the issues that occurred during the installation. It can be merged first.

Do we need to add a release note? Since the label has been changed, it may have an impact on the users' business.

**Comment by jabellard** [comment]
> /lgtm This is the first attempt of the karmada-operator to install multiple instances in the same namespace. Currently, I haven't found any other blocking points, and this PR is already sufficient to address the issues that occurred during the installation. It can be merged first.
> 
> Do we need to add a release note? Since the label has been changed, it may have an impact on the users' business.

That's a good point. I just added a note for that. @RainbowMango , any comments before we can move forward with merging this?

**Review by RainbowMango — COMMENTED** [review]
/assign

File: operator/pkg/controlplane/apiserver/manifests.go [hunk 1]
```diff
@@ -131,29 +138,33 @@ spec:
...
     targetPort: 5443
   selector:
-    karmada-app: karmada-apiserver
+    app.kubernetes.io/name: karmada-apiserver
+    app.kubernetes.io/instance: {{ .KarmadaInstanceName }}
   type: {{ .ServiceType }}
 `
 
-	// KarmadaAggregatedAPIServerDeployment is karmada aggreagated apiserver deployment manifest
+	// KarmadaAggregatedAPIServerDeployment is karmada aggregated apiserver deployment manifest
```
Comment (RainbowMango) [inline operator/pkg/controlplane/apiserver/manifests.go:146]: nice catch!

File: operator/pkg/controlplane/manifests.go [hunk 2]
```diff
@@ -17,76 +17,84 @@ limitations under the License.
 package controlplane
 
 const (
-	// KubeControllerManagerDeployment is KubeControllerManage deployment manifest
+	// KubeControllerManagerDeployment is KubeControllerManager deployment manifest
```
Comment (RainbowMango) [inline operator/pkg/controlplane/manifests.go:20]: NICE!

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
Do we need to backport this patch to the previous release?

**Comment by RainbowMango** [comment]
OK Joe, would you like to do the backport thing? Here is the guideline of how to cherry-pick: https://karmada.io/docs/next/contributor/cherry-picks/

**Comment by jabellard** [comment]
> OK Joe, would you like to do the backport thing? Here is the guideline of how to cherry-pick: https://karmada.io/docs/next/contributor/cherry-picks/

Just submitted a [PR](https://github.com/karmada-io/karmada/pull/6200) for that.
