### PR TITLE
fix that multiple same spread constraints are allowed

### LINKED ISSUE #3356: Multiple same spread constraints are allowed
**What happened**:
multiple same spread constraints are allowed
**What you expected to happen**:
multiple same spread constraints are not allowed
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Multiple same spread constraints should not be allowed.
**Which issue(s) this PR fixes**:
Fixes #3356

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/assign @jwcesign

File: pkg/util/validation/validation.go [hunk 1]
```diff
@@ -118,15 +118,22 @@ func ValidateSpreadConstraint(spreadConstraints []policyv1alpha1.SpreadConstrain
 		}
 
 		if len(constraint.SpreadByField) > 0 {
-			spreadByFields.Insert(string(constraint.SpreadByField))
+			marked := spreadByFieldsWithErrorMark[constraint.SpreadByField]
```
Comment (jwcesign) [inline pkg/util/validation/validation.go:121]: How about writing the code like this below?
```go
	spreadByFieldsWithErrorMark := make(map[policyv1alpha1.SpreadFieldValue]struct{})
        ...
	if len(constraint.SpreadByField) > 0 {
		_, marked := spreadByFieldsWithErrorMark[constraint.SpreadByField]
		if marked {
			allErrs = append(allErrs, field.Invalid(fldPath, spreadConstraints, fmt.Sprintf("multiple %s spread constraints are not allowed", constraint.SpreadByField)))
			continue
		}
		spreadByFieldsWithErrorMark[constraint.SpreadByField] = struct{}{}
	}
```

Comment (whitewindmills) [reply pkg/util/validation/validation.go:121]: There will be nine duplicated region errors if ten region spread constraints exist.

**Comment by jwcesign** [comment]
/lgtm

cc @RainbowMango for checking

**Review by RainbowMango — APPROVED** [review]
/approve
/remove-kind bug
/kind cleanup
