### PR TITLE
fix unexpected interference between different e2e use cases

### LINKED ISSUE #5256: flake test: the resource selector  scope of some Policies in E2E use case is too large to affect other use cases.
**What happened**:

The resource selector  scope of some Policies in E2E use case is too large to affect other use cases.

take below case as an example:

https://github.com/karmada-io/karmada/blob/1430ecbd2eb7e8321724ed9b6b08436b9b0b051f/test/e2e/propagationpolicy_test.go#L558-L568

this policy matches all deployment, however, e2e use cases are running in parallel, it may be result in other case failure.

**What you expected to happen**:

e2e use cases do not affect each other

**How to reproduce it (as minimally and precisely as possible)**:

I will list relevant failures in the comments below

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

The scope of some Policy's resourceSelector in E2E use case is too large to affect other use cases.

detail refer to #5256

**Which issue(s) this PR fixes**:

Fixes #5256

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
A little more background on the problem?

**Comment by chaosi-zju** [comment]
> A little more background on the problem?

yes, I will add a issue to describe it~

File: test/e2e/propagationpolicy_test.go [hunk 1]
```diff
@@ -538,6 +538,7 @@ var _ = ginkgo.Describe("[ImplicitPriority] propagation testing", func() {
 					APIVersion: deployment.APIVersion,
 					Kind:       deployment.Kind,
 					Name:       deployment.Name,
+					Namespace:  deployment.Namespace,
```
Comment (zhzhuang-zju) [inline test/e2e/propagationpolicy_test.go:541]: In fact, there's no need to change it here, because the namespace of the deployment is by default the same as the one of the pp

**Comment by zhzhuang-zju** [comment]
/lgtm
thanks~

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/approve
