### PR TITLE
[ut] improve download from httptest

### LINKED ISSUE #2671: go test doesn't successfully on Goland
**What happened**:
When I run `go test` the `pkg/karmadactl/cmdinit/utils/util_test.go` on Goland,
image

In the console shows `Process finished with the exit code 0`, while Goland don't display the test tree green.
image

**What you expected to happen**:
Test case shall be green in Goland window
image

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others: `go version go1.18.3 darwin/arm64`  
image

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
`TestDownloadFile` no longer depend on internet.
Also fixes #2671.

**Which issue(s) this PR fixes**:
Fixes #2671

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/karmadactl/cmdinit/utils/util.go [hunk 1]
```diff
@@ -18,13 +18,20 @@ type Downloader struct {
...
+var isTesting = false
+
 // Read Implementation of Downloader
 func (d *Downloader) Read(p []byte) (n int, err error) {
 	n, err = d.Reader.Read(p)
 	d.Current += int64(n)
-	fmt.Printf("\rDownloading...[ %.2f%% ]", float64(d.Current*10000/d.Total)/100)
-	if d.Current == d.Total {
-		fmt.Printf("\nDownload complete.")
+	if !isTesting {
```
Comment (RainbowMango) [inline pkg/karmadactl/cmdinit/utils/util.go:28]: Why don't we just make the change as shown in https://github.com/karmada-io/karmada/issues/2671#issuecomment-1287828359?

I suppose the real code should not involve testing logic.

**Review by RainbowMango — COMMENTED** [review]
I see a binary file `pkg/karmadactl/cmdinit/utils/testdata/test.tar.gz` is included in this patch,
is it a mistake?

File: pkg/karmadactl/cmdinit/utils/util.go (hunk 1 above)
Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:28]: I don't known what the affect of this change. So I keep the origin format.

**Comment by ikaven1024** [comment]
> I see a binary file `pkg/karmadactl/cmdinit/utils/testdata/test.tar.gz` is included in this patch,

These file is embed, and test will download this file. So we don't need a real crd tar from internel.
https://github.com/karmada-io/karmada/blob/5a01019f360bcab5ae420c7e1cba06b9b17dba53/pkg/karmadactl/cmdinit/utils/util_test.go#L15-L16

File: pkg/karmadactl/cmdinit/utils/util.go (hunk 1 above)
Comment (RainbowMango) [reply pkg/karmadactl/cmdinit/utils/util.go:28]: It should be OK. the only effect I can imagine is the output messages might add an additional `blank` line(`\n`).

Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:28]:
```go
func main() {
	fmt.Printf("\rDownloading...[ %.2f%% ]", 90.0)
	fmt.Printf("\rDownloading...[ %.2f%% ]", 95.0)
	fmt.Printf("\rDownloading...[ %.2f%% ]", 100.0)
	fmt.Printf("\nDownload complete.")
}
```
Output:
```
Downloading...[ 100.00% ]
Download complete.
```

```go
func main() {
	fmt.Printf("\rDownloading...[ %.2f%% ]\n", 90.0)
	fmt.Printf("\rDownloading...[ %.2f%% ]\n", 95.0)
	fmt.Printf("\rDownloading...[ %.2f%% ]\n", 100.0)
	fmt.Printf("Download complete.\n")
}
```

Output:
```
Downloading...[ 90.00% ]
Downloading...[ 95.00% ]
Downloading...[ 100.00% ]
Download complete.
```

Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:28]: These are different. In origin code the `Downloading ...` log will cover the previous.

File: pkg/karmadactl/cmdinit/utils/util_test.go [hunk 2]
```diff
@@ -1,26 +1,63 @@
...
 
+// This file is created by:
+// mkdir -p testdata; cd testdata; echo test > test.txt; tar czf test.tar.gz test.txt; rm -f test.txt
+//go:embed testdata/test.tar.gz
+var testTarData []byte
+
 const (
-	filePath = "./crds.tar.gz"
-	folder   = "./crds"
+	testTar  = "test.tar.gz"
```
Comment (jwcesign) [inline pkg/karmadactl/cmdinit/utils/util_test.go:19]: I see the tar file is quite simple, can we just create it in the start of testing code and delete it after finish?

Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util_test.go]: done

File: pkg/karmadactl/cmdinit/utils/util.go (hunk 1 above)
Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go]: @RainbowMango , I have remove the `isTesting` flag. Instead add a `io.Writer` output, and print the log to it. In tests, output is assigned `ioutil.Discard`, and will not print the log.

---
I test this code before change, and output:
```
I1026 14:28:17.690860   50020 deploy.go:269] download crds file:https://github.com/karmada-io/karmada/releases/download/v1.3.0/crds.tar.gz
Downloading...[ 100.00% ]
Downloading...[ 100.00% ]
Download complete.e
```

after change:
```
I1026 14:31:01.082274   50274 deploy.go:269] download crds file:https://github.com/karmada-io/karmada/releases/download/v1.3.0/crds.tar.gz
Downloading...[ 100.00% ]
Downloading...[ 100.00% ]
Download complete.
```

These outputs is same.

File: pkg/karmadactl/cmdinit/utils/util_test.go [hunk 3]
```diff
@@ -1,26 +1,112 @@
...
+			t.Fatal(err)
+		}
+		return buf
+	}()
+
+	s := httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
+		if _, err := io.Copy(rw, serverTar); err != nil {
+			t.Fatal(err)
+		}
+	}))
```
Comment (RainbowMango) [inline pkg/karmadactl/cmdinit/utils/util_test.go:83]: It's a good idea that uses a fake file server.

File: pkg/karmadactl/cmdinit/utils/util_test.go [hunk 4]
```diff
@@ -1,26 +1,112 @@
...
+		}
+		defer func() {
+			_ = os.RemoveAll(tmpDir)
+		}()
+
+		// prepare test file
+		file := filepath.Join(tmpDir, testFileName)
+		if err = ioutil.WriteFile(file, testFileContent, 0600); err != nil {
+			t.Fatal(err)
+		}
```
Comment (RainbowMango) [inline pkg/karmadactl/cmdinit/utils/util_test.go:39]: Maybe we don't need really create the file, we can just create a tarball, here is an example:
https://github.com/golang/go/blob/939f9fd64a740ef770a0ca3588f8c193dceebe83/src/archive/tar/example_test.go#L19

Then, I guess we can remove the `nolint:gocyclo` then.

Comment (RainbowMango) [reply pkg/karmadactl/cmdinit/utils/util_test.go:39]: Just a reminder, the `ioutil.WriteFile` has been deprecated.

File: pkg/karmadactl/cmdinit/utils/util.go [hunk 5]
```diff
@@ -18,13 +18,15 @@ type Downloader struct {
...
+var output io.Writer = os.Stdout
+
 // Read Implementation of Downloader
 func (d *Downloader) Read(p []byte) (n int, err error) {
 	n, err = d.Reader.Read(p)
 	d.Current += int64(n)
-	fmt.Printf("\rDownloading...[ %.2f%% ]", float64(d.Current*10000/d.Total)/100)
+	fmt.Fprintf(output, "\rDownloading...[ %.2f%% ]", float64(d.Current*10000/d.Total)/100)
 	if d.Current == d.Total {
-		fmt.Printf("\nDownload complete.")
```
Comment (RainbowMango) [inline pkg/karmadactl/cmdinit/utils/util.go:27]: What if we just add a `\n` at the end? I'm curious about what would happen.

File: pkg/karmadactl/cmdinit/utils/util_test.go (hunk 4 above)
Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util_test.go:39]: Thanks, I will try it.

File: pkg/karmadactl/cmdinit/utils/util.go (hunk 5 above)
Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:27]: I also think it need a `\n` at the end. @prodanlabs  may explain it.

Comment (RainbowMango) [reply pkg/karmadactl/cmdinit/utils/util.go:27]: This is probably the minimum fix.

The `fsprint` is pretty annoying because some static check tools would raise a warning about unchecked return value...

Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:27]: First, we can't append `\n` to `Downloading...[ %.2f%% ]`, otherwise it will print
```
Downloading...[ 1.00% ]
Downloading...[ 2.00% ]
Downloading...[ 3.00% ]
...
```

While we expect these logs are print in one line. e.g:
```
Downloading...[ 100.00% ]
```

Then, `\nDownload complete.` I think we shall append to it. Leave it to another PR after @prodanlabs affirm.

Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:27]: Will you accept it, @RainbowMango ?

Comment (RainbowMango) [reply pkg/karmadactl/cmdinit/utils/util.go:27]: I'll get back to you after I try it.

Comment (RainbowMango) [reply pkg/karmadactl/cmdinit/utils/util.go:27]: I tried this, and looks fine:
```golang
// Read Implementation of Downloader
func (d *Downloader) Read(p []byte) (n int, err error) {
	n, err = d.Reader.Read(p)
	if err != nil {
		if err == io.EOF {
			return
		}
	}

	d.Current += int64(n)
	fmt.Printf("\rDownloading...[ %.2f%% ]", float64(d.Current*10000/d.Total)/100)
	if d.Current == d.Total {
		println("Download complete.")
	}
	return
}
```

The output:
```bash
Downloading...[ 100.00% ]Download complete.
```

Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:27]:
```go
		if err == io.EOF {  // mistake? shall be err != io.EOF
			return
		}
```

Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:27]:
```go
	fmt.Printf("\rDownloading...[ %.2f%% ]", float64(d.Current*10000/d.Total)/100)
	if d.Current == d.Total {
		fmt.Println("\nDownload complete.")
	}
```

Output:
```
Downloading...[ 100.00% ]
Download complete.
```

Test in Goland, and work well.

**Comment by RainbowMango** [comment]
@ikaven1024 I run it on my side. 
```
-bash-4.2# ./_output/bin/linux/amd64/karmadactl init
I1027 17:58:29.167512 3564283 deploy.go:154] kubeconfig file: /root/.kube/horen.config, kubernetes: https://127.0.0.1:43369
...
I1027 17:58:31.418472 3564283 deploy.go:267] download crds file:https://github.com/karmada-io/karmada/releases/download/v1.3.0/crds.tar.gz
Downloading...[ 100.00% ]
Download complete.
Downloading...[ 100.00% ]
Download complete.
I1027 17:58:32.362271 3564283 deploy.go:503] Create karmada kubeconfig success.

```

File: pkg/karmadactl/cmdinit/utils/util.go (hunk 5 above)
Comment (RainbowMango) [reply pkg/karmadactl/cmdinit/utils/util.go:27]: > // mistake? shall be err != io.EOF

Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:27]: It's strange. When I use `err == io.EOF`, testing will not print the download info.

```
=== RUN   TestDownloadFile
--- PASS: TestDownloadFile (0.01s)
PASS
```

After change to `err != io.EOF`, download info appears:

```
=== RUN   TestDownloadFile
Downloading...[ 100.00% ]
Download complete.
--- PASS: TestDownloadFile (0.01s)
PASS
```

Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util.go:27]: I change it to
https://github.com/karmada-io/karmada/blob/7315de1c5e890525bf330fc0e2f8d68346a45542/pkg/karmadactl/cmdinit/utils/util.go#L22-L36

karmadactl init output:
```
I1027 19:08:36.240173   14705 deploy.go:270] download crds file:https://github.com/karmada-io/karmada/releases/download/v1.3.0/crds.tar.gz
Download complete.     
```

go test output:
```
=== RUN   TestDownloadFile
Download complete.       
--- PASS: TestDownloadFile (0.02s)
PASS
```

File: pkg/karmadactl/cmdinit/utils/util.go [hunk 6]
```diff
@@ -21,11 +21,17 @@ type Downloader struct {
 // Read Implementation of Downloader
 func (d *Downloader) Read(p []byte) (n int, err error) {
 	n, err = d.Reader.Read(p)
+	if err != nil {
+		if err != io.EOF {
+			return
+		}
+		// The width of the log shall not less than `Downloading...[ %.2f%% ]`
+		fmt.Println("\rDownload complete.       ")
```
Comment (RainbowMango) [inline pkg/karmadactl/cmdinit/utils/util.go:29]: :) 

It'd be nice to keep it simple, like:
```suggestion
		fmt.Println("\nDownload complete.")
```

File: pkg/karmadactl/cmdinit/utils/util_test.go [hunk 7]
```diff
@@ -1,26 +1,82 @@
...
+	}
+	err = DeCompress(downloadTar, tmpDir)
+	if err != nil {
+		t.Fatal(err)
+	}
 
-	url := "https://github.com/karmada-io/karmada/releases/download/v0.9.0/crds.tar.gz"
-	if err := DownloadFile(url, filePath); err != nil {
-		panic(err)
+	got, err := ioutil.ReadFile(filepath.Join(tmpDir, testFileName))
```
Comment (RainbowMango) [inline pkg/karmadactl/cmdinit/utils/util_test.go:74]:
```suggestion
	got, err := os.ReadFile(filepath.Join(tmpDir, testFileName))
```

**Review by RainbowMango — COMMENTED** [review]
Just one nit.

File: pkg/karmadactl/cmdinit/utils/util_test.go (hunk 7 above)
Comment (ikaven1024) [reply pkg/karmadactl/cmdinit/utils/util_test.go]: I update to go 1.9, and see the deprecated info, :)

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
