### PR TITLE
fix rebalancer auto deleted failed

### LINKED ISSUE #5985: WorkloadRebalancer doesn't get deleted after TTL.
**What happened**:
A WorkloadRebalancer created with a TTL(Time To Live) field in the spec is not getting deleted after TTL has reached.

**What you expected to happen**:
WorkloadRebalancer should get deleted after TTL.

**How to reproduce it (as minimally and precisely as possible)**:
Create a workloadRebalancer with .spec.ttlSecondsAfterFinished . Verify that it is not deleted after TTL has been passed.

**Anything else we need to know?**:
NA

**Possible Cause**:
I debugged this and found few issues with the code of the [workloadrebalancer_controller.go](https://github.com/karmada-io/karmada/blob/master/pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go) file.

- The controller reconciles when the workloadrebalancer is created or the spec changes. [See here](https://github.com/karmada-io/karmada/blob/8fa7c2cc7df1a8d4061f6cfea035cb0625694605/pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go#L59). 
- We are checking for the **rebalance.Status.FinishTime == nil** before setting the rebalancer.Status = *newStatus [here](https://github.com/karmada-io/karmada/blob/8fa7c2cc7df1a8d4061f6cfea035cb0625694605/pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go#L93). So, line 93 always evaluates to true and it never reconciles again and the workload rebalancer doesn't get deleted.

**Environment**:
- Karmada version: 1.11
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix rebalancer auto deleted failed

**Which issue(s) this PR fixes**:

Fixes #5985

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed the bug of WorkloadRebalancer doesn't get deleted after TTL.
```

### CODE REVIEW

File: pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go [hunk 1]
```diff
@@ -90,7 +90,7 @@ func (c *RebalancerController) Reconcile(ctx context.Context, req controllerrunt
 		return controllerruntime.Result{}, err
 	}
 
-	if rebalancer.Status.FinishTime == nil {
+	if newStatus.FinishTime == nil {
 		// should never reach here.
```
Comment (RainbowMango) [inline pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go:94]: My question is why we need to keep this check since it `should never reach here`?

**Review by RainbowMango — COMMENTED** [review]
/assign

File: pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go (hunk 1 above)
Comment (RainbowMango) [reply pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go:94]: It would be better to move this where referencing the `FinishTime`.

File: pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go [hunk 2]
```diff
@@ -90,15 +90,12 @@ func (c *RebalancerController) Reconcile(ctx context.Context, req controllerrunt
...
-		// should never reach here.
-		klog.Errorf("finishTime shouldn't be nil, current status: %+v", rebalancer.Status)
-		return controllerruntime.Result{}, nil
-	}
-
 	// 3. when all workloads finished, judge whether the rebalancer needs cleanup.
 	rebalancer.Status = *newStatus
 	if rebalancer.Spec.TTLSecondsAfterFinished != nil {
+		if rebalancer.Status.FinishTime == nil {
+			return controllerruntime.Result{}, fmt.Errorf("finishTime shouldn't be nil, current status: %+v", rebalancer.Status)
```
Comment (RainbowMango) [inline pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go:97]: Looks better now.
But we should not dump so many status.
```suggestion
			return controllerruntime.Result{}, fmt.Errorf("finish time should not be nil")
```

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
