### PR TITLE
fix(util/proxy): fix tls.config when secret.spec.caBundle is nil

### LINKED ISSUE #4370: insecureSkipTLSVerification is true,but  cluster.spec.secret.caBundle must be set, it's unexpected
**What happened**:
Use karmadactl get pods, Print error `cluster(xxx) is inaccessible, please check authorization or network`, I check karmada-aggregated-apiserver log:
image

It seems that if caBundle not set,   karmadactl get pods must be failed
image

**What you expected to happen**:
if insecureSkipTLSVerification = true, command line `karmadactl get pods`   should be executed successfully
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.8.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by CharlesQQ**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #4370 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```
`karmadactl`: Fixed return err in case of  secret.spec. caBundle is nil
```

### CODE REVIEW

File: pkg/util/proxy/proxy.go [hunk 1]
```diff
@@ -124,7 +124,7 @@ func NewThrottledUpgradeAwareProxyHandler(location *url.URL, transport http.Roun
 
 func GetTlsConfigForCluster(ctx context.Context, cluster *clusterapis.Cluster, secretGetter SecretGetterFunc) (*tls.Config, error) {
 	// The secret is optional for a pull-mode cluster, if no secret just returns a config with root CA unset.
-	if cluster.Spec.SecretRef == nil {
+	if cluster.Spec.SecretRef == nil || cluster.Spec.InsecureSkipTLSVerification {
```
Comment (jwcesign) [inline pkg/util/proxy/proxy.go:127]: Should we set the RootCAs even if InsecureSkipTLSVerification is true(If the caBundle exists)?

Comment (CharlesQQ) [reply pkg/util/proxy/proxy.go:127]: > Should we set the RootCAs even if InsecureSkipTLSVerification is true(If the caBundle exists)?

en.., sure, It's a batter choice

Comment (CharlesQQ) [reply pkg/util/proxy/proxy.go]: /cc @jwcesign

**Review by jwcesign — COMMENTED** [review]
lgtm

cc @chaosi-zju for double checking

File: pkg/util/proxy/proxy.go [hunk 2]
```diff
@@ -139,7 +139,13 @@ func GetTlsConfigForCluster(ctx context.Context, cluster *clusterapis.Cluster, s
...
 	caBundle, err := getClusterCABundle(cluster.Name, caSecret)
 	if err != nil {
-		return nil, fmt.Errorf("failed to get CA bundle for cluster %s: %v", cluster.Name, err)
+		return &tls.Config{
+			MinVersion: tls.VersionTLS13,
+			// Ignore false positive warning: "TLS InsecureSkipVerify may be true. (gosec)"
+			// Whether to skip server certificate verification depends on the
+			// configuration(.spec.insecureSkipTLSVerification, defaults to false) in a Cluster object.
+			InsecureSkipVerify: cluster.Spec.InsecureSkipTLSVerification, //nolint:gosec
+		}, nil
```
Comment (chaosi-zju) [inline pkg/util/proxy/proxy.go:148]: hi, in your case, `cluster.Spec.InsecureSkipTLSVerification=true` and `caBundle=""`, you code works fine.

But, if `cluster.Spec.InsecureSkipTLSVerification=false` and `caBundle=""`, this case may be we should report error if caBundle is empty?

Otherwise, you see, caBundle is empty and we return `&tls.Config{InsecureSkipVerify: false}`, this is a invalid config.

Comment (jwcesign) [reply pkg/util/proxy/proxy.go:148]: >  if cluster.Spec.InsecureSkipTLSVerification=false and caBundle="", this case may be we should report error if caBundle is empty?

I think, if the ca in the container is correct, it will still works fine

Comment (CharlesQQ) [reply pkg/util/proxy/proxy.go:148]: > hi, in your case, `cluster.Spec.InsecureSkipTLSVerification=true` and `caBundle=""`, you code works fine.
> 
> But, if `cluster.Spec.InsecureSkipTLSVerification=false` and `caBundle=""`, this case may be we should report error if caBundle is empty?
> 
> Otherwise, you see, caBundle is empty and we return `&tls.Config{InsecureSkipVerify: false}`, this is a invalid config.

got it!!!

File: pkg/util/proxy/proxy.go [hunk 3]
```diff
@@ -139,7 +139,16 @@ func GetTlsConfigForCluster(ctx context.Context, cluster *clusterapis.Cluster, s
...
+		if cluster.Spec.InsecureSkipTLSVerification {
+			return &tls.Config{
+				MinVersion: tls.VersionTLS13,
+				// Ignore false positive warning: "TLS InsecureSkipVerify may be true. (gosec)"
+				// Whether to skip server certificate verification depends on the
+				// configuration(.spec.insecureSkipTLSVerification, defaults to false) in a Cluster object.
+				InsecureSkipVerify: cluster.Spec.InsecureSkipTLSVerification, //nolint:gosec
+			}, nil
+		}
+		return nil, fmt.Errorf("insecureSkipTLSVerification is false, but failed to get CA bundle for cluster %s: %v", cluster.Name, err)
```
Comment (jwcesign) [inline pkg/util/proxy/proxy.go:151]: How about this? @chaosi-zju @CharlesQQ 
```go
func getClusterCABundle(clusterName string, secret *corev1.Secret) []byte {
	caBundle, found := secret.Data[clusterapis.SecretCADataKey]
	if !found {
		return []byte{}
	}
	return caBundle
}

func GetTlsConfigForCluster(ctx context.Context, cluster *clusterapis.Cluster, secretGetter SecretGetterFunc) (*tls.Config, error) {
        ...
        caBundle := getClusterCABundle(cluster.Name, caSecret)
	caCertPool := x509.NewCertPool()
	caCertPool.AppendCertsFromPEM(caBundle)
	return &tls.Config{
		RootCAs:    caCertPool,
		MinVersion: tls.VersionTLS13,
		// Ignore false positive warning: "TLS InsecureSkipVerify may be true. (gosec)"
		// Whether to skip server certificate verification depends on the
		// configuration(.spec.insecureSkipTLSVerification, defaults to false) in a Cluster object.
		InsecureSkipVerify: cluster.Spec.InsecureSkipTLSVerification, //nolint:gosec
	}, nil
```

Comment (chaosi-zju) [reply pkg/util/proxy/proxy.go:151]: > I think, if the ca in the container is correct, it will still work fine

I got your point.

> How about this?

I think fine

Comment (jwcesign) [reply pkg/util/proxy/proxy.go:151]: Hi, @CharlesQQ 
Can you help update this?

Comment (CharlesQQ) [reply pkg/util/proxy/proxy.go]: > How about this? @chaosi-zju @CharlesQQ
> 
> ```go
> func getClusterCABundle(clusterName string, secret *corev1.Secret) []byte {
> 	caBundle, found := secret.Data[clusterapis.SecretCADataKey]
> 	if !found {
> 		return []byte{}
> 	}
> 	return caBundle
> }
> 
> func GetTlsConfigForCluster(ctx context.Context, cluster *clusterapis.Cluster, secretGetter SecretGetterFunc) (*tls.Config, error) {
>         ...
>         caBundle := getClusterCABundle(cluster.Name, caSecret)
> 	caCertPool := x509.NewCertPool()
> 	caCertPool.AppendCertsFromPEM(caBundle)
> 	return &tls.Config{
> 		RootCAs:    caCertPool,
> 		MinVersion: tls.VersionTLS13,
> 		// Ignore false positive warning: "TLS InsecureSkipVerify may be true. (gosec)"
> 		// Whether to skip server certificate verification depends on the
> 		// configuration(.spec.insecureSkipTLSVerification, defaults to false) in a Cluster object.
> 		InsecureSkipVerify: cluster.Spec.InsecureSkipTLSVerification, //nolint:gosec
> 	}, nil
> ```

motified!!!

**Comment by jwcesign** [comment]
Nice work! Thanks for your contribution.

/lgtm

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks @CharlesQQ 
LGMT

I think this should affect user behavior. Can we add a release note to explain it?

**Comment by CharlesQQ** [comment]
> Thanks @CharlesQQ LGMT
> 
> I think this should affect user behavior. Can we add a release note to explain it?

yes
