### PR TITLE
Restrict the cluster sync mode for the unjoin and unregister command

### LINKED ISSUE #801: karmadactl unjoin doesn't delete agent when unjoinning a pull mode cluster
**What happened**:
When unjoining a pull mode cluster, the resources associated with agent still remain in the unjonning cluster.

**What you expected to happen**:
`karmadactl unjoin` should clean up resources associated with agent from the unjoining pull mode cluster

**How to reproduce it (as minimally and precisely as possible)**:
1.Set up environment
```sh
root@myserver:~/karmada# hack/local-up-karmada.sh

root@myserver:~/karmada# hack/create-cluster.sh member1 $HOME/.kube/karmada.config

root@myserver:~/karmada# kubectl config use-context karmada-apiserver
```
2.Join member1 in pull mode
```sh
root@myserver:~/karmada# hack/deploy-karmada-agent.sh $KUBECONFIG karmada-apiserver $KUBECONFIG member1

root@myserver:~/karmada# kubectl get cluster
NAME      VERSION   MODE   READY   AGE
member1   v1.19.1   Pull   True    3m19s
```
3.Unjoin member1
```sh
root@myserver:~/karmada# karmadactl unjoin member1 --cluster-kubeconfig=$KUBECONFIG

root@myserver:~/karmada# kubectl get cluster
No resources found
```
4.Check the resources associated with karmada agent
```sh
root@myserver:~/karmada# kc get deploy -n karmada-system --context member1
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
karmada-agent   1/1     1            1           5m34s

root@myserver:~/karmada# kc get clusterrole karmada-agent --context member1
NAME            CREATED AT
karmada-agent   2021-10-12T01:39:26Z

root@myserver:~/karmada# kc get clusterrolebinding karmada-agent --context member1
NAME            ROLE                        AGE
karmada-agent   ClusterRole/karmada-agent   6m2s
```
They still remain in the unjoining cluster, is it an oversight or intention?

**Anything else we need to know?**:

**Environment**:
- Karmada version: v0.8.0
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Restrict the cluster sync mode for the unjoin and unregister command.
```bash
$ karmadactl get cluster
NAME      CLUSTER   VERSION   MODE   READY   AGE     ADOPTION
member1   Karmada   v1.31.2   Push   True    17h     -
member3   Karmada   v1.31.2   Pull   True    3d23h   -
$ karmadactl unregister member1  --cluster-kubeconfig ~/.kube/members.config --karmada-config ~/.kube/karmada.config --cluster-context member1 -v=4 
I0124 11:10:55.943833 2452252 unregister.go:188] Unregistering cluster. cluster name: member1
I0124 11:10:55.943887 2452252 unregister.go:189] Unregistering cluster. karmada-agent deployed in namespace: karmada-system
I0124 11:10:55.943901 2452252 unregister.go:190] Unregistering cluster. member cluster secrets stored in namespace: karmada-cluster
error: cluster member1 is a Push mode member cluster, please use command `unjoin` if you want to unregister cluster
$ karmadactl unjoin member3 --cluster-kubeconfig=/root/.kube/members.config --cluster-context=member3                                               
error: cluster member3 is a Pull mode member cluster, please use command `unregister` if you want to unregister cluster
```

**Which issue(s) this PR fixes**:
Fixes #801

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmadactl`: The `unjoin` command is restricted to only unjoin push mode member clusters. The `unregister` command is restricted to only unregister pull mode member clusters.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
> error: cluster member1 is a Push mode member cluster, please use command `unjoin` if you want to unregister cluster
> error: cluster member3 is a Pull mode member cluster, please use command `unregister` if you want to unregister cluster

No data was changed or removed before this log, right?

**Comment by zhzhuang-zju** [comment]
> No data was changed or removed before this log, right?

Yes, I put the validations ahead of the `unjoin/unregister` operations

**Comment by zhzhuang-zju** [comment]
> https://github.com/karmada-io/karmada/actions/runs/12944367640/job/36105361982#step:6:2572
[FAIL] [CronFederatedHPA] CronFederatedHPA testing Scale FederatedHPA [It] Test scale FederatedHPA testing

/retest

File: pkg/karmadactl/util/cluster.go [hunk 1]
```diff
@@ -95,6 +96,19 @@ func DeleteClusterObject(controlPlaneKubeClient kubeclient.Interface, controlPla
 	return err
 }
 
+// GetClusterSyncMode return the sync mode of the member cluster.
+func GetClusterSyncMode(controlPlaneKarmadaClient karmadaclientset.Interface, clusterName string) (clusterv1alpha1.ClusterSyncMode, error) {
+	target, err := controlPlaneKarmadaClient.ClusterV1alpha1().Clusters().Get(context.TODO(), clusterName, metav1.GetOptions{})
+	if apierrors.IsNotFound(err) {
+		return clusterv1alpha1.Push, fmt.Errorf("no cluster object %s found in karmada control Plane", clusterName)
```
Comment (XiShanYongYe-Chang) [inline pkg/karmadactl/util/cluster.go:103]: Is it better for sycnmode to return an empty string when the returned err is not null?

The first is that it's easier to read and understand, and the second is that the handler of the mode function is improperly handled.

File: pkg/karmadactl/util/cluster.go [hunk 2]
```diff
@@ -95,6 +96,19 @@ func DeleteClusterObject(controlPlaneKubeClient kubeclient.Interface, controlPla
 	return err
 }
 
+// GetClusterSyncMode return the sync mode of the member cluster.
+func GetClusterSyncMode(controlPlaneKarmadaClient karmadaclientset.Interface, clusterName string) (clusterv1alpha1.ClusterSyncMode, error) {
```
Comment (XiShanYongYe-Chang) [inline pkg/karmadactl/util/cluster.go:100]: In my opinion, this function doesn't feel very necessary, and inconvenient to test

File: pkg/karmadactl/unjoin/unjoin_test.go [hunk 3]
```diff
@@ -118,7 +118,7 @@ func TestRunUnJoinCluster(t *testing.T) {
 			clusterConfig:          &rest.Config{},
 			karmadaClient:          fakekarmadaclient.NewSimpleClientset(),
 			prep: func(_ kubeclient.Interface, _ kubeclient.Interface, karmadaClient karmadaclientset.Interface, _ *CommandUnjoinOption) error {
-				karmadaClient.(*fakekarmadaclient.Clientset).Fake.PrependReactor("delete", "clusters", func(coretesting.Action) (bool, runtime.Object, error) {
+				karmadaClient.(*fakekarmadaclient.Clientset).Fake.PrependReactor("get", "clusters", func(coretesting.Action) (bool, runtime.Object, error) {
```
Comment (XiShanYongYe-Chang) [inline pkg/karmadactl/unjoin/unjoin_test.go:121]: Is delete changed to get because a query is added?

File: pkg/karmadactl/util/cluster.go (hunk 1 above)
Comment (zhzhuang-zju) [reply pkg/karmadactl/util/cluster.go]: Thx, done

File: pkg/karmadactl/unjoin/unjoin_test.go (hunk 3 above)
Comment (zhzhuang-zju) [reply pkg/karmadactl/unjoin/unjoin_test.go:149]: Yes, I made some new changes in these test files, please take another look

Comment (XiShanYongYe-Chang) [reply pkg/karmadactl/unjoin/unjoin_test.go:149]: Some comments can be added to facilitate understanding.

Comment (zhzhuang-zju) [reply pkg/karmadactl/unjoin/unjoin_test.go:149]: I think the test name is enough, or could you provide some better comments?

**Comment by zhzhuang-zju** [comment]
https://github.com/karmada-io/karmada/actions/runs/13170601820/job/36760129166?pr=6081#step:5:28
github rate-limiter failed

/retest

File: pkg/karmadactl/unjoin/unjoin_test.go (hunk 3 above)
Comment (XiShanYongYe-Chang) [reply pkg/karmadactl/unjoin/unjoin_test.go:149]: okay

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/lgtm

**Review by RainbowMango — COMMENTED** [review]
/assign

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
