### PR TITLE
Fix Resource's annotation have not been updated after the overridepolicy updated

### LINKED ISSUE #507: Resources have not been updated after the overridepolicyis updated.
**What happened**:
1. Current environment.
```
## OverridePolicy:
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  creationTimestamp: "2021-07-08T07:37:50Z"
  generation: 1
  name: nginx3333
  namespace: test
spec:
  overriders:
    plaintext:
    - operator: add
      path: /metadata/annotations
      value:
        aa: bb
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx3333
    namespace: test
  targetCluster:
    clusterNames:
    - host

## Deployment has updated in host:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    aa: bb
  creationTimestamp: "2021-07-08T06:13:18Z"
  generation: 2
  labels:
    app: nginx3333
  name: nginx3333
  namespace: test
```

2. Updated overridepolicy in Karmada.
```
## OverridePolicy:
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  creationTimestamp: "2021-07-08T07:37:50Z"
  generation: 1
  name: nginx3333
  namespace: test
spec:
  overriders:
    plaintext:
    - operator: add
      path: /metadata/annotations
      value:                                           <--------- value has updated
        bb: cc
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx3333
    namespace: test
  targetCluster:
    clusterNames:
    - host
 
## Deployment had not updated in host:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    aa: bb
  creationTimestamp: "2021-07-08T06:13:18Z"
  generation: 2
  labels:
    app: nginx3333
  name: nginx3333
  namespace: test
```

**Anything else we need to know?**:
Is this the design of karmada itself ?
I think the deployment should update when updated overridepolicy.

**Environment**:
- Karmada version: latest

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When overridepolicy's overriders modified, the resource's annotations have not been updated in member clusters.

**Which issue(s) this PR fixes**:
Fixes #507 

**Special notes for your reviewer**:
I will merge the annotations from `desire object` and `member cluster object`, this resulting in old annotations which added by overridepolicy can not be removed from newest object. Because we don't know which annotations are added by user before, and which annotations are setted by controllers in a member cluster.

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/util/objectwatcher/retain.go [hunk 1]
```diff
@@ -44,6 +46,12 @@ func RetainClusterFields(desiredObj, clusterObj *unstructured.Unstructured) erro
 	return nil
 }
 
+func mergeAnnotations(desiredObj, clusterObj *unstructured.Unstructured) {
+	for key, value := range clusterObj.GetAnnotations() {
+		util.MergeAnnotation(desiredObj, key, value)
+	}
+}
+
```
Comment (RainbowMango) [inline pkg/util/objectwatcher/retain.go:54]: How about move this function to `util` package?

```
// MergeAnnotations merges the annotations from 'src' to 'dst'.
func MergeAnnotations(dst *unstructured.Unstructured, src *unstructured.Unstructured) {
	for key, value := range src.GetAnnotations() {
		MergeAnnotation(dst, key, value)
	}
}
```

**Comment by RainbowMango** [comment]
```
I0716 08:59:55.717105   30038 suite_test.go:204] Got 3 member cluster and all in ready state.
There are 3 clusters
propagation with label and group constraints testing Deployment propagation testing 
  deployment propagation with label and group constraints testing
  /home/runner/work/karmada/karmada/test/e2e/scheduling_test.go:81
STEP: creating policy(karmadatest-gjr/deploy-tgp)
I0716 08:59:56.056286   30038 scheduling_test.go:70] created policy(karmadatest-gjr)%!(EXTRA string=deploy-tgp)
STEP: creating deployment(karmadatest-gjr/deploy-tgp)
STEP: collect the target clusters in resource binding
I0716 08:59:56.118938   30038 scheduling_test.go:85] created deployment(karmadatest-gjr/deploy-tgp)
STEP: removing policy(karmadatest-gjr/deploy-tgp)
```
