### PR TITLE
Check if the resource exists before creating it

### LINKED ISSUE #2981: Keep creating namespaces
**What happened**:
After this https://github.com/karmada-io/karmada/pull/2825 merged, the namespace will be continued creating.

**What you expected to happen**:
Not continue creating.

**How to reproduce it (as minimally and precisely as possible)**:
I checked the code, and the function `EnsureNamespaceExist` is only invoked when cluster init(karmada-agent init and karmadactl init).

And I tested release-1.4 branch, init clusters with `local-up-karmada.sh` and` karmadactl init`, both works correctly, but the problem is not reproduced.
@yizhang-zen, can you give more information about this? how to reproduce this problem?

**Anything else we need to know?**:
none

**Environment**:
- Karmada version: release-1.4 branch
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):release-1.4 branch
- Others: none

### PR DESCRIPTION
**Pull request by jwcesign**
Signed-off-by: jwcesign <jiangwei115@huawei.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Referring to #2981, sometimes the namespace is created in advance, to give less privilege to Karmada. So if we want to create resource, checking if it exists is necessary

**Which issue(s) this PR fixes**:
Fixes #2981 

**Special notes for your reviewer**:
@lonelyCZ 

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-agent`: Check if the resource exists before creating it. Sometimes the resource is created in advance, to give less privilege to Karmada.
```

### CODE REVIEW

**Comment by jwcesign** [comment]
cc @lonelyCZ for checking

File: pkg/util/namespace.go [hunk 1]
```diff
@@ -10,6 +10,20 @@ import (
 	kubeclient "k8s.io/client-go/kubernetes"
 )
 
+// IsNamespaceExist tells if specific already exists.
```
Comment (RainbowMango) [inline pkg/util/namespace.go:13]:
```suggestion
// IsNamespaceExist tells if the namespace already exists.
```

Comment (jwcesign) [reply pkg/util/namespace.go]: fixed

**Comment by jwcesign** [comment]
cc @RainbowMango @lonelyCZ , any more suggestions?

File: pkg/util/serviceaccount_test.go [hunk 2]
```diff
@@ -187,6 +201,63 @@ func TestEnsureServiceAccountExist(t *testing.T) {
...
+			args: args{
+				client:    alwaysErrorKubeClient,
+				namespace: metav1.NamespaceDefault,
+				name:      "test",
+			},
+			want:    false,
+			wantErr: true,
+		},
+		{
+			name: "error",
```
Comment (a7i) [inline pkg/util/serviceaccount_test.go:237]: `"error"` is the same sub-test name as above:
```suggestion
			name: "check service account exists error ",
```

File: pkg/util/namespace_test.go [hunk 3]
```diff
@@ -14,6 +14,70 @@ import (
...
+				reactor:   nil,
+			},
+			want:    false,
+			wantErr: false,
+		},
+		{
+			name: "namespace already exists",
+			args: args{
+				client:    fake.NewSimpleClientset(&corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: "default"}}),
+				namespace: "default",
```
Comment (a7i) [inline pkg/util/namespace_test.go:56]: for consistency:
```suggestion
				namespace: metav1.NamespaceDefault,
```

File: pkg/util/namespace_test.go [hunk 4]
```diff
@@ -14,6 +14,70 @@ import (
...
+				},
+			},
+			want:    false,
+			wantErr: true,
+		},
+		{
+			name: "namespace not exists",
+			args: args{
+				client:    fake.NewSimpleClientset(&corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: "default-1"}}),
+				namespace: "default",
```
Comment (a7i) [inline pkg/util/namespace_test.go:46]: for consistency:
```suggestion
				namespace: metav1.NamespaceDefault,
```

File: pkg/util/namespace_test.go [hunk 5]
```diff
@@ -14,6 +14,70 @@ import (
...
+		name    string
+		args    args
+		want    bool
+		wantErr bool
+	}{
+		{
+			name: "query namespace error",
+			args: args{
+				client:    fake.NewSimpleClientset(&corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: "default"}}),
+				namespace: "default",
```
Comment (a7i) [inline pkg/util/namespace_test.go:34]: for consistency:
```suggestion
				namespace: metav1.NamespaceDefault,
```

File: pkg/util/namespace_test.go [hunk 6]
```diff
@@ -162,6 +227,17 @@ func TestEnsureNamespaceExist(t *testing.T) {
 			},
 			wantErr: false,
 		},
+		{
+			name: "check namespace exists error",
+			args: args{
+				client:    fake.NewSimpleClientset(&corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: "default"}}),
+				namespace: "default",
```
Comment (a7i) [inline pkg/util/namespace_test.go:234]: for consistency:
```suggestion
				namespace: metav1.NamespaceDefault,
```

**Comment by jwcesign** [comment]
@a7i , Thanks for the review, PTAL.

**Comment by a7i** [comment]
@jwcesign Thank you, LGTM. though I'm not a maintainer so that may not count :)

**Review by RainbowMango — APPROVED** [review]
/approve
/lgtm
Thanks.
