### PR TITLE
make cluster represents more precise resources

### LINKED ISSUE #344: Support scheduling according to member cluster resources
**What would you like to be added**:
Support scheduling according to member cluster resources

**Why is this needed**:
### Background
As Kubernetes is used in more and more scenarios, a single cluster sometimes cannot meet a large task (such as the AI training scenario). Therefore, we need multiple clusters to provide resources for a task at the same time.
During the research process, we found that the ‘karmada’ project is the multi-cluster project that best meets our needs. However, karmada is still relatively simple in scheduling implementation, and cannot handle the above-mentioned demand for splitting tasks based on member cluster resources.

### Proposal
Karama supports a richer scheduling strategy through plug-ins: supports split scheduling and Re-balance of tasks based on the available resources of the Member cluster.

### High-level design

1. Provide more accurate and real-time NodeSummary for scheduler. For example, using the Informer method to monitor resource changes instead of regular List; adding the 'Pending' resource statistics in the Member cluster in the NodeSummary;
2. Support new scheduling strategy: Scheduling workload according to the amount of available resources of the Member clusters, and the aggregation/balance (scheduling to as few clusters as possible OR balanced scheduling to each cluster) mode is supported for scheduling.
3. Improve the Re-balance capability: When partial resource exceptions occur in the Member cluster, or the Manager cluster scheduling is not accurate enough, the exception can be found and re-balanced.

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:
change cluster api according to #344

**Which issue(s) this PR fixes**:
Part of #344 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Cluster API Changes: Add ResourceSummary
```

### CODE REVIEW

File: pkg/apis/cluster/v1alpha1/types.go [hunk 1]
```diff
@@ -150,6 +158,24 @@ type NodeSummary struct {
...
+}
+
+// Resources represents the allocatable, allocating and allocated resources in a specific cluster.
+type Resources struct {
+	// Allocatable represents the allocatable resources across all nodes.
+	Allocatable corev1.ResourceList `json:"allocatable,omitempty"`
+	// Allocating represents the allocating resources across all nodes whose node name has not been set.
+	Allocating corev1.ResourceList `json:"allocating,omitempty"`
+	// Allocated represents the resources that have been allocated across all nodes.
+	Allocated corev1.ResourceList `json:"allocated,omitempty"`
```
Comment (RainbowMango) [inline pkg/apis/cluster/v1alpha1/types.go:176]: Give the fields an explicit `// +optional`.

File: pkg/apis/cluster/v1alpha1/types.go [hunk 2]
```diff
@@ -127,6 +127,14 @@ type ClusterStatus struct {
...
 	// +optional
 	NodeSummary NodeSummary `json:"nodeSummary,omitempty"`
+
+	// Nodes represents the numbers of all nodes and ready nodes in the member cluster.
+	// +optional
+	Nodes Nodes `json:"nodes,omitempty"`
+
+	// Resources represents the allocatable, allocating and allocated resources in the member cluster.
+	// +optional
+	Resources Resources `json:"resource,omitempty"`
```
Comment (RainbowMango) [inline pkg/apis/cluster/v1alpha1/types.go:137]: `Resource` might be an uncountable word, how about change `Resources` --> `Resource`?

**Review by RainbowMango — COMMENTED** [review]
Post my comments focus on field types, only some nits.

@kevin-wangzefeng could you please take a look at the comments for each field.

By the way, @Garrybest can you add an agenda to the meeting agenda, if no objection, we can move forward this?

File: pkg/apis/cluster/v1alpha1/types.go [hunk 3]
```diff
@@ -150,6 +158,24 @@ type NodeSummary struct {
...
+	TotalNum int `json:"totalNum,omitempty"`
+	// ReadyNum is the number of ready nodes in the cluster.
+	ReadyNum int `json:"readyNum,omitempty"`
+}
+
+// Resources represents the allocatable, allocating and allocated resources in a specific cluster.
+type Resources struct {
+	// Allocatable represents the allocatable resources across all nodes.
+	Allocatable corev1.ResourceList `json:"allocatable,omitempty"`
+	// Allocating represents the allocating resources across all nodes whose node name has not been set.
```
Comment (RainbowMango) [inline pkg/apis/cluster/v1alpha1/types.go:173]: This sentence might something wrong because we can't set nodes to a `resource` or `node`.

**Comment by Garrybest** [comment]
Sure, I'm going to add an agenda. @RainbowMango

File: pkg/apis/cluster/v1alpha1/types.go (hunk 2 above)
Comment (Garrybest) [reply pkg/apis/cluster/v1alpha1/types.go:137]: We cannot. `Resource` has been used according to

File: pkg/apis/cluster/v1alpha1/types.go (hunk 1 above)
Comment (Garrybest) [reply pkg/apis/cluster/v1alpha1/types.go:176]: OK.

File: pkg/apis/cluster/v1alpha1/types.go [hunk 4]
```diff
@@ -150,6 +158,24 @@ type NodeSummary struct {
 	Used corev1.ResourceList `json:"used,omitempty"`
 }
 
+// Nodes represents the numbers of all nodes and ready nodes in a specific cluster.
+type Nodes struct {
+	// TotalNum is the total number of nodes in the cluster.
+	TotalNum int `json:"totalNum,omitempty"`
```
[the remark this answers is not in the document]
Comment (Garrybest) [reply pkg/apis/cluster/v1alpha1/types.go:164]: OK.

File: pkg/apis/cluster/v1alpha1/types.go [hunk 5]
```diff
@@ -127,6 +127,14 @@ type ClusterStatus struct {
 	// NodeSummary represents the summary of nodes status in the member cluster.
 	// +optional
 	NodeSummary NodeSummary `json:"nodeSummary,omitempty"`
+
+	// Nodes represents the numbers of all nodes and ready nodes in the member cluster.
+	// +optional
+	Nodes Nodes `json:"nodes,omitempty"`
```
[the remark this answers is not in the document]
Comment (Garrybest) [reply pkg/apis/cluster/v1alpha1/types.go:133]: Sounds good.

File: pkg/apis/cluster/v1alpha1/types.go [hunk 6]
```diff
@@ -127,6 +127,14 @@ type ClusterStatus struct {
 	// NodeSummary represents the summary of nodes status in the member cluster.
 	// +optional
 	NodeSummary NodeSummary `json:"nodeSummary,omitempty"`
+
+	// Nodes represents the numbers of all nodes and ready nodes in the member cluster.
```
[the remark this answers is not in the document]
Comment (Garrybest) [reply pkg/apis/cluster/v1alpha1/types.go:131]: Good idea. Although at present we only calculate the numbers of nodes, more information about the summary may be added in the future.

**Comment by Garrybest** [comment]
If the definition is ok, the further work will go on.

File: pkg/apis/cluster/v1alpha1/types.go [hunk 7]
```diff
@@ -141,13 +145,24 @@ type APIEnablement struct {
...
 	Allocatable corev1.ResourceList `json:"allocatable,omitempty"`
-	// Used represents the resources have been used across all nodes.
-	Used corev1.ResourceList `json:"used,omitempty"`
+	// Allocating represents the allocating resources of pending pods which are not scheduled.
+	// +optional
+	Allocating corev1.ResourceList `json:"allocating,omitempty"`
+	// Allocated represents the resources that have been allocated across all nodes.
+	// +optional
+	Allocated corev1.ResourceList `json:"allocated,omitempty"`
 }
```
Comment (RainbowMango) [inline pkg/apis/cluster/v1alpha1/types.go:166]: Just add suggested comments:
```golang
// ResourceSummary represents the summary of resources in the member cluster.
type ResourceSummary struct {
	// Allocatable represents the resources of a cluster that are available for scheduling.
	// Total amount of allocatable resources on all nodes.
	// +optional
	Allocatable corev1.ResourceList `json:"allocatable,omitempty"`
	// Allocating represents the resources of a cluster that are pending for scheduling.
	// Total amount of required resources of all Pods that waiting for scheduling.
	// +optional
	Allocating corev1.ResourceList `json:"allocating,omitempty"`
	// Allocated represents the resources of a cluster that have been scheduled.
	// Total amount of required resources of all Pods that has been scheduled to node.
	// +optional
	Allocated corev1.ResourceList `json:"allocated,omitempty"`
}
```

**Review by RainbowMango — COMMENTED** [review]
Yeah, LGTM. Just want to adjust some comments.

**Comment by RainbowMango** [comment]
@Garrybest I suggest only make the necessary changes in this PR, let the legacy code adopt the new API. 
Let's try merging this by this weekend.

For the new fields, we can calculate the resources in the following PR.

**Comment by RainbowMango** [comment]
/retitle "make cluster represents more precise resources"

**Comment by Garrybest** [comment]
@RainbowMango Sounds Good👌. Thanks for suggestion.

File: pkg/apis/cluster/v1alpha1/types.go [hunk 8]
```diff
@@ -126,7 +126,11 @@ type ClusterStatus struct {
 
 	// NodeSummary represents the summary of nodes status in the member cluster.
 	// +optional
-	NodeSummary NodeSummary `json:"nodeSummary,omitempty"`
+	NodeSummary *NodeSummary `json:"nodeSummary,omitempty"`
+
+	// ResourceSummary represents the allocatable, allocating and allocated resources in the member cluster.
```
[the remark this answers is not in the document]
Comment (RainbowMango) [reply pkg/apis/cluster/v1alpha1/types.go:131]: Forgot to update this comment?

File: pkg/controllers/status/cluster_status_controller.go [hunk 9]
```diff
@@ -330,18 +331,19 @@ func getAPIEnablements(clusterClient *util.ClusterClient) ([]v1alpha1.APIEnablem
 	return apiEnablements, nil
 }
 
-func getNodeSummary(informerManager informermanager.SingleClusterInformerManager) (v1alpha1.NodeSummary, error) {
-	var nodeSummary = v1alpha1.NodeSummary{}
+func getClusterSummary(informerManager informermanager.SingleClusterInformerManager) (*v1alpha1.NodeSummary, *v1alpha1.ResourceSummary, error) {
```
Comment (RainbowMango) [inline pkg/controllers/status/cluster_status_controller.go:334]: Why not split this function to `getNodeSummary` and `getResourceSummary`?

File: pkg/apis/cluster/v1alpha1/types.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (Garrybest) [reply pkg/apis/cluster/v1alpha1/types.go:131]: Right, I will fix it.

File: pkg/controllers/status/cluster_status_controller.go (hunk 9 above)
Comment (Garrybest) [reply pkg/controllers/status/cluster_status_controller.go:334]: If splitting, we should list all nodes twice.

Comment (RainbowMango) [reply pkg/controllers/status/cluster_status_controller.go:334]: Sorry, I can't see why we list `nodes` twice. Did I miss something?

Comment (RainbowMango) [reply pkg/controllers/status/cluster_status_controller.go:334]: Oh, I see it is `allocatable := getClusterAllocatable(nodes)`.

Comment (RainbowMango) [reply pkg/controllers/status/cluster_status_controller.go:334]: But I still prefer to split this function, we can get `Nodes` and `Pods` first, then calculate `NodeSummary` and `ResourceSummary` respectively, which will make it easier to test by unit test.

Comment (Garrybest) [reply pkg/controllers/status/cluster_status_controller.go:334]: That's reasonable.

File: pkg/controllers/status/cluster_status_controller.go [hunk 10]
```diff
@@ -330,20 +330,31 @@ func getAPIEnablements(clusterClient *util.ClusterClient) ([]v1alpha1.APIEnablem
 	return apiEnablements, nil
 }
 
-func getNodeSummary(informerManager informermanager.SingleClusterInformerManager) (v1alpha1.NodeSummary, error) {
-	var nodeSummary = v1alpha1.NodeSummary{}
+func listNodesAndPods(informerManager informermanager.SingleClusterInformerManager) ([]*corev1.Node, []*corev1.Pod, error) {
```
Comment (RainbowMango) [inline pkg/controllers/status/cluster_status_controller.go:333]: `ListNodes` and `ListPods` are totally independent, can we split `listNodesAndPods` to two functions?
My concern is what if we want to list another resource in the future? like `service`, then it will be a  broken change for this function, both its name and return list should be updated.

Comment (RainbowMango) [reply pkg/controllers/status/cluster_status_controller.go:333]: Let's merge this before vocation and fix this then.
