### PR TITLE
Cherry pick of #7387: fix: lookup Job completions by cluster name instead of positional index

### LINKED ISSUE #7393: Backport #7387
**Which PR needs cherry-picks:**

PR 7387

**Which release branches need this patch:**

- [x] release-1.17 #7397
- [x] release-1.16 #7401 

**How to cherry-pick PRs:**

The `hack/cherry_pick_pull.sh` script can help you initiate a cherry-pick
automatically, please follow the instructions at [this guideline](https://karmada.io/docs/contributor/cherry-picks).

The script will send the PR for you and automatically include the release notes from the original PR in the new PR description.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a **separate line**.

Then, the issue will be assigned to you.

**Useful References:**

- Release timeline: https://karmada.io/docs/releases
- How to cherry-pick PRs: https://karmada.io/docs/contributor/cherry-picks

**Anything else we need to know:**

### PR DESCRIPTION
**Pull request by Ady0333**
Cherry pick of #7387 on release-1.16.

#7387: fix: lookup Job completions by cluster name instead of positional index

**What type of PR is this?**

/kind bug

**What this PR does / why we need it:**

Backport of #7387 to release-1.16. Fixes a bug where Job completions were assigned to wrong clusters when using divided replica scheduling with cluster names not in alphabetically ordered.

**Which issue(s) this PR fixes:**

Fixes #7393

**Does this PR introduce a user-facing change?**
```release-note
Fixed a bug where Job completions were assigned to wrong clusters when using divided replica scheduling with cluster names not in alphabetical order.
```

**Additional notes:**

Manual cherry-pick due to merge conflicts in imports section (added `fmt` and `slices` imports needed by the fix).

### CODE REVIEW

**Comment by Ady0333** [comment]
Hello @XiShanYongYe-Chang , this is the cherry pick for release - 1.16.

File: pkg/controllers/binding/common.go [hunk 1]
```diff
@@ -18,6 +18,8 @@ package binding
 
 import (
 	"context"
+	"fmt"
+	"slices"
```
Comment (XiShanYongYe-Chang) [inline pkg/controllers/binding/common.go]: Can you help delete useless packages?

[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/controllers/binding/common.go]: +1

Comment (Ady0333) [reply pkg/controllers/binding/common.go]: Yes, i'll delete all the useless packages!!!

**Comment by Ady0333** [comment]
Hello @XiShanYongYe-Chang , 
I made all the suggested changes...check them once and let me know if any changes are needed!!!

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
/lgtm
/approve
