### PR TITLE
Fix the issue of missing workqueue metrics in the Karmada controller

### LINKED ISSUE #5696: karmada controller can't find metrics workqueue_depth
**Please provide an in-depth description of the question you have**:

curl karmada metrics endpoint, like ` curl http://127.0.0.1:10358/metrics`, can't found metrics `workqueue_depth`

```curl http://127.0.0.1:10358/metrics |grep queue
controller_runtime_reconcile_total{controller="cluster",result="requeue"} 0
controller_runtime_reconcile_total{controller="cluster",result="requeue_after"} 20665
controller_runtime_reconcile_total{controller="clusterResourceBinding_status_controller",result="requeue"} 0
controller_runtime_reconcile_total{controller="clusterResourceBinding_status_controller",result="requeue_after"} 0
controller_runtime_reconcile_total{controller="clusterresourcebinding",result="requeue"} 0
controller_runtime_reconcile_total{controller="clusterresourcebinding",result="requeue_after"} 0
controller_runtime_reconcile_total{controller="cronfederatedhpa",result="requeue"} 0
controller_runtime_reconcile_total{controller="cronfederatedhpa",result="requeue_after"} 0
controller_runtime_reconcile_total{controller="federatedhpa",result="requeue"} 0
controller_runtime_reconcile_total{controller="federatedhpa",result="requeue_after"} 0
controller_runtime_reconcile_total{controller="federatedresourcequota",result="requeue"} 0
controller_runtime_reconcile_total{controller="federatedresourcequota",result="requeue_after"} 0
controller_runtime_reconcile_total{controller="namespace",result="requeue"} 0
controller_runtime_reconcile_total{controller="namespace",result="requeue_after"} 0
controller_runtime_reconcile_total{controller="remedy-controller",result="requeue"} 0
controller_runtime_reconcile_total{controller="remedy-controller",result="requeue_after"} 0
controller_runtime_reconcile_total{controller="resourceBinding_status_controller",result="requeue"} 0
controller_runtime_reconcile_total{controller="resourceBinding_status_controller",result="requeue_after"} 0
10controller_runtime_reconcile_total{controller="resourcebinding",result="requeue"} 0
0 6139controller_runtime_reconcile_total{controller="resourcebinding",result="requeue_after"} 0
6controller_runtime_reconcile_total{controller="serviceimport",result="requeue"} 0
 controller_runtime_reconcile_total{controller="serviceimport",result="requeue_after"} 0
 controller_runtime_reconcile_total{controller="work",result="requeue"} 0
 controller_runtime_reconcile_total{controller="work",result="requeue_after"} 0
 controller_runtime_reconcile_total{controller="workload-rebalancer",result="requeue"} 0
0controller_runtime_reconcile_total{controller="workload-rebalancer",result="requeue_after"} 0
 61396    0     0  8595k      0 --:--:-- --:--:-- --:--:-- 9992k
```

But  I can find `workqueue_depth` metric in other controller which  developed by ourselves. The versions of controller-runtime are the same with karmada.

```
curl http://127.0.0.1:8891/metrics  |grep -i queue
controller_runtime_reconcile_total{controller="deployment",result="requeue"} 0
0 15955 controller_runtime_reconcile_total{controller="deployment",result="requeue_after"} 12
   0 15955    0     0   200k      0 --:--:-- --:--:-- --:--:--  202k
# HELP workqueue_adds_total Total number of adds handled by workqueue
# TYPE workqueue_adds_total counter
workqueue_adds_total{name="deployment"} 998
# HELP workqueue_depth Current depth of workqueue
# TYPE workqueue_depth gauge
workqueue_depth{name="deployment"} 0
# HELP workqueue_longest_running_processor_seconds How many seconds has the longest running processor for workqueue been running.
# TYPE workqueue_longest_running_processor_seconds gauge
workqueue_longest_running_processor_seconds{name="deployment"} 0
# HELP workqueue_queue_duration_seconds How long in seconds an item stays in workqueue before being requested
# TYPE workqueue_queue_duration_seconds histogram
workqueue_queue_duration_seconds_bucket{name="deployment",le="1e-08"} 0
```

**What do you think about this question?**:
why  karmada controller can't find metrics workqueue_depth

workqueue_depth is  necessary to check whether there is congestion in the workqueue.

**Environment**:
- Karmada version:
v1.11
- Kubernetes version:
v1.23
- Others:
sigs.k8s.io/controller-runtime v0.18.4

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This pr removes the apiserver dependency on resourceinterpreter. For details about why to remove the apiserver reference, see https://github.com/karmada-io/karmada/pull/5945#issuecomment-2540449813.

This pr is part of #5945. It focuses on removing only the dependency of the apiserver repository, thus directly solving the problem of missing workqueue metrics and facilitating the prcherry-pick to the previous version (v1.10, v1.11 and v1.12).

**Which issue(s) this PR fixes**:
Fixes #5696 
Part of #5954 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed the issue of missing work queue metrics.
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/assign

**Comment by RainbowMango** [comment]
cc @lxtywypc 
Could you please take a look?

File: pkg/resourceinterpreter/customized/webhook/serviceresolvers.go [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+	defaultResolver ServiceResolver
+}
+
+func (r *serviceResolver) ResolveEndpoint(namespace, name string, port int32) (*url.URL, error) {
+	res, err := resolveCluster(r.services, namespace, name, port)
+	if err != nil && apierrors.IsNotFound(err) {
+		return r.defaultResolver.ResolveEndpoint(namespace, name, port)
+	}
+	return res, err
+}
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/webhook/serviceresolvers.go:39]: We can get the service first and 
- if service is not found, then construct service URL from namespace and name.
- if service exists, then construct the service URL from the external URL or cluster IP.

File: pkg/resourceinterpreter/customized/webhook/serviceresolvers.go [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+// resolveCluster parses Service resource to url.
+// It is lifted from https://github.com/kubernetes/apiserver/blob/release-1.31/pkg/util/proxy/proxy.go#L105.
+func resolveCluster(services corev1.ServiceLister, namespace, id string, port int32) (*url.URL, error) {
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/webhook/serviceresolvers.go:43]:
```suggestion
func resolveCluster(namespace, id string, port int32) (*url.URL, error) {
```
We can try to remove the service lister from the function signatures; this will make it easy to build a unit test.

File: pkg/resourceinterpreter/customized/webhook/serviceresolvers.go (hunk 1 above)
Comment (XiShanYongYe-Chang) [reply pkg/resourceinterpreter/customized/webhook/serviceresolvers.go]: updated.

File: pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+							{Name: "https", Port: 443, TargetPort: intstr.FromInt32(1443)},
+							{Port: 1234, TargetPort: intstr.FromInt32(1234)},
+						}}},
+				port: 443,
+			},
+			want:    "https://np:443",
+			wantErr: assert.NoError,
+		},
+		{
+			name: "external name",
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go:104]:
```suggestion
			name: "ExternalName service can be resolved",
```

File: pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+						ClusterIP: "hit",
+						Ports: []corev1.ServicePort{
+							{Port: 1234, TargetPort: intstr.FromInt32(1234)},
+						}}},
+				port: 443,
+			},
+			wantErr: assert.Error,
+		},
+		{
+			name: "cluster ip",
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go:40]:
```suggestion
			name: "ClusterIP service can be resolved",
```

File: pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+			args: args{
+				svc: &corev1.Service{
+					ObjectMeta: metav1.ObjectMeta{Namespace: "one", Name: "alfa"},
+					Spec: corev1.ServiceSpec{
+						Type:      corev1.ServiceTypeClusterIP,
+						ClusterIP: "hit",
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go:46]:
```suggestion
						ClusterIP: "10.10.10.10",
```
Why not use a normal IP?

File: pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+		port int32
+	}
+	tests := []struct {
+		name    string
+		args    args
+		want    string
+		wantErr assert.ErrorAssertionFunc
+	}{
+		{
+			name: "cluster ip without 443 port",
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go:25]:
```suggestion
			name: "ClusterIP service without expected port can not be resolved",
```

File: pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go [hunk 7]
```diff
@@ -0,0 +1,139 @@
...
+							{Name: "https", Port: 443, TargetPort: intstr.FromInt32(1443)},
+							{Port: 1234, TargetPort: intstr.FromInt32(1234)},
+						}}},
+				port: 443,
+			},
+			want:    "https://hit:443",
+			wantErr: assert.NoError,
+		},
+		{
+			name: "none cluster ip",
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go:57]:
```suggestion
			name: "headless service can not be resolved",
```

File: pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go [hunk 8]
```diff
@@ -0,0 +1,139 @@
...
+					Spec: corev1.ServiceSpec{
+						Type:      corev1.ServiceTypeClusterIP,
+						ClusterIP: corev1.ClusterIPNone,
+					}},
+				port: 443,
+			},
+			wantErr: assert.Error,
+		},
+		{
+			name: "loadbalancer",
```
Comment (RainbowMango) [inline pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go:70]:
```suggestion
			name: "LoadBalancer service can be resolved",
```

**Review by RainbowMango — COMMENTED** [review]
Generally looks good, but please
1. organize the tests case by order `normal cases` --> `abnormal cases`, and make sure each test has a meaningful name.
2. Please provide a test report, to show the metrics are emitted as expected from both `karmada-controller-manager` and `karmada-agent`.

**Comment by XiShanYongYe-Chang** [comment]
> organize the tests case by order normal cases --> abnormal cases

Test cases are organized by service type. If all abnormal cases are placed at the end, the organization relationship will be broken.

**Comment by XiShanYongYe-Chang** [comment]
`karmada-controller-manager`:

```
curl http://127.0.0.1:8080/metrics | grep workqueue_work_duration_seconds_sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22344    0 22344    0     0  10.2M      0 --:--:-- --:--:-- --:--:-- 10.6M
workqueue_work_duration_seconds_sum{controller="endpointslice-collect",name="endpointslice-collect"} 0
workqueue_work_duration_seconds_sum{controller="scale target worker",name="scale target worker"} 0
workqueue_work_duration_seconds_sum{controller="service-export",name="service-export"} 0
workqueue_work_duration_seconds_sum{controller="work-status",name="work-status"} 0
```

`karmada-agent`:

```
 curl http://127.0.0.1:8080/metrics | grep workqueue_work_duration_seconds_sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18997    0 18997    0     0  8576k      0 --:--:-- --:--:-- --:--:-- 9275k
workqueue_work_duration_seconds_sum{controller="endpointslice-collect",name="endpointslice-collect"} 0
workqueue_work_duration_seconds_sum{controller="service-export",name="service-export"} 0
workqueue_work_duration_seconds_sum{controller="work-status",name="work-status"} 0
```

**Review by RainbowMango — COMMENTED** [review]
/lgtm

wait @lxtywypc  for a while

**Comment by CharlesQQ** [comment]
Test results were as expected @RainbowMango 
```
# curl http://127.0.0.1:10358/metrics |grep workqueue_depth
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3927    0  3927    0     0   6756      0 --:--:-- --:--:-- --:--:--  6759# HELP workqueue_depth Current depth of workqueue
# TYPE workqueue_depth gauge
workqueue_depth{controller="agent-csr-approving-controller",name="agent-csr-approving-controller"} 0
workqueue_depth{controller="binding-controller",name="binding-controller"} 1712
workqueue_depth{controller="binding-eviction",name="binding-eviction"} 0
workqueue_depth{controller="cluster-binding-eviction",name="cluster-binding-eviction"} 0
workqueue_depth{controller="cluster-controller",name="cluster-controller"} 0
workqueue_depth{controller="cluster-resource-binding-application-failover-controller",name="cluster-resource-binding-application-failover-controller"} 0
workqueue_depth{controller="cluster-resource-binding-controller",name="cluster-resource-binding-controller"} 0
workqueue_depth{controller="cluster-resource-binding-graceful-eviction-controller",name="cluster-resource-binding-graceful-eviction-controller"} 0
workqueue_depth{controller="cluster-resource-binding-status-controller",name="cluster-resource-binding-status-controller"} 0
workqueue_depth{controller="cluster-status-controller",name="cluster-status-controller"} 0
workqueue_depth{controller="clusterPropagationPolicy reconciler",name="clusterPropagationPolicy reconciler"} 0
workqueue_depth{controller="cronfederatedhpa-controller",name="cronfederatedhpa-controller"} 0
workqueue_depth{controller="dependencies resource detector",name="dependencies resource detector"} 993
workqueue_depth{controller="dependencies-distributor",name="dependencies-distributor"} 941
workqueue_depth{controller="endpointslice-controller",name="endpointslice-controller"} 0
workqueue_depth{controller="execution-controller",name="execution-controller"} 4005
workqueue_depth{controller="federated-resource-quota-status-controller",name="federated-resource-quota-status-controller"} 0
workqueue_depth{controller="federated-resource-quota-sync-controller",name="federated-resource-quota-sync-controller"} 0
workqueue_depth{controller="federatedHPA-controller",name="federatedHPA-controller"} 0
workqueue_depth{controller="namespace-sync-controller",name="namespace-sync-controller"} 0
workqueue_depth{controller="propagationPolicy reconciler",name="propagationPolicy reconciler"} 778
workqueue_depth{controller="remedy-controller",name="remedy-controller"} 0
workqueue_depth{controller="resource detector",name="resource detector"} 1019
workqueue_depth{controller="resource-binding-application-failover-controller",name="resource-binding-application-failover-controller"} 0
workqueue_depth{controller="resource-binding-graceful-eviction-controller",name="resource-binding-graceful-eviction-controller"} 0
workqueue_depth{controller="resource-binding-status-controller",name="resource-binding-status-controller"} 0
workqueue_depth{controller="service-export",name="service-export"} 0
workqueue_depth{controller="service-export-controller",name="service-export-controller"} 0
workqueue_depth{controller="service-import-controller",name="service-import-controller"} 0
workqueue_depth{controller="taint-manager",name="taint-manager"} 0
workqueue_depth{controller="unified-auth-controller",name="unified-auth-controller"} 0
workqueue_depth{controller="work-status",name="work-status"} 1992
workqueue_depth{controller="work-status-controller",name="work-status-controller"} 4002
workqueue_depth{controller="workload-rebalancer",name="workload-rebalancer"} 0
```

**Comment by RainbowMango** [comment]
Thanks @CharlesQQ for the feedback.

**Comment by lxtywypc** [comment]
I have finished test in out environment, it works well.  

LGTM.

**Review by RainbowMango — APPROVED** [review]
Great!
Thanks for the confirmation. 

Now, let's fix this on master, and then this will be backported to all affected releases.

/approve
