### PR TITLE
bugfix: support  join 1.24 k8s: auto create secret when sa not create

### LINKED ISSUE #1961: join 1.24版本的k8s的集群会失败
**What happened**:
测试了下join 1.24版本的k8s的集群，发现会失败

日志
```
(base) [root@10-29-22-116 karmada]# kubectl karmada --kubeconfig=/etc/karmada/karmada-apiserver.config join member1 --cluster-kubeconfig=/root/.kube/kind-k8s-1-24 --cluster-context=kind-kind-k8s-1-24 -v 6
I0605 15:40:05.902449  374049 join.go:148] joining cluster. cluster name: member1
I0605 15:40:05.902512  374049 join.go:149] joining cluster. cluster namespace: karmada-cluster
(base) [root@10-29-22-116 karmada]# kubectl karmada --kubeconfig=/etc/karmada/karmada-apiserver.config join member1 --cluster-kubeconfig=/root/.kube/kind-k8s-1-24 --cluster-context=kind-kind-k8s-1-24 -v 6
I0605 16:21:50.706944  430078 join.go:148] joining cluster. cluster name: member1
I0605 16:21:50.707218  430078 join.go:149] joining cluster. cluster namespace: karmada-cluster
I0605 16:21:50.708664  430078 loader.go:372] Config loaded from file:  /etc/karmada/karmada-apiserver.config
I0605 16:21:50.709382  430078 loader.go:372] Config loaded from file:  /root/.kube/kind-k8s-1-24
I0605 16:21:50.710384  430078 join.go:172] joining cluster config. endpoint: https://kind.debug.daozzg.com:57443
I0605 16:21:50.726892  430078 round_trippers.go:553] GET https://172.18.0.7:32443/api/v1/namespaces/karmada-cluster 200 OK in 16 milliseconds
I0605 16:21:50.748153  430078 round_trippers.go:553] GET https://kind.debug.daozzg.com:57443/api/v1/namespaces/karmada-cluster 200 OK in 19 milliseconds
I0605 16:21:50.750648  430078 round_trippers.go:553] GET https://kind.debug.daozzg.com:57443/api/v1/namespaces/karmada-cluster/serviceaccounts/karmada-member1 200 OK in 1 milliseconds
I0605 16:21:50.758322  430078 round_trippers.go:553] GET https://kind.debug.daozzg.com:57443/api/v1/namespaces/karmada-cluster/serviceaccounts/karmada-impersonator 200 OK in 6 milliseconds
I0605 16:21:50.760966  430078 round_trippers.go:553] GET https://kind.debug.daozzg.com:57443/apis/rbac.authorization.k8s.io/v1/clusterroles/karmada-controller-manager:karmada-member1 200 OK in 2 milliseconds
I0605 16:21:50.761387  430078 join.go:367] ensure ClusterRole succeed as already exist. ClusterRole: karmada-controller-manager:karmada-member1
I0605 16:21:50.763847  430078 round_trippers.go:553] GET https://kind.debug.daozzg.com:57443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/karmada-controller-manager:karmada-member1 200 OK in 2 milliseconds
I0605 16:21:50.764051  430078 join.go:391] ensure ClusterRole succeed as already exist. ClusterRole: karmada-controller-manager:karmada-member1
I0605 16:21:51.767682  430078 round_trippers.go:553] GET https://kind.debug.daozzg.com:57443/api/v1/namespaces/karmada-cluster/serviceaccounts/karmada-member1 200 OK in 2 milliseconds
Error: failed to get serviceAccount secret from cluster(member1), error: failed to get serviceAccount secret, error: no specific secret found in namespace: karmada-cluster
(base) [root@10-29-22-116 karmada]# 
```

**What you expected to happen**:
join 成功

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl karmada --kubeconfig=/etc/karmada/karmada-apiserver.config join member1 --cluster-kubeconfig=/root/.kube/kind-k8s-1-24 --cluster-context=kind-kind-k8s-1-24 -v 6
```
**Anything else we need to know?**:

排查发现是因为新版本的k8s 不会自动为sa创建secret 导致的
image

参考这里 :
https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets
image

在https://github.com/karmada-io/karmada/blob/master/pkg/util/serviceaccount.go#L76  增加当sa.secrets为空时，创建secret
再次测试，发现join 成功

是否可以这样修复？

**Environment**: kind 
- Karmada version: v1.2.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.2.0
- Others:

### PR DESCRIPTION
**Pull request by zgfh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
support  join 1.24 k8s  
**Which issue(s) this PR fixes**:
Fixes #1961

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by calvin0327** [comment]
image
code lint.

File: pkg/util/serviceaccount.go [hunk 1]
```diff
@@ -83,7 +83,25 @@ func WaitForServiceAccountSecretCreation(client kubeclient.Interface, asObj *cor
 			}
 			return false, fmt.Errorf("failed to retrieve service account(%s/%s) from cluster, err: %v", asObj.Namespace, asObj.Name, err)
 		}
-		clusterSecret, err = GetTargetSecret(client, serviceAccount.Secrets, corev1.SecretTypeServiceAccountToken, asObj.Namespace)
+		if len(serviceAccount.Secrets) == 0 {
```
Comment (XiShanYongYe-Chang) [inline pkg/util/serviceaccount.go:86]: Is it possible that the secret of the serviceAccount is being created but has not been created successfully?

File: pkg/util/serviceaccount.go [hunk 2]
```diff
@@ -83,7 +83,25 @@ func WaitForServiceAccountSecretCreation(client kubeclient.Interface, asObj *cor
...
+				ObjectMeta: metav1.ObjectMeta{
+					Namespace: serviceAccount.Namespace,
+					Name:      serviceAccount.Name,
+					Annotations: map[string]string{
+						"kubernetes.io/service-account.name": serviceAccount.Name,
+					},
+				},
+				Type: corev1.SecretTypeServiceAccountToken,
+			}
+			clusterSecret, err = CreateSecret(client, secret)
```
Comment (XiShanYongYe-Chang) [inline pkg/util/serviceaccount.go:97]: Is it possible that the token information is not generated for the newly created secret?

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Just guess some possible scenarios.

File: pkg/util/serviceaccount.go (hunk 1 above)
Comment (RainbowMango) [reply pkg/util/serviceaccount.go:86]: Good point.

Comment (XiShanYongYe-Chang) [reply pkg/util/serviceaccount.go:86]: For kubernetes clusters with versions smaller than v1.22, no token will be generated when a secret is created for ServiceAccount.

Maybe we need to wait a while for the creation of `serviceAccount secret token`, if timeout, we can create the secret.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
For kubernetes clusters with versions smaller than v1.22, no token will be generated when a secret is created for ServiceAccount.

Maybe we need to wait a while for the creation of serviceAccount secret token, if timeout, we can create the secret.

**Comment by zgfh** [comment]
> For kubernetes clusters with versions smaller than v1.22, no token will be generated when a secret is created for ServiceAccount.
> 
> Maybe we need to wait a while for the creation of serviceAccount secret token, if timeout, we can create the secret.

it will be ok ,becuse it will check again , Until one of the two ways creates the correct secret

**Comment by XiShanYongYe-Chang** [comment]
> it will be ok ,becuse it will check again , Until one of the two ways creates the correct secret

Ok, I got it.

Just one more question: for the secret name created manually, directly using serviceaccount's name may be too simple, which may cause conflicts with existing secrets.

**Comment by calvin0327** [comment]
`generateName` is better?

**Comment by XiShanYongYe-Chang** [comment]
> `generateName` is better?

I think generating the secret name with a random string will be better.

**Comment by calvin0327** [comment]
```golang
secret := &corev1.Secret{
	ObjectMeta: metav1.ObjectMeta{
		Namespace:  serviceAccount.Namespace,
		GenerateName:  fmt.Sprintf("%s-token-", serviceAccount.Name)
		Annotations: map[string]string{
			"kubernetes.io/service-account.name": serviceAccount.Name,
		},
	},
	Type: corev1.SecretTypeServiceAccountToken,
}
```

@XiShanYongYe-Chang you are right, a random string will be better.  GenerateName can be used directly to generate random names with prefix. e.g : `member1-impersonator-token-lfg48`. what do you think?

**Comment by XiShanYongYe-Chang** [comment]
@calvin0327  I agree with you.

File: pkg/util/serviceaccount.go [hunk 3]
```diff
@@ -83,14 +83,34 @@ func WaitForServiceAccountSecretCreation(client kubeclient.Interface, asObj *cor
 			}
 			return false, fmt.Errorf("failed to retrieve service account(%s/%s) from cluster, err: %v", asObj.Namespace, asObj.Name, err)
 		}
-		clusterSecret, err = GetTargetSecret(client, serviceAccount.Secrets, corev1.SecretTypeServiceAccountToken, asObj.Namespace)
+		if len(serviceAccount.Secrets) == 0 {
```
Comment (liggitt) [inline pkg/util/serviceaccount.go:86]: triggering off the length of this list is not really correct... this list can contain the names of non-token secrets

File: pkg/util/serviceaccount.go [hunk 4]
```diff
@@ -83,14 +83,34 @@ func WaitForServiceAccountSecretCreation(client kubeclient.Interface, asObj *cor
...
+		}
+
 		if err != nil {
 			if apierrors.IsNotFound(err) {
 				return false, nil
 			}
 			return false, err
 		}
-
+		if _, ok := clusterSecret.Data["token"]; !ok {
```
Comment (liggitt) [inline pkg/util/serviceaccount.go:111]: after creating `clusterSecret`, you need to wait for the token controller to populate the Data["token"] field

File: pkg/util/serviceaccount.go (hunk 3 above)
Comment (RainbowMango) [reply pkg/util/serviceaccount.go:86]: Thanks for the reminder.

File: pkg/util/serviceaccount.go (hunk 4 above)
Comment (RainbowMango) [reply pkg/util/serviceaccount.go:111]: +1
Yes, it is the `token` we should waiting for, not the `secret`.

**Review by RainbowMango — COMMENTED** [review]
Hi @liggitt , 
I'm so excited to meet you here!!! Appreciate your comments.
Thank you!

File: pkg/util/serviceaccount.go (hunk 4 above)
Comment (zgfh) [reply pkg/util/serviceaccount.go:111]: I'm not sure if I understand correctly
wait already existed:
https://github.com/karmada-io/karmada/pull/1972/files#diff-b8f6d51c2457af24cffeb6f3b26e7b35f3df727ce4a851e082bfae84742f124aL78

so ,there just return false ,it will check again

File: pkg/util/serviceaccount.go (hunk 3 above)
Comment (zgfh) [reply pkg/util/serviceaccount.go:86]: any better idea for this? 

should we just create the secret all the time? i test it work with k8s 1.18,1.23,1.24

Comment (liggitt) [reply pkg/util/serviceaccount.go:86]: Yes. If you are using a secret based token, you should create it, not use the auto-generated one

**Comment by zgfh** [comment]
> > if we use random，how to find it by sa？
> 
> Sorry, am I missing some scenes? Can you help point out when do we need to find it by `sa`.
@XiShanYongYe-Chang 
https://github.com/karmada-io/karmada/pull/1972/files#diff-b8f6d51c2457af24cffeb6f3b26e7b35f3df727ce4a851e082bfae84742f124aL76

see here,I'm not sure if I understand correctly

this method return secret for a sa, if use random, how to find the existed secret?

**Comment by zgfh** [comment]
> > this method return secret for a sa, if use random, how to find the existed secret?
> 
> 
> 
> I think we can generate a secret name before waiting to get or create the target secret.

if that，should we just generate a random sa？

**Comment by XiShanYongYe-Chang** [comment]
> if that，should we just generate a random sa？

It also will be ok. IMOP, just trying to keep the same way as Kubernetes: 

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/tokens_controller.go#L392

**Comment by zgfh** [comment]
thanks all for help this
Is there anything else that needs to be fixed?

File: pkg/util/serviceaccount.go [hunk 5]
```diff
@@ -83,14 +83,26 @@ func WaitForServiceAccountSecretCreation(client kubeclient.Interface, asObj *cor
...
-			if apierrors.IsNotFound(err) {
-				return false, nil
+		clusterSecret, err = GetSecret(client, serviceAccount.Namespace, serviceAccount.Name)
+		if apierrors.IsNotFound(err) {
+			secret := &corev1.Secret{
+				ObjectMeta: metav1.ObjectMeta{
+					Namespace: serviceAccount.Namespace,
+					Name:      serviceAccount.Name,
+					Annotations: map[string]string{
+						"kubernetes.io/service-account.name": serviceAccount.Name,
```
Comment (XiShanYongYe-Chang) [inline pkg/util/serviceaccount.go:93]: We can use `corev1.ServiceAccountNameKey` here.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
@zgfh Thanks! 

Other parts look good to me.

File: pkg/util/serviceaccount.go (hunk 5 above)
Comment (zgfh) [reply pkg/util/serviceaccount.go]: fixed,thanks

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

File: pkg/util/secret.go [hunk 6]
```diff
@@ -38,6 +38,11 @@ func GetTargetSecret(client kubeclient.Interface, secretReferences []corev1.Obje
 	return nil, errNotFound
 }
 
+// GetSecret just try to get the secret.
+func GetSecret(client kubeclient.Interface, namespace, name string) (*corev1.Secret, error) {
+	return client.CoreV1().Secrets(namespace).Get(context.TODO(), name, metav1.GetOptions{})
+}
+
```
[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/util/secret.go:45]: It may be consistent with other operations on Secret. Therefore, it is abstracted as a method.

[the remark this answers is not in the document]
Comment (RainbowMango) [reply pkg/util/secret.go:45]: consistent with what operation?

[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/util/secret.go:45]: `CreateSecret`, `PatchSecret` and `GetTargetSecret`.

[the remark this answers is not in the document]
Comment (RainbowMango) [reply pkg/util/secret.go:45]: Fine. We can improve it later.
/approve

**Comment by XiShanYongYe-Chang** [comment]
Hi @zgfh, would you mind syncing this change to the previous version?

You can refer to https://github.com/karmada-io/karmada/blob/master/docs/contributors/devel/cherry-picks.md

**Comment by zgfh** [comment]
> Hi @zgfh, would you mind syncing this change to the previous version?
> 
> You can refer to https://github.com/karmada-io/karmada/blob/master/docs/contributors/devel/cherry-picks.md

happy to do
but need some help: Which branches need fixing,  v0.9, v0.10, v1.0, v1.1,, v1.12?

**Comment by RainbowMango** [comment]
v1.12, v1.11 and v1.10. We currently maintain the last 3 releases.
