### PR TITLE
work: fix workload name conflicts

### LINKED ISSUE #358: work: name conflicts when different workloads have the same name
**What happened**:
When different workload have the same name, the *work* that creating by the *ResourceBindingController* will have the same name in one *ExecutionSpaceName*, which would cause execution chaos. 

Reason: The work's name is the same with the resource binding, but it's namespace is associated with cluster. I suggest to adding namespace to generate works' name. 
https://github.com/karmada-io/karmada/blob/7a0d6c9b8c49919752b63eb710962f95f52dc2f3/pkg/util/helper/binding.go#L177-L182

**What you expected to happen**:
The work's name may contain namespace to distinguish with each other.

**How to reproduce it (as minimally and precisely as possible)**:
For example:
I create 2 deployment in 2 different namespace but having the same name, only one work will be created. When I delete them, the member cluster also runs one of a deployment which may cause resource leak.

```bash
[root@garryfang /data/garryfang/karmada/samples/nginx]# kubectl get deployments.apps -A
NAMESPACE   NAME    READY   UP-TO-DATE   AVAILABLE   AGE
garrytest   nginx   2/2     2            2           23s
lynntest    nginx   10/10   10           10          84s
```

```bash
[root@garryfang /data/garryfang/karmada/samples/nginx]# kubectl get works.work.karmada.io -A
NAMESPACE            NAME                  AGE
karmada-es-member1   garrytest-namespace   23h
karmada-es-member1   lynntest-namespace    4d12h
karmada-es-member1   nginx-deployment      99s
karmada-es-member2   garrytest-namespace   23h
karmada-es-member2   lynntest-namespace    4d12h
karmada-es-member3   garrytest-namespace   23h
karmada-es-member3   lynntest-namespace    4d12h
```
Only one work exists.

**Anything else we need to know?**:

**Environment**:
- Karmada version: latest
- Others:

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #358

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/controllers/status/workstatus_controller.go [hunk 1]
```diff
@@ -198,7 +198,7 @@ func (c *WorkStatusController) handleDeleteEvent(key keys.FederatedKey) error {
 
 	// Given the workload might has been deleted from informer cache, so that we can't get work object by it's label,
 	// we have to get work by naming rule as work's name also is binding's name and binding's name consist of workload's name and kind.
```
Comment (RainbowMango) [inline pkg/controllers/status/workstatus_controller.go:200]: The comment needs an update as well, right?

Comment (Garrybest) [reply pkg/controllers/status/workstatus_controller.go:200]: Right👍, I will fix it.

**Review by RainbowMango — APPROVED** [review]
Thanks for doing this. :)
