### PR TITLE
fix: apply ClusterFailureThreshold to ClusterClientSetFunc errors

### LINKED ISSUE #7408: Apply ClusterFailureThreshold to ClusterClientSetFunc failures
## Problem

`syncClusterStatus` has two paths to `Ready=False`, but only one respects `ClusterFailureThreshold`:

| Path | Threshold-protected? |
|---|---|
| A: probe failure | Yes: `thresholdAdjustedReadyCondition` |
| B: `ClusterClientSetFunc` failure | **No**: `setStatusCollectionFailedCondition` writes `Ready=False` immediately |

By default, a cluster that is genuinely unreachable over the network gets 30 seconds of grace. A local
credential configuration error (which may be transient and self-healing) gets none. This
asymmetry causes spurious `Ready=False` transitions that can trigger workload failover for
clusters that were never actually unhealthy. Each such transition also fires cluster health
alerts, generating operational toil and eroding confidence in alerting over time.

```mermaid
flowchart TD
    A[syncClusterStatus] --> B[ClusterClientSetFunc\nreads Cluster.Spec.SecretRef\nfrom local cache]

    B -->|error| C["setStatusCollectionFailedCondition\n(no threshold)"]
    C --> D[Ready=False written immediately ❌]

    B -->|success| E[getClusterHealthStatus\nnetwork probe to member cluster]
    E --> F[generateReadyCondition]
    F --> G[thresholdAdjustedReadyCondition\nClusterFailureThreshold applied]
    G -->|within threshold| H[Ready=True retained ✅]
    G -->|threshold elapsed| I[Ready=False written ✅]

```

## A Common Operational Pattern on Managed Platforms That Hits This

At Bloomberg, we run a managed multi-cluster platform built atop Karmada. As part of each control plane, we run a cluster registration sub-system to fully automate member cluster registration. In that sub-system, we have two main components:
- cluster-registration-controller: Registers clusters for Karmada.
- cluster-credentials-controller: Provides Karmada with credentials for registered clusters by creating and rotating short-lived JWTs and populating `SecretRef` on `Cluster` objects.

An erroneous spec update from the registration controller that does not preserve `SecretRef` transiently clears it. The credentials controller will restore it, but if the Karmada status controller reconciles the cluster before the ref is restored, it will write `Ready=False` immediately with no tolerance window.

We observed this exact failure in our environment, with log messages like the following appearing in the Karmada controller manager log streams:
```
E0415 20:13:46.794325       1 cluster_status_controller.go:193] Failed to create a ClusterClient for the given member cluster: region1-test-01, err is : cluster region1-test-01 does not have a secret
```

The registration controller issue is being fixed on our side. This request of change in the controller manager will add an extra safe guard to mitigate these type of false alarms that can cause panic, specially in production environments.

## Behaviour Change

| Scenario | Before | After |
|---|---|---|
| First failed reconcile; cluster was `Ready=True` | Immediate `Ready=False` | `Ready=True` retained; threshold timer starts |
| Failure resolves within `ClusterFailureThreshold` | `Ready=False` written; flips back on next pass | `Ready=True` retained throughout; zero churn |
| Failure persists beyond `ClusterFailureThreshold` | `Ready=False` (already written) | `Ready=False` written |
| First reconcile after Karmada controller manager restart (cache empty) | Immediate `Ready=False` | Same: no threshold protection without cache |

### PR DESCRIPTION
**Pull request by Tej-Katika**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

`syncClusterStatus` has two paths that can write `Ready=False`, but only the network probe path respects `ClusterFailureThreshold`. When `ClusterClientSetFunc` fails (e.g. a `SecretRef` that is transiently missing during credential rotation), `Ready=False` is written immediately with no grace period — bypassing `thresholdAdjustedReadyCondition` entirely.

This causes spurious failovers on clusters that are perfectly healthy; Karmada just couldn't build a client for one reconcile cycle.

The fix routes the client build error through the same `thresholdAdjustedReadyCondition` logic used by the probe path. If the cluster was `Ready=True` and the error clears within `ClusterFailureThreshold`, the condition is retained and no failover fires. If the failure persists beyond the threshold, `Ready=False` is written as before.

The `setStatusCollectionFailedCondition` helper is removed since it is now unused.

**Which issue(s) this PR fixes**:

Fixes #7408

**Special notes for your reviewer**:

The behavior table from the issue:

| Scenario | Before | After |
|---|---|---|
| First failed reconcile; cluster was `Ready=True` | Immediate `Ready=False` | `Ready=True` retained; threshold timer starts |
| Failure resolves within `ClusterFailureThreshold` | `Ready=False` written; flips back next pass | `Ready=True` retained throughout; no churn |
| Failure persists beyond `ClusterFailureThreshold` | `Ready=False` (already written) | `Ready=False` written |
| Cold start (cache empty after controller restart) | Immediate `Ready=False` | Same — no protection without prior cache entry |

Two new test cases added to `TestClusterStatusController_syncClusterStatus`:
- `ClusterClientSetFunc error within threshold retains Ready=True`
- `ClusterClientSetFunc error beyond threshold writes Ready=False`

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed the issue that a transient `ClusterClientSetFunc` failure (e.g. missing `SecretRef` during credential rotation) would immediately set the cluster `Ready=False` without respecting `ClusterFailureThreshold`, potentially triggering unnecessary workload failover.
```

### CODE REVIEW

**Comment by jabellard** [comment]
@Tej-Katika , thanks for working on this.

The scope of the change looks broader than I expected though. Can you please explain why they are also changes in the scheduler directory?

**Review by RainbowMango — COMMENTED** [review]
/assign

**Comment by Tej-Katika** [comment]
> @Tej-Katika , thanks for working on this.
> 
> The scope of the change looks broader than I expected though. Can you please explain why they are also changes in the scheduler directory?

Hey @jabellard, good catch. Those scheduler changes came in because this branch was created on top of another branch I   had open at the time for a separate PR. They're completely unrelated to this fix. I'll rebase onto master to drop them and keep only the changes relevant to this issue.

**Comment by jabellard** [comment]
Thanks @Tej-Katika for this awesome contribution for a very serious problem of very dire consequences. 

As your first contribution, this is super impressive, and I look forward to other awesome contributions from you in the future.

Generally looks good!
/lgtm

/cc @RainbowMango @XiShanYongYe-Chang for another look.

File: pkg/controllers/status/cluster_status_controller_test.go [hunk 1]
```diff
@@ -228,6 +229,124 @@ func TestClusterStatusController_syncClusterStatus(t *testing.T) {
 		err := c.syncClusterStatus(context.Background(), cluster)
 		assert.Empty(t, err)
 	})
+	t.Run("ClusterClientSetFunc error within threshold retains Ready=True", func(t *testing.T) {
```
Comment (XiShanYongYe-Chang) [inline pkg/controllers/status/cluster_status_controller_test.go:232]: The final check of this test truly achieves the purpose of the test 👍, and I think it can directly replace the previous UT case "ClusterClientSetFunc returns error."

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~, can you help squash the commits into one?

**Comment by RainbowMango** [comment]
/lgtm

The implementation looks good to me — the threshold-adjusted ready condition logic effectively prevents cluster status flapping due to transient network issues.

As @XiShanYongYe-Chang requested above, would you mind [tidying the commits](https://karmada.io/docs/next/contributor/github-workflow/#squash-commits)?

**Comment by Tej-Katika** [comment]
Squashed the commits. 

/cc @RainbowMango @XiShanYongYe-Chang @jabellard

**Comment by RainbowMango** [comment]
/retest
unrelated https://github.com/karmada-io/karmada/actions/runs/24873208667/job/72824621525?pr=7426
```
[FAILED] in [It] - /home/runner/work/karmada/karmada/test/e2e/suites/base/karmadactl_test.go:596 @ 04/24/26 05:34:41.122
  STEP: Removing PropagationPolicy(karmadatest-zvhdk/pod-8x9sq) @ 04/24/26 05:34:41.3
  STEP: Removing Pod(karmadatest-zvhdk/pod-zrrvz) @ 04/24/26 05:34:41.318
  << Timeline

  [FAILED] Unexpected error:
      <exec.CodeExitError>: 
      error running /home/runner/go/bin/karmadactl --kubeconfig=/home/runner/.kube/karmada.config --karmada-context=karmada-apiserver --namespace=karmadatest-zvhdk top pod pod-zrrvz -n karmadatest-zvhdk -C member3:
      Command stdout:
      
      stderr:
      error: cluster(member3): podmetrics.metrics.k8s.io "karmadatest-zvhdk/pod-zrrvz" not found
      
      error:
      exit status 1
      {
          Err: <*errors.errorString | 0xc0007c7eb0>{
              s: "error running /home/runner/go/bin/karmadactl --kubeconfig=/home/runner/.kube/karmada.config --karmada-context=karmada-apiserver --namespace=karmadatest-zvhdk top pod pod-zrrvz -n karmadatest-zvhdk -C member3:\nCommand stdout:\n\nstderr:\nerror: cluster(member3): podmetrics.metrics.k8s.io \"karmadatest-zvhdk/pod-zrrvz\" not found\n\nerror:\nexit status 1",
          },
          Code: 1,
      }
  occurred
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/suites/base/karmadactl_test.go:596 @ 04/24/26 05:34:41.122

  Full Stack Trace
    github.com/karmada-io/karmada/test/e2e/suites/base.init.func33.2.2.1()
    	/home/runner/work/karmada/karmada/test/e2e/suites/base/karmadactl_test.go:596 +0x85
    github.com/karmada-io/karmada/test/e2e/suites/base.init.func33.2.2()
    	/home/runner/work/karmada/karmada/test/e2e/suites/base/karmadactl_test.go:592 +0x90
```

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
Thanks @Tej-Katika for taking this!

**Comment by jabellard** [comment]
@RainbowMango @XiShanYongYe-Chang , should we backport this?

**Comment by jabellard** [comment]
I created [this issue to track backporting](https://github.com/karmada-io/karmada/issues/7428).

I have some team mates who want to contribute to Karmada. They'll be sending PRs soon.

**Comment by XiShanYongYe-Chang** [comment]
> @RainbowMango @XiShanYongYe-Chang , should we backport this?

I think it's necessary

> I have some team mates who want to contribute to Karmada. They'll be sending PRs soon.

Looking forward to it :)

**Comment by RainbowMango** [comment]
We can do that if you think it's necessary in your deployment. 
By the way, there is a patch at the end of this month.
