### PR TITLE
Correct DNSNames of karmada-apiserver certificate in operator installation mode

### LINKED ISSUE #4322: In operator installation mode, controller-manager restarts continuously
**What happened**:
In operator installation mode, ```controller-manager``` restarts continuously.
**What you expected to happen**:
Component ```controller-manager``` works normally and does not restart
**How to reproduce it (as minimally and precisely as possible)**:
- Follow the [tutorial](https://github.com/karmada-io/karmada/blob/master/operator/README.md) to install ```karmada```
- waitting for about 3 minutes, and exec ```kubectl get pods -A|grep controller-manager```
```bash
➜  karmada git:(master) ✗ kubectl get pods -A|grep controller-manager
kube-system          kube-controller-manager-karmada-host-control-plane      1/1     Running            0              33m
test                 karmada-demo-controller-manager-7d7b866f4f-6fl5c        0/1     CrashLoopBackOff   6 (4m7s ago)   28m
test                 karmada-demo-kube-controller-manager-675567bb57-g6kxs   1/1     Running            0              28m
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Correct DNSNames of karmada-apiserver certificate in operator installation mode
**Which issue(s) this PR fixes**:
Fixes #4322

**Special notes for your reviewer**:
NONE
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by chaunceyjiang — COMMENTED** [review]
/lgtm

**Comment by chaunceyjiang** [comment]
We just discovered this issue. It was introduced by #4210.

**Comment by calvin0327** [comment]
/lgtm 

@zhzhuang-zju Indeed, we need add DNS `*.karmada-system.svc` to certs. thanks for doing this.

File: operator/pkg/certs/certs.go [hunk 1]
```diff
@@ -473,8 +473,8 @@ func apiServerAltNamesMutator(cfg *AltNamesMutatorConfig) (*certutil.AltNames, e
 			"kubernetes",
 			"kubernetes.default",
 			"kubernetes.default.svc",
-			fmt.Sprintf("*.%s.svc.cluster.local", cfg.Namespace),
-			fmt.Sprintf("*.%s.svc", cfg.Namespace),
+			fmt.Sprintf("*.%s.svc.cluster.local", constants.KarmadaSystemNamespace),
```
Comment (calvin0327) [inline operator/pkg/certs/certs.go:476]: Indeed, we need to add dns `*.karmada-system.svc.cluster.local` to certs.
Whether we should keep the previous dns？

Comment (zhzhuang-zju) [reply operator/pkg/certs/certs.go:476]: In fact, previous dns is not used. I will post the verification report later

**Comment by zhzhuang-zju** [comment]
Verification report：
- Follow the [tutorial](https://github.com/karmada-io/karmada/blob/master/operator/README.md) to install karmada
- Generate kubeconfig of  karmada-apiserver
```bash
kubectl get secret -n test karmada-demo-admin-config -o jsonpath={.data.kubeconfig} | base64 -d > ~/.kube/karmada-apiserver.config
```
- View apiserver resources
```bash
➜  karmada git:(master) ✗ export KUBECONFIG=~/.kube/karmada-apiserver.config         
➜  karmada git:(master) ✗ kubectl describe apiservice v1beta1.custom.metrics.k8s.io  
Name:         v1beta1.custom.metrics.k8s.io
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2023-11-27T03:27:06Z
  Resource Version:    613
  UID:                 3371991b-4076-4a20-95d8-c9d4bace4e2d
Spec:
  Ca Bundle:               LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcllYSnQKWVdSaE1CNFhEVEl6TVRFeU56QXpNakl5TTFvWERUTXpNVEV5TkRBek1qSXlNMW93RWpFUU1BNEdBMVVFQXhNSAphMkZ5YldGa1lUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtTUE0wVmM3dlRDCnRIcG44ZGsvakdPR0FMRFNYTXRmQXI3L1UyNFRTejhTalUzQ0MweEJtVDc0VUw4eEltNXZyWlhhQlMyZTQxemMKT2Z1VWZyeTF4WW9WdTA0ZTdadCtZeTNSNHpubG5HMVBLZDVvS3gxU3JjYjJXMHJ3KzR6MDgrdWZVUGk3bnA5QgpGQitOQmh0ZUdkMG1zeWdzc0llbGtGemtxRmxBQXE4VXJHbk9MZHZlMzFzZWJUQ3liRzd5Yk5FeUJJckhTdWZNCldDNk9VS0tmc3BIeGtOUUhhS0pGYTZSNHR6aURtSUZUWkppM1I1T3dTUDQzRDNrU1pZSWtkNENCeGY2ZkcxNVEKaitEZkp6QUl5UWV6LzNTSnY3MG1ST1Jna0NEc01VSi92RkpjWTRGZ1V0TGpVR2dHOFJjOTIzd0YzdHFXSk5tdQprWE1SN29UbXBrVUNBd0VBQWFOV01GUXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGTnJmRWc0VlZuWHNjeTdUVHdkL0gyb3g1WVllTUJJR0ExVWRFUVFMTUFtQ0IydGgKY20xaFpHRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRmpoQ0lJclJoM2MrekI3aFdmNWU4UVJkSUZBdHRORQpNZWlNaGRpUHVkdkJwbTQwR2ZxUjBITnFxaG5EekdOKzlNTGlFYVFzQXZ5VVBmdEV1aDBIWCtRRERvS1loRFpTCjBDUGF1MWloSDlUdnNWM1dKR3FqVUVnYXFVV0dnTW1zSW12ZE5nZG5acnZnSDNkVDJwcHc2NFZYM1crYVRwbmMKT0JmVDkyTzNFaXVBTk9IK1VtQURXRGpkdzR5K2dBVWpwRHE1TlFNZzNUSkY4dG9XN3lkZlpCV0pUMG1keVlxYwpBY2hWUmNpL1FQeXRVR3dPTmJ4WTQrejBwSTQ4Y2t4VVUrWURzeGVNdjE3ZHE3TzRQZFUzK2dyWWRIaTl0Nm9lCldmRzVwOGRKbFFsQ3Q0dHd0TEk5Y1Q0MjgxdzdQV2dBTjhQaDNlbUFOSDlCQnhUZHl0djd3N1U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  Group:                   custom.metrics.k8s.io
  Group Priority Minimum:  100
  Service:
    Name:            karmada-demo-metrics-adapter
    Namespace:       karmada-system
    Port:            443
  Version:           v1beta1
  Version Priority:  200
Status:
  Conditions:
    Last Transition Time:  2023-11-27T03:27:06Z
    Message:               all checks passed
    Reason:                Passed
    Status:                True
    Type:                  Available
Events:                    <none>
➜  karmada git:(master) ✗ kubectl describe apiservice v1alpha1.cluster.karmada.io    
Name:         v1alpha1.cluster.karmada.io
Namespace:    
Labels:       apiserver=true
              app=karmada-aggregated-apiserver
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2023-11-27T03:24:47Z
  Resource Version:    260
  UID:                 ef7e6a2d-ec8e-438a-bad3-57c173a766e7
Spec:
  Ca Bundle:               LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcllYSnQKWVdSaE1CNFhEVEl6TVRFeU56QXpNakl5TTFvWERUTXpNVEV5TkRBek1qSXlNMW93RWpFUU1BNEdBMVVFQXhNSAphMkZ5YldGa1lUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtTUE0wVmM3dlRDCnRIcG44ZGsvakdPR0FMRFNYTXRmQXI3L1UyNFRTejhTalUzQ0MweEJtVDc0VUw4eEltNXZyWlhhQlMyZTQxemMKT2Z1VWZyeTF4WW9WdTA0ZTdadCtZeTNSNHpubG5HMVBLZDVvS3gxU3JjYjJXMHJ3KzR6MDgrdWZVUGk3bnA5QgpGQitOQmh0ZUdkMG1zeWdzc0llbGtGemtxRmxBQXE4VXJHbk9MZHZlMzFzZWJUQ3liRzd5Yk5FeUJJckhTdWZNCldDNk9VS0tmc3BIeGtOUUhhS0pGYTZSNHR6aURtSUZUWkppM1I1T3dTUDQzRDNrU1pZSWtkNENCeGY2ZkcxNVEKaitEZkp6QUl5UWV6LzNTSnY3MG1ST1Jna0NEc01VSi92RkpjWTRGZ1V0TGpVR2dHOFJjOTIzd0YzdHFXSk5tdQprWE1SN29UbXBrVUNBd0VBQWFOV01GUXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGTnJmRWc0VlZuWHNjeTdUVHdkL0gyb3g1WVllTUJJR0ExVWRFUVFMTUFtQ0IydGgKY20xaFpHRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRmpoQ0lJclJoM2MrekI3aFdmNWU4UVJkSUZBdHRORQpNZWlNaGRpUHVkdkJwbTQwR2ZxUjBITnFxaG5EekdOKzlNTGlFYVFzQXZ5VVBmdEV1aDBIWCtRRERvS1loRFpTCjBDUGF1MWloSDlUdnNWM1dKR3FqVUVnYXFVV0dnTW1zSW12ZE5nZG5acnZnSDNkVDJwcHc2NFZYM1crYVRwbmMKT0JmVDkyTzNFaXVBTk9IK1VtQURXRGpkdzR5K2dBVWpwRHE1TlFNZzNUSkY4dG9XN3lkZlpCV0pUMG1keVlxYwpBY2hWUmNpL1FQeXRVR3dPTmJ4WTQrejBwSTQ4Y2t4VVUrWURzeGVNdjE3ZHE3TzRQZFUzK2dyWWRIaTl0Nm9lCldmRzVwOGRKbFFsQ3Q0dHd0TEk5Y1Q0MjgxdzdQV2dBTjhQaDNlbUFOSDlCQnhUZHl0djd3N1U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  Group:                   cluster.karmada.io
  Group Priority Minimum:  2000
  Service:
    Name:            karmada-demo-aggregated-apiserver
    Namespace:       karmada-system
    Port:            443
  Version:           v1alpha1
  Version Priority:  10
Status:
  Conditions:
    Last Transition Time:  2023-11-27T03:24:47Z
    Message:               all checks passed
    Reason:                Passed
    Status:                True
    Type:                  Available
Events:                    <none>
```
- check pods status. There is no restart after 22 hours of installation.
```bash
➜  karmada git:(master) ✗ export KUBECONFIG=~/.kube/karmada-host.config     
➜  karmada git:(master) ✗ kubectl get pods -ntest
NAME                                                    READY   STATUS    RESTARTS   AGE
karmada-demo-aggregated-apiserver-6bff9584dc-lj7qd      1/1     Running   0          22h
karmada-demo-apiserver-65c9b44dc5-7zl52                 1/1     Running   0          22h
karmada-demo-controller-manager-7d7b866f4f-6ndqd        1/1     Running   0          22h
karmada-demo-etcd-0                                     1/1     Running   0          22h
karmada-demo-kube-controller-manager-675567bb57-c8klf   1/1     Running   0          22h
karmada-demo-metrics-adapter-7b59b645b9-6877p           1/1     Running   0          22h
karmada-demo-metrics-adapter-7b59b645b9-sl8sp           1/1     Running   0          22h
karmada-demo-scheduler-79887875d8-rls2h                 1/1     Running   0          22h
karmada-demo-webhook-76775c8f65-hjjz6                   1/1     Running   0          22h
```
- View certificate DNS
```bash
➜  karmada git:(master) ✗ echo $(cat ~/.kube/karmada-apiserver.config| grep "client-certificate-data"| awk '{print $2}')| base64 -d  >apiserver.pem
➜  karmada git:(master) ✗ openssl x509 -noout -text -in apiserver.pem                                                                              
...
            X509v3 Subject Alternative Name: 
                DNS:*.karmada-system.svc, DNS:*.karmada-system.svc.cluster.local, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:localhost, IP Address:127.0.0.1, IP Address:172.18.0.2
...       
```

**Review by RainbowMango — APPROVED** [review]
/approve

File: operator/pkg/certs/certs.go (hunk 1 above)
Comment (chaunceyjiang) [reply operator/pkg/certs/certs.go:476]: /cc @zhzhuang-zju Have you ever tested creating a pp?

Comment (zhzhuang-zju) [reply operator/pkg/certs/certs.go:476]: Not yet, have you found any problems?
