### PR TITLE
Fixed the issue where PP/CPP cannot be deleted because the resources API selected by PP/CPP do not exist on the control plane

### LINKED ISSUE #6913: 创建一个错误配置的PropagationPolicy后删除不了的问题
错误配置如下：
```yaml
Name:         test3-ingress-policy
Namespace:    default
Labels:       propagationpolicy.karmada.io/permanent-id=ca07bae5-21b5-4526-a8f8-aa0e620e15db
Annotations:  <none>
API Version:  policy.karmada.io/v1alpha1
Kind:         PropagationPolicy
Metadata:
  Creation Timestamp:             2025-11-07T01:17:36Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2025-11-07T01:18:41Z
  Finalizers:
    karmada.io/propagation-policy-controller
  Generation:  2
  Managed Fields:
    API Version:  policy.karmada.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:conflictResolution:
        f:placement:
          .:
          f:clusterAffinity:
            .:
            f:clusterNames:
        f:preemption:
        f:priority:
        f:resourceSelectors:
        f:schedulerName:
    Manager:         ___go_build_karmada_demo.exe
    Operation:       Update
    Time:            2025-11-07T01:17:36Z
  Resource Version:  2556268
  UID:               1ed6b83c-0d0a-40a7-a867-774e8fbac63d
Spec:
  Conflict Resolution:  Abort
  Placement:
    Cluster Affinity:
      Cluster Names:
        sk224
  Preemption:  Never
  Priority:    0
  Resource Selectors:
    API Version:   v1
    Kind:          Ingress
    Name:          test3-ingress
    Namespace:     default
  Scheduler Name:  default-scheduler
Events:            <none>
```
具体错误在于分发资源配置的version和kind，删除时控制台卡住。

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #6913

**Special notes for your reviewer**:

I think that this PR is an optimization aimed at improving user operations. Do you think it needs to be cherry-picked?

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed the issue where PP/CPP cannot be deleted because the resources API selected by the PP/CPP do not exist on the control plane.
```

### CODE REVIEW

File: pkg/detector/detector.go [hunk 1]
```diff
@@ -1116,6 +1116,12 @@ func (d *ResourceDetector) HandlePropagationPolicyDeletion(policyID string, reso
 		}
 
 		rawObjects, err := helper.FetchResourceTemplatesByLabelSelector(d.DynamicClient, d.InformerManager, d.RESTMapper, objRef, labels.SelectorFromSet(claimMetadata))
+		if meta.IsNoMatchError(err) {
+			// hit here means the API of the target resource is not installed in the control-plane,
+			// so we don't need to do the following cleanup for this resource.
+			klog.Infof("target API %s is not installed, skipping cleanup", objRef.APIVersion+"/"+objRef.Kind)
+			continue
+		}
```
[the remark this answers is not in the document]
Comment (XiShanYongYe-Chang) [reply pkg/detector/detector.go:1125]: Thanks, updated.

**Comment by zhzhuang-zju** [comment]
thanks
/assign

File: pkg/detector/detector.go [hunk 2]
```diff
@@ -1147,18 +1129,21 @@ func (d *ResourceDetector) HandleClusterPropagationPolicyDeletion(policyID strin
 		}
 
 		rawObjects, err := helper.FetchResourceTemplatesByLabelSelector(d.DynamicClient, d.InformerManager, d.RESTMapper, objRef, labels.SelectorFromSet(claimMetadata))
+		if meta.IsNoMatchError(err) {
+			klog.Infof("target API %s is not installed, skipping cleanup", objRef.APIVersion+"/"+objRef.Kind)
```
Comment (zhzhuang-zju) [inline pkg/detector/detector.go]: ~~We can add some detailed info, like the policyName~~

File: pkg/detector/detector.go [hunk 3]
```diff
@@ -1100,45 +1104,23 @@ func (d *ResourceDetector) ReconcileClusterPropagationPolicy(key util.QueueKey)
...
-	}
-	return errors.NewAggregate(errs)
-}
-
 // HandleClusterPropagationPolicyDeletion handles ClusterPropagationPolicy delete event.
 // After a policy is removed, the label and annotation claimed on relevant resource template will be removed (which gives
 // the resource template a change to match another policy).
 //
 // Note: The relevant ClusterResourceBinding or ResourceBinding will continue to exist until the resource template is gone.
 func (d *ResourceDetector) HandleClusterPropagationPolicyDeletion(policyID string, resources []policyv1alpha1.ResourceSelector) error {
```
Comment (zhzhuang-zju) [inline pkg/detector/detector.go]: This function is no longer used and can be removed.

File: pkg/detector/detector.go [hunk 4]
```diff
@@ -1100,45 +1104,23 @@ func (d *ResourceDetector) ReconcileClusterPropagationPolicy(key util.QueueKey)
...
-	var errs []error
-	for _, resource := range util.ExtractUniqueNamespacedSelectors(resources) {
-		objRef := workv1alpha2.ObjectReference{
-			APIVersion: resource.APIVersion,
-			Kind:       resource.Kind,
-			Namespace:  resource.Namespace,
-		}
-
-		rawObjects, err := helper.FetchResourceTemplatesByLabelSelector(d.DynamicClient, d.InformerManager, d.RESTMapper, objRef, labels.SelectorFromSet(claimMetadata))
-		if err != nil {
```
Comment (RainbowMango) [inline pkg/detector/detector.go:1119]: I understand the key point is that we didn't ignore the `NoMatch` error (`meta.IsNoMatchError(err) `).  
So, how do you think of another approach: just add the check here and ignore no-match errors?

I'm asking because I'm thinking if it is easy to cherry-pick?

**Comment by RainbowMango** [comment]
It seems this issue was introduced by #6656 in release 1.15 when fixing another issue #6513.

File: pkg/detector/detector.go (hunk 3 above)
Comment (XiShanYongYe-Chang) [reply pkg/detector/detector.go]: Oh, thanks for reminding.

**Comment by XiShanYongYe-Chang** [comment]
> It seems this issue was introduced by #6656 in release 1.15 when fixing another issue #6513.

Yes, it is.

File: pkg/detector/detector.go (hunk 4 above)
Comment (XiShanYongYe-Chang) [reply pkg/detector/detector.go:1119]: Are you suggesting that we don't proceed with refactoring and instead eliminate redundant code? Am I understanding right?

Comment (RainbowMango) [reply pkg/detector/detector.go:1119]: No, as long as it's not a blocker for cherry-pick, we can move this forward.

Comment (XiShanYongYe-Chang) [reply pkg/detector/detector.go:1119]: Oh, it won't block cherry-picking.

**Comment by XiShanYongYe-Chang** [comment]
@gemini-code-assist
Considering that the current PR needs to be cherry-picked to a previous release, could you provide a suggestion for a release note for the current PR?

File: pkg/detector/detector.go [hunk 5]
```diff
@@ -1116,49 +1119,21 @@ func (d *ResourceDetector) HandlePropagationPolicyDeletion(policyID string, reso
 		}
 
 		rawObjects, err := helper.FetchResourceTemplatesByLabelSelector(d.DynamicClient, d.InformerManager, d.RESTMapper, objRef, labels.SelectorFromSet(claimMetadata))
-		if err != nil {
-			errs = append(errs, err)
+		if meta.IsNoMatchError(err) {
+			klog.Infof("target API %s is not installed, skipping cleanup", objRef.APIVersion+"/"+objRef.Kind)
```
Comment (RainbowMango) [inline pkg/detector/detector.go]:
```suggestion
			klog.Info("Skip cleanup as API(%s, Kind=%s) not installed or has been removed", objRef.APIVersion, objRef.Kind)
```
Usually log the APIVersion kind with the format `gvk.Group + "/" + gvk.Version + ", Kind="`

Comment (XiShanYongYe-Chang) [reply pkg/detector/detector.go]: Thanks.

**Comment by whitewindmills** [comment]
LGTM
leave the merge to @zhzhuang-zju

**Comment by XiShanYongYe-Chang** [comment]
/kind bug
Convenient for handling in the release notes
