### PR TITLE
fix the issue of invalid protobuf execution

### LINKED ISSUE #4529: failed to use "update-estimator-protobuf.sh" to generated proto code?
**What happened**:

when I updated `pkg/estimator/pb/types.go`, I change `MaxAvailableReplicasRequest` to following:

```go
// MaxAvailableReplicasRequest represents the request that sent by gRPC client to calculate max available replicas.
type MaxAvailableReplicasRequest struct {
	// Cluster represents the cluster name.
	// +required
	Cluster string `json:"cluster" protobuf:"bytes,1,opt,name=cluster"`
	// ReplicaRequirements represents the requirements required by each replica.
	// +required
	ReplicaRequirements ReplicaRequirements `json:"replicaRequirements" protobuf:"bytes,2,opt,name=replicaRequirements"`
	// Namespace namespace
	// +optional
	Namespace string `json:"namespace" protobuf:"bytes,3,opt,name=namespace"`
}
```

then I use `hack/update-estimator-protobuf.sh` to generate proto code, it did nothing?

Beg for help about how to use `hack/update-estimator-protobuf.sh` to generate proto code, it did nothing?

**What you expected to happen**:

generate proto code successful.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix the issue of invalid protobuf execution

**Which issue(s) this PR fixes**:

Fixes #4529

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: hack/update-estimator-protobuf.sh [hunk 1]
```diff
@@ -61,6 +61,15 @@ ${GOPATH}/bin/go-to-protobuf \
...
   --proto-import="${KARMADA_ROOT}/third_party/protobuf"
 
+# go-to-protobuf has a argument:
+#    -o, --output-base string        Output base; defaults to $GOPATH/src/
+# So the protobuf code generated to ${GOPATH}/src/github.com/karmada-io/karmada by default
+# But we usually fork the karmada repo from karmada-io/karmada, we may not put the root path to ${GOPATH}/src/github.com/karmada-io/karmada in local file system
+# In this case, we need move the generated file from ${GOPATH}/src/github.com/karmada-io/karmada to ${KARMADA_ROOT}
+if [[ "${KARMADA_ROOT}" != "${GOPATH}/src/github.com/karmada-io/karmada" ]]; then
+  mv -f "${GOPATH}"/src/github.com/karmada-io/karmada/pkg/estimator/pb/* "${KARMADA_ROOT}"/pkg/estimator/pb/
+fi
```
Comment (RainbowMango) [inline hack/update-estimator-protobuf.sh:71]: Can we detect the generated location instead of moving the file?

By the way, it is concerning if just moving files from `${GOPATH}"/src/github.com/karmada-io/karmada/pkg/estimator/pb/*`, because the files might be outdated, not the one just generated.

Comment (chaosi-zju) [reply hack/update-estimator-protobuf.sh:71]: got it

**Review by RainbowMango — COMMENTED** [review]
/assign

File: hack/update-estimator-protobuf.sh [hunk 2]
```diff
@@ -20,9 +20,26 @@ set -o pipefail
...
+# go-to-protobuf has a argument:
+#    -o, --output-base string        Output base; defaults to $GOPATH/src/
+# So the protobuf code generated to ${GOPATH}/src/github.com/karmada-io/karmada by default
+# But we usually fork the karmada repo from karmada-io/karmada, we may not put the root path to ${GOPATH}/src/github.com/karmada-io/karmada in local file system
+# To ensure that the generated file is under ${KARMADA_ROOT}, we create a temporary ${GOPATH} and soft link ${KARMADA_ROOT} to ${GOPATH}/src/github.com/karmada-io/karmada
+
+go_path="${KARMADA_ROOT}/_go"
+clean_gopath() {
+  # ${GOPATH}/pkg/mod directory is readonly, without go clean -modcache, rm command will fail with `Permission denied`
+  go clean -modcache
```
Comment (RainbowMango) [inline hack/update-estimator-protobuf.sh:32]: We don't need to download mod files in this tmp path.

See https://github.com/karmada-io/karmada/blob/181af49291b25f3f710c645afec9683456dead3b/hack/update-codegen.sh#L35-L45.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
