### PR TITLE
`karmada-operator`: Grand proxy permission to system:admin

### LINKED ISSUE #5571: Failed to proxy to member clusters with Karmada deployed by karmada-operator
**What happened**:

I have a karmada control plane installed by karmada-operator and it has joined a member cluster (member1). When I execute the command `karmadactl --operation-scope members`, it failed with  following error message:

```shell
$ karmadactl --karmada-context karmada-apiserver get deploy --operation-scope members                                                                                                     
error: cluster(member1) is inaccessible, please check authorization or network
```

**What you expected to happen**:

The result should be like this:

```shell
$ karmadactl --karmada-context karmada-apiserver get deploy --operation-scope members
NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE   ADOPTION
nginx   member1   1/1     1            1           10m   Y
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Refer to other installation method, operator missed two rbac config:

<details>
<summary>cluster-proxy-admin</summary>

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2024-09-19T08:22:24Z"
  labels:
    karmada.io/system: "true"
  name: cluster-proxy-admin
  resourceVersion: "282"
  uid: 1561fe60-eec6-405d-a981-0a9ca417c09d
rules:
- apiGroups:
  - cluster.karmada.io
  resources:
  - clusters/proxy
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2024-09-19T08:22:24Z"
  labels:
    karmada.io/system: "true"
  name: cluster-proxy-admin
  resourceVersion: "283"
  uid: ddebc2b0-2ead-4fca-bf8e-40d6634b5d8f
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-proxy-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:admin
```
</details>

when this two rbac config applied to karmada, the issue gone.

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

auto authorize system:admin to proxy member clusters in operation install method

**Which issue(s) this PR fixes**:

Fixes #5571

**Special notes for your reviewer**:

test report:

```shell
$ karmadactl --karmada-context karmada-apiserver get deploy --operation-scope members
NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE   ADOPTION
nginx   member1   1/1     1            1           9s    Y
```

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-operator`: Fixed `system:admin` can not proxy to member cluster issue.
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks, we need it.
LGTM

**Comment by zhzhuang-zju** [comment]
thanks
/lgtm

**Review by RainbowMango — COMMENTED** [review]
/assign

**Comment by RainbowMango** [comment]
/retitle `karmada-operator`: Grand proxy permission to system:admin

File: operator/pkg/util/apiclient/idempotency.go [hunk 1]
```diff
@@ -281,6 +281,31 @@ func CreateOrUpdateClusterRole(client clientset.Interface, clusterrole *rbacv1.C
 	return nil
 }
 
+// CreateOrUpdateClusterRoleBinding creates a Clusterrolebinding if the target resource doesn't exist. If the resource exists already, this function will update the resource instead.
```
Comment (RainbowMango) [inline operator/pkg/util/apiclient/idempotency.go:284]:
```suggestion
// CreateOrUpdateClusterRoleBinding creates a Clusterrolebinding if the target resource doesn't exist. 
// If the resource exists already, this function will update the resource instead.
```

**Review by RainbowMango — COMMENTED** [review]
Generally looks good to me, just some nits from me.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
