### PR TITLE
fix karmada instance aggregated service externalName error

### LINKED ISSUE #4209: The latest Karmada-operator cannot install karmada instance
**What happened**:

When I installed the karmada instance through karmada-operator by referring to the documentation  https://github.com/karmada-io/karmada/tree/master/operator#create-a-karmada-instance

I found an error.

```bash
E1106 19:15:40.649295   60506 planner.go:93] "failed to executed the workflow" err="failed to apply aggregated APIService resource to karmada controlplane, err: namespaces \"test1\" not found" workflow=init karmada="test1/karmada-demo"
E1106 19:15:40.664007   60506 controller.go:324] "Reconciler error" err="[failed to apply aggregated APIService resource to karmada controlplane, err: namespaces \"test1\" not found, Operation cannot be fulfilled on karmadas.operator.karmada.io \"karmada-demo\": the object has been modified; please apply your changes to the latest version and try again]" controller="karmada" controllerGroup="operator.karmada.io" controllerKind="Karmada" Karmada="test1/karmada-demo" namespace="test1" name="karmada-demo" reconcileID=c3e5137b-2ae7-4291-82c9-13f941e5d2f6
```

The service needs to be created in the cluster's built-in ns karmada-system corresponding to the karmada control plane. However, the ns test1 where the CR is located is used in the code, so the error ns does not exist.

**What you expected to happen**:

karmada instance can be installed normally

**How to reproduce it (as minimally and precisely as possible)**:

follow the doc https://github.com/karmada-io/karmada/tree/master/operator#create-a-karmada-instance

**Anything else we need to know?**:

It should be a bug introduced by this issue https://github.com/karmada-io/karmada/pull/3750

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix the latest Karmada-operator cannot install karmada instance

**Which issue(s) this PR fixes**:
Fixes #4209

Two bugs fixed in this pr

1. Karmada instance Aggregated service is installed on the correct namespace karmada-system
2. Fix karmada instance Aggregated service externalName to the correct value, which should be the service corresponding to karmada control plane

the example instance yaml
```yaml
kubectl apply -f - <<EOF
apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: karmada-demo
  namespace: test
EOF
```
the results
```bash
➜  karmada git:(master) ✗ kubectl get po -n test
NAME                                                    READY   STATUS    RESTARTS   AGE
karmada-demo-aggregated-apiserver-7bf4c5458f-zv4pz      1/1     Running   0          2m20s
karmada-demo-apiserver-65794cbd78-hmx99                 1/1     Running   0          2m41s
karmada-demo-controller-manager-69dbbcc866-nzxw6        1/1     Running   0          2m16s
karmada-demo-etcd-0                                     1/1     Running   0          2m43s
karmada-demo-kube-controller-manager-6949485b85-6d9mt   1/1     Running   0          2m16s
karmada-demo-metrics-adapter-68b67644dc-b7fmh           1/1     Running   0          2m16s
karmada-demo-metrics-adapter-68b67644dc-v9k5k           1/1     Running   0          2m16s
karmada-demo-scheduler-847795db5c-9thjs                 1/1     Running   0          2m16s
karmada-demo-webhook-766df78896-ccwkl                   1/1     Running   0          2m16s

➜  karmada git:(master) ✗ kubectl -n test  get karmada karmada-demo -o yaml | grep -C 10 'conditions'
      resources: {}
    kubeControllerManager:
      imageRepository: registry.k8s.io/kube-controller-manager
      imageTag: v1.25.4
      replicas: 1
      resources: {}
  hostCluster:
    networking:
      dnsDomain: cluster.local
status:
  conditions:
  - lastTransitionTime: "2023-11-06T11:40:52Z"
    message: karmada init job is completed
    reason: Completed
    status: "True"
    type: Ready
  secretRef:
    name: karmada-demo-admin-config
    namespace: test
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-operator`: Fix karmada instance aggregated service externalName and namespace error.
```

### CODE REVIEW

File: operator/pkg/karmadaresource/apiservice/apiservice.go [hunk 1]
```diff
@@ -123,13 +127,17 @@ func karmadaMetricsAdapterAPIService(client *aggregator.Clientset, name, namespa
 	return nil
 }
 
-func karmadaMetricsAdapterService(client clientset.Interface, name, namespace string) error {
+func karmadaMetricsAdapterService(client clientset.Interface, name, namespace, karmadaControlPlaneServiceName, karmadaControlPlaneNamespace string) error {
```
Comment (calvin0327) [inline operator/pkg/karmadaresource/apiservice/apiservice.go:130]: ditto.

File: operator/pkg/karmadaresource/apiservice/apiservice.go [hunk 2]
```diff
@@ -30,8 +30,8 @@ func init() {
 }
 
 // EnsureAggregatedAPIService creates aggregated APIService and a service
-func EnsureAggregatedAPIService(aggregatorClient *aggregator.Clientset, client clientset.Interface, name, namespace, caBundle string) error {
-	if err := aggregatedApiserverService(client, name, namespace); err != nil {
+func EnsureAggregatedAPIService(aggregatorClient *aggregator.Clientset, client clientset.Interface, name, namespace, karmadaControlPlaneServiceName, karmadaControlPlaneNamespace, caBundle string) error {
```
Comment (calvin0327) [inline operator/pkg/karmadaresource/apiservice/apiservice.go:33]: The values of both of these variables `name` and `karmadaControlPlaneServiceName` are `data.Name()`, whether we can use the `name` variable directly?

File: operator/pkg/karmadaresource/apiservice/apiservice.go [hunk 3]
```diff
@@ -81,8 +85,8 @@ func aggregatedApiserverService(client clientset.Interface, name, namespace stri
 }
 
 // EnsureMetricsAdapterAPIService creates APIService and a service for karmada-metrics-adapter
-func EnsureMetricsAdapterAPIService(aggregatorClient *aggregator.Clientset, client clientset.Interface, name, namespace, caBundle string) error {
-	if err := karmadaMetricsAdapterService(client, name, namespace); err != nil {
+func EnsureMetricsAdapterAPIService(aggregatorClient *aggregator.Clientset, client clientset.Interface, name, namespace, karmadaControlPlaneServiceName, karmadaControlPlaneNamespace, caBundle string) error {
```
Comment (calvin0327) [inline operator/pkg/karmadaresource/apiservice/apiservice.go:88]: ditto.

File: operator/pkg/karmadaresource/apiservice/apiservice.go (hunk 2 above)
Comment (wawa0210) [reply operator/pkg/karmadaresource/apiservice/apiservice.go:33]: I suggest clarifying by two differently named parameters, because they express different meanings, which is more clear, although the values ​​are currently the same

Comment (calvin0327) [reply operator/pkg/karmadaresource/apiservice/apiservice.go:33]: ok, I'm with you.

**Comment by calvin0327** [comment]
/lgtm

@RainbowMango @jwcesign /cc

**Comment by jwcesign** [comment]
I think we need release notes:
```
`karmada-operator`: Fix karmada instance aggregated service externalName error.
```

**Comment by wawa0210** [comment]
> I think we need release notes:
> 
> ```
> `karmada-operator`: Fix karmada instance aggregated service externalName error.
> ```

done

File: operator/pkg/karmadaresource/apiservice/apiservice.go (hunk 2 above)
Comment (jwcesign) [inline operator/pkg/karmadaresource/apiservice/apiservice.go:33]: So， if I deploy following yaml:
```
apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: karmada-demo
  namespace: test
```

The parameter is named "karmada-demo" and the parameter namespace is "test". Why do we need it as a parameter? Can you explain it to me?

Comment (wawa0210) [reply operator/pkg/karmadaresource/apiservice/apiservice.go:33]: image

karmada instance will create a constant namespace karmada-system to save karmada resources, including aggregated service

Comment (jwcesign) [reply operator/pkg/karmadaresource/apiservice/apiservice.go:33]: I understand, thank you for explaining.

So can we make the parameter name more unified, one is host cluster, one is karmada control plane.

Here, the demo ns is in host cluster, karmada-system is in karmada-control plane.


So the parameter should be: 
```
func EnsureAggregatedAPIService(aggregatorClient *aggregator.Clientset, client clientset.Interface, karmadaServiceName, KarmadaServiceNamespace, hostClusterServiceName, hostClusterNamespace, caBundle string)
```

@XiShanYongYe-Chang, please help me confirm.

Comment (XiShanYongYe-Chang) [reply operator/pkg/karmadaresource/apiservice/apiservice.go:33]: It's a bit too hard to name, before the logic in our code and in the documentation we advertised to the public, one was `host cluster` and the other was `karmada control plane`.

Comment (wawa0210) [reply operator/pkg/karmadaresource/apiservice/apiservice.go:33]: > It's a bit too hard to name, before the logic in our code and in the documentation we advertised to the public, one was `host cluster` and the other was `karmada control plane`.

Maybe this is more in line with karmada norms ? 

```golang
func EnsureAggregatedAPIService(aggregatorClient *aggregator.Clientset, client clientset.Interface, karmadaControlPlaneServiceName, karmadaControlPlaneNamespace, hostClusterServiceName, hostClusterNamespace, caBundle string)
```

Comment (jwcesign) [reply operator/pkg/karmadaresource/apiservice/apiservice.go:33]: +1

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
LGTM

**Review by RainbowMango — APPROVED** [review]
/approve
