### PR TITLE
fix bug: avoid updating directly cached resource template

### LINKED ISSUE #3878: Resource template cannot be reconciled again due to cache modification
**What happened**:
I deleted propagation policy `default/test-pp` to unbind from configmap `default/test-cm`, but find that configmap `default/test-cm` cannot be reconciled again. 
image

that means configmap `default/test-cm` cannot be matched by new propagation policy `default/test-pp-1`.
image

**What you expected to happen**:
configmap `default/test-cm` can be matched by new propagation policy `default/test-pp-1`.

**How to reproduce it (as minimally and precisely as possible)**:
1. create such configmap(keep labels non-nil):
```
apiVersion: v1
data:
  a: b
kind: ConfigMap
metadata:
  labels:
    a: b
  name: test-cm
  namespace: default
```
2. create propagation policy.
3. delete propagation policy after configmap is propagated.
4. check if configmap can be reconcile again.

**Anything else we need to know?**:
`detector` deletes directly policy labels from cached resource template.
https://github.com/karmada-io/karmada/blob/d916d877a4942d9abf0467d65562d471acf8138d/pkg/detector/detector.go#L1117-L1131

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
avoid updating directly cached resource template.

**Which issue(s) this PR fixes**:
Fixes #3878

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmada-controller-manager: Avoid updating directly cached resource template.
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot.

In order to prevent other places where the utility methods are called from modifying the objects in the cache, I think it would be better to directly make modifications within the utility methods.

Furthermore, this issue indicates that we do not have an end-to-end (E2E) coverage for this scenario. If possible, could you please provide an additional E2E use case or create an issue to track this task?

**Comment by whitewindmills** [comment]
> I think it would be better to directly make modifications within the utility methods.

The number of resources may be huge, and the calling frequency of this utility function is very high. It is obviously not necessary to perform a deep copy every time we read a resource through this utility function. We only make a deep copy in a few places that need to be modified.

> Furthermore, this issue indicates that we do not have an end-to-end (E2E) coverage for this scenario. If possible, could you please provide an additional E2E use case or create an issue to track this task?

good suggestion.
tracked issue: https://github.com/karmada-io/karmada/issues/3884

**Comment by XiShanYongYe-Chang** [comment]
> The number of resources may be huge, and the calling frequency of this utility function is very high. It is obviously not necessary to perform a deep copy every time we read a resource through this utility function. We only make a deep copy in a few places that need to be modified.

In this case, should we consider adding some comments in the utility func to indicate the need for attention when modifying cache issues, so as to prevent overlooking this factor when using it in new places?

**Comment by whitewindmills** [comment]
> In this case, should we consider adding some comments in the utility func to indicate the need for attention when modifying cache issues, so as to prevent overlooking this factor when using it in new places?

:+1:

**Comment by whitewindmills** [comment]
ptal @XiShanYongYe-Chang @RainbowMango @chaunceyjiang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
/lgtm

File: pkg/detector/policy.go [hunk 1]
```diff
@@ -272,9 +272,13 @@ func (d *ResourceDetector) removeResourceLabelsIfNotMatch(objectReference workv1
 		return false, nil
 	}
 
+	object = object.DeepCopy()
+	objLabels := object.GetLabels()
 	for _, labelKey := range labelKeys {
-		util.RemoveLabel(object, labelKey)
```
Comment (chaunceyjiang) [inline pkg/detector/policy.go:276]: Just a question, why not use the `util.RemoveLabel` function?

Comment (whitewindmills) [reply pkg/detector/policy.go:276]: improve execution efficiency. every call of `util.RemoveLabel` will get and set labels.

Comment (chaunceyjiang) [reply pkg/detector/policy.go:276]: Can we extend this function? Like this: `util.RemoveLabels(object, labelKeys...)`

Comment (whitewindmills) [reply pkg/detector/policy.go:276]: sure

**Review by chaunceyjiang — COMMENTED** [review]
/lgtm

**Review by RainbowMango — COMMENTED** [review]
/assign

**Comment by whitewindmills** [comment]
done

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by whitewindmills** [comment]
@XiShanYongYe-Chang @RainbowMango  should we cherry-pick it to the previous branch?

**Comment by RainbowMango** [comment]
+1
