### PR TITLE
Fix work status not sync to control plane when apiserver failed and recovered soon

### LINKED ISSUE #2863: Workload not synced to control plane version
**What happened**:
When I send the deployment to multiple clusters, everything is ok. After one of the clusters fails and then recovers, I modify the delivered deployment on the cluster, and it is not synchronized back to the version of the karmada control plane.

**What you expected to happen**:
I hope to directly modify the distributed deployment on the cluster, which can be automatically synchronized back to the version of the karmada control plane

**How to reproduce it (as minimally and precisely as possible)**:
Send the deployment to multiple clusters, After one of the clusters fails and then recovers, modify the delivered deployment on the cluster, and it is not synchronized back to the version of the karmada control plane.

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.3.0

### PR DESCRIPTION
**Pull request by Poor12**
Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When cluster status is unhealthy, we should not stop informer manager because when apiserver recovered, workload can not sync to karmada control plane.

Reproduction：
1.Failover is close.
2.Deploy a deployment to m1 and m2.
3.m1 apiserver failed. The cluster status of m1 became false. Soon it recovered. The cluster status of m1 became true again.
4.Update the deployment in m1. But the control plane cannot perceive the change of deployment in m1.

Reason:
Informer of m1 didn't work and could not collect update events.

**Which issue(s) this PR fixes**:
Fixes #2863 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
karmada-controller-manager/karmada-agent: fix work status not sync to control plane when apiserver failed and recovered soon.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Good job, can we add an e2e test to cover this case?

File: test/e2e/failover_test.go [hunk 1]
```diff
@@ -141,6 +141,117 @@ var _ = framework.SerialDescribe("failover testing", func() {
 			})
 		})
 	})
+
+	ginkgo.Context("Deployment status synchronization when cluster failed and recovered soon", func() {
```
Comment (XiShanYongYe-Chang) [inline test/e2e/failover_test.go:145]: This e2e test doesn't involve failover. It's more like a test case for resource state collection. How about moving it to `resource_test.go`?

File: test/e2e/failover_test.go [hunk 2]
```diff
@@ -141,6 +141,117 @@ var _ = framework.SerialDescribe("failover testing", func() {
...
+		ginkgo.BeforeEach(func() {
+			policyNamespace = testNamespace
+			policyName = deploymentNamePrefix + rand.String(RandomStrLength)
+			deploymentNamespace = testNamespace
+			deploymentName = policyName
+			deployment = testhelper.NewDeployment(deploymentNamespace, deploymentName)
+			numOfFailedClusters = 1
+			originalReplicas = 3
+
+			// set MaxGroups=MinGroups=1, label is location=CHN.
```
Comment (XiShanYongYe-Chang) [inline test/e2e/failover_test.go:161]: This comment seems unrelated.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
