### PR TITLE
Replace colon with point in the rbac resource name

### LINKED ISSUE #2393: make OLM work with karmada
**What would you like to be added**:

seems `karmada` not working with [OLM](https://olm.operatorframework.io/), can we make it wokring?

some error logs:
```
{"level":"error","ts":1660873894.1330693,"logger":"controllers.operator","msg":"Could not update Operator status","request":"/pixie-operator.px-operator","error":"Operation cannot be fulfilled on operators.operators.coreos.com \"pixie-operator.px-operator\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/build/vendor/github.com/go-logr/zapr/zapr.go:132\ngithub.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators.(*OperatorReconciler).Reconcile\n\t/build/pkg/controller/operators/operator_controller.go:167\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/build/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/build/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/build/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99"}
```

cc @XiShanYongYe-Chang

### PR DESCRIPTION
**Pull request by Poor12**
Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Use `karmadactl apply` to apply rbac resources to all clusters
```
karmadactl apply -f olm.yaml --all-clusters
```

It will auto-generate a policy, and policy name will include ":", and create failed.
The same as #2549 

olm works well with Karmada.
```
root@karmada-dev-linux-shentiecheng:~/karmada# kubectl --kubeconfig ~/.kube/members.config --context member1 get po -A 
NAMESPACE             NAME                                                              READY   STATUS      RESTARTS       AGE 
default               nginx-85b98978db-mcdxh                                            1/1     Running     0              54m
kube-system           coredns-64897985d-8b5tc                                           1/1     Running     0              43h
kube-system           coredns-64897985d-gkhjc                                           1/1     Running     0              43h
kube-system           etcd-member1-control-plane                                        1/1     Running     0              43h
kube-system           kindnet-kxkhl                                                     1/1     Running     13 (19h ago)   43h
kube-system           kube-apiserver-member1-control-plane                              1/1     Running     1 (19h ago)    43h
kube-system           kube-controller-manager-member1-control-plane                     1/1     Running     5 (19h ago)    43h
kube-system           kube-proxy-gkfjj                                                  1/1     Running     0              43h
kube-system           kube-scheduler-member1-control-plane                              1/1     Running     5 (19h ago)    43h
local-path-storage    local-path-provisioner-5ddd94ff66-zfpl7                           1/1     Running     19 (19h ago)   43h
my-grafana-operator   grafana-operator-controller-manager-787cbf857c-5tz8s              2/2     Running     0              2m6s
olm                   catalog-operator-865494bfbf-sspqj                                 1/1     Running     0              6m50s
olm                   ec41fdd641ffbaf50ad3099709aa193c6800139147ff26ead6d08bd792dw26w   0/1     Completed   0              2m48s
olm                   olm-operator-f7746965-lvm66                                       1/1     Running     0              6m51s
olm                   operatorhubio-catalog-mw229                                       1/1     Running     0              6m46s
olm                   packageserver-6884744f49-hnw6n                                    1/1     Running     0              6m47s
olm                   packageserver-6884744f49-wvdxz                                    1/1     Running     0              6m47s
```
**Which issue(s) this PR fixes**:
Fixes #2393 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
`karmadactl`: Fixed the error of resources whose name contains colons failing to be created when using `karmadactl apply`.
```

### CODE REVIEW

File: pkg/util/names/names.go [hunk 1]
```diff
@@ -154,5 +154,8 @@ func GeneratePolicyName(namespace, name, gvk string) string {
 	hash := fnv.New32a()
 	hashutil.DeepHashObject(hash, namespace+gvk)
 
+	if strings.Contains(name, ":") {
```
Comment (XiShanYongYe-Chang) [inline pkg/util/names/names.go:157]: How about adding some similar comments here?

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Ask @lonelyCZ @carlory to help take a look. The `GeneratePolicyName` func is mainly used by `karmadactl promote` and `karmadactl apply` command.

/cc @lonelyCZ @carlory

File: pkg/util/names/names.go (hunk 1 above)
Comment (Poor12) [reply pkg/util/names/names.go:164]: Done

**Comment by carlory** [comment]
LGTM

**Comment by XiShanYongYe-Chang** [comment]
Ask for @RainbowMango to help take a look.
/assign @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
Please help to cherry-pick this patch.
